### ISSUE TITLE
Move back executors to main `testkube` repos

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1011]
**Why should it be implemented?**

As testkube is getting popular it would be better to place executors in the main repo as one with so many stars. 
It would increase contributors of possible new executors. 

**Describe the improvement**

Create `executors` directory move: 
- `curl` 
- `postman` 
- `example`
- `cypress`
to directory

Create: 
- build pipelines on only when each of executors subfolder changed

**Comment by vsukhin** [comment]
It will also simplify dependecy solving issues. A lot of modern repos are monorepo based

**Comment by exu** [comment]
We had it on beginning monorepo but decided to split in some time (was thinking that it'll be easier to have executors - back then they was separate REST services - as separate deploy units) 
but looks like there are always pros and cons for each solution :)

**Comment by exu** [comment]
We need to make decision about builds and versioning as it'll be cumbersome to manage versions of particular executors separately (or we can stick with testkube version and put it for all executors? a little overhead of rebuilding all each time something change)

**Comment by lreimer** [comment]
I think there should be two types of executors: core executors bundled with the initial Testkube installation and community or optional executors that can be added (and versioned) separately later on. 
This would allow the user to configure his actual installation according to his needs (a Java developer needs different test tools and executors compared to a TypeScript or Python developer).

**Comment by exu** [comment]
@lreimer good points - we can move only go-based executors with common infrastructure to our repo - but still allow to create/register external ones. 

Moving to our repo just simplify using libs and managing CI/CD pipelines

**Comment by rangoo94** [comment]
It's done with https://github.com/kubeshop/testkube/pull/3304.
