### ISSUE TITLE
Trying to run inexistent bug throws runtime error

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1016]
**Describe the bug**

**To Reproduce**
1. Try running an inexistent tests with `testkube tests run [random]`

**Expected behavior**
Handled/formated error message. 

**Version / Cluster**
- Which testkube version? 0.9.11
- What Kubernetes cluster? Minikube
- What Kubernetes version? 1.23.1

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/155202977-e46ab0f9-d5c3-436b-96a7-a28fce8c6371.png)
 
**Additional context**

**Comment by exu** [comment]
Nice catch! Fixed in mentioned issue
