### ISSUE TITLE
Installing testkube does not create .testkube/config.json

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1017]
**Describe the bug**
When installing/updating testkube, the following error appears from not being able to read the Testkube config file. 
```
{
  "level": "error",
  "ts": 1645557105.601299,
  "caller": "config/config.go:20",
  "msg": "can't load configuration file",
  "error": "open /Users/abdallahabedraba/.testkube/config.json: no such file or directory",
  "stacktrace": "github.com/kubeshop/testkube/cmd/kubectl-testkube/config.init.0\n\t/home/runner/work/testkube/testkube/cmd/kubectl-testkube/config/config.go:20\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:6498\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:6475\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:6475\nruntime.doInit\n\t/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:6475\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.7/x64/src/runtime/proc.go:238"
}
```

Have mitigated for now by creating a `config.json` with an empty object `{}`

**To Reproduce**
1. Delete current testkube and config file
2. Install testkube again
3. Run `testkube version`

**Expected behavior**
Testkube correctly setup

**Version / Cluster**
- Which testkube version? 0.9.11
- OS: MacOS

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/155203432-1c6ee3df-f1b3-4c55-b3ed-c2b84773baf1.png)
 
**Additional context**

**Comment by exu** [comment]
Hi @aabedraba thanks for checking this - fixed in linked pull request
