### ISSUE TITLE
Getting tests don't work in custom namespace - save installation namespace in config

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1088]
**Describe the enhancement**

When installed in `my-testkube` namespace I'm receving error when trying to use testkube like in all docs available - there is no strict point which states that I should use `--namespace=my-testkube` flag in usage for all commands
```
➜  ~ t get tests
getting server info: services "testkube-api-server" not found
⨯ getting all tests in namespace testkube (error: api/list-tests returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"services \"testkube-api-server\" not found","reason":"NotFound","details":{"name":"testkube-api-server","kind":"services"},"code":404}
'
error: services "testkube-api-server" not found)
```

**To Reproduce**
1. install: `kubectl testkube install --namepace=my-testkube` 
2. run: `kubectl testkube get tests` 

** Solution

We could implement namespace loading from config. add command 
```
kubectl configure namespace my-testkube
```

then saved namespace should be used as default one on call to `kubectl testkube` command

**Comment by mlushpenko** [comment]
Run into the same problem but the suggested fix didn't help - even the version command doesn't work:

```
kubectl testkube version
error trying to reach service: Address is not allowed

████████ ███████ ███████ ████████ ██   ██ ██    ██ ██████  ███████
   ██    ██      ██         ██    ██  ██  ██    ██ ██   ██ ██
   ██    █████   ███████    ██    █████   ██    ██ ██████  █████
   ██    ██           ██    ██    ██  ██  ██    ██ ██   ██ ██
   ██    ███████ ███████    ██    ██   ██  ██████  ██████  ███████
                                           /tɛst kjub/ by Kubeshop


Client Version 1.0.14
Server Version  error trying to reach service: Address is not allowed
Commit 04c2e9b60909240ceb636e220e5e320856f274f0
Built by goreleaser
Build date 2022-04-29T11:19:13Z
```

I've tried this command to fix namespace `kubectl testkube config namespace monitoring`

**Comment by exu** [comment]
For now testkube don't handle namespace - we've removed as we've get too many edge cases :/
