### ISSUE TITLE
Add schedule for tests and testsuites

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#1091]
**Is your feature request related to a problem? Please describe.**
User needs to be able to run tests and testsuites on a specific schedule

**Describe the solution you'd like**
They need to be able to provide a schedule for test or testsuite using cli

**Comment by olensmar** [comment]
the original idea was to have scheduling provided by an external service - i.e. CI / CD, etc - which would trigger the execution of tests via the Testkube API - since running of tests is usually coupled with some other event (build, deploy, etc) - and not just at a specific time..

**Comment by bioslikk** [comment]
Would love to understand a bit more the about what means having an external service scheduling tests. 
The direction we are going towards is to make Test orchestration very independent from CI/CD. 
So users don't require CI/CD to schedule, or trigger a Test execution in an automated way (they can still use it ofc)
The first steps is to start with scheduling, later on, we want to find a solution that allows tests to be triggered based on cluster changes. e.g., when a new helm chart deploy is done.
