### ISSUE TITLE
Few thoughts on enhancements

### ISSUE THREAD

**Issue by ewawadr** [kubeshop/testkube#1129]
**Describe the enhancement you'd like to see**

I investigated shortly testkube for our purposes and would like to share some feedback, because idea for product is good, however at the moment it was not straightforward to install/configure/use.

We use ArgoCD for deployments, so I chose Helm installation with ArgoCD and some observations here:

- Is Minio/S3 necessary? It was mentioned that it's used only at the moment for artifacts from Cypress, but helm installation assumes that some address will be configured. It would be good to disable Minio altogether, if it's not planned to be used.
- MongoDB, at the moment it's installed together with helm chart. Would it be possible to use external MongoDB instance and not create it together with helm chart.?
- Additionally, at the moment there's variable MONGO_DSN and there's parameter for it in Helm chart, but you can't safely provide password that way. It would be good to have ability to provide MongoDB user/password from existing k8s secret, so we could just pass secret name/key, where password is stored. 
- There should be also ability to configure other MongoDB connection options, because MongoDB can be configured as ReplicaSet. It would be good to be able to specify: hosts, database name, auth source, replicaset name, as separate helm parameters.
- It would be also good to not have hard dependency on certmanager, alternatively maybe it could be done by some k8s job that would create required certificates?
- Ingress, it would be good to also provide some working example for Traefik, because it's another popular alternative to nginx, which is used in e.g. k3s/k3d. I tried to prepare equivalent ingress definitions for Traefik, but it's hard, because it's not clearly stated, which requests should go to API, which to dashboard .
- Authentication/Authorization (OAuth2/SSO), at the moment access to dashboard/API is public, which might be hard to justify in enterprise enviornment. It would be sufficient to be able to provide configuration for existing OAuth2 providers like Dex or Keycloak and have appropriate code in API/Dashboard that would check that request contains valid JWT token in headers, if authorization is enabled. Additionally it could check for roles/scopes that would be checked in JWT token and it would be configurable, if any scope/role is needed for access.
- Custom namespaces, helm chart was installed on custom namespace and I could add test from CLI and list it from CLI, but only test-executions were returned by API and visible in Dashboard, for GET /v1/tests there were no results from API. It might be related to https://github.com/kubeshop/testkube/issues/1088 
- Docker images, in some environments there's no direct access to DockerHub, all used images should be configurable. I haven't checked that one, but it would be good to have ability to configure on Helm chart level, what images will be used by e.g. test-executors.
- Postman executor, it should be possible to specify not only test collection, but also to provide environment file. This environment file might be preexisting secret in k8s, but in general it might contain sensitive data, so it should be stored securely. Maybe this might be generalized to allow to mount arbitrary ConfigMap/Secrets into test-executor's pod.

**Additional context**
testkube v0.10.6 installed by Helm

**Comment by exu** [comment]
Thanks @ewawadr thanks for your great feedback, we'll take it into consideration during incoming work

**Comment by exu** [comment]
Hi @ewawadr 

We've just addressed some of the issues you've described, 

- https://github.com/kubeshop/testkube/issues/1138
- https://github.com/kubeshop/testkube/issues/1137
- https://github.com/kubeshop/testkube/issues/1136
- https://github.com/kubeshop/testkube/issues/1135
- https://github.com/kubeshop/testkube/issues/1134
- https://github.com/kubeshop/testkube/issues/1133

In terms of Auth/authz - we're already checking the use of `Oauth2-proxy` to allow passing to a lot of providers.  https://github.com/kubeshop/testkube/issues/1123

Thanks for great feedback!, closing for now as all issues that you've described are in separate tasks now.
