### ISSUE TITLE
Remove Jetstack from Testkube

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1135]
**Describe the enhancement you'd like to see**

Allow configure certificates manually by user in helm charts. Or update docs about how to do it manually. 

We should allow to configure certs manually in:
- all ingresses 
- operator

> It would be also good to not have hard dependency on certmanager, alternatively maybe it could be done by some k8s job that would create required certificates?

DoD: 
- Create Job for generating certs
- Create CronJob for refreshing certs

**Comment by TheBrunoLopes** [comment]
do we know if this solved ?
cc: @vsukhin

**Comment by vsukhin** [comment]
No. it needs to be implemented

**Comment by TheBrunoLopes** [comment]
How is this important to the user ?

**Comment by vsukhin** [comment]
It simplifies Testkue installation removing cert-manager dependency
