### ISSUE TITLE
Demo Cluster does not show results

### ISSUE THREAD

**Issue by donnalux** [kubeshop/testkube#1140]
**To Reproduce**
1. Clear cache
2. Click on https://demo.testkube.io/dashboard
3. See modal requesting Teskkube API endpoint

![image](https://user-images.githubusercontent.com/102221761/159693810-39526f10-5e2c-41de-93e0-c3ba8987f57d.png)

**Expected behavior**
Should see results by default 
https://demo.testkube.io/results/v1

**Comment by exu** [comment]
Looks like fixed.
