### ISSUE TITLE
Running tests in cli with args is quite hard

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1149]
**Describe the enhancement you'd like to see**
Example 
```
kubectl testkube run test k6-api-server -f --args='--vus' --args=1000 --args='--iterations' --args='10000'
```

Maybe we should consider doing just `--args='--vus 1000 --iterations 10000'` 
It would need to be split into chunks and passed as array in command.

**Comment by lreimer** [comment]
I totally agree that using args can be very cumbersome in case of many required arguments. I like the suggestion to specify just one single args and then tokenize on space.


For your K6 example you could however alternatively specify the arguments as options as part of the test script, e.g.
```
export const options = {
   vus: 1000, 
   iterations: 10000,
};
```
