### ISSUE TITLE
Add executor for Zed Attack Proxy (ZAP)

### ISSUE THREAD

**Issue by lreimer** [kubeshop/testkube#1157]
**Is your feature request related to a problem? Please describe.**
As a software engineer I want to run regular API or penetration tests against deployed workloads.

**Describe the solution you'd like**
The OWASP Zed Attack Proxy (ZAP) provides a set of scripts to perform Baseline, Full and API scans that can easily be run as a Docker container (https://hub.docker.com/r/owasp/zap2docker-stable). A suitable executor implementation could trigger the relevant scripts (base on test subtype) with the required parameters.

**Additional context**
- leverage test sub type to determine if base, full or API scan should run
- specify test parameters as simple YAML or JSON file (similar to CURL executor)

**Comment by lreimer** [comment]
Working implementation here: https://github.com/lreimer/testkube-executor-zap

**Comment by exu** [comment]
https://github.com/kubeshop/testkube-executor-zap

**Comment by exu** [comment]
Still tests, docs, examples, and article needed @TheBrunoLopes I think we've lost this little one ;) we should get back to it in incoming releases

**Comment by fivenp** [comment]
Here's the [SVG icon](https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=1192%3A42994) for this executor

`<svg width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0_1192_42994)">
<g clip-path="url(#clip1_1192_42994)">
<path opacity="0.1" d="M12.729 24.0088C18.9538 24.0088 24 18.9625 24 12.7377C24 6.51294 18.9538 1.46674 12.729 1.46674C6.50421 1.46674 1.45801 6.51294 1.45801 12.7377C1.45801 18.9625 6.50421 24.0088 12.729 24.0088Z" fill="white"/>
<path d="M0.947245 4.72315L9.89595 0.873024C9.9278 0.85883 9.96362 0.856301 9.99715 0.865879C10.0307 0.875457 10.0598 0.896532 10.0793 0.925407L14.916 7.79627C14.931 7.81675 14.9411 7.8405 14.9452 7.86559C14.9494 7.89068 14.9476 7.91639 14.9399 7.94064C14.9322 7.96489 14.919 7.98699 14.9012 8.00514C14.8833 8.02329 14.8615 8.03698 14.8374 8.04509L13.5278 8.48161C13.5037 8.49047 13.4821 8.50494 13.4647 8.52384C13.4473 8.54273 13.4347 8.5655 13.4278 8.59025C13.421 8.61501 13.4202 8.64103 13.4254 8.66617C13.4307 8.6913 13.4418 8.71483 13.458 8.73479L17.2775 13.5365C17.2945 13.5574 17.3059 13.5822 17.3109 13.6086C17.3158 13.635 17.3141 13.6622 17.3058 13.6878C17.2976 13.7133 17.2831 13.7365 17.2637 13.755C17.2443 13.7736 17.2205 13.787 17.1946 13.7941L15.5402 14.2001C15.5139 14.2066 15.4897 14.2196 15.4698 14.2379C15.4498 14.2563 15.4348 14.2793 15.4261 14.305C15.4174 14.3306 15.4153 14.358 15.42 14.3847C15.4247 14.4114 15.436 14.4364 15.4529 14.4576L21.0928 21.5816C21.1156 21.6095 21.1282 21.6443 21.1284 21.6804C21.1286 21.7164 21.1165 21.7514 21.094 21.7795C21.0715 21.8076 21.04 21.8272 21.0048 21.8349C20.9696 21.8425 20.9329 21.8379 20.9007 21.8217L8.24153 14.5143C8.21579 14.4989 8.19485 14.4767 8.18105 14.45C8.16726 14.4234 8.16115 14.3935 8.16341 14.3636C8.16568 14.3336 8.17623 14.305 8.19388 14.2807C8.21154 14.2564 8.23559 14.2376 8.26336 14.2262L9.79119 13.6195C9.81743 13.6082 9.84021 13.5901 9.85719 13.5671C9.87418 13.5442 9.88476 13.5171 9.88787 13.4887C9.89097 13.4603 9.88649 13.4316 9.87487 13.4055C9.86326 13.3794 9.84492 13.3568 9.82175 13.3401L4.67951 9.62966C4.65748 9.61224 4.64024 9.58951 4.62939 9.5636C4.61855 9.53768 4.61446 9.50944 4.61752 9.48152C4.62057 9.4536 4.63067 9.42691 4.64685 9.40396C4.66304 9.38101 4.68479 9.36254 4.71007 9.35029L5.88431 8.83519C5.91028 8.82345 5.93267 8.80504 5.94922 8.78184C5.96577 8.75865 5.97589 8.73148 5.97855 8.70311C5.98121 8.67474 5.97632 8.64617 5.96437 8.6203C5.95241 8.59443 5.93383 8.57218 5.9105 8.55582L0.916689 5.00253C0.893509 4.98582 0.875176 4.96326 0.86356 4.93716C0.851944 4.91106 0.84746 4.88234 0.850567 4.85393C0.853673 4.82553 0.864259 4.79846 0.881243 4.77549C0.898227 4.75251 0.921003 4.73445 0.947245 4.72315V4.72315Z" fill="white"/>
</g>
</g>
<defs>
<clipPath id="clip0_1192_42994">
<rect width="24" height="24" fill="white" transform="translate(0 0.0057373)"/>
</clipPath>
<clipPath id="clip1_1192_42994">
<rect width="24" height="24.0087" fill="white"/>
</clipPath>
</defs>
</svg>
`
