### ISSUE TITLE
Dashboard - consider moving log output as first active tab

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1189]
Restults tab have same information as header so maybe it's good idea to make Logs first tab ?

<img width="946" alt="image" src="https://user-images.githubusercontent.com/30776/161229326-e4c12a88-3334-48cb-867a-28a635dc4f3b.png">

**Comment by Toxer10** [comment]
Closing
<img width="770" alt="image" src="https://user-images.githubusercontent.com/25991946/161532888-aa4138db-ca1d-4f50-9473-e5a9d9d06134.png">
