### ISSUE TITLE
Dashboard - curl logo is not readable

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1190]
dark logo on dark bg

<img width="303" alt="image" src="https://user-images.githubusercontent.com/30776/161229569-edb5bedd-0e0d-493a-8c34-ab28634d8322.png">

**Comment by donnalux** [comment]
![curl_logo](https://user-images.githubusercontent.com/102221761/161499531-9bc9483b-eeca-4bac-9f69-80ee6b52d7bc.svg)

**Comment by Toxer10** [comment]
Closing
<img width="854" alt="image" src="https://user-images.githubusercontent.com/25991946/161532754-1a13c0f6-e5e0-44d4-be7c-a0ec1acd5266.png">
