### ISSUE TITLE
Dashboard - add new `CLI commands` to test

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1191]
Add new commands to CLI commands for test: 
* `kubectl testkube get test TEST_NAME`
* `kubectl testkube get executions --test TEST_NAME`

<img width="342" alt="image" src="https://user-images.githubusercontent.com/30776/161230613-8b98b9df-b693-45ec-8376-c42a7c5e1ab7.png">

**Comment by Toxer10** [comment]
Closing
<img width="853" alt="image" src="https://user-images.githubusercontent.com/25991946/161532673-840ac1ce-2a91-4cca-aab0-2f2642ca3e2a.png">
