### ISSUE TITLE
Dashboard - add `CLI commands` tab to executions

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1192]
**Describe the enhancement you'd like to see**

Add command: 
- `kubectl testkube get execution EXECUTION_ID` 

<img width="788" alt="Zrzut ekranu 2022-04-1 o 11 04 41" src="https://user-images.githubusercontent.com/30776/161232129-7695ed55-0a6b-469f-ba05-9e833a44e26f.png">

**Comment by Toxer10** [comment]
Closing
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/25991946/161532427-d12ded6c-227a-4c77-a61a-f85fd8baee25.png">
