### ISSUE TITLE
Dashboard - invalid dates formatting

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1193]
no space between dates (this one should be designed better by [@Donna Leonard](https://kubeshop.slack.com/team/U038J6YLDK2) as it looks a little unreadable), additionally sometimes those dates are wrapping sometimes no.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/30776/161232531-b23082fd-b624-4609-bac9-2d07878984a6.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/30776/161232563-b43f30e2-a91a-43cb-b842-baee29b126c0.png">

**Comment by donnalux** [comment]
**UX Design:**
https://www.figma.com/file/K7PwsINvkMrs8mvmkjC0wf/TestKube?node-id=1185%3A6888

**Comment by TheBrunoLopes** [comment]
Dates are fixed now.
<img width="690" alt="image" src="https://user-images.githubusercontent.com/13501228/169515596-3f1eb902-f6c2-48e2-ac62-043ae575f3c9.png">
