### ISSUE TITLE
Dasboard - after clicking on execution from test suite - execution is not loaded

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1194]
**Describe the bug**

When click this: 
<img width="1644" alt="Zrzut ekranu 2022-04-1 o 11 11 04" src="https://user-images.githubusercontent.com/30776/161233588-8d58c38e-d629-4687-9436-1f6d54f7e2a0.png">

Dashboard loads this: 
<img width="1667" alt="image" src="https://user-images.githubusercontent.com/30776/161233367-cf9a1d4f-47d9-4db9-a988-71b86eb2ca7c.png">

and it should open test execution details

**Comment by TheBrunoLopes** [comment]
Solved
