### ISSUE TITLE
Add executor for Artillery

### ISSUE THREAD

**Issue by abhishek9686** [kubeshop/testkube#1201]
**Is your feature request related to a problem? Please describe.**
Artillery is a modern, powerful & easy-to-use performance testing toolkit. it is used to ship scalable applications that stay performant & resilient under high load. I believe that performance is a feature. The software which is fast and reliable makes for happier users, and happier users make for more revenue

**Describe the solution you'd like**
You can use Artillery to run two types of performance tests:

- Tests that put load on a system, i.e. load tests, stress tests, and soak tests
- Tests that verify that a system is working as expected, i.e. continuous functional tests, also known by a number of other names such as: synthetic monitoring, semantic monitoring, production scripted testing, and continuous verification. Think ping on steroids - automated probes running continuously against services & APIs to test key user journeys.

A suitable executor implementation could trigger the artillery tests with flexiblity to pull from git repo or pass configuration file as parameter to the executor.

**Comment by tkonieczny** [comment]
Artillery executor: https://github.com/kubeshop/testkube-executor-artillery
Manual and examples: https://kubeshop.github.io/testkube/executor-artillery/
Looks like the issue wasn't updated, and the Artillery executor is now available, so I'm closing it
