### ISSUE TITLE
Dashboard - font color contrast makes text unreadable

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1204]
On selection 
Right hand-side green text is unreadable 

<img width="744" alt="image" src="https://user-images.githubusercontent.com/30776/161476107-4058736d-fba8-4107-902e-6f61584e3b82.png">

**Comment by donnalux** [comment]
**UX Design:**
https://www.figma.com/file/K7PwsINvkMrs8mvmkjC0wf/TestKube?node-id=1179%3A5702
