### ISSUE TITLE
API response uses `_` key

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1207]
**Describe the bug**
convention is to use `camelCase` in key names

latest execution: 

<img width="802" alt="image" src="https://user-images.githubusercontent.com/30776/161531500-b5a77545-1667-4080-8c1f-b16e2cca0118.png">

**Comment by exu** [comment]
@vsukhin @Toxer10

**Comment by Toxer10** [comment]
> @vsukhin @Toxer10 FYI

Once `latest_execution` is changed to `latestExecution` - let me know, will change this field on the frontend

**Comment by vsukhin** [comment]
ok, will fix
