### ISSUE TITLE
Variable obfuscation

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1220]
**Describe the enhancement you'd like to see**
As a user I want to be able to that a certain variable be obfuscated "*****" from all logs and also it's value not be shown when I'm listing all the variable values.
Depends on https://github.com/kubeshop/testkube/issues/1217

Also as user, I can always change or delete this variable but I can't ever retrieve it's current value.

**Comment by rangoo94** [comment]
Looks like it's done in https://github.com/kubeshop/testkube/issues/2159.
