### ISSUE TITLE
Authentication for API and UI

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1272]
### Goal
Allow users that expose Testkube (e.g., to the Internet) to configure an Authentication layer in order to control who has access to it. 

### UI UX
As a user I would be able to use the OAuth provider that was configured when Testkube was installed and I would see something like this:
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/13501228/163405962-de805a8c-01b3-4f7a-b3b9-19bbe1074bb4.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/13501228/163406002-08d340b0-e161-43f2-a05d-69c2020daa87.png">

After login in, I would be able to log out and to also copy the config necessary to configure my CLI auth.

### CLI UX
**Allow authentication to be token based.**
It should be possible to configure by doing `export TESTKUBE_SERVER=https://pepperoni.testkube.io`  & `export TESTKUBE_TOKEN=eyGFaxd.......`
or  by doing `kubectl testkube config set TESTKUBE_SERVER https://pepperoni.... TESTKUBE_TOKEN eyGFaxdd....`

After Testkube is installed in the cluster, there should be a message printout with the CLI command that the user could copy so that he could connect to it. 

### Cluster installation UX
All configuration necessary must be done only using helm values with requiring much effort from the user.
Great documentation on which values to pass are very important here. Our Documentation should be very similar to this one from DroneCI https://docs.drone.io/server/provider/github/

Linked issues:
https://github.com/kubeshop/testkube/issues/1354
https://github.com/kubeshop/testkube/issues/1347

**Comment by vsukhin** [comment]
And actually we can define scopes for each method in OpenAPI spec like in one of the examples above

**Comment by TheBrunoLopes** [comment]
@vsukhin can you add all the issues that were created as a result of this one here? It gets harder to track what's the ongoing work otherwise.
Even though the other issues will implement the features mentioned here. Don't remove the requirement spec that was written here, if we delete it, it's gets also hard to see what's the intended user experience without going through different issues. We should copy, but not delete the original.

**Comment by vsukhin** [comment]
@TheBrunoLopes Restored and linked
