### ISSUE TITLE
Dashboard - Stretch log output "window"  

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1288]
**Describe the enhancement you'd like to see**

As a tester I want to see as much as possible from log output. 

I think at least we should stretch to bottom of browser window (flex?) 

<img width="1673" alt="Zrzut ekranu 2022-04-13 o 09 28 34" src="https://user-images.githubusercontent.com/30776/163123412-7594228d-3f89-4e83-ad6e-63fcadc1cfcb.png">

@donnalux could we consider stretching a little to the left and right? Does it have sense?

**UX Design:**
Disregard the copy and download icon buttons on the screens for now. TBC on when/if that work will be completed.

https://www.figma.com/file/K7PwsINvkMrs8mvmkjC0wf/TestKube?node-id=1667%3A15685

**Comment by donnalux** [comment]
@exu I've added this to design backlog, definitely needs work, let me noodle on it for a bit...
