### ISSUE TITLE
Helm Chart : Please Include nodeSelector and tolerations for minio deployment in testkube-api helm chart.

### ISSUE THREAD

**Issue by Garvit-Jethwani** [kubeshop/testkube#1300]
**Describe the enhancement you'd like to see**
For adding toleration to minio pod, tolerations in spec of template of minio.yaml is needed in testkube-api helm chart.

**Additional context**
For deploying to minio pod in tainted nodes, there is need of setting toleration, but in deployment there is no field tolerance and nodeSelector in [minio.yaml](https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/templates/minio.yaml) and its corresponding values.yaml

**Comment by vsukhin** [comment]
Hey, @Garvit-Jethwani Does it work for you https://github.com/kubeshop/helm-charts/pull/137?

**Comment by Garvit-Jethwani** [comment]
@vsukhin Yes that will do it. Thanks a lot.
