### ISSUE TITLE
LogOutput in dashboard showing wrong error message

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1324]
**Describe the bug**
When no logs are yet available from the execution, the dashboard shows the following error.

This issue is easier to find when running a cluster in the cloud (GKE in my case) as they're generally slower than local clusters, so the error shows for a long whil.

```
{"type":"error","content":"unable to parse requirement: values[0][job-name]: Invalid value: \"sso/executionser-satyr\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')"}
```

**To Reproduce**
1. Run a (Cypress) test
2. Check instantly the LogOutput of the execution in the browser  

**Version / Cluster**
- Which testkube version? 1.0.5
- What Kubernetes cluster? GKE
- What Kubernetes version? 1.23.1

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/164201920-e3d9ecb5-2cfe-4541-9f8f-dcfaa15b52a7.png)

**Comment by TheBrunoLopes** [comment]
@Toxer10 @exu is this still an issue ?

**Comment by exu** [comment]
We can't reporoduce it anymore - so closing.
