### ISSUE TITLE
Build docker images for arm64

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1352]
**Is your feature request related to a problem? Please describe.**
On my Linux Arm64 machine, the docker images for Testkube cannot start, with the following error 

```
pod/testkube-operator-controller-manager-7f45b5d87c-nz2x9   1/2     CrashLoopBackOff   25         10h
pod/testkube-dashboard-6d48b8dd9c-4tgfg                     0/1     CrashLoopBackOff   25         10h
pod/testkube-api-server-6d47b7b7d4-lztks                    0/1     CrashLoopBackOff   25         10h
```

Logs from pods

```
ubuntu:~$ k logs pod/testkube-dashboard-6d48b8dd9c-4tgfg
standard_init_linux.go:219: exec user process caused: exec format error
```

Which is an error related to different target machine of the docker image

**Describe the solution you'd like**
Add linux/arm64 target for the docker images built

**Comment by exu** [comment]
I would go with 
- linux x64 (is now)
- linux arm64
- mac m1 
- mac intel x64 chips 
- NTH: windows x64 (need to research)

**Comment by aabedraba** [comment]
Instructions for platforms 
https://github.com/containerd/containerd/blob/v1.4.3/platforms/platforms.go#L63-L106

**Comment by ypoplavs** [comment]
Docker images for `Testkube` are now being built for both platforms.
