### ISSUE TITLE
Cannot run tests from the dashboard

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1353]
**Describe the bug**
When trying to run a test from the dashboard, which has been accessed through `kubectl-testkube dashboard`, running tests does not work. 

From the console, I get this error 

_Access to fetch at 'https://demo.testkube.io/results/v1/tests/cypress-example/executions' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

Perhaps the button has hardcoded the url demo.testkube.io?

**Comment by aabedraba** [comment]
![image](https://user-images.githubusercontent.com/27779735/164433361-854d02a3-a50f-4af4-816b-c30c8afd92a2.png)

**Comment by vsukhin** [comment]
Yeah to run demo.testkibe.io from localhost you need to have CORS permissions. And this is default value for api url

**Comment by aabedraba** [comment]
@vsukhin but this dashboard is spun up from kubectl-testkube dashboard, I did not access demo.testkube.io whatsoever. 

I think the button's is hardcoded to demo.testkube.io when it should be the value of localhos:8080, no?

**Comment by vsukhin** [comment]
Yes, sounds like, it's hardcoded, it should be a var for it in Helm values

**Comment by exu** [comment]
@pavloburchak @Toxer10 added to v1.1 project
