### ISSUE TITLE
Make `goreleaser` builds run in parallel for `kubectl-testkube` plugin

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1356]
For now, `goreleaser` builds are made in sequential order which results in quite long build times

We could make them run in parallel to speed up.

**Comment by exu** [comment]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/30776/164449921-808d0149-33cf-49a4-9cac-4e459fab0303.png">

Currently it's about 12min

**Comment by ypoplavs** [comment]
Implemented GoReleaser Pro feature to build binaries for each OS in parallel. Now the build time takes 6-7 min. 
PR was merged.

<img width="933" alt="Screenshot 2022-05-10 at 16 55 53" src="https://user-images.githubusercontent.com/45286051/168016677-4d7cdc22-8f5e-4390-8c2e-b900c705cbe0.png">
