### ISSUE TITLE
Helm installation guide not working

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1360]
**Describe the bug**
Following the guide to install [Testkube through Helm](https://kubeshop.github.io/testkube/installing/#manual-testkube-helm-charts-installation) does not work.

The following error is returned 

```sh
✗ helm install --create-namespace my-testkube testkube/testkube

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]
```

**To Reproduce**
1. Follow instruction from [Testkube helm installation](helm repo add testkube https://kubeshop.github.io/helm-charts)
2. Failure at second step should be expected

**Version / Cluster**
- Which testkube version? 1.0.8
- What Kubernetes cluster? Minikube, Kind
- What Kubernetes version? 1.23

**Comment by vsukhin** [comment]
We need to update this doc with dependency list from https://github.com/kubeshop/helm-charts/tree/main/charts/testkube

**Comment by nicufk** [comment]
It seems that cert manager is not installed in the cluster, cert manager is a dependency
