### ISSUE TITLE
Improve Slack integration

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#1394]
Register a testkube-bot to the slack app store and improve user experience on integration with the testkube

**Comment by donnalux** [comment]
![Testkube_icon_slack](https://user-images.githubusercontent.com/102221761/167620237-77307c09-238e-4afa-95d4-c684baeef222.svg)

Let me know if you need a different format or size. From what I can see 36x36px is the size slack apps use.

**Comment by donnalux** [comment]
[Slack_Payload.txt](https://github.com/kubeshop/testkube/files/8661239/Slack_Payload.txt)
