### ISSUE TITLE
Add GitHub App authentication for test repos

### ISSUE THREAD

**Issue by joebowbeer** [kubeshop/testkube#1395]
**Describe the enhancement you'd like to see**

Add GitHub App authentication for test repos. This is particularly useful for organizations with private repos.

https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps#about-github-apps

Compared to PAT auth, which is the only form supported now:
* GitHub App provides fine-grained control to a specific set of private repos
* GitHub App does not need a dedicated (bot) user

**Additional context**

See:
* https://github.com/argoproj/argo-cd/blob/master/docs/user-guide/private-repositories.md#github-app-credential

**Comment by vsukhin** [comment]
hey, @joebowbeer
Sound like a great suggestion. As you might see, we've already strated working on different authentication tasks. For example, recently we provided ingress configurations for our UI to work with github OAuth, and planning to work on CLI Oauth in next couple of weeks   https://github.com/kubeshop/testkube/issues/1354. Definitely, yuor request will be a part of these efforts ;) Really glad to see such requests from out community!

**Comment by TheBrunoLopes** [comment]
Looks like we did OAuth on the other ticket and we forgot to close this one
@joebowbeer have you had the chance to take a look at our OAuth feature ? :)

**Comment by TheBrunoLopes** [comment]
Hey Joe!
We have plans to update the test sources, but I wanted to check if that aligns with your use case. Could I show you what we have planned on a quick call and so you can tell me if that would be useful for you.
Leaving me callendly link here: https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by ahmedimf1** [comment]
@TheBrunoLopes 
Was there an implementation that replaces the need for username and Personal Access Token? I would like to avoid using my credentials in the cluster and, maybe, instead use GitHub apps:

https://docs.github.com/en/apps/using-github-apps/authorizing-github-apps

**Comment by joebowbeer** [comment]
@TheBrunoLopes can you reopen?

I'm not seeing support for GitHup App auth, which I think would be the preferred method for many users

https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-admin-guide/github-app-auth

**Comment by rangoo94** [comment]
Hi @ahmedimf1 and @joebowbeer!

We are working to provide the GitHub App integration, but it will be only a part of the Testkube Cloud and Enterprise offerings.

Due to the nature of GitHub Apps, the solution will need to be strictly connected to the user and token management, therefore we are unable to provide it as part of the Open Source version, as we support it only in the Cloud.

I hope that we will deliver it soon, as it will heavily simplify the user flow.

Cc: @TheBrunoLopes

**Comment by marcportabellaclotet-mt** [comment]
That would be a nice feature.
Meanwhile we could use some k8s cron to automatically update the secret used in testkube.
Some time ago I wrote [a token generator](https://github.com/marcportabellaclotet-mt/gh-app-token-generator) , which can be used to create github tokens with github app credentials

**Comment by joebowbeer** [comment]
https://docs.testkube.io/articles/test-workflows-content#using-github-app
