### ISSUE TITLE
Document declarative setup for test repos

### ISSUE THREAD

**Issue by joebowbeer** [kubeshop/testkube#1396]
**Describe the enhancement you'd like to see**

How to configure testkube declaratively using GitOps?

Please document how to add test repo authentication to the configuration via helm or kustomize.

Documenting the relevant config maps and secrets would be a good first step.

**Additional context**

Example declarative setup docs:

https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/

**Comment by aabedraba** [comment]
We've covered these instructions for both ArgoCD and Flux here: https://docs.testkube.io/articles/gitops-overview
