### ISSUE TITLE
Docs for CRDs: `Test` and `TestSuite`

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1407]
As a software engineer (contributor) i need to know about internals of CRDs in testkube

Describe possible fields and meaning of: 
- `Test` CRD 
- `TestSuite` CRD

**Comment by vsukhin** [comment]
And Executor / Webhook

**Comment by vLia** [comment]
Addressed with: https://github.com/kubeshop/testkube/commit/c699e48960b7fbf3d9da6a982cddd44e195489f3
