### ISSUE TITLE
Ask for Telemetry permission when using the CLI for the first time 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1412]
Resuming this is what we are planning to do:
- [x] Change welcoming message when installing Testkube to:
Welcome to
<img width="603" alt="image" src="https://user-images.githubusercontent.com/13501228/170250461-e08b3f4c-9be0-4df5-99b1-aea77f7685e9.png">
To help improve the quality of Testkube, we collect anonymous basic telemetry data.

Head out to https://kubeshop.github.io/testkube/telemetry/ to read our policy or feel free to disable telemetry by typing:
testkube disable telemetry
Happy Testing! 🚀

- Make sure that the only data that is gathered is:
  - [x] Nº of CLI installations
  - [x] Nº of unique CLI usages in a day
  - [x] Nº of installations to a cluster
  - [x] Nº of unique active cluster installations
  - [x] Nº of people who disables telemetry. (change the name on the cli from analytics to telemetry to be consistent)
  - [x] Nº of unique sessions in the UI

- [x] Update the docs https://kubeshop.github.io/testkube/telemetry/ with the new command renaming and data structure if something changed. 

- [ ] If the user does `testkube disable telemetry` or already has telemetry disabled on the CLI, make sure this also applies when the user is installing Testkube in the cluster.

cc: @kubeshop/testkube 

---- EDIT ------

**Describe the solution you'd like**

Could the testkube cli ask for analytics permissions when using the command for the first time?

**Comment by aabedraba** [comment]
From the gcloud command install 

![image](https://user-images.githubusercontent.com/27779735/165764829-6e5f0c57-2790-4c1a-b60c-e5fcb139e6b3.png)

**Comment by TheBrunoLopes** [comment]
@olensmar @dimonlex @aabedraba 
Another approach could be that when user is installing Testkube, Instead of a user prompt, we can print that we track usage analytics and that they can disable it with the following command
I was wondering how this works when the CLI is running inside a CI/CD system were we can't make prompts ? 

@exu @vsukhin When Testkube is added to a docker image or installed in an automated manner, how could the user configure this process to not have analytics? 🤔

One example of a non blocking flow, would be to show this at the moment of installation:
Welcome to Testkube
<img width="806" alt="image" src="https://user-images.githubusercontent.com/13501228/168322182-b2d3a1dd-8b33-4791-90b8-3542eb5d1311.png">
To help improve the quality of Testkube, we collect anonymous basic telemetry data. Head out to https://kubeshop.github.io/testkube/telemetry/ to read our policy or feel free to disable Telemetry by typing: 
`testkube disable telemetry`
Happy Testing! 🚀

Thoughts?

**Comment by TheBrunoLopes** [comment]
If the user disabled analytics on the CLI we should also disable analytics on the cluster it's connecting.

**Comment by TheBrunoLopes** [comment]
Lets also remove API URIs from server. Instead the server sends an health check each 30m.
From CLI only things checked could be:
- Installation of CLI.
- Installation of Cluster
- If it was used that day.
- Analytic disables.

**Comment by aabedraba** [comment]
For CI installations `testkube install --disable-analytics` could work, although it's not very user-friendly in my opinion. 

Pherhaps an alternative solution could be: 
1- prompt for analytics and wait for yes
2- if in 10 seconds there's no answer, assume it's a no and proceed

**Comment by TheBrunoLopes** [comment]
Thanks for the feedback @aabedraba 
Resuming this is what we are planning to do:
- Change welcoming message when installing Testkube to:
Welcome to
<img width="603" alt="image" src="https://user-images.githubusercontent.com/13501228/170250461-e08b3f4c-9be0-4df5-99b1-aea77f7685e9.png">
To help improve the quality of Testkube, we collect anonymous basic telemetry data.

Head out to https://kubeshop.github.io/testkube/telemetry/ to read our policy or feel free to disable telemetry by typing:
testkube disable telemetry
Happy Testing! 🚀

- Make sure that the only data that is gathered is:
  - Nº of CLI installations
  - Nº of unique CLI usages in a day
  - Nº of installations to a cluster
  - Nº of unique active cluster installations
  - Nº of people who disables telemetry. (change the name on the cli from analytics to telemetry to be consistent)
  - Nº of unique sessions in the UI

- Update the docs https://kubeshop.github.io/testkube/telemetry/ with the new command renaming and data structure if something changed. 

- If the user does `testkube disable telemetry` or already has telemetry disabled on the CLI, make sure this also applies when the user is installing Testkube in the cluster.

cc: @kubeshop/testkube

**Comment by exu** [comment]
message after installing with `tk install`: 

<img width="434" alt="image" src="https://user-images.githubusercontent.com/30776/173004903-d6d242d1-e9c7-436f-b7ef-98b1e6dce5c6.png">

**Comment by exu** [comment]
@TheBrunoLopes FYI extracted "If the user does testkube disable telemetry or already has telemetry disabled on the CLI, make sure this also applies when the user is installing Testkube in the cluster" task into separate issue https://github.com/kubeshop/testkube/issues/1747

New dashboard based on Segment.io and PostgreSQL Warehouse here https://app.databox.com/datawall/3356825606efd432131da8ebd1e15115062beb474
