### ISSUE TITLE
Dashboard - Add error message somewhere in case of failing test 

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1415]
**Describe the enhancement you'd like to see**
There is no error message from API - just log output visible in Test

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/30776/165924625-314096a6-50c5-4ea3-8113-ab92ed7f6d89.png">

error message in `executionResult`

<img width="806" alt="image" src="https://user-images.githubusercontent.com/30776/165924735-b247e572-4d5d-46bf-8739-110d38e5a685.png">

**Comment by donnalux** [comment]
@exu is UX still required? this is what I'm seeing now in the logs on that example you provided:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/102221761/167820290-cd5cc5ee-5fb7-43de-902d-7978f3d5d69a.png">

**Comment by donnalux** [comment]
Fixed
