### ISSUE TITLE
Cypress test not starting

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1416]
**Describe the bug**

<img width="658" alt="image" src="https://user-images.githubusercontent.com/30776/165925795-0473a0ab-2401-4fd1-84e7-ad43e7e7635e.png">

```
cat examples/test-git-dir.json | go run cmd/agent/main.go
{"type":"event","content":"running test [6183cec12acc0cb7de5c249e]"}
{"type":"error","content":"npm install error: process error: exec: not started"}
exit status 1
```

**Version / Cluster**
- Demo cluster 
- local go build also looks wasted

**Comment by vLia** [comment]
@vsukhin I added this commit for the cypress executor, but would be nice if someone double-checked if it actually fixed the issue: https://github.com/kubeshop/testkube-executor-cypress/commit/4649d22a526e2b72318b1f79d0aa86864f46ce60 as there were other parts of the test failing from what I can remember
