### ISSUE TITLE
Testkube Github Action

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1421]
**Create a Testkube Github action that allows users to:**
- **CRUD** Tests/TestSuites
- Trigger Tests/TesSuite Runs. The runs can be sync or async.

AC:
- Write a Doc Section on how to use the Testkube Github action.
- Write Blogpost to showcase how to create a pipeline in github showcasing all of the features of a Testkube's github action.
- We should implement this action in our CI/CD on github
- Authentication should be done using the api token feature developed in https://github.com/kubeshop/testkube/issues/1272.
- No manual Ingress configuration should be required.

**Comment by olensmar** [comment]
Would be great if this doesn't require kubeconfig/kubectl access - perhaps just some kind of API key!?

**Comment by TheBrunoLopes** [comment]
Agree. added to the AC

**Comment by vsukhin** [comment]
Will move doc and blogpost into separate ticket
