### ISSUE TITLE
UI - TestSuite Creation

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1423]
- As a user I want create a **TestSuite** using existing tests from my cluster.
- Use should also be able to add delays in between the tests.
- Basic and Secret variables should be possible to be added at the moment of TestSuite creation
- Before the resulting TestSuite CRD is sent to the cluster. It should be show, possible to edit, and possible to be copied elsewhere.
- After the user reviews the CRD to be saved in the cluster. He should finally press Create

AC:
- Mention this feature in in the [docs here](https://kubeshop.github.io/testkube/testsuites-creating/) as a possible (and easiest) path on how to create a TestSuite)
- Create a blogpost about creating Testsuites in Testkube.

**Comment by Toxer10** [comment]
Closing as implemented long time ago
1) Creating form
![Image](https://user-images.githubusercontent.com/25991946/188586990-c419946a-0af4-4d7f-960b-9de9b805e96b.png)
2) Adding tests to a test suite, adding variables
![Image](https://user-images.githubusercontent.com/25991946/188587272-0ea70734-d641-4260-bb7d-b260045f8d2a.png)
