### ISSUE TITLE
Run a Test with multiple parallel jobs in the same execution

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1431]
As a performance engineer I want to run results from multiple pods and to merge results back as single output result

**Comment by TheBrunoLopes** [comment]
Seems like this feature of parallel jobs could be "exposed" to the user somehow
https://kubernetes.io/docs/concepts/workloads/controllers/job/#parallel-jobs

**Comment by lreimer** [comment]
That was the initial idea, and under the hood it will use these features. But if you only use the K8s standards using `.spec.completions` and `.spec.parallelism` this will look like individual executions, even though it was the same execution.

**Comment by TheBrunoLopes** [comment]
closing. will be done in https://github.com/kubeshop/testkube/issues/2356
