### ISSUE TITLE
Testkube cypress init container stuck in intialization

### ISSUE THREAD

**Issue by pythi0s** [kubeshop/testkube#1458]
**Describe the bug**
Following the [docs](https://kubeshop.github.io/testkube/cypress-executors/#creating-a-new-test), I was trying to just check out Testkube for Cypress. 
When I execute `kubectl testkube start test kubeshop-cypress` command, testkube pod fails as its init container is stuck in initialization:
```
jack@sparrow:~/Documents$ kubectl get pods -n testkube
NAME                                                    READY   STATUS       RESTARTS   AGE
6273e1745f5a5e3c2a4ddec4-6jwfh                          0/1     Init:Error   0          2m48s
jetstack-cert-manager-6f774b8586-d7zk7                  1/1     Running      0          37m
jetstack-cert-manager-cainjector-dd4bf5c4c-shcrl        1/1     Running      0          37m
jetstack-cert-manager-webhook-85c46cfcc4-hg8qg          1/1     Running      0          37m
testkube-api-server-6d9cb6b788-94qcn                    1/1     Running      0          36m
testkube-dashboard-7f6f6dc6f-vl5vn                      1/1     Running      0          36m
testkube-minio-testkube-79d99f9746-h8jp6                1/1     Running      0          36m
testkube-mongodb-5d766b7d58-gdtm7                       1/1     Running      0          36m
testkube-operator-controller-manager-78bd65f589-j95sx   2/2     Running      0          36m
```
Upon checking logs, I found this error but not able to figure out why:
```
jack@sparrow:~/Documents/istio$ kubectl logs -n testkube 6273e1745f5a5e3c2a4ddec4-6jwfh 6273e1745f5a5e3c2a4ddec4-init 
{"type":"event","content":"running test [6273e1745f5a5e3c2a4ddec4]"}
{"type":"error","content":"process error: exit status 128\noutput: Cloning into 'repo'...\nfatal: unable to access 'https://github.com/kubeshop/testkube-executor-cypress.git/': SSL: no alternative certificate subject name matches target host name 'github.com'\n"}
```

**To Reproduce**
1. Follow the docs to install Testkube
2. Try out Cypress example

**Expected behavior**
Tests should be run successfully.

**Version / Cluster**
- Which testkube version? 
```
Client Version 1.0.21
Server Version v1.0.21
Commit 0ab7c30d4690aac76147ea833983feb63e53c76f
Built by goreleaser
Build date 2022-05-05T11:36:20Z
```
- What Kubernetes cluster?
**Local Minikube**
```
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
cpus: 4
memory: 4096
```
- What Kubernetes version?
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

Can anyone help me in noticing what I am doing wrong here? Any help is appreciated!

**Comment by TheBrunoLopes** [comment]
Hi @pythi0s thank you for reporting your issue.
We are looking into that and will comeback to you asap.

**Comment by vsukhin** [comment]
It might be Minikube related issue. I saw sometimes issues with connection to Internet from Minikube including DNS problems on my Ubuntu laptop. The only thing that really helped was stopping/starting and even deleting k8s cluster in Minikube, in worse cases I had to reboot my laptop

**Comment by vsukhin** [comment]
Hey @pythi0s Did it help?

**Comment by pythi0s** [comment]
Hey @vsukhin, apologies for replying so late. I just tried deleting an entire minikube cluster and starting again from scratch. I am still getting same error. Might be an issue with my machine.
Anyway, thanks for your responses, closing this issue.
