### ISSUE TITLE
Remove webpack config from dashboard

### ISSUE THREAD

**Issue by hamzahsn** [kubeshop/testkube#1461]
**Why should it be implemented?**
As it's not possible to contribute to `testkube-dashboard`, I decided to raise the issue here:

The file `webpack.config.js` in the root project is not actually necessary to bundle the project as CRA already has its `webpack` config behind the scenes and working perfectly so this file is basically unnecessary and it might cause some issues in the future. 

**Describe the improvement**

Useless code for the configuration.

**Comment by TheBrunoLopes** [comment]
@pavloburchak @Toxer10 not sure if related with https://github.com/kubeshop/testkube/issues/1462

**Comment by Toxer10** [comment]
Closed in 1.5.3
