### ISSUE TITLE
Remove useless config in dashboard

### ISSUE THREAD

**Issue by hamzahsn** [kubeshop/testkube#1462]
**Why should it be implemented?**
As it's not possible to contribute to `testkube-dashboard`, I decided to raise the issue here:

`.babelrc` in the root project is not necessary to transpile any code as CRA already gives us this feature working like a charm and as well it might cause an issue in the future.

**Describe the improvement**

Useless config code.

**Describe the improvement**
 
**Additional context**
Add any other context about the problem here if needed.

**Comment by TheBrunoLopes** [comment]
Hi @hamzahsn thanks for reporting this issue.
We are looking into this.
On a similar note, are you finding it easy to use testkube-dashboard ?

**Comment by TheBrunoLopes** [comment]
@Toxer10 @pavloburchak is this issue important, complex or ?

**Comment by Toxer10** [comment]
Closed in 1.5.3
