### ISSUE TITLE
Proxy Settings for Running the Example/Sample Cypress Tests behind a Corporate Proxy

### ISSUE THREAD

**Issue by s-king94** [kubeshop/testkube#1475]
**Describe the bug**
Getting connection refused error when trying to clone the example testkube repository from within containers for running the tests.

{"type":"event","content":"running test [627519ea0861f671e2068408]"}
{"type":"error","content":"process error: exit status 128\noutput: Cloning into 'repo'...\nfatal: unable to access 'https://github.com/kubeshop/testkube-executor-cypress.git/': Failed to connect to github.com port 443 after 5 ms: Connection refused\n"}

**To Reproduce**
1. Follow the docs to install Testkube
2. Try out Cypress example

**Expected behavior**
Tests should be run successfully.

**Version / Cluster**
- Which testkube version?
Client Version 1.0.13
Server Version v1.0.13
Commit b0449a5827e7c7f7c345184fa6bbfff30f0d4805
Built by goreleaser
Build date 2022-04-28T04:55:11Z

- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
KubeAdm
- What Kubernetes version?
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

Any help in this regard would be heartily appreciated. Thanks in advance!

**Comment by vsukhin** [comment]
hey @s-king94 Let's us think a bit, not a typical usage case for our framework, but probably we will see it frequently for enterprise users

**Comment by s-king94** [comment]
hi @vsukhin , there is perhaps a way to set the proxy from within the containers. 
We had reproduced the issue on a curl docker image's container as well and fixed it after setting the proxy. Something along the same line might work for the testkube containers as well. Using "export https_proxy=<proxy-url>" helped us to set the proxy when we had the interactive shell control of the container.
An option to set the proxy in the testkube cli would really help.

**Comment by vsukhin** [comment]
Sure, thing @s-king94. Thank you for this suggestion. I will work on this task at the beginning of next week

**Comment by vsukhin** [comment]
Hey @s-king94 We've added to new parameters for Run command for both test and test suite, `http-proxy` and `https-proxy`. We propagate values from these parameters to HTTP_PROXY and HTTPS_PROXY environment variables of executor containers

**Comment by vsukhin** [comment]
You're welcome, @s-king94 !
