### ISSUE TITLE
Use `ogen-go` instead of `swagger-codegen`

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1479]
**Describe the enhancement you'd like to see**

Looks like ogen could be better fit that swagger coode get for our usage. 

**Additional context**

Reimplement model on top of ogen and refactor models for testkube openapi spec

**Comment by vsukhin** [comment]
Generation is failed, not clear what statement is wrong. Submitted an issue https://github.com/ogen-go/ogen/issues/414

**Comment by vsukhin** [comment]
We leave it for team discussion

**Comment by rangoo94** [comment]
Looks like it was marked as Done in Testkube v1.3 project, @vsukhin - is there still some discussion expected?
