### ISSUE TITLE
Deleting a test keeps executions

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#1515]
**Describe the bug**
When deleting a test with multiple executions, and creating another test with the same name, the executions show up under the new test.

**To Reproduce**
1. Create test: `kubectl testkube create test --file "example-project.xml" --type "soapui/xml" --name test`
2. Run test: `kubectl testkube start test -f test`
3. Check UI and see one execution for test test 
4. Delete test: `kubectl testkube delete test test`
5. Check UI and see test gone
6. Create test with same name: `kubectl testkube create test --file "example-project.xml" --type "soapui/xml" --name test`
7. Check UI and see new test with older execution

**Expected behavior**
The newly created test has no executions associated

**Version / Cluster**
latest version, local kind cluster

**Comment by olensmar** [comment]
@exu @TheBrunoLopes suggest we prioritize this, it's very annoying... we should at least connect results to some internal ID of a test - and not the name (since the name could potentially change anyway) - so that old results don't get associated with the wrong test...
