### ISSUE TITLE
`testkube generate test-crds` needs access to "KUBENERETES_MASTER" env variable

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1518]
**Describe the bug**
When running `testkube generate test-crds`, apparently Testkube needs access to kubectl or at least some cluster environment vairables. 

This breaks the integration with ArgoCD as Testkube would be running from inside a pod that does not have direct access to the container. 

The generate command should be agnostic of the cluster to be able to run it. 

Would that be possible? 

**To Reproduce**
1. Run the `testkube generate test-crds` in an environment that does not have a Kubernetes cluster

**Comment by vsukhin** [comment]
cluster check was removed
