### ISSUE TITLE
Testkube `generate` should support TestSuites

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1519]
**Is your feature request related to a problem? Please describe.**
Currently `testkube generate` only supports generates test CRDS; as a user running ArgoCD integration, I want to also generate CRDS for TestSuites.

**Comment by aabedraba** [comment]
Currently `testkube generate` helps creating CRDs out of Tests. The TestSuites would need to be created manually.

**Comment by vsukhin** [comment]
we have more interesting task to implement https://github.com/kubeshop/testkube/issues/3785
