### ISSUE TITLE
GitHub action to trigger execution of a test

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#153]
As a user I want to execute test scripts as part of my GitHub CI - a corresponding action should allow me to do this

**Comment by olensmar** [comment]
I'm guessing this requires us to include an ingress controller - as the github action will need to call our api-server from the outside?!

**Comment by olensmar** [comment]
this should be possible today by invoking kubectl kubtest from github action - perhaps we can start by documenting this approach?

**Comment by TheBrunoLopes** [comment]
done
