### ISSUE TITLE
Order Tests and TestSuites by last execution time

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1552]
Tests and TestSuites should be sorted based on the following priorities:
- Never Run first
- Then has the most recent execution **started or finished** (this allows that in progress tests also appear on top)

**Comment by olensmar** [comment]
How about simply adding sort-buttons to the top of each column? In that case users can choose what to sort on - default could be as suggested above!?

**Comment by fivenp** [comment]
We actually want: 

Sort by 'last_update' (execution, or creation date))

Example: 

I have a very old test which never ran. 
I have a recently created a test 
I have another test that was finished right now

Order will be 
1. Recently executed
2. Recently created
3. Old test never run
