### ISSUE TITLE
`testkube-operator` is restarting

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1553]
```sh 
kl testkube-operator-controller-manager-754455f74d-jb7sj --previous

error: previous terminated container "kube-rbac-proxy" in pod "testkube-operator-controller-manager-754455f74d-jb7sj" not found
2022-05-19T17:03:49.151Z	ERROR	controller-runtime.manager	Failed to get API Group-Resources	{"error": "Get \"https://10.11.240.1:443/api?timeout=32s\": dial tcp 10.11.240.1:443: i/o timeout"}
sigs.k8s.io/controller-runtime/pkg/manager.New
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/manager/manager.go:312
main.main
	/workspace/main.go:81
runtime.main
	/usr/local/go/src/runtime/proc.go:250
2022-05-19T17:03:49.151Z	ERROR	setup	unable to start manager	{"error": "Get \"https://10.11.240.1:443/api?timeout=32s\": dial tcp 10.11.240.1:443: i/o timeout"}
main.main
	/workspace/main.go:90
runtime.main
	/usr/local/go/src/runtime/proc.go:250
```

Strange error

looks like there was 5 restarts in 15h 

```
kgp
NAME                                                    READY   STATUS    RESTARTS   AGE
oauth2-proxy-85c4b9fbf-ctpwj                            1/1     Running   0          15h
testkube-api-server-5f5dd7657b-tb4vw                    1/1     Running   0          15h
testkube-dashboard-77d8d794f9-xhvbg                     1/1     Running   0          15h
testkube-minio-testkube-64cd475b94-qlldb                1/1     Running   0          15h
testkube-mongodb-5d95f44fdd-wsg6t                       1/1     Running   0          15h
testkube-operator-controller-manager-754455f74d-jb7sj   2/2     Running   5          15h
```

**Comment by vLia** [comment]
Observing the logs on testkube-dev, we can see there was a leader election failure at 2022-05-24T12:22 :
https://console.cloud.google.com/logs/query;cursorTimestamp=2022-05-24T12:22:45.659116070Z;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22testkube-328312%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22testkube-dev%22%0Aresource.labels.namespace_name%3D%22testkube%22%0Alabels.k8s-pod%2Fcontrol-plane%3D%22controller-manager%22%0Atimestamp%3D%222022-05-24T12:22:35.658727944Z%22%0AinsertId%3D%22ndulz2mm8bkeb25f%22;timeRange=2022-05-12T13:10:10.309Z%2F2022-05-31T10:10:10.309218Z?project=testkube-328312

At the same time we can observe the K8s cluster logs went silent for 4 minutes:
https://console.cloud.google.com/logs/query;cursorTimestamp=2022-05-24T12:22:33.247590Z;query=resource.type%3D%22k8s_cluster%22%0Aresource.labels.project_id%3D%22testkube-328312%22%0Aresource.labels.location%3D%22us-east1-b%22%0Aresource.labels.cluster_name%3D%22testkube-dev%22%20severity%3E%3DDEFAULT%0Atimestamp%3D%222022-05-24T12:22:33.247590Z%22%0AinsertId%3D%226dbf3b6c-b809-41f6-9410-844e808d73f8%22;timeRange=2022-05-24T12:21:11.221Z%2F2022-05-24T12:21:11.221Z--PT1H?project=testkube-328312

And shown "Error creating: insufficient quota to match these scopes" errors in 3 minutes.

Once the IP addresses quota and the CPU quota was increased, the live migration of pods worked, and the errors were gone.

Will create follow-up issues to improve logging and monitoring.

**Comment by vLia** [comment]
The error did not appear for a day after quota increase. Closing this ticket.
