### ISSUE TITLE
K6 executor doesn't handle errors

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1590]
**Describe the bug**

1. Create failed k6 test (could be check which fails) 
e.g. 
```
import http from 'k6/http';
import { check } from 'k6';

export default function () {
  const baseURI = `${__ENV.API_URI || 'http://google.pl'}`;

  check(http.get(`${baseURI}/joke`), {
    'joke should be about Chuck': r => r.body.includes("Chuck") // this should fail
  });
}
```

2. run it 

3. test execution is successful and shouldn't

![Zrzut ekranu 2022-05-27 o 11 57 36](https://user-images.githubusercontent.com/30776/170677448-6cc7109f-bd82-4b22-bcff-f4a54aafbe51.png)

**Comment by Toxer10** [comment]
Tried it today and it did not work properly.

**Comment by Toxer10** [comment]
```
export default function () {
  const isFailed = Math.random() > 0.5;
  console.log('isFailed: ', isFailed);

  if (isFailed) {
    fail('Failed 1');
  } else {
    fail('Failed 2');
  }
}
``` 
This test returns `passed` all the time
