### ISSUE TITLE
Multiple testkube dashboards use same API endpoint

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#1605]
When accessing multiple dashboards for the first time they seem to "inherit" the API endpoint of the previously used dashboard - instead of using their own

![image](https://user-images.githubusercontent.com/1917063/171364735-29ca8f31-999e-4c75-a4d5-5f958a1ffdef.png)

**Comment by Toxer10** [comment]
First of all we should have this implemented https://github.com/kubeshop/testkube/issues/1541, then we'll check if we should add something on the frontend side
