### ISSUE TITLE
kubectl-testkube Installation scripts for operating systems

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#161]
It would be great to have possibility to install kubetest plugin from different software management apps
- [x] brew
- [x] deb
- [x] apt 
- [x] chocolatey (https://chocolatey.org/)
- [ ] krew as @Tarick suggested 
- [ ] snap 
- [ ] pacman 
- [ ] dnf
- [ ] scoop
- [ ] yum
- [ ] rpm
- [x] go install
- [x] manually  
- [ ] flatpack
- [ ] appimage

It's tracking ticket for all possible installers (feel free to add separate tickets for particular installers if needed)

**Comment by jasmingacic** [comment]
For the beginning let's add a simple script and this to v1.0.0

**Comment by exu** [comment]
#319 as first task

**Comment by exu** [comment]
HomeBrew support added in #v0.6.17

**Comment by exu** [comment]
For 0.9 #833  #832

**Comment by tkonieczny** [comment]
`chocolatey` is already supported - should also be marked as ready

**Comment by TheBrunoLopes** [comment]
closing this issue as we added support for the most popular package manners.
will create a separate issue in case we decide to add more package managers

**Comment by mhmxs** [comment]
Hey, I was looking for testkube at both [Nix](https://search.nixos.org/packages) and [Krew](https://krew.sigs.k8s.io/plugins/) without any luck :)  Maybe it does make sense to create packages for them.
