### ISSUE TITLE
Start doesn't work for Windows 10 in PowerShell to launch a process

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#1630]
**Describe the bug**
Port forwarding is not working for Windows 10 in PowerShell

**To Reproduce**
1. Run 'kubectl testkube dashboard'
2. In Windows 20 PowerShell
3. See error - start command is not found

**Expected behavior**
port forward kubectl command should be started in background

**Version / Cluster**
- Which testkube version? - 1.2.14
- What Kubernetes cluster? - local Minikube)
- What Kubernetes version? - 1.23.2

**Comment by TheBrunoLopes** [comment]
Great find!
regarding the start command, is`testkube start...` the one that doesn't work ? If so, since it was deprecated in favour of `testkube run...` let's just hide it (and not fix it).

**Comment by vsukhin** [comment]
No, it's for MS Windows own start command
