### ISSUE TITLE
Github Testkube integration

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1639]
**Is your feature request related to a problem? Please describe.**

As a software engineer I want to get feedback for my pipielines as Github comment
We could start with comments for Github but also think about other integrations 

<img width="411" alt="image" src="https://user-images.githubusercontent.com/30776/173075446-e07975c1-74cb-4510-a4b5-e94a5a6c66df.png">

Testkube could add comments for given CICD system 
Or even generate some nice charts or test results

**Comment by rangoo94** [comment]
Running tests easily is now possible in GitHub workflows with the [**Run on Testkube**](https://github.com/marketplace/actions/run-on-testkube) GitHub Action.

**Comment by TheBrunoLopes** [comment]
Great contribution @rangoo94
