### ISSUE TITLE
Possibility to leave Repository path empty

### ISSUE THREAD

**Issue by puukko81** [kubeshop/testkube#1640]
It would be more usable to add tests if Repository path wasn't mandatory field. With some folder structures current functionality may even lead to situation where test can be added only via CLI.

**Comment by exu** [comment]
Hi @puukko81 thanks for getting with that, 
You can omit `--git-path` param and Testkube will use root path of repository then and run against it. 

If you're creating Test from CRD just pass empty path `""`.

Hope it help you.

**Comment by olensmar** [comment]
@exu perhaps this needs to be clarified in the documentation and/or cli help!?

**Comment by exu** [comment]
@pavloburchak please check also dashboard.

**Comment by exu** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/30776/173295213-d7a902c8-def3-49a9-a5c9-2ff611db3c3b.png">
