### ISSUE TITLE
Possibility to define Cypress test case location folder

### ISSUE THREAD

**Issue by puukko81** [kubeshop/testkube#1641]
Test cases may lay either in e2e folder or in integration folder. It seems that Testkube only searches the tests from integration folder.

**Comment by exu** [comment]
Hi @puukko81 I was able to run recent Cypress tests with `Testkube` and `Cypress 10.1.0`
I've just released the new Cypress executor (`v1.1.1`), which is able to run recent E2E-based Cypress tests. 

Make sure your Testkube cypress executor was upgraded to version `1.1.1` 
```
kubectl testkube upgrade 
# .... after a while 

# run this 
kubectl get executor -ntestkube cypress-executor -oyaml | grep image

# you should see such executor image:
  image: kubeshop/testkube-cypress-executor:1.1.1
``` 

Please ping us if it's solving your use case, I will close this issue for now.

Have fun with Testkube 🚀
