### ISSUE TITLE
Integration between Testkube and Argo Rollouts

### ISSUE THREAD

**Issue by eduardhildebrandt** [kubeshop/testkube#1651]
I would like to execute tests before and after a rollout of an application. With Argo Rollouts it is easy to configure blue/green and canary deployments. Argo Rollouts allows to run K8S jobs before and after a promotion. Currently I just use bash scripts to execute curl commands in order to test if the application is working correctly. It would be great if I could use testkube instead.

As far as I can tell it is easy to start a test using a REST call (e.g in a K8S job):
`curl -X POST -H "Content-Type: application/json" -d '{}' "http://testkube-api-server:8088/v1/tests/scheduled-test/executions"`

But this call is not blocking. This just starts the test and does not wait until the test has finished. It would be great to have an API call to start the test or test-suite, wait until it is finished and return a status code depending on the result of the test execution. This would make integration in CI/CD tools much easier.

**Comment by vsukhin** [comment]
Hey @eduardhildebrandt Thank you for an excellent questions. Please check api call docs for test execution at https://kubeshop.github.io/testkube/openapi/. For POST /executions method we support `Sync` parameter, it's false by defaul, but you can set it to `true`. Test suite doesn't support sync execution at the moment. We will add this feature to our backlog

**Comment by eduardhildebrandt** [comment]
Hey @vsukhin Thank you very much for your quick feedback. Using the POST /executions method with sync parameter I was able to integrate Testkube with ArgoRollouts and execute smoke tests before promoting the application. Thanks!

**Comment by vsukhin** [comment]
Sure, thing @eduardhildebrandt You're welcome. Will work on test suite sync option!

**Comment by vsukhin** [comment]
Hi @eduardhildebrandt added `sync` flag to POST /test-suite-executions. Please upgrade Testkueb to latest release

**Comment by eduardhildebrandt** [comment]
Hi @vsukhin I tested version 1.2.19. It works. Awesome! Thank you so much!

Offtopic: Is it possible to create Test and TestSuite resources in other namespaces than "testkube"? Different teams should be able to deploy their tests in their own namespaces. There are ClusterRoles with the permission to GET and LIST all tests and testsuites. But it seems that Testkube is not seeing the tests in namespaces other than "testkube". Am I missing something? Is it possible to configure Testkube in a way that it is working cluster wide?

**Comment by eduardhildebrandt** [comment]
There is an other issue:

If I execute: `curl -X 'POST' 'http://localhost:8088/v1/test-suites/grafana-smoke/executions' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"sync": true}'`

then the call blocks until the test suite was executed.

But the response contains:

`"status": "running"`

IMHO this is not correct. It should be "passed".

**Comment by vsukhin** [comment]
It's weird, that you see `running` status for sync call, I got only `passed` during testing. `running` is for async call, let's me check it out
