### ISSUE TITLE
Artifacts generation for curl and postman type tests.

### ISSUE THREAD

**Issue by Garvit-Jethwani** [kubeshop/testkube#1653]
**Describe the enhancement you'd like to see**
Can there be a possibility of generating yaml or json report for curl and postman tests as well.

**Additional context**
The STDOUT of these tests execution results in -o json or yaml will be needed to save in file, needing changes in their respective executors.

**Comment by TheBrunoLopes** [comment]
Hi @Garvit-Jethwani !
Thanks for this suggestion! I would love to know a bit more about your use case, are these reports going to be used by another system ? :)
I was able to get execution results in yaml or in json by doing: `tk get executions <execution id> -ojson` or `tk get executions <execution id> -oyaml`. Were you searching for this functionality on the UI as well ?

**Comment by Garvit-Jethwani** [comment]
Hi @TheBrunoLopes, I am using go sdk to create, run and download the generated artifacts for a test, since there is no artifacts generated for these tests(postman and curl), so I thought it would be good to store the results of these type of test's execution in minio pod and through download-artifacts go sdk, I can have artifacts downloaded to desired locations for further use.

**Comment by Garvit-Jethwani** [comment]
Can access the logs as test-output string after the execution. So artifacts generation not needed. Thank You.

**Comment by TheBrunoLopes** [comment]
Hey @Garvit-Jethwani !
That's great, I liked your idea of storing some results of tests and accessing them at a later stage.
Maybe there's way we also make the retrieval of those logs easier for you. Would you be ok with having a short call with me so that I can get some feedback from you ? 
here's my calendar link -> https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by Garvit-Jethwani** [comment]
Hi @TheBrunoLopes the retrieval of logs is easy as I am naming the execution of test so I have the test output stored in testkube execution struct against the particular test execution name which I can access at any time. Sure I would also like to connect and give feedback on testkube.
