### ISSUE TITLE
Expression in Grafana board not correct

### ISSUE THREAD

**Issue by eduardhildebrandt** [kubeshop/testkube#1656]
The expression
`"expr": "testkube_executions_count{result=\"success\"}",`
in the provided Grafana board is not correct.

IMHO it should be:
`"expr": "testkube_executions_count{result=\"passed\"}",`

Beside this the metric testkube_executions_count seems to be counting suite and test executions. If I execute one test suite with one test inside, then the metric increases by 2. This is not the behaviour I expected. I suggest having two different metrics for suites and tests.

**Comment by vsukhin** [comment]
Thank you @eduardhildebrandt for good points. We haven't refreshed Grafana board for a while. Kinda short-handed :) Need to improve the stuff!

**Comment by vsukhin** [comment]
hey @eduardhildebrandt. refactored metrics, have a look
