### ISSUE TITLE
Allow my Testkube Test to fetch the test files from a branch Dynamically 

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1658]
### Context
When I open a new PR from my feature branch my CI/CD pipeline creates a new environment for me to run tests on to see if it will break anything.In Testkube I set the branch where the tests are going to be fetched from when I'm creating the test, however, the branch will need to be specified for each execution because it will be a different one.

### Question
How can I tell Testkube the branch which I want to fetch my tests from when I'm triggering an execution ?

**Comment by TheBrunoLopes** [comment]
tagging for visibility @schoren @xoscar @mathnogueira

**Comment by exu** [comment]
@TheBrunoLopes, for now, git branch is part of `Test` Custom Resource and to get test from different branch you should create new one based on that branch. 

Is this resolving your issue?

**Comment by Ardesco** [comment]
Has anybody come up with a workaround that will allow you to easily modify the branch on the fly to test PR builds?

(I'm all for using something else somebody smart has done so I don't have to)

Are there any plans to add this functionality into TestKube?  If so are there any rough timelines?

**Comment by vsukhin** [comment]
hey, @Ardesco Can you please describe your flow in details with examples?

**Comment by Ardesco** [comment]
Flow i'm looking at implementing is as follows:

1. Raise a PR with test changes
2. Have testkube check out the PR branch and run it to see if there are any errors
3. Merge the branch if all tests pass

Obviously I don't know what the branch name will be in advance, I'm only going to know that when the PR is raised, so I'm looking for a way to dynamically set the branch when kicking off a test run (e.g. pass it in as a variable when calling /test-suites/{id}/executions that can be used to specify the branch to check out when running that execution).

**Comment by Ardesco** [comment]
@vsukhin is the above enough information?

**Comment by vsukhin** [comment]
yes, I will ping @TheBrunoLopes for prioritisation for this request

**Comment by TheBrunoLopes** [comment]
Hello @Ardesco this is definitely important.
We'll implement it in this release

**Comment by Ardesco** [comment]
Excellent news, thank you @TheBrunoLopes

**Comment by scott-david-walker** [comment]
@TheBrunoLopes - Do we have an ETA for the next release? Also, will there be some configurability so that rather than merging the changes, we can approve/reject prs?

**Comment by TheBrunoLopes** [comment]
We follow the model of a rolling release which means, as soon as a feature is developed and tested, we release it right away instead of waiting for a set of specific features and then releasing everything.
This one is being worked on right now by @vsukhin . Should be ready by the end of the week.
