### ISSUE TITLE
Consider using ConfigMap for testkube config instead of mongodb collection

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1675]
**Describe the enhancement you'd like to see**

To simplify configuration and make it a little bit cloud-native I want to have testkube config like telemetry enabled and other stuff inside single config map

**Comment by vsukhin** [comment]
ConfigMaps are read only and we need to store changes there. Sounds like, we need have Config CRD for Testkube

**Comment by olensmar** [comment]
@vsukhin not sure what you meant - ConfigMaps are definitely updateable!? Just apply changes as needed?!

**Comment by vsukhin** [comment]
Yes, they are updateable in general, but mounted in read only mode to pod, so pod can't update it and needs to be restarted to read new values from mounted volume (for example). In our case, we need to change configuration at any time during pod lifetime
