### ISSUE TITLE
`kubectl-testkube dashboard` fails if port 8080 is in use

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1683]
**Describe the bug**
`kubectl-testkube dashboard` fails if port 8080 is in use

**To Reproduce**
1. Expose any app in 8080
2. Run `kubectl-testkube dashboard` 

**Expected behavior**
Would be great if Testkube could search for the next available port, like 8081, 8082, etc.. 🤔

**Version / Cluster**
- Which testkube version? 1.2.23
- What Kubernetes cluster? KinD 
- What Kubernetes version? 1.24.1

**Comment by TheBrunoLopes** [comment]
Nice suggestion, added this issue for the v1.4 release
