### ISSUE TITLE
Add spinner for Testkube installation or other long running CLI ops

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#1719]
**Describe the enhancement you'd like to see**
Add spinner for Testkube installation or other long running CLI ops

**Comment by exu** [comment]
We could consider using something like https://github.com/charmbracelet/bubbletea ?

**Comment by vsukhin** [comment]
Yeah, looks cool!

**Comment by fivenp** [comment]
Here's a proposal (not using a spinner but being more verbose on what is currently GOING to happen, what is happening right now and a status update once it succeeded/failed)

https://www.figma.com/file/59vZTaJ6O2wTk0Qyqh2IJJ/Testkube-CLI?node-id=142%3A2027

**Comment by exu** [comment]
Spinner and Info needs rewrite of term UI as after tries we can't fit it here.

**Comment by tkonieczny** [comment]
Related/duplicated issue: https://github.com/kubeshop/testkube/issues/311

**Comment by TheBrunoLopes** [comment]
wont do for now.
