### ISSUE TITLE
Artifacts don't appear on the UI as on the CLI

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1724]
Check thread : https://discord.com/channels/884464549347074049/885185660808474664/990861765048946738

**Comment by exu** [comment]
@Toxer10 @pavloburchak you can use new `features` data for executors now 

https://demo.testkube.io/results/v1/executors

**Comment by Toxer10** [comment]
Hey @mogggggg! We fixed that issue with the artifacts tab that you reported.
Feel free to take a look and let us know if there's anything else we can do to help 😉

**Comment by mogggggg** [comment]
Thanks @Toxer10, confirming this works for us now - looks good!

**Comment by mogggggg** [comment]
Hmm, unfortunately this seems to be broken again!

**Comment by exu** [comment]
@mogggggg since 1.4 you'll need to add "features" array to your executor with "artifacts". 

```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  creationTimestamp: "2022-04-07T17:41:33Z"
  generation: 39
  name: cypress-executor
  namespace: testkube
  resourceVersion: "207224858"
  uid: 04617731-a7c0-410a-8215-649efc990a39
spec:
  features:
  - artifacts
  - junit-report
  image: kubeshop/testkube-cypress-executor:1.1.4
  types:
  - cypress/project
```

**Comment by mogggggg** [comment]
Confirming as working again after adding `features` array 🎉
