### ISSUE TITLE
GCP auth plugin warning when using CLI

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1729]
**Describe the bug**

GCP auth plugin warning

```
W0630 08:38:49.925654   68511 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

```
**To Reproduce**
1. Run 'tk get tests'

**Comment by vsukhin** [comment]
gcloud components install gke-gcloud-auth-plugin

**Comment by exu** [comment]
Looks like now Auth plugins are loaded dynamically. 

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke


To fix this issue locally cluster configuration need to be set to use new auth plugins 

```sh 
gcloud components install gke-gcloud-auth-plugin
gke-gcloud-auth-plugin --version
```

Next set env variable to point Google go client to use new system 
```
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
```
you can store it into your `.zshrc` / `.bashrc` file. 


Next do components update to make sure you're in recent version 
```sh
gcloud components update
```

And reload your cluster config (without this step I couldn't make it work)   
```sh
gcloud container clusters get-credentials YOUR_CLUSTER_NAME 
```


Details here: 
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
