### ISSUE TITLE
E2E tests on new release run automatically - feedback from tests passed to Slack channel

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#175]
As a Kubtest engineer I want to know that kubtest is not broken after releasing new version/alpha-beta-version

Run e2e API server test suite based on Postman collection (intest/e2e dir)

**Comment by exu** [comment]
look at https://docs.google.com/document/d/1t42g32__8w7N9Z7PEXBXD-Q-AcxKT3fU7D_a1nLmaRA/edit?usp=sharing
for test details

**Comment by exu** [comment]
Look at `test/e2e/` directory

**Comment by olensmar** [comment]
would be great if we could use kubtest for this:
- test api-server with postman collections!?
- test dashboard with cypress!?
