### ISSUE TITLE
After Isito injection testkube connection error happens

### ISSUE THREAD

**Issue by Zogoo** [kubeshop/testkube#1761]
**Describe the bug**
A K8s environment with Istio TLS connection between pods.
Without Istio injection "testkube" cannot connect to the actual test endpoint because TLS connection `Connection reset by peer` error happens. 

**To Reproduce**
1. Run 'kubectl testkube run test'
2. Inject "testkube" name space with Istio
   `kubectl label namespace testkube istio-injection=disabled --overwrite`
3. See error
error: error trying to reach service: read tcp 172.17.0.1:59970->172.17.0.38:8088: read: connection reset by peer
⨯ getting test suites executions list (error: api/GET-testkube.TestSuiteExecutionsResult returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error trying to reach service: read tcp 172.17.0.1:59972-\u003e172.17.0.38:8088: read: connection reset by peer","reason":"ServiceUnavailable","code":503}

**Expected behavior**

**Version / Cluster**
- Which testkube version? : 1.2.48 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  Minikube, Istio mTLS between pods.
- What Kubernetes version?
   v1.21.11

**Screenshots**
 ```bash
$kube get pods -n testkube
NAME                                                    READY   STATUS    RESTARTS   AGE
testkube-api-server-f86c985b8-297fs                     2/2     Running   1          20h
testkube-dashboard-6f5f84f8d8-5b9t7                     2/2     Running   0          20h
testkube-minio-testkube-64cd475b94-fc5hb                2/2     Running   0          20h
testkube-mongodb-6c9c5db4d5-wq9xh                       2/2     Running   0          20h
testkube-operator-controller-manager-66ff4cdfd4-tblg2   3/3     Running   1          20h
 ```
 
**Additional context**
172.17.0.37:8088 - API server internal IP address
172.17.0.1:59970 - Not sure which pod's IP address it is.

API server POD log
```bash
Available migrations for v1.3.0
No migrations available for v1.3.0
{"level":"warn","ts":1657104355.4716427,"caller":"api-server/main.go:105","msg":"Getting uniqe clusterId","error":null}
{"level":"info","ts":1657104355.5050254,"caller":"v1/server.go:279","msg":"Testkube API configured","namespace":"testkube","clusterId":"clusterbb669eef1b556e914a11107ae51ccfa9","telemetry":false}
segment 2022/07/06 10:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": read tcp 172.17.0.37:40666->35.155.223.175:443: read: connection reset by peer
segment 2022/07/06 10:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
{"level":"info","ts":1657104355.5379503,"caller":"api-server/main.go:130","msg":"starting Testkube API server","telemetryEnabled":true,"clusterId":"clusterbb669eef1b556e914a11107ae51ccfa9","namespace":"testkube"}

 ┌───────────────────────────────────────────────────┐
 │                   Fiber v2.31.0                   │
 │               http://127.0.0.1:8088               │
 │       (bound on host 0.0.0.0 and port 8088)       │
 │                                                   │
 │ Handlers ........... 166  Processes ........... 1 │
 │ Prefork ....... Disabled  PID ................. 1 │
 └───────────────────────────────────────────────────┘

segment 2022/07/06 10:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": read tcp 172.17.0.37:32808->52.34.77.50:443: read: connection reset by peer
segment 2022/07/06 10:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 11:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 11:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 12:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 12:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 13:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 13:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 14:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 14:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 15:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 15:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 16:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 16:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 17:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 17:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 18:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": EOF
segment 2022/07/06 18:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
segment 2022/07/06 19:45:55 ERROR: sending request - Post "https://api.segment.io/v1/batch": read tcp 172.17.0.37:44758->44.241.139.196:443: read: connection reset by peer
segment 2022/07/06 19:45:55 ERROR: 1 messages dropped because they failed to be sent and the client was closed
< Ommiting same error logs>
```

**Comment by vsukhin** [comment]
Thank you, @Zogoo Really glad that users started using Testkube in complex K8s envs, like Istio or Openshift. We didn't trt it in such a configuration. Need to check it out

**Comment by exu** [comment]
Hi @Zogoo thanks for getting Istio issue - we'll try to reproduce it on our clusters, as it's first time when we facing Istio issues. 

Can you provide to us your config around network policies? Is your service allowed to communicate with Testkube?

**Comment by Zogoo** [comment]
@vsukhin , @exu I'm also very glad for the fast response and seeing the excitement for the issue. I'm sorry for the lack of information. I have just updated steps. 
@exu we don't have any specific blocking rules between service and pods. If you give me what configs that you need for investigation I will be happy to help with that.

**Comment by ypoplavs** [comment]
Hello @Zogoo,

We have updated our Helm charts with a policy that allows to run `testkube` in Istio setup with mTLS enabled. Please upgrade the charts in your k8s cluster to a latest version - `1.3.20` and let us know about the results.

**Comment by Zogoo** [comment]
@ypoplavs hey thanks for the very quick update. I was expecting a new tag in Github when you mention "1.3.20", Or am I missing some other way to check it out? Could you please some direction on how to get the 1.3.20 version?

**Comment by vsukhin** [comment]
Hey, Zogoo. The simplest way is to run our cli command like `kubectl testkube upgrade`. It will install latest helm chart for you.
Or manually `helm upgrade --install testkube kubeshop/testkube`

**Comment by Zogoo** [comment]
@vsukhin 
cc: @ypoplavs @exu 
I still could not todo test it. Because I have got other error in my env. https://github.com/kubeshop/testkube/issues/1816.
I will let you guys know once I could run the test in my Istio env.

**Comment by Zogoo** [comment]
@vsukhin 
cc: @ypoplavs , @exu 

After I uninstall and re-install testkube situation get changed from #1816.
Issue: No execution log
```bash
$kubectl testkube watch execution 62d6622aefb5328d0a1c5921
Getting pod logs
Execution completed
⨯ unexpected end of JSON input
Use following command to get test execution details:
$ kubectl testkube get execution 62d6622aefb5328d0a1c5921
kube testkube get execution 62d6622aefb5328d0a1c5921
ID:        62d6622aefb5328d0a1c5921
Name:      pds-test-1
Type:      postman/collection
Duration:

Test execution started
```

**Comment by vsukhin** [comment]
Hey, @Zogoo What do see when the test was executed, if you run kubectl testkube get pods -n testkube. Are executor pods in completed state? If not can you check their logs and describe pods comands?

**Comment by Zogoo** [comment]
@vsukhin 
nope they are in the same situation that I mentioned in other issue #1816 1816

```bash
zogoo% kube get pods -n testkube
NAME                                                    READY   STATUS     RESTARTS   AGE
62d6622aefb5328d0a1c5921-8pdwf                          1/2     NotReady   0          18h
testkube-api-server-57f7fc998d-thttx                    2/2     Running    1          19h
testkube-dashboard-6bd9dd679f-vpm2r                     2/2     Running    0          19h
testkube-minio-testkube-64cd475b94-wsqbf                2/2     Running    0          19h
testkube-mongodb-6c9c5db4d5-bphrx                       2/2     Running    0          19h
testkube-operator-controller-manager-85b979bbf6-gllwj   3/3     Running    1          19h
```
Description of pod returns a massive amount of information, if you tell me which part is useful for your investigation let me share that part here.

**Comment by vsukhin** [comment]
Thank you @Zogoo I guess, it's important to understand, why they are not ready. Should give us some ideas what is wrong. You can copy last 15 lines of describe command. If you want, we can have a short Google Meet session at this time tomorrow or when you have time to check them together

**Comment by ypoplavs** [comment]
Hey @Zogoo here is my Calendly link: https://calendly.com/yulia-poplavska/30min
Please choose suitable time for you.

**Comment by Zogoo** [comment]
@ypoplavs I booked it on the 9th of August. Looking for seeing you there.

**Comment by ypoplavs** [comment]
It's necessary to disable Istio injection in `testkube` namespace and re-install the tool:

-  remove Testkube from your Istio cluster: `helm uninstall testkube -n testkube` 
-  run `kubectl label namespace testkube istio-injection=disabled --overwrite`
- install Testkube `helm install testkube testkube/testkube`

It's important to check that Istio is not in testkube namespace anymore since it won't prevent jobs from correct execution.
