### ISSUE TITLE
Cannot run postman collection

### ISSUE THREAD

**Issue by Zogoo** [kubeshop/testkube#1816]
**Describe the bug**
It's not working even the sample collection file. https://kubeshop.github.io/testkube/getting-started/
```bash
kubectl testkube create test --file my_postman_collection.json --type postman/collection --name my-test-name
kubectl testkube watch execution 62d10d38cf10983bda6c758e
Getting pod logs
Execution completed
⨯ unexpected end of JSON input
````

**To Reproduce**
1. Install the latest "testkube" with the latest helm chart. And follow https://kubeshop.github.io/testkube/getting-started/
2. Specify '...'
3. See error

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
```bash
zogoo% kubectl get pods -n testkube
NAME                                                    READY   STATUS     RESTARTS   AGE
62d0dafa67c1793e3eb2cfab-6rlxj                          1/2     NotReady   0          3h35m
62d0db9e67c1793e3eb2cfad-t59nd                          1/2     NotReady   0          3h32m
62d1005b9f1f47b5bd0465d9-6q6sl                          1/2     NotReady   0          55m
62d10d01cf10983bda6c758c-t5hvq                          1/2     NotReady   0          2m1s
62d10d38cf10983bda6c758e-jtwff                          1/2     NotReady   0          67s
testkube-api-server-54d86fcc7c-kzf2n                    2/2     Running    2          2m58s
testkube-dashboard-6f5f84f8d8-48rgw                     2/2     Running    0          2m58s
testkube-minio-testkube-64cd475b94-dl9dz                2/2     Running    0          2m58s
testkube-mongodb-6c9c5db4d5-5l4jf                       2/2     Running    0          2m58s
testkube-operator-controller-manager-7c77fd4bd9-trrc2   3/3     Running    1          2m58s
```
Helm: `testkube          	testkube     	1       	2022-07-15 06:44:23.182162536 +0000 UTC	deployed	testkube-1.3.24`
Client Version 1.3.4
Server Version v1.3.10
Commit
Built by Homebrew
Build date

**Comment by vsukhin** [comment]
So, it's still in Istio, right? Does this command work kubectl testkube watch execution 62d10d38cf10983bda6c758e ?

**Comment by vsukhin** [comment]
Hey @Zogoo Guess, the reason of this error in this 
62d0dafa67c1793e3eb2cfab-6rlxj                          1/2     NotReady   0          3h35m
62d0db9e67c1793e3eb2cfad-t59nd                          1/2     NotReady   0          3h32m
62d1005b9f1f47b5bd0465d9-6q6sl                          1/2     NotReady   0          55m
62d10d01cf10983bda6c758c-t5hvq                          1/2     NotReady   0          2m1s
62d10d38cf10983bda6c758e-jtwff                          1/2     NotReady   0          67s

It means that executors pod were not started. Most likely, because of lack of resources or not available to get executor image from Docker Hub. You can try to check the logs using `kubectl logs 62d10d38cf10983bda6c758e-jtwff  -n testkube` or `kubectl describe pod 62d10d38cf10983bda6c758e-jtwff  -n testkube`

**Comment by Zogoo** [comment]
@vsukhin but the error says error on the end of JSON. Do you think it's not related with the error?

**Comment by exu** [comment]
@Zogoo just FYI, we've pending Istio research issue done by @ypoplavs. We'll inform you.

**Comment by Zogoo** [comment]
@vsukhin thanks for your reply. I have got the following result. 

```bash
$kubectl logs 62d10d38cf10983bda6c758e-jtwff -n testkube 
{"type":"event","content":"running test [62d10d38cf10983bda6c758e]"}
{"type":"line","content":"newman\n\n"}
{"type":"line","content":"Kubeshop\n"}
{"type":"line","content":"\n→ Home\n"}
{"type":"line","content":"  GET https://kubeshop.io/ "}
{"type":"line","content":"[errored]\n"}
{"type":"line","content":"     Client network socket disconnected before secure TLS connection was established\n"}
{"type":"line","content":"  2. Body matches string\n"}
{"type":"line","content":"\n→ Team\n"}
{"type":"line","content":"  GET https://kubeshop.io/our-team "}
{"type":"line","content":"[errored]\n"}
{"type":"line","content":"     Client network socket disconnected before secure TLS connection was established\n"}
{"type":"line","content":"  4. Status code is 200\n"}
```

**Comment by vsukhin** [comment]
Hey, @Zogoo. As you can see from above log the problem is in establishing connection from your kubernetes cluster to external http web site. We will need to check it out @ypoplavs. Might be some additional policies required

**Comment by ypoplavs** [comment]
Hey @Zogoo,
It’s the result from the k8s cluster with Istio, correct? 
Could you please run the following command `kubectl get PeerAuthentication -A` and provide the output here?

**Comment by Zogoo** [comment]
> Hey @Zogoo, It’s the result from the k8s cluster with Istio, correct? Could you please run the following command `kubectl get PeerAuthentication -A` and provide the output here?

@ypoplavs 
```bash
NAMESPACE      NAME                  MODE         AGE
istio-system   default               STRICT       8d
testkube       testkube-api-server   PERMISSIVE   19h
```

**Comment by vsukhin** [comment]
Hey @Zogoo We did a bit more tuning for Istio
