### ISSUE TITLE
Webhook based notification

### ISSUE THREAD

**Issue by geowalrus4gh** [kubeshop/testkube#1824]
Currently notification supports only slack
A Webhook based notification could help integrate with many other notification systems.

**Comment by vsukhin** [comment]
Hey @geowalrus4gh We already have implemented webhook support for Testkube. Check our docs or just call cli command `kubectl testkube create webhook --help`

**Comment by TheBrunoLopes** [comment]
@geowalrus4gh Is there anything we can do to help you with setting up Testkube webhooks or anything else?
We are more than happy to help you, feel free to book a call with us to help you with any struggle you might have https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by geowalrus4gh** [comment]
> Hey @geowalrus4gh We already have implemented webhook support for Testkube. Check our docs or just call cli command `kubectl testkube create webhook --help`. But we are planning to merge webhook and Slack notfications modules in near future, becuase Webhook is a general way to do things

Yes its great to see that webhook is already there. Is it possible to map a webhook to a specific test ? . Each test case might send webhooks to different urls.

**Comment by vsukhin** [comment]
Hey @geowalrus4gh Not yet, we have a common webhook for all tests. Create an issue and reference @TheBrunoLopes to make it a higher priority for dev team ;)

**Comment by exu** [comment]
Created separate issue for Test/Testsuite filtered webhooks, #1891
