### ISSUE TITLE
Playwright executor

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1835]
- Add support for [Playwright](https://playwright.dev/)
- Writte blogpost about how to write an executor (using https://playwright.dev/ as the example)
- Do a video as well.

**Comment by TheBrunoLopes** [comment]
Added this issue to the next release.

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/1835?planning-poker) with Zenhub @nicufk @vLia

**Comment by vLia** [comment]
Externally contributed PR: https://github.com/kubeshop/testkube-executor-playwright/pull/1
