### ISSUE TITLE
Add ability to set args in the Test manifest

### ISSUE THREAD

**Issue by mogggggg** [kubeshop/testkube#1854]
**Describe the enhancement you'd like to see**
We would like the ability to be able to set `args` in the Test manifest. At the moment it is only possible to set this when running a test execution using `kubectl testkube` but we're in the process of deploying a handful of tests and are hoping to be able to accomplish setting everything up purely using manifest files.

We're wanting to use this specifically for creating k6 tests at this stage (need the ability to point to a test file and set the number of virtual users) but this would probably come in handy for Cypress later on too.

Thanks!

**Comment by TheBrunoLopes** [comment]
Hey @mogggggg thank you for the feedback. Going to check this with the team and get back to you asap.
