### ISSUE TITLE
parameter should be `testkube-api.storage.accessKeyID` in artifacts-storage.md

### ISSUE THREAD

**Issue by bishal7679** [kubeshop/testkube#1926]
**Why should it be implemented?**
The parameter should be  `testkube-api.storage.accessKeyID` and D is missing here

![Screenshot (221)](https://user-images.githubusercontent.com/70086051/181278462-54fdfec4-4178-4f30-ab5b-3341cbe79ca8.png)

**Describe the improvement**

![Screenshot (222)](https://user-images.githubusercontent.com/70086051/181278963-2fc4966e-d08d-4e79-b0ca-f7a2b35b51cb.png)

**Comment by vsukhin** [comment]
thank you for noting @bishal7679 ! fixed in latest release
