### ISSUE TITLE
API - Add test type field to Test Suite steps list

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#1936]
Please add `type` field for Test Suite steps list.
Something like this, in test-suite schema, would be perfect
`"steps": [
    {
      "stopTestOnFailure": true,
      "execute": {
        "namespace": "string",
        "name": "string",
        "type": "test-type"
      },
      "delay": {
        "duration": 0
      }
    }
  ]`

**Comment by pavloburchak** [comment]
Please add `type` field for Test Suite steps list.
`"steps": [
    {
      "stopTestOnFailure": true,
      "execute": {
        "namespace": "string",
        "name": "string",
        **"type": "test-type"**
      },
      "delay": {
        "duration": 0
      }
    }
  ]`

**Comment by TheBrunoLopes** [comment]
Just to confirm, this is for the Test Suite Schema sent from the api server, correct ?
Showing this in the yaml CRD doesn't seem useful to me, so let's not add it there as well :)

**Comment by pavloburchak** [comment]
@TheBrunoLopes this is a desired schema I sent. Current is without "type". Am I get you right, we will not going to add "type" field here? It is needed to display icon in the UI
<img width="309" alt="image" src="https://user-images.githubusercontent.com/25755402/181489758-2340e8b7-6dd8-4fbe-a157-961a6a1da107.png">

**Comment by vsukhin** [comment]
We can't add this field to test suite crd, because it's a part of test crd, having them in 2 places will create a conflict. But we can add an api method, that will return a list of tests for requested test suite

**Comment by TheBrunoLopes** [comment]
great, just making sure :)
