### ISSUE TITLE
Add `kubectl testkube debug create-issue` command to automatically create GitHub issue with debug info from the CLI

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#1937]
**Is your feature request related to a problem? Please describe.**
Follow-up to https://github.com/kubeshop/testkube/issues/1647

As a **Testkube user** I would like to **have my environment info automatically populated when opening bug reports**, so that I can **focus more on describing my issue**.

Issue#1647 implements the `tk debug info` command to show summary of the Testkube environment information. The purpose of this Issue is to implement using the GitHub API the creation of a new bug report.

**Describe the solution you'd like**
`kubectl testkube debug create-issue` should allow the user to populate a Testkube GitHub issue on the CLI and open up a browser to finalize the creation.

**Additional context**
The CLI UX of the `debug` command was promptly discussed during the UX meeting on 28.06.

**Comment by exu** [comment]
@vLia Can we make it top level `tk create-issue` command?

**Comment by vLia** [comment]
@exu Sorry, just noticed your comment.
We can make it a top level command very easily, however there was a discussion that there are already too many top level commands, and it is getting confusing from the UX perspective. Plus it seems like due to size and api limitations it is not possible to add the logs with one call, so the actual value of this functionality will be diminished.
