### ISSUE TITLE
Automatically create CronJob for scheduled test

### ISSUE THREAD

**Issue by mogggggg** [kubeshop/testkube#1944]
**Describe the enhancement you'd like to see**
We would like for Testkube to automatically create the CronJobs used by scheduled tests once a test is created. We're in the process of setting up a handful of scheduled tests and are hoping to accomplish managing them all via our CI/CD using manifest files. At the moment when we deploy a scheduled tests we need to run `kubectl testkube run test` for the CronJob to be created.

**Comment by vsukhin** [comment]
Yeah, we need to refactor this to be more convinient

**Comment by vsukhin** [comment]
So, we should detect that new manifest was deployed to the k8s cluster using ArgoCD or any other manfiest based tool and automatically create or update a CronJob, if it's a scheduled test, right?

**Comment by mogggggg** [comment]
@vsukhin Yep, that would be amazing. In our case we're using Terraform along with the `kubernetes_manifest` resource

**Comment by vsukhin** [comment]
Sounds good, probably we will need to move Cron job creation part to kubernetes operator whenever Test crd is created or changed
