### ISSUE TITLE
Unable to create tests via UI due to "405 - Not allowed"

### ISSUE THREAD

**Issue by krzwiatrzyk** [kubeshop/testkube#1949]
**Describe the bug**
I want to use UI to create the test. However, using K6 method and placing an example test configuration from Testkube documentation results with error: **405 - Not allowed** as visible on the screen.

I have used the ingress configuration from the chart.

![image](https://user-images.githubusercontent.com/52850037/182103161-5ba4dc47-6084-46fe-98f0-6a33bbc016cc.png)

**To Reproduce**
1. Install Testkube using Helm Charts and expose it behind Kubernetes Nginx Ingress controller.
2. Try to create any K6 test.
3. See error

**Expected behavior**
Successfult test creation.

**Version / Cluster**
- Which testkube version? `1.3.95`
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) `K3s`
- What Kubernetes version? `1.21.12`

**Screenshots**
Logs from Dashboard pod:
```
10.42.1.12 - - [01/Aug/2022:08:12:11 +0000] "POST /dashboard/tests/default/tests HTTP  /1.1" 405 559 "https://testkube.<REDACTED>/dashboard/tests/add-test" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/  103.0.0.0 Safari/537.36" "10.144.231.7" 
```
 
**Additional context**
I wonder if the issue is within Nginx Ingress Controller or within Testkube itself. I can see in both component log regarding 405 responses but without any additional explanation.

What I have tried:
- I can't create tests using Testkube CLI when port-forwarded dashboard to localhost (omitted ingress-nginx)
- address POST method (which is send via UI) to CROSS Allowed in Ingress configuration (no success)

**Comment by krzwiatrzyk** [comment]
Request URL: https://testkube.cloud-oss.toss.comarch/dashboard/tests/default/tests

**Comment by krzwiatrzyk** [comment]
When using `testkube dashboard` command everything works.

**Comment by TheBrunoLopes** [comment]
Hi @krzwiatrzyk we are taking a look.
Meanwhile can you check if your URL configured in the UI is the correct one here.
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/13501228/182112768-d3d4b9a9-c6e6-4452-890f-ba940b5680d4.png">

On the bottom left corner you will be able to see a cogwheel button that allows you to change the URL

**Comment by krzwiatrzyk** [comment]
@TheBrunoLopes that was it, I hadn't exposed API (i thought that dashboard will redirect requests to the API server - my bad). Thanks for explanation.

Closing the issue with hope that it may help someone in future searching term `Testkube 405 Not allowed` :)

**Comment by TheBrunoLopes** [comment]
I'm very happy that you managed to find the issue @krzwiatrzyk 
Your feedback is very useful for us. I would love to get a few minutes of your time and understand your use case. Would you be ok with going on a quick call with me to talk about your experience with Testkube?
https://calendly.com/bruno-at-kubeshop/30min-1
