### ISSUE TITLE
`install` command fails with GKE

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#1960]
GKE has a new authentication method to Kubernetes clusters: https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke

After installing the `gke-gcloud-auth-plugin` I tried using Testkube to install it in my cluster but I got the following error: 

```
⨯ Installing testkube (error: process error: exit status 1
output: F0801 15:15:20.376203    6739 main.go:27] print credential failed with error: failure while executing gcloud, with args [config config-helper --format=json]: exit status 127
Unable to connect to the server: getting credentials: exec: executable gke-gcloud-auth-plugin failed with exit code 1
)
```

Is it possible to fix this issue as more and more users are going to have to migrate to this new authentication method once kubectl 1.25 is out?

**Comment by exu** [comment]
closes #1729

**Comment by exu** [comment]
@aabedraba if you could make those steps: 




Looks like now Auth plugins are loaded dynamically. 

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke


To fix this issue locally cluster configuration need to be set to use new auth plugins 

```sh 
gcloud components install gke-gcloud-auth-plugin
gke-gcloud-auth-plugin --version
```

Next set env variable to point Google go client to use new system 
```
export USE_GKE_GCLOUD_AUTH_PLUGIN=True
```
you can store it into your `.zshrc` / `.bashrc` file. 


Next do components update to make sure you're in recent version 
```sh
gcloud components update
```

And reload your cluster config (without this step I couldn't make it work)   
```sh
gcloud container clusters get-credentials YOUR_CLUSTER_NAME 
```


Details here: 
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

**Comment by aabedraba** [comment]
Hi @exu 

I did follow these instructions before opening this issue, which are the same ones as the link from Google Cloud I provided in my initial comment. But just to be sure I ran them again and now it worked...

Thanks so much!
