### ISSUE TITLE
Deprecation issue in testkube-dev cluster

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1965]

**Comment by exu** [comment]
![Image](https://user-images.githubusercontent.com/30776/182243851-52941f29-f117-4a53-953e-b4878b00a00c.png)

**Comment by ypoplavs** [comment]
As per official documentation this is the list of API versions that is removed in v1.22
https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

As for our resources we do not use beta versions anymore. Our `Ingress` resources utilise only [networking.k8s.io/v1] api.
