### ISSUE TITLE
Show test scheduling in UI

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#1970]
For tests that I have scheduled using the Cron feature I would like the following improvements in the dashboard:
- an indicator in the list of tests showing that it has a schedule (with a hover showing scheduling details + next execution time?)
- scheduling details in the test details + next execution time
- a "Scheduled Tests" view/list/filter that shows all scheduled tests - either by name or by "next schedule" - perhaps using some kind of timeline visualisation!? -> helps me get a high-level overview of what tests that are running when

**Comment by vsukhin** [comment]
Yeah, I did something similar in other project with sorting by task next scheduled time

**Comment by aabedraba** [comment]
This will be part of the Testkube Calendar feature. 👍🏽
