### ISSUE TITLE
Make Helm and Kubectl not a hard dependency on the CLI

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#1979]
Add helm and kubectl as dependencies in brew, apt and choco to be installed automatically during Testkube installation.

**Comment by exu** [comment]
- apt - don't have helm neither kubectl in official repos.

**Comment by vLia** [comment]
Self-published choco and brew have the added dependency now.

Create PR to add it to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/109385

**Comment by vLia** [comment]
PR was merged
