### ISSUE TITLE
Dashboard - Parse possible terminal color codes

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1992]
**Describe the enhancement you'd like to see**

As an UI user I want to see terminal output in the same way as users sees it in terminal
 
example k6 test in terminal and UI 
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/30776/182588805-7614f93e-2785-4708-8c72-4a129ace7dcb.png">

**Additional context**
We would need any lib which is able to "colorize" terminal output

On backend side research possibility of forcing color codes for existing executors

**Comment by TheBrunoLopes** [comment]
It seems like there's some colour coding after all.

**Comment by fivenp** [comment]
If you plan to use https://github.com/nteract/ansi-to-react – feel free to use the color palette from the figma for the colors :) 

* 600 shade for main colors
* 300 shade for bright colors
* 800 or 900 shade for background

**Comment by pavloburchak** [comment]
@exu As I can see now, API doesn't provide color coding for execution's log output.

![Image](https://user-images.githubusercontent.com/25755402/188607710-c29b3a11-f208-4d62-82d7-df9ceb8d1912.png)
