### ISSUE TITLE
Make test, testsuite operations atomic

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#1998]
**Describe the enhancement you'd like to see**
Now for example if there is an error in deleting a test it won't delete it secrets but the test is deleted.

**Additional context**
Add any other context, CLI input/output, etc. about the enhancement here.

**Comment by vsukhin** [comment]
We should have a kind of Saga for this. Compensate failed operations with reverse ones

**Comment by exu** [comment]
Can't controller handle those for CRD's? during delete remove all deps?

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/1998?planning-poker) with Zenhub @nicufk @vLia

**Comment by vsukhin** [comment]
We need to define each operation to support

**Comment by vsukhin** [comment]
we didn't wrok on this issue
