### ISSUE TITLE
API - Investigation on ability to send events

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#2004]
Front-end currently sends a lot of requests to API in a second to keep info updated all the time. It is required to add an ability for front-end to subscribe for some data updates to keep it updated and not ping api every sec. This will significantly improve performance. Here is list of needed data:
- tests/test-suites list
- test/test-suite details
- test/test-suite executions list

**Comment by rangoo94** [comment]
Closing this ticket, as the research is basically done. We have tickets for the GraphQL implementation 👍
