### ISSUE TITLE
Timeout error when using testkube client on EKS with public K8s API endpoint and private worker nodes

### ISSUE THREAD

**Issue by nivhty** [kubeshop/testkube#2013]
**Describe the bug**
Get timeout error when running some of testkube cli commands (eg: testkube version) on a local environment.

**To Reproduce**
1. Create an EKS with a public K8s API endpoint and private worker nodes.
2. Install `testkube`.
3. Run `testkube version`
4. Get timeout error.

**Expected behavior**
Get information about the version of testkube client and server after running `testkube version`

**Version / Cluster**
- Which testkube version?  `1.4.6`
- What Kubernetes cluster? EKS with public K8s API endpoint and private worker nodes 
- What Kubernetes version? `1.22`

**Screenshots**
Timeout error output, with `10.12.34.215` is the pod IP of `testkube-api-server` pod.
```
api/GET-testkube.ServerInfo returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error trying to reach service: dial tcp 10.12.34.215:8088: connect: connection timed out","reason":"ServiceUnavailable","code":503}
```
 
**Additional context**
API seems to be working fine via dashboard UI after using the command `testkube dashboard` for port forwarding.
Heath check resulting 200 after port forwarding `testkube-api-server` pod.
<img width="409" alt="image" src="https://user-images.githubusercontent.com/49474736/183369185-c7d476ad-40b4-4504-91e3-a9107c97fefc.png">

**Comment by nivhty** [comment]
Found the problem. We are using `Pod networking in Amazon EKS using the Amazon VPC CNI plugin for Kubernetes` so our pod's IPs are real network interface IPs. The pod IPs are being controlled with an attached security group that doesn't allow the master node to access the pod at port `8088`.

Solution: Allow traffic from the master node security group access to port `8088` in the worker nodes security group.

**Comment by exu** [comment]
Thanks for the feedback @nivhty for sure it'll also help others in future!
