### ISSUE TITLE
Sharing variables between postman collection tests inside a test-suite

### ISSUE THREAD

**Issue by ili-shmidt-wib** [kubeshop/testkube#2014]
### Use case:

Assume the above test-suite:
1. Register user with username, password (generate a password inside the test).
2. Login user (with the generated password from the previous collection test) and run tests.

I would suggest using postman's global variables and running all test-suite tests in a shared postman's workspace.

**Comment by TheBrunoLopes** [comment]
Hi @ili-shmidt-wib! I'm Bruno, the Product leader for Testkube!
This seems awesome! We have been thinking about doing something like this for some time, but we decided to wait a bit for user feedback before going deep into it. 
Would you spare 15m and have a call with us https://calendly.com/bruno-at-kubeshop/15-minute-to understand this use case better ? Would really appreciate it 🥇

**Comment by exu** [comment]
Exactly! I would plan some abstraction over all possible executors for passing data

**Comment by ili-shmidt-wib** [comment]
Hi, @TheBrunoLopes @exu
I would love to :)

Scheduled for
18:00 - 18:15, Wednesday, August 24, 2022
