### ISSUE TITLE
Creating new test-suite with post method to /test-suites endpoint ignores the variables of the test-suite

### ISSUE THREAD

**Issue by ili-shmidt-wib** [kubeshop/testkube#2053]
**Describe the bug**
When creating test-suite with variables via API request - the variables are being ignored.
It worked as expected but currently in v1.4.19 it doesn't.

**Comment by exu** [comment]
hi @ili-shmidt-wib can you pass more details? 
Like how are you calling APIs, what example payload?

**Comment by ili-shmidt-wib** [comment]
Hi @exu,
This is pretty critical issue for me because i pass the variables from test-suites to the tests it runs.

**This action works as expected in 1.4.10 server version.**

Current version: 
Client Version 1.4.21
Server Version v1.4.21

Calling `/v1/test-suites` with POST method
Payload:
```
{
  "name": "testsuite-name",
  "labels": {
    "app": "some-label"
  },
  "steps": [
    {
      "execute": {
        "stopTestOnFailure": true,
        "name": "step-1"
      }
    },
    {
      "execute": {
        "stopTestOnFailure": true,
        "name": "step-2"
      }
    }
  ],
  "variables": {
    "variable-1": {
      "name": "variable-1",
      "value": "some-lovely-value",
      "type": "basic"
    },
    "variable-2": {
      "name": "variable-2",
      "value": "some-lovely-and-nice-value",
      "type": "basic"
    }
  }
}
```

The variables are ignored and not listed as part of the test-suite

**Comment by ili-shmidt-wib** [comment]
Hi @exu, 
Do you have by any chance an expectation when this bug might be solved?

**Comment by vsukhin** [comment]
Please use latest structure for Test and TestSuite object https://kubeshop.github.io/testkube/openapi/

**Comment by ili-shmidt-wib** [comment]
Hi @vsukhin,
LOL
Alright now it makes sense,
That leads me to the next question which is how can i use the `kubectl testkube install` to specify a specific version to be installed.
So that my testkube won't break while deployment?
And thanks for the quick response!

**Comment by vsukhin** [comment]
Welcome, @ili-shmidt-wib We don't have an option to select a particular Testkube version during installation. We always install latest one, but you can install manually Testkube Helm Chart and in this case you can request a particular Testkube version

**Comment by ili-shmidt-wib** [comment]
@vsukhin
At first place i started installing with helm but had trouble of getting an error - I asked if anyone encountered it in the discord channel and had an advice to use testkube k8s plugin for installation instead.
But now its mandatory for me to use helm. Do you know where i can find the commands that the plugin executes when running 'kubectl-testkube install'? maybe i can spot the problem.
![Screen Shot 2022-08-12 at 22 13 25](https://user-images.githubusercontent.com/104712602/184427754-529a8184-394d-4e87-be4e-1fbcd435aece.png)
han

**Comment by vsukhin** [comment]
yes, https://github.com/kubeshop/testkube/blob/main/cmd/kubectl-testkube/commands/common.go#L44

**Comment by ili-shmidt-wib** [comment]
Thanks @vsukhin!
Error resolved :)
Adding the helm installation commands if someone would find it helpful.

### Installing testkube using helm with explicit version.

```
helm upgrade --install jetstack jetstack/cert-manager --namespace testkube --create-namespace --version v1.7.1 --set installCRDs=true
helm repo add kubeshop https://kubeshop.github.io/helm-charts
helm repo update
helm upgrade --install --create-namespace --namespace testkube testkube kubeshop/testkube --version <specify_testkube_version>
```

Versions can be found here: [](https://artifacthub.io/packages/helm/kubeshop/testkube)
