### ISSUE TITLE
Testkube UI doesn't connect to the correct URI when using Testkube Dashboard command

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2064]
When the users do "kubectl testkube dashboard" the default URI on it's ui says "default" and it's not connected as expected to the "https:/localhost...." one

**Comment by exu** [comment]
Add proxy to dashboard in API

Will proxy if dashboard exists

**Comment by exu** [comment]
Proxy don't work correctly with dashboard
