### ISSUE TITLE
Upgrade MongoDB in Helm charts

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2067]
Install current Mongo first (Testkube uses it currently):
```
helm upgrade --install  mongo bitnami/mongodb --version 11.0.0
```

Upgrade to the recent version of Mongo
```
helm upgrade --install  mongo bitnami/mongodb --version 13.0.0
```

figure out automatic way of doing the same in Testkube Helm chart

**Comment by ypoplavs** [comment]
It has been decided to leave Mongo at version 11 since later charts versions introduce many bugs. Downgrade script was added for users who had already installed TK with version 12.
