### ISSUE TITLE
UI - add segment.io session

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2069]
- Get number of sessions with unique id for a given day.

### **Important note**
We want a clear separation between events sent from users installations and the [demo UI.](https://demo.testkube.io/)
Lets still capture events sent from the demo.testkube.io, but just store them in different places.
This is true for this metric and other metrics we are going to add in the future

**Comment by exu** [comment]
@TheBrunoLopes please define what kind of metrics we need here

**Comment by TheBrunoLopes** [comment]
Just this one for now:
- Get number of sessions with unique id for a given day.

is this enough ?

**Comment by exu** [comment]
Looks like JS session is for single website only
