### ISSUE TITLE
Documentation on how to use a Cypress project with a PRIVATE (bitbucket) git repository is incomplete

### ISSUE THREAD

**Issue by TheLeanMachine** [kubeshop/testkube#2076]
**Describe the bug**
[The documentation](https://kubeshop.github.io/testkube/executor-cypress/) on how to create a testkube test from a Cypress project does not explain how do do it when it's a **private** repository.

**To Reproduce**

1. Place code in a (bitbucket) repository that requires authentication before cloning
2. Create new test from Cypress project via testkube dashboard, [with the help of the documentation](https://kubeshop.github.io/testkube/executor-cypress/)
3. As type use "git directory"
4. As URl use the HTTPS one, **containing the username** (like: `https://username@bitbucket.com/...`)
5. As token use an **Atlassian API token** (see screenshots)
6. Test is created, BUT: When executing it, it fails[1] (I guess logs in testkube are missing, since the test didn't run - this makes sense from a developer perspective, but it's not that end-user friendly)...
7. Note that, when I am using a - publicly accessible! - Cypress demo project my testkube test created from Cypress project works[2]!

[1]
<img width="1527" alt="Screenshot 2022-08-17 at 10 15 09" src="https://user-images.githubusercontent.com/3470837/185069447-c5900d28-f632-4694-afe9-4e237cc1402d.png">
Logs from teskube's API-server from DataDog...
<img width="1623" alt="Screenshot 2022-08-17 at 10 11 24" src="https://user-images.githubusercontent.com/3470837/185069549-f06042a3-1bd1-469b-a58e-e878a1abd3d0.png">
<img width="1589" alt="Screenshot 2022-08-17 at 10 12 30" src="https://user-images.githubusercontent.com/3470837/185069580-7f29e376-7208-49b9-adf2-c9ef81593246.png">

[2] Example of succesfull test run, using _publicly accessible_ testkube testrepo
<img width="1691" alt="Screenshot 2022-08-17 at 10 02 51" src="https://user-images.githubusercontent.com/3470837/185069643-a91f79f4-413c-45c2-810c-b55c5c1bb758.png">

**Expected behavior**
Cypress project is checked out, tests are run.

**Version / Cluster**
- testkube version: 1.4.21
- AWS EKS 
- K8s version: 1.22

**Screenshots**
This is how my test config looks like... 
<img width="1100" alt="Screenshot 2022-08-17 at 09 47 29" src="https://user-images.githubusercontent.com/3470837/185071228-7886222b-9fa8-486e-ae93-f67fae8ba6fb.png">

As "Token" I used the value of my personal Atlassian API-Token...
<img width="1331" alt="Screenshot 2022-08-17 at 09 49 23" src="https://user-images.githubusercontent.com/3470837/185075111-041fd31a-ca9f-4575-b03c-30b0c3ee0781.png">
sian API-token...

**Comment by vsukhin** [comment]
hey @TheLeanMachine. Thank you a lot for this detailed request! We definitely need to add more documentation for different use cases of Testkube env!
Regarding your sample I have a few questions:
1. Guess, you can provide bitbucket https uri without your username, but
2. Provide this username in a separate field (botth username and token will be automatically added to you https uri
3. Do you have all your tests in a root of your repo or is there a folder with tests to run? (in this case you need to provide `path` parameter)
4. Can you please execute `kubectl get pods -n testkube` after your started your test and `kubectl logs 653535.. -n teskube`, so I can see what is happening with test execution?

**Comment by TheLeanMachine** [comment]
Hi @vsukhin ,

(first of all thanks 4 the quick reply!)

I have to admit, I don't understand what U mean by "Provide this username in a separate field"....which form input field should I use for this?

Currently, my form-input now looks like this (bitbucket username removed; path to Cypress project added)...
<img width="941" alt="Screenshot 2022-08-17 at 12 32 21" src="https://user-images.githubusercontent.com/3470837/185099754-5278ac7f-9a63-4054-9c71-9f5899f74ab3.png">

...but when I run the test, execution fails, again (expectedy, wihtout any output)...
<img width="1584" alt="Screenshot 2022-08-17 at 12 32 42" src="https://user-images.githubusercontent.com/3470837/185099851-0a812a12-e557-4ab2-99fc-5eb73961fe6b.png">

when I do `kubectl get pods -n testkube`, I can see a container ha an `InitError`...
 <img width="682" alt="Screenshot 2022-08-17 at 12 41 20" src="https://user-images.githubusercontent.com/3470837/185100292-918a9ee3-11ea-4d32-969c-713225dbd447.png">

This might be caused by a permission problem on my side (I am not a DevOps engineer in my organisation), but when I try to obtain the container logs with `kubectl logs 653535.. -n teskube` i just see the message `\Error from server (NotFound): namespaces "teskube" not found`

(I will speak to a DevOps engineer, in order to sort out the last problem...)

**Comment by TheLeanMachine** [comment]
UPDATE: The responsible DevOps engineer says: "We cannot get any logs from containers of that pod, as it's not properly initialised"

In DataDog, I see this message in the API-server's log...
<img width="1446" alt="Screenshot 2022-08-17 at 13 02 43" src="https://user-images.githubusercontent.com/3470837/185103270-2b907c57-3cdf-47fa-822e-0174e1f9a529.png">

**Comment by vsukhin** [comment]
Hey, @TheLeanMachine Please use `-n testkube`, it's a spelling typo.
Sounds like, we don't have a username field in Test UI creation. Can you try to create a test using our CLI. Missed username might be a reason of pod failure to check out a private repo

**Comment by TheLeanMachine** [comment]
lol, how embarassing that I did not see this... ^^

Anyhow, this is the output...
`Defaulted container "62fcd193cc6c2fe22315c199" out of: 62fcd193cc6c2fe22315c199, 62fcd193cc6c2fe22315c199-init (init)
Error from server (BadRequest): container "62fcd193cc6c2fe22315c199" in pod "62fcd193cc6c2fe22315c199-zgqh9" is waiting to start: PodInitializing`

**Comment by TheLeanMachine** [comment]
Hm, strange: Does testkube work with bitbucket, at all...?

I copied all the code from the official demo project to my public bitbucket repo...
<img width="1495" alt="Screenshot 2022-08-17 at 13 58 26" src="https://user-images.githubusercontent.com/3470837/185113248-149afa1a-b9cc-4552-896c-f12ed19e5823.png">

...but this is ALSO failing...
<img width="1530" alt="Screenshot 2022-08-17 at 13 59 03" src="https://user-images.githubusercontent.com/3470837/185113332-8d8c0f9a-e720-4e14-8d57-a12a0c5725ae.png">

This is surprising to me!

**Comment by vsukhin** [comment]
Thank you, I see
I guess, it's auth related thing. Please create the test yusing cli, it supports both --git-username and --git-token parameters

**Comment by TheLeanMachine** [comment]
Thanks, will try that out.

Have a nice day!

**Comment by TheLeanMachine** [comment]
Hm, sadly it seems to cause the same symptoms...

This is the command...
`kubectl testkube create test --git-uri https://bitbucket.org/xchangeteam/xchange-frontend.git --git-branch master --git-path apps/xchange-app-e2e --name cypress-leasing-app-v5 --type cypress/project --git-username <BITBUCKET_USER> --git-token <BITBUCKET_API_TOKEN>`

**Comment by TheLeanMachine** [comment]
(Mildly) questioning, if this actually an auth-related problem...

...at least, when I create this test backed by [a public repo](https://bitbucket.org/xchangeteam/kais-public-stuff) using this command
`kubectl testkube create test --git-uri https://bitbucket.org/xchangeteam/kais-public-stuff.git --git-branch main --git-path examples --name public-created-via-cli --type cypress/project`

....then the result looks the same:
<img width="1539" alt="Screenshot 2022-08-17 at 16 24 50" src="https://user-images.githubusercontent.com/3470837/185159880-6509145d-de7a-4f43-a3ec-809531380910.png">

**Comment by TheLeanMachine** [comment]
Probably does not help much, but this is the latest error I am seeing in the API-server's log...

<img width="1169" alt="Screenshot 2022-08-17 at 16 36 47" src="https://user-images.githubusercontent.com/3470837/185164710-b8be75e7-fa7c-4d15-b930-638eae01d052.png">

(Gotta say: _Automatically providing the test-container's logs in case of error_ would be an amazing feature ^^)

**Comment by TheLeanMachine** [comment]
God-dammit!
Really sorry, I have wasted your time... (I selected a "Project" in bitbucket, that reset the "Private"-checkbox...anyhow)

I recreated the repo as a public one, now. [Same URL](https://bitbucket.org/xchangeteam/kais-public-stuff).

At least we're getting closer...
(finally, I want to use a private repo. anyway)

**Comment by TheLeanMachine** [comment]
Hm, strange.
Test is still failing, even with actual public bitbucket repo, now:
(I created the via UI)

<img width="1301" alt="Screenshot 2022-08-17 at 17 57 21" src="https://user-images.githubusercontent.com/3470837/185187142-f8408241-4b5a-464e-854e-3bdd7dba4d55.png">

(same behavior, when using repo-URL `https://bitbucket.org/xchangeteam/kais-public-stuff.git`)

**Comment by vsukhin** [comment]
kubectl testkube create test --git-uri https://bitbucket.org/xchangeteam/kais-public-stuff.git --git-branch master --git-path examples --name public-created-via-cli --type cypress/project

```
kubectl testkube get execution 62fd14f926190455406544d2
ID:         62fd14f926190455406544d2
Name        public-created-via-cli-2
Number:            2
Test name:         public-created-via-cli
Type:              cypress/project
Status:            passed
Start time:        2022-08-17 16:19:05.541 +0000 UTC
End time:          2022-08-17 16:20:30.007 +0000 UTC
Duration:          00:01:24

It looks like this is your first time using Cypress: 10.4.0

[STARTED] Task without title.
[TITLE]  Verified Cypress!       /home/node/.cache/Cypress/10.4.0/Cypress
[SUCCESS]  Verified Cypress!       /home/node/.cache/Cypress/10.4.0/Cypress

Opening Cypress...
[317:0817/162005.304881:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 511: Permission denied (13)
[511:0817/162005.352808:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

tput: No value for $TERM and no -T specified
================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.4.0                                                                         │
  │ Browser:        Electron 102 (headless)                                                        │
  │ Node Version:   v17.9.1 (/usr/local/bin/node)                                                  │
  │ Specs:          1 found (simple.cy.js)                                                         │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  simple.cy.js                                                                    (1 of 1)
[317:0817/162008.048565:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 587: Permission denied (13)

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      1                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     8 seconds                                                                        │
  │ Spec Ran:     simple.cy.js                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /tmp/git-sparse-checkout3472858567/repo/examples/cypress/vi     (1 second)
                          deos/simple.cy.js.mp4                                                     


tput: No value for $TERM and no -T specified
================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  simple.cy.js                             00:08        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:08        1        1        -        -        -  


Status Test execution completed with success 🥇
```

**Comment by TheLeanMachine** [comment]
Again, my bad: I did use `main` as main branch, but this was wrong for the repo I created...at least, **now the public tests are passing**:

<img width="1344" alt="Screenshot 2022-08-17 at 18 35 27" src="https://user-images.githubusercontent.com/3470837/185195003-9922d619-81a6-453a-8241-af67c9d1a36f.png">

Sorry 4 all the inconvenience!

**Comment by TheBrunoLopes** [comment]
Hi @TheLeanMachine! I'm Bruno the Product Leader for Testkube. I would love to get in touch with you to understand if there's anything else Testkube could be doing better to support your testing needs.
Would you spare 15m to go on a call with us https://calendly.com/bruno-at-kubeshop/15-minute-meeting ?
Really appreciate your input ;)

ps: just created an issue to add the missing field on the UI: https://github.com/kubeshop/testkube/issues/2086

**Comment by TheLeanMachine** [comment]
Hi @TheBrunoLopes,

yes, let's make that happen. Thanks for the bug report!

**Comment by TheLeanMachine** [comment]
Hi @vsukhin ,

I made the formerly public repo private (in order to change as little as possible) and created a new test with:

`kubectl testkube create test --git-uri https://bitbucket.org/xchangeteam/kais-public-stuff.git  --git-branch master --git-path examples --name private-cypress-demo-v1 --type cypress/project --git-username <MY_BITBUCKET_USERNAME> --git-token <MY_BITBUCKET_PASSWORD>`

...so, using the password of my bitbucket-user, instead of the API-token. Sadly, the test fails, too..

<img width="1431" alt="Screenshot 2022-08-18 at 11 27 50" src="https://user-images.githubusercontent.com/3470837/185361500-e8885299-d381-4c65-9123-f6e543764a37.png">


But when I try to obtain the test-containers logs, if fail to do so...

<img width="482" alt="Screenshot 2022-08-18 at 11 20 27" src="https://user-images.githubusercontent.com/3470837/185361628-d250ed7a-ae24-4d2f-8c48-5398b173c634.png">


So... @vsukhin , how did U manage to see the "fatal: could not read Username for 'https://bitbucket.org/': No such device or address"-error?

**Comment by vsukhin** [comment]
So, we start init container before executing cypress test. Init container is simply saving data in a pod volume, this is the only thing it does. Try to call CLI command `kubectl testkube get execution 62fe14f9261904554065c1b8`. You should see it there after execution fails

**Comment by TheLeanMachine** [comment]
Cool, seeing this now (will investigate further, now):

just FYI:
`waseemmir@Waseems-MacBook-Pro-container-Xchange dev-finance2 % kubectl testkube get execution  62fe0252cc6c2fe22315c1b6
ID:         62fe0252cc6c2fe22315c1b6
Name        private-cypress-demo-v1-1
Number:            1
Test name:         private-cypress-demo-v1
Type:              cypress/project
Status:            failed
Start time:        2022-08-18 09:11:46.65 +0000 UTC
End time:          2022-08-18 09:11:51.979 +0000 UTC
Duration:          00:00:05

Status test execution failed:

⨯ process error: exit status 128
output: Cloning into 'repo'...
remote: Bitbucket Cloud recently stopped supporting account passwords for Git authentication.
remote: See our community post for more details: https://atlassian.community/t5/x/x/ba-p/1948231
remote: App passwords are recommended for most use cases and can be created in your Personal settings:
remote: https://bitbucket.org/account/settings/app-passwords/
fatal: Authentication failed for 'https://bitbucket.org/xchangeteam/kais-public-stuff.git/'`

**Comment by vsukhin** [comment]
Nice, at least, there is a reason - Bitbucket Cloud recently stopped supporting account passwords for Git authentication.

**Comment by TheLeanMachine** [comment]
As pointed out, the cause for the problem is [bitbucket, (intentionally) disabling support for username/password authentication](https://community.atlassian.com/t5/Bitbucket-articles/Announcement-Bitbucket-Cloud-account-password-usage-for-Git-over/ba-p/1948231).

The solution is to [create an APP password](https://support.atlassian.com/bitbucket-cloud/docs/create-an-app-password/) and **use it instead of the password of the user's bitbucket account**.

<img width="1398" alt="Screenshot 2022-08-18 at 14 05 29" src="https://user-images.githubusercontent.com/3470837/185391345-0ed117f4-697c-4646-8940-13153203e6d4.png">

@vsukhin Thanks 4 quick latency feedback

@TheBrunoLopes still looking forward to chatting w/ you ;-)
