### ISSUE TITLE
CRD + CLI for orchestrating scripts

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#209]
As a tester i need to run multiple scripts after each other to validate that my application is working as expected. Today I have to manually run each script separately - I need to be able to orchestrate the execution of multiple scripts in sequence, with the same input to each of them. 
- The results should show if the test passed/failed - if it failed I need to know which script that failed, and why
- The scripts I orchestrate should run sequentially to start with
- I need to be able to configure property values that would be passed to all scripts (for example an endpoint or username/password)

I would like a visual tool for creating these in the long run - but for now I'm ok with having to write a YAML/CRD file that specifies which scripts to run in which order, with parameters/etc as described above. Once I've uploaded my tests to k8s I should be able to run/list/etc them as I can do for scripts today with the kubectl kubtest plugin - and get results correspondingly.

**Comment by exu** [comment]
implemented #738
