### ISSUE TITLE
Allow for minio image repository customization in helm-chart

### ISSUE THREAD

**Issue by bobrossthepainter** [kubeshop/testkube#2091]
**Describe the enhancement you'd like to see**
Hello,
could you please make the image repository for the minio container customizable. So it is possible for projects which have no connection to docker-hub to use the setup of testkube with the helm chart.

Btw, thanks for the great project!
Regards
Rob

**Additional context**
Code-Reference: https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/templates/minio.yaml#L51

**Comment by TheBrunoLopes** [comment]
Hi @bobrossthepainter !
Thank you for raising this, it's a good point.
Let's do it. Just added it for the current release.
We will get back to you in a bit.

**Comment by bobrossthepainter** [comment]
While scrolling through the config, I just found another non-customizable image. It's the kube-proxy of the operator.
https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/deployment.yaml#L26

Maybe you can add this as well.

Thanks! :)

**Comment by vsukhin** [comment]
Sure, thing)

**Comment by ypoplavs** [comment]
Hello @bobrossthepainter,

We have updated our `helm-chart` with the changes you requested. Please run `helm repo update` to retrieve the latest versions of the packages and you will be able to pass customizable images to `kube-proxy` and `minio` using `--set`. option.
Please let us know if you have any issues with that.
