### ISSUE TITLE
docs: Add FAQ section

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2112]
List of questions to add:

- Can I run any test on Testkube ?
- How do I install Testkube ?
- How do I expose it to the internet ?
- How do I setup my CI/CD to trigger tests ?
- Doest Testkube have customer support ?

**Comment by TheBrunoLopes** [comment]
@olensmar @exu
thoughts on if we there's a few more we should add/remove ?

**Comment by yllek** [comment]
How can I add custom test executors? Or how do I use tests that are not supported yet?
How do I get help within Testkube?
Where can I find what's coming next for Testkube? (link to roadmap?)

**Comment by jfermi** [comment]
Anyone who writes content for the FAQs can leave it as a comment here or send me a text file and I will create a FAQ to add to the docs.

**Comment by jfermi** [comment]
Sorry - I will update the current FAQ doc.

**Comment by TheBrunoLopes** [comment]
Reopening this to add the mentioned questions.
https://kubeshop.github.io/testkube/FAQ
