### ISSUE TITLE
Cypress executor image, browser setup

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2119]
Currently Cypress executor image is built based on Node image. It's extended with a few GTK-related packages and xvfb, and cypress is installed with npm.
- Electron isn't the best choice as browser for E2E tests - it's better to use real browser (for example Chrome/Chromium) instead
- Official Cypress images are available (https://github.com/cypress-io/cypress-docker-images) - browser images (with all dependencies and browser), or included images (with dependencies, browser, and Cypress) may be useful
- --headless mode in Chromium browser is already stable for a while - in my opinion it's better to use it by default instead of xvfb

**Describe the enhancement you'd like to see**
- switching to Chrome/Chromium as the default browser, using official Cypress images if possible
- possibility to select specific browser/cypress version

**Comment by vsukhin** [comment]
Guess, we have an issue about a custom browser for cypress

**Comment by vsukhin** [comment]
I see. Yes, this is one more ticket about executor parameters (defalt or a selected configuration, this was done for Ginkgo)

**Comment by vsukhin** [comment]
So, we need to use original cypress image and use data prepared by init container to support all cypress features

**Comment by vsukhin** [comment]
Implemented support for multiple Cypress images https://kubeshop.github.io/testkube/test-types/executor-cypress/#using-different-cypress-images

**Comment by tkonieczny** [comment]
```Tip: Look for recent executor versions here https://hub.docker.com/repository/registry-1.docker.io/kubeshop/testkube-cypress-executor/tags?page=1&ordering=last_updated.```
I got the login screen there - I think that's the correct link: https://hub.docker.com/r/kubeshop/testkube-cypress-executor/tags?page=1&ordering=last_updated
