### ISSUE TITLE
Support access to git repo using self signed certificate

### ISSUE THREAD

**Issue by dmasar** [kubeshop/testkube#2136]
**Is your feature request related to a problem? Please describe.**
When creating test from git specs I need to access git repository which is using self signed ssl certificate

**Describe the solution you'd like**
Need some way to tell executor to trust self signed certificates

**Describe alternatives you've considered**

**Additional context**
test is created with command:
kubectl testcube create test --git-uri https://<host>/xfrb/portal.git --git-branch dev/main --git-path test/portal --name cypress --type cypress/project

execution of test failed with error:
fatal: unable to access 'https://<host>/xfrb/portal.git/': SSL certificate problem: unable to get local issuer certificate

<host> is using self signed certificate

**Comment by TheBrunoLopes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2136?planning-poker) with Zenhub @nicufk @pavloburchak @vLia @vsukhin

**Comment by TheBrunoLopes** [comment]
AC:
- Containers must run as non-root

**Comment by mattiaforc** [comment]
Hi everybody, I tried to create a gradle test that should fetch a private git repository that has a self signed certificate, but I encountered a few problems:
- from the CLI, executing the command ’testkube create -t gradle/test —name test-cert —git-uri xxxx —git-certificate-secret cert’ outputs a failed validation, telling me that only one certificate path should be specified only once. 
- I created a certificate secret from file, and I tried editing manually the Test CR, which accepted the new field certificateSecret (as a string), but it did not show from the UI (looking at the configuration->definition tab) and the test, when run, failed as always because it could not validate the self signed certificate. 

What am I missing? Plus, as a side question, how can I set a more verbose logging when the test will be run (e.g. showing the log related to the new certificate validation)?

**Comment by nicufk** [comment]
Hi @mattiaforc, issue was closed after the implementation but there are the fixes that are still in progress, like the ones that you encountered. 
also there will be more logs for the certificate as well.

**Comment by nicufk** [comment]
@mattiaforc you can try it now with the latest release, it is not tested thoroughly though.

**Comment by mattiaforc** [comment]
@nicufk Thanks for the quick feedback! Now I see the configuration both in the CR and in the UI, the CLI works just fine too. But, the executor still fails; have a look at the logs:

```json
{"type":"line","content":"📦 Using certificate for git authentication from secret: gitlab","time":"2023-01-20T16:10:44.758277949Z"}
{"type":"line","content":"✅ Fetching certificate from path /etc/certs","time":"2023-01-20T16:10:44.758282909Z"}
{"type":"line","content":"✅ Found certificate /etc/certs/..2023_01_20_16_10_41.146514658/ca-certificates.crt","time":"2023-01-20T16:10:44.75832865Z"}
{"type":"line","content":"✅ Found certificate /etc/certs/ca-certificates.crt","time":"2023-01-20T16:10:44.758338051Z"}
{"type":"line","content":"❌ Failed to configure git to use certificate /etc/certs/ca-certificates.crt, output: \n Error: exit status 255","time":"2023-01-20T16:10:44.760854201Z"}
```

In the code, [this is](https://github.com/kubeshop/testkube/blob/f900c8ef4d38e7a6c38fd254ac2ed477859fb9d8/pkg/executor/content/fetcher.go#L180) where it fails. I double checked the certificate secret, and that `ca-certificates.crt` file works fine on a alpine/git image, running that same `git config` command and then pulling the repo. 

Could it be some permission problem maybe?

**Comment by mattiaforc** [comment]
After digging a bit, I found out that the problem was indeed permissions - the init container does not run as root, but when the `git config --global` is run, it does not have enough privileges: `error: could not lock config file //.gitconfig: Permission denied`. Running a debug pod as root solves the problem. 

So, how should I proceed now? Do you think the fix could be applied to the base image for the executors (i.e. making the `.gitconfig` accessible to any user), or should I run the jobs as root user? If that's the case, I think it should be configurable directly from the helm chart instead of having to build a custom executor/etc...

**Comment by nicufk** [comment]
Hey @mattiaforc, thanks for the investigation you made, a very good input. I think the best solution is to make .gitconfig accessible for the running user, we prefer to run the containers as non root because openshift users cannot run them otherwise.

**Comment by mattiaforc** [comment]
Hi @nicufk, I 100% agree, running Testkube on Openshift myself 😃  This has to be done in every executor image though? I think this will take some time!

**Comment by nicufk** [comment]
@mattiaforc fortunately we have a init container that is cloning the tests from git repos, you can check the latest PR.

**Comment by mattiaforc** [comment]
Hi @nicufk, yes luckily the init container is a good place to do such configuration! I redeployed the new version of testkube, but the problem still occurs (the image of the init container is: kubeshop/testkube-executor-init:0.7.29), as you can see from these commands I tried to run as the default user:

```bash
/root $ git config --global http.sslCAInfo /etc/certs/ca-certificates.crt 
error: could not lock config file //.gitconfig: Permission denied
/root $ ls -la /r
root/  run/
/root $ ls -la /root/
ls: can't open '/root/': Permission denied
total 0
/root $ ls -la /
total 4
dr-xr-xr-x    1 root     root            40 Jan 30 16:00 .
dr-xr-xr-x    1 root     root            40 Jan 30 16:00 ..
drwxr-xr-x    1 root     root            20 Jan 26 09:24 bin
drwxrwsrwx    2 root     10011200         6 Jan 30 16:00 data
drwxr-xr-x    5 root     root           380 Jan 30 16:00 dev
drwxr-xr-x    1 root     root            38 Jan 30 16:00 etc
drwxr-xr-x    2 root     root             6 Jan  9 12:46 home
drwxr-xr-x    1 root     root            17 Jan  9 12:46 lib
drwxr-xr-x    5 root     root            44 Jan  9 12:46 media
drwxr-xr-x    2 root     root             6 Jan  9 12:46 mnt
drwxr-xr-x    2 root     root             6 Jan  9 12:46 opt
dr-xr-xr-x  294 root     root             0 Jan 30 16:00 proc
drwx------    1 root     root            24 Jan 26 09:22 root
drwxr-xr-x    1 root     root            42 Jan 30 16:00 run
drwxr-xr-x    2 root     root          4096 Jan  9 12:46 sbin
drwxr-xr-x    2 root     root             6 Jan  9 12:46 srv
dr-xr-xr-x   13 root     root             0 Jul  4  2022 sys
drwxrwxrwt    2 root     root             6 Jan  9 12:46 tmp
drwxr-xr-x    1 root     root            81 Jan 26 09:22 usr
drwxr-xr-x    1 root     root            17 Jan 26 09:22 var
/root $ ls -la /root/.gitconfig
ls: /root/.gitconfig: Permission denied
```

**Comment by nicufk** [comment]
Hey @yyefet, do you still have the same problem with the latest release? I cannot reproduce it on my side

**Comment by jnamdar** [comment]
Hi @nicufk, we do have reproduced the issue mentioned here https://github.com/kubeshop/testkube/issues/2136#issuecomment-1398620155  

It actually seems to work fine in the `init` container (the cert setup logs do not give any errors), but in the executor container we have the same error.  

We have installed testkube with the official helm chart v1.9.141. We can get around the issue by providing the `GIT_SSL_NO_VERIFY` env variable with the value `true `when we run the test, but obviously that's not ideal.
