### ISSUE TITLE
Make it possible to explicitly set the Cypress version that is being used by testkube with the Cypress-NX-executor

### ISSUE THREAD

**Issue by TheLeanMachine** [kubeshop/testkube#2142]
**Is your feature request related to a problem? Please describe.**

(Prerequisite for working on this FR is, that [this FR here](https://github.com/kubeshop/testkube/issues/2141) has already been implemented!)

Sadly, I still cannot use NX-integration right away, as currently it seems to use the `latest` version of Cypress.
Problem: Our tests still run with `9.x` of Cypress, we haven't migrated, yet (even if we plan to do so)...

**Describe the solution you'd like**
A way to specify the Cypress version, being used to run the Cypress tests. Either a field in the test's definition. Or sth like an environment variable....

Note that for "plain Cypress tests" this already does work, by overriding the `cypress` version in the `devDependencies`, [as shown here](https://github.com/kubeshop/testkube-example-cypress-project/tree/main/v8-test). I successfully tried this out on my testkube cluster...
<img width="1726" alt="Screenshot 2022-08-24 at 13 44 37" src="https://user-images.githubusercontent.com/3470837/186410409-c70b5bd3-c702-45de-87d1-2321bcd4381f.png">

**Describe alternatives you've considered**
Migrating our Cypress tests to version `10`.

**Additional context**
This ticket is a follow-up [of this feature request](https://github.com/kubeshop/testkube/issues/2141).

**Comment by tkonieczny** [comment]
I think this one is also partially related: https://github.com/kubeshop/testkube/issues/2119 (possibility to select different cypress versions and browsers)

**Comment by TheLeanMachine** [comment]
UPDATE: I placed a `package.json` on the same level as the cypress.json config file ([as shown in the official examples](https://github.com/kubeshop/testkube-example-cypress-project/tree/main/v8-test)).

It works for me, now. CLOSE-ing...

<img width="1742" alt="Screenshot 2022-09-02 at 15 13 37" src="https://user-images.githubusercontent.com/3470837/188153646-36d60d9b-b2aa-41ed-b583-ec56bed24737.png">
