### ISSUE TITLE
predict if my cluster has enough resources to run tests

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#2150]
I would like Testkube to warn me if I'm trying to run tests that my cluster will (probably) not have enough resources to run... for example if I'm trying to run a load-test when there are already several tests in flight. As an extension I would like to tell Testkube to run my tests "when there are enough resources available" (instead of immediately)

not sure if Testkube can have some algorithm for some guesstimation in this regard!? can it find out what resources a cluster has available? perhaps it can learn from previous request runs how long a test usually takes and the resources it usually consumes!? 

I understand this is near impossible to get right - but even a simple algorithm would be helpful - maybe even something that users have to configure - i.e. "allow only X simultaneous tests"

**Comment by tkonieczny** [comment]
I think there is a simple solution for this. If we would gather resource usage history for the tests it should be relatively easy to "predict" the next execution and decide if it's safe to schedule it. Most of the tests won't change significantly, and they will be mainly reran, so the only thing unknown is running new Tests for the first time. And, that's where we can optionally display some warning

**Comment by TheBrunoLopes** [comment]
won't do for now.
