### ISSUE TITLE
Support GitOps for test script management

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#219]
I want to use GitHub for managing my test scripts and not have to update them manually in kubtest every time I update them. 

Possible Solution: 
- a "import from GitHub" wizard that finds all supported scripts in my repo and uploads them into k8s, adding a reference to the original script as an annotation to the script resource
- a webhook that listens for changes to scripts in github and updates them in k8s automatically - based on the above annotation

**Comment by olensmar** [comment]
could be resolved as part of #264 which provides shared mechanics for getting scripts for execution from Git

**Comment by olensmar** [comment]
#596 is related - but more specific to argocd gitops workflows

**Comment by exu** [comment]
This will be implemented as git based content (like for Cypress) which on the end don't need to be updated

**Comment by exu** [comment]
All work will be done in https://github.com/kubeshop/testkube/issues/795

**Comment by olensmar** [comment]
thanks @exu but that's not what I meant - i'll reopen this if I still think it is needed

**Comment by exu** [comment]
@olensmar ok so maybe I don't get correctly porpose of this task - let's plan it if be needed in future
