### ISSUE TITLE
UI: Variables created in UI is not visible after few seconds

### ISSUE THREAD

**Issue by sharmajee1** [kubeshop/testkube#2199]
**Describe the bug**
[Please Watch me](https://discordapp.com/channels/884464549347074049/885185660808474664/1012991700135850016)

**Version / Cluster**
- Which testkube version? 
Client Version 1.5.2
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
Local Minikube
- What Kubernetes version?
minikube version: v1.25.1
*

**Comment by rajeshpillai** [comment]
This is my first post and apologies if any posting rule is broken.  Let me know and I will correct it.  

I was evaluating testkube for an upcoming projects and this is where I got stuck as well.  I thought it's my setup issue.  But verified on couple of different systems with latest versions to ensure this.  

I am creating variables in the dashboard UI and after saving the message appears of successful save.  But when I check the variables again they are not shown in the UI.  

Tested on ubuntu, mac loca machine with minikube.  I want the test k6 test output to be logged in influxdb and the url was being setup in the variable which was being ignored by the execution.

**Comment by sharmajee1** [comment]
> 

This issue is to solve the same problem @rajeshpillai

**Comment by TheLeanMachine** [comment]
I can confirm that behavior.

After "successfully" saving the env vars...
<img width="1583" alt="Screenshot 2022-09-01 at 14 42 52" src="https://user-images.githubusercontent.com/3470837/187916667-a7418836-cac8-43b6-a2b5-b62a53b7ce10.png">

...they won't show up after reload:
<img width="1265" alt="Screenshot 2022-09-01 at 14 43 05" src="https://user-images.githubusercontent.com/3470837/187916729-e544109a-53b2-4e58-a982-8a8686156691.png">

**Comment by TheLeanMachine** [comment]
As a workaround, you can set the required vars [via --secret-env and --env flag](https://kubeshop.github.io/testkube/cli/kubectl-testkube_create_test/).

For example...

```
kubectl testkube create test --git-uri <REPO_URL> --git-branch <BRANCH_TO_CHECKOUT> --git-path <PATH_TO_CYPRESS_TESTS_IN_REPO> --name your-example-test --type cypress/project --git-username <YOUT_GIT_USERNAME> --git-token <APP_PASSWORD_OR_TOKEN> --env CYPRESS_CONFIG_FILE=apps/xchange-app-e2e/cypress.json --env CYPRESS_FIXTURES_FOLDER=apps/xchange-app-e2e/src/fixtures --env CYPRESS_INTEGRATION_FOLDER=apps/xchange-app-e2e/src/integration --env CYPRESS_PLUGINS_FILE=apps/xchange-app-e2e/src/plugins/index.js
```

Note that these are still not shown under "Variables & Secrets". But in the test's definition, they are...

<img width="1386" alt="Screenshot 2022-09-01 at 15 11 47" src="https://user-images.githubusercontent.com/3470837/187922930-b1341699-2512-458e-aa3c-f597b1bf6239.png">

**Comment by TheBrunoLopes** [comment]
Hello, thanks for reporting this guys.
We are taking a look into this, will report to you soon.

**Comment by Toxer10** [comment]
Hello, @TheLeanMachine, we just fixed the display issue of the variables on the UI. However, I'm noticing that you have your variables under the ENVs and not under the Variables field.
