### ISSUE TITLE
UI not showing steps in testsuite

### ISSUE THREAD

**Issue by ili-shmidt-wib** [kubeshop/testkube#2211]
<img width="241" alt="Screen Shot 2022-09-01 at 14 57 39" src="https://user-images.githubusercontent.com/104712602/187913528-6d131c5a-306d-406f-a9de-fe91294069d5.png">

**Comment by Toxer10** [comment]
Hey, @ili-shmidt-wib, thanks for reporting! We fixed this bug in the latest release.

**Comment by ili-shmidt-wib** [comment]
Thanks!
@Toxer10
