### ISSUE TITLE
Docs: Add examples for running Testkube integated with "S3" and "Cloud Storage" 

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2213]
**Describe the enhancement you'd like to see**

Users are confused on how to use testkube with S3
Write docs with examples about using it 
Second part should be about integrating Testkube with "Cloud Storage" from Google

**Comment by senare** [comment]
also : https://github.com/kubeshop/testkube/issues/2299

**Comment by TheBrunoLopes** [comment]
will be done in https://github.com/kubeshop/testkube/issues/2299
