### ISSUE TITLE
Update docker images to recent ones

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2214]
**Describe the enhancement you'd like to see**

To follow good security practice, we need to use recent base docker images building our software. 

- [ ] Testkube main repo
- [ ] Operator
- [ ] Executor: template 
- [ ] Executor: postman
- [ ] Executor: cypress
- [ ] Executor: curl 
- [ ] Executor: maven
- [ ] Executor: gradle
- [ ] Executor: artillery
- [ ] Executor: kubepug
- [ ] Executor: soapui
- [ ] Executor: JMeter
- [ ] Executor: ..... ??

**Comment by tkonieczny** [comment]
Related: https://github.com/kubeshop/testkube/issues/2109

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2214?planning-poker) with Zenhub @nicufk @vLia

**Comment by TheBrunoLopes** [comment]
ac:
- make sure we don't add breaking changes

**Comment by TheBrunoLopes** [comment]
won't be needed for now.
