### ISSUE TITLE
Hide Sensitive variables from UI

### ISSUE THREAD

**Issue by abhipsnl** [kubeshop/testkube#2219]
**Is your feature request related to a problem? Please describe.**
With the new release, we can see the variables in UI, but few variables are sensitive.
Which are not visible in the test settings, but they are visible in the run output.

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/27809898/188155367-f3b67471-0172-45f7-b080-2952eab35d9e.png">

<img width="526" alt="image" src="https://user-images.githubusercontent.com/27809898/188155588-19268e49-2055-4ca3-86fb-4be85bb73868.png">

**Describe the solution you'd like**
Hide all sensitive variables in UI

**Describe alternatives you've considered**
Or add some flag in deployment, if sensitive enabled true show them, if false don’t show them.

**Comment by sharmajee1** [comment]
Even from CLI the secrets are visible 

```
╰─➤  kubectl testkube get execution 6312356eaa82962a076db84b                                                                  1 ↵
ID:         6312356eaa82962a076db84b
Name        dev-silicon-card-card-test-postman-collection-12
Number:            12
Test name:         dev-silicon-card-card-test-postman-collection
Type:              postman/collection
Status:            failed
Start time:        2022-09-02 16:55:10.149 +0000 UTC
End time:          2022-09-02 16:55:29.342 +0000 UTC
Duration:          00:00:19

  Variables:    2
  - keyCloakClientSecret = 1234 🔒
  - keyCloakClientSecret-gw = 1234 🔒

Status test execution failed:

```

**Comment by pavloburchak** [comment]
Looks like for latest UI version this issue is not occurring. Can you still see it @abhipsnl ?
