### ISSUE TITLE
testkube installation is failing with helm chart from mongoDB version of 12.0.0

### ISSUE THREAD

**Issue by sharmajee1** [kubeshop/testkube#2251]
**Describe the bug**
I was doing a fresh installation of testkube using helm chart with the mongoDB version of 12.0.0 and mongo pods were crashing.
But when I increased the mongo version to 13.1.2 the issue got resolved, unable to find more details.

**K8s Platform**
- OKE kubernetes
-  Fresh installation

**Screenshots**
Logs details
 
[message.txt](https://github.com/kubeshop/testkube/files/9524686/message.txt)

**Comment by ypoplavs** [comment]
Hello @sharmajee1,

Could you please specify on what platform you run k8s cluster (GCP, AWS etc)? And did you do an upgrade or fresh install of Testkube?

Also could you please paste output of `kubectl describe pod mongo-pod-name -n testkube` command.

**Comment by sharmajee1** [comment]
> Hello @sharmajee1,
> 
> Could you please specify on what platform you run k8s cluster (GCP, AWS etc)? And did you do an upgrade or fresh install of Testkube?
> 
> Also could you please paste output of `kubectl describe pod mongo-pod-name -n testkube` command.

Updated the issue, I have attached the message.txt file, but now the old pod is deleted, next time I will try to attach those info too.

**Comment by gioppoluca** [comment]
I believe is similar to this:
https://github.com/kubeshop/testkube/issues/2232

**Comment by ypoplavs** [comment]
Hello @sharmajee1 

We have updated our helm-charts with a Mongo version 11, since later versions introduce many bugs. Could you please install the latest chart version of testkube?

**Comment by vsukhin** [comment]
closed in favor of #2232
