### ISSUE TITLE
Telemetry: UI & Test Usage

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2253]
### **UI specific metrics**
- H: Get number of unique active users. Being done in https://github.com/kubeshop/testkube/issues/2069 ✅ 
- L: Average time on the following pages: Test & Suite List ; Test & Test suite page. Test/suite settings.
- L: Nº of actions: 
   - Create Test
   - Create Testsuite
   - Run TestSuite
   - Run Test

### **Test runs:**
- H: Nº Test executions.
    - Get the type of test (cypress,k6,postman, etc...)
    - Duration
    - Data around resource usage: CPU, Memory, storage, etc...
    - Visualization: <img width="884" alt="image" src="https://user-images.githubusercontent.com/13501228/189109187-8ce7aa29-628c-460c-8f3e-93ea0e9ecd92.png">

- H: Nº of Test Suite runs:
    - Visualization: <img width="884" alt="image" src="https://user-images.githubusercontent.com/13501228/189110519-99c5daf3-e21c-4dc2-b315-dea0d8f9f5ad.png">

- M: Nº of Test Creations (add test type and source type)
- M: Nº of Test Suite creations

### - Notes
- all metrics should have daily & weekly views/calculations.
- **priority levels:** H > M > L (lets focus on the H first)

**Comment by TheBrunoLopes** [comment]
AC: Complete the backend issue that adds an api endpoint to disable telemetry.

**Comment by vsukhin** [comment]
From what I understood there, we will need send these 4 events for telemetry collection. And then based on this data UI will be used to prepare reports

**Comment by exu** [comment]
@vsukhin yes, just pass different event type, segment will create automatically new table for that events.

**Comment by vsukhin** [comment]
@TheBrunoLopes  all 4 events were added and sent to segment.io. We need to create related reports there
