### ISSUE TITLE
[Spike] Research if we can get a list of labels from the Cluster

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2257]
Please time box this to max 1 hour :) 

We want to allow our users to add labels to their tests / test suites in the UI. 
Since we want them to avoid having potential typos and a quicker way to add recurring labels we will provide them with an[ auto-suggest / typeahead](https://baseweb.design/components/select/#select-creatable) for label keys/values. 

<img width="612" alt="image" src="https://user-images.githubusercontent.com/132332/189202383-07f4b3ad-8449-4002-b28f-fb0f79f5ffe2.png">  

For this to happen we need to know if we can also get pre-existing labels (key/values) from other cluster resources (but at least testkube related labels!) :)

**Comment by vsukhin** [comment]
So, after checking the docs, I didn't find a method or command to get labels for all Culster resoutrces. Label is not a separate resource, it's a part of resource metadata. Still we can collect all labels for Testkube CRD, like Test or Test Suite. But keep it mind, that we will need to check each object in the list to get labels. So, it will be quite slow, if we have a lot of tests. Might be we need to chache them in this case

**Comment by fivenp** [comment]
Don't really want to re-open this issue – but out of curiosity:

@tkonieczny just mentioned the `--show-labels` flag recently and I was wondering if we potentially could abuse it to collect all labels from the cluster? 

e.g. 
`$ kubectl get all --show-labels`

**Comment by vsukhin** [comment]
I guess, it was I meant above, we just list all the resources and take labels ffrom each of them. We can try it out
