### ISSUE TITLE
Cypress executor - --git-commit - "can't find branch in params" error

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2271]
**Describe the bug**
Cypress project fails with "can't find branch in params" error if test is created with `--git-commit`.

**To Reproduce**
1. Create test with `--git-commit`, for example: `tk create test --type cypress/project --git-uri https://github.com/kubeshop/testkube --git-commit ed374e40c2c45265f4b99e5c9725f0727fdbebe7 --git-path test/cypress/executors/cypress-10 --name cypress-executor-test-commit-only`
2. Run test: ` tk run test cypress-executor-test-commit-only`
3. Check execution logs:
```
$ kubectl testkube get execution 631f861d9fa1f68606c401ce
W0912 21:20:54.425555  132935 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
client version is older than api version, please upgrade
ID:         631f861d9fa1f68606c401ce
Name        cypress-executor-test-commit-only-1
Number:            1
Test name:         cypress-executor-test-commit-only
Type:              cypress/project
Status:            failed
Start time:        2022-09-12 19:18:53.948 +0000 UTC
End time:          2022-09-12 19:19:02.2 +0000 UTC
Duration:          00:00:08

Status test execution failed:

⨯ can't find branch in params, repo:&{Type_:git Uri:https://github.com/kubeshop/testkube Branch: Commit:ed374e40c2c45265f4b99e5c9725f0727fdbebe7 Path:test/cypress/executors/cypress-10 Username: Token: UsernameSecret:<nil> TokenSecret:<nil>}
```
```
$ kubectl logs 631f861d9fa1f68606c401ce-tkg5z -n testkube
{"type":"event","content":"running test [631f861d9fa1f68606c401ce]"}
{"type":"error","content":"can't find branch in params, repo:\u0026{Type_:git Uri:https://github.com/kubeshop/testkube Branch: Commit:ed374e40c2c45265f4b99e5c9725f0727fdbebe7 Path:test/cypress/executors/cypress-10 Username: Token: UsernameSecret:\u003cnil\u003e TokenSecret:\u003cnil\u003e}"}
```

**Expected behavior**
Successful test execution.

**Version / Cluster**
```
$ tk version
...
Client Version 1.5.16
Server Version v1.5.17
Commit 1a6d03c3f59a62874c5494b9650eef8f804f0d46
Built by goreleaser
Build date 2022-09-12T11:09:22Z
```
 
**Additional context**
Error message may suggest `--git-branch` is mandatory, but it's not possible to pass both --git-commit and --git-branch:
```
validating passed flags (error: please pass only one of `--git-branch` or `--git-commit`)
```

**Comment by vsukhin** [comment]
Yeah, it's an old check in executor itself before Commit parameter was introduced. will fix it tmo
	if execution.Content.Repository.Branch == "" {
		return fmt.Errorf("can't find branch in params, repo:%+v", execution.Content.Repository)
	}

**Comment by vsukhin** [comment]
Yeah, it's an old check in executor itself before Commit parameter was introduced. will fix it tmo
	if execution.Content.Repository.Branch == "" {
		return fmt.Errorf("can't find branch in params, repo:%+v", execution.Content.Repository)
	}
