### ISSUE TITLE
Fix dependabot issues

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2278]
https://github.com/kubeshop/testkube/security/dependabot

**Comment by tkonieczny** [comment]
Related: https://github.com/kubeshop/testkube/issues/2109

**Comment by TheBrunoLopes** [comment]
<img width="1689" alt="image" src="https://user-images.githubusercontent.com/13501228/189914194-9e57e490-a443-424c-8c33-25444e4f2b07.png">
<img width="1689" alt="image" src="https://user-images.githubusercontent.com/13501228/189914234-570a9d38-8a98-4deb-b93d-be58c3b5252d.png">
