### ISSUE TITLE
Remove ALL demo.testkube.io references from Helm values file

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2298]
- Remove all ingress configurations that mention the url demo.testkube.io
- Remove all references that might relate with any cluster that belongs to demo or dev environments that the testkube team might deploy to.

**Comment by dejanzele** [comment]
This is currently half-implemented.

References to the url `demo.testkube.io` have been removed.
Only thing left is to remove the environment values files, but we need to do some internal changes in order to be able to remove those files.
