### ISSUE TITLE
Docs: Installation improvements

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2299]
- When using helm to deploy Testkube describe in the installation docs the following:
- All the components that are going to be installed. For each one of them describe how to (which values need to be provided to):
   - Change mongodb
   - Connect to a different s3 solution instead of minio.
   - Expose API server using the ingress
   - Expose UI using ingress

**Comment by senare** [comment]
also: https://github.com/kubeshop/testkube/issues/2213
