### ISSUE TITLE
Support k8s v1/alpha1 authentication for Legacy clusters

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2301]
- Seems that right now our CLI expects v1/beta1 to be in place, but there's some users that don't have the most recent one.
- It should fall back to the older auth method in case v1/beta1 is not available.

**Comment by dejanzele** [comment]
@TheBrunoLopes 

ExecPlugin `client.authentication.k8s.io/v1alpha1` was deprecated and removed from Kubernetes in version 1.24.
Here are the deprecation notes from the v1.24 [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#deprecation)

Users who are running Kubernetes versions older than v1.24, should ensure the following:
* update `aws-cli` to latest version
* make sure their `kubectl` version is X-1,X or X+1 of their Kubernetes version
* make sure they are using ExecPlugin version `client.authentication.k8s.io/v1beta1` or newer (either by updating the kubeconfig manually, or regenerating the kubeconfig using a command like `aws update-kubeconfig`, or a combination of both)

I have validated that TestKube CLI works for the following versions:
* EKS v1.20.15
* kubectl v1.20.0
* aws-cli v2.7.31
* `user.exec.apiVersion` updated from `client.authentication.k8s.io/v1alpha1` to `client.authentication.k8s.io/v1beta1`

**Comment by vsukhin** [comment]
@dejanzele should we close it?

**Comment by dejanzele** [comment]
we have put together steps on what to do for legacy tools (Helm V2, Kubernetes < v1.22, awscli < v2.7...), I'll close it now
