### ISSUE TITLE
how to configure external mongodb with TLS enabled and Minio storage for testkube

### ISSUE THREAD

**Issue by chandana194** [kubeshop/testkube#2307]
### Discussed in https://github.com/kubeshop/testkube/discussions/2292

<div type='discussions-op-text'>

<sup>Originally posted by **nizamkhazi87** September 15, 2022</sup>
Can we configure external mongodb and minio istead of a default installation which comes along with testkube instalation .
If yes , Can have a documentation for same so to follow and learn </div>

**Comment by vsukhin** [comment]
Closing in favor of #2308
