### ISSUE TITLE
Provide connection to external mongodb with ssl certificate

### ISSUE THREAD

**Issue by nizamkhazi87** [kubeshop/testkube#2308]
We are not able to connect external mongodb with ssl certificate.
Most of the installation with the kubernates required ssl certificate to connect database which is install in different cluster .
Currently there is no option to configure ssl cert for any external database . It will be help full for all we they store test result in there local or centralise database with their own backup .

Solution Which i like to have . 
Provide ssl cert path in api-server yaml after installing testkube where they can specify cert path which they have created in configmap / cert which got created in kubernates.

**Comment by vLia** [comment]
Hey @nizamkhazi87,
We released recently some changes to address this issue. You can see the docs here: https://kubeshop.github.io/testkube/using-testkube/dependencies/#ssl-connections

When dealing with an existing installation, you can create the Kuberenetes secret from the docs with the values having the contents of the certificate files in base64, update the api-server environment variables `API_MONGO_DSN` and `API_MONGO_SSL_CERT`, and restart the api-server for the changes to take effect.

Please let us know how this goes!

**Comment by vsukhin** [comment]
please let us know, if you have any questions
