### ISSUE TITLE
Option to run test on multiple pod parallelly  

### ISSUE THREAD

**Issue by nizamkhazi87** [kubeshop/testkube#2310]
Good to have feature to run k6 test parallelly on multiple pod using option .

**Comment by TheBrunoLopes** [comment]
Hello @nizamkhazi87.
This one seems very interesting, would you be ok with jumping on a quick call with us to understand how to implement this in the best way ?
Feel free to book it here -> https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by tkonieczny** [comment]
Related: https://github.com/kubeshop/testkube/issues/1431

**Comment by tkonieczny** [comment]
I created an issue for parallel execution of all tests in Testsuite: https://github.com/kubeshop/testkube/issues/2356. It could be used as workaround for this issue.

**Comment by TheBrunoLopes** [comment]
This feature will be done as part of this issue. Closing this one, to not have duplicates. https://github.com/kubeshop/testkube/issues/2356
