### ISSUE TITLE
Allow users to add labels to Tests + Test Suites

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2322]
**Describe the enhancement you'd like to see**
We would like our users to be able to add labels to their testkube tests + test suites on the UI. (Labels help to categorise and bundle/cluster resources together to be able to target later actions easier (e.g. filters, etc))

The ux should follow this example here: 
https://baseweb.design/components/select/#select-creatable-multi-pick

* The user can select existing labels (for the beginning let's just include testkube labels – not cluster wide labels)
* The user can also create a new label in here 
* Be aware – the user can only create a new label if there's a `:` separator in his string

I tried to mock all cases and scenarios in Figma:
https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=1485%3A98952

**This affects the following views:** 

1. [Test Creation](https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=27%3A22735)
2. [Test Suite Creation](https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=5%3A6676)
3. [Test Settings](https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=27%3A17386)
4. [Test Suite Settings](https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=5%3A12401)
5. We do also need to change how we display labels across the UI (e.g. page title, entity cards, etc)  (for example here: https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=8%3A10291)

**Additional context**
![image](https://user-images.githubusercontent.com/132332/191094032-452e64d8-4608-4139-96c5-da5dfc95ef72.png)

**Comment by olensmar** [comment]
i'm sure you've discussed this but it's not spelled out in the issue: why do users need labels? what problems could labels solve? i.e. "As a Tester or DevOps engineer I need labels to help me do what?"

**Comment by fivenp** [comment]
Very well said (and adapted)... 
We do already have the functionality to add labels on the API + CLI / CRD – so this is more of a catch up feature on the UI. But as you mentioned – we could def. guide our users a little bit better within the UI and explain them why they'd need labels.
