### ISSUE TITLE
Parallel Testsuite tests execution

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2356]
**Is your feature request related to a problem? Please describe.**
Currently it's only possible to execute tests concurrently with labels, however it's not convenient and it's not possible to get clear result if all of them passed (as the whole).

**Describe the solution you'd like**
The idea is to allow executing tests in parallel on the Testsuite level. The long term solution may be to allow configuring different Testsuite parts to run in parallel. However, the initial and relatively easy to implement solution would be to allow configuring the whole Testsuite as parallel/concurrent. So if this option will be enabled for specific Testsuite, every Test in the Testsuite will be executed in parallel.
Discussed yesterday with @TheBrunoLopes

**Comment by exu** [comment]
I think we can go here with really simple implementation: 

Just use [][]testStep instead of []testStep.

Current implementation is just a list of testSteps
If we would add additional dimension we can create simple matrix e.g.

Before: 
```yaml
- 'Run test 1' 
- 'delay 100ms'
- 'Run test 2'
```

After: 
```yaml
- ['Run test 1', 'Run test 2'] // parallel run
- ['delay 100ms']
- ['Run test 3', 'Run test 2'] // parallel run
```

**Comment by exu** [comment]
cc: @Toxer10 @fivenp @pavloburchak what do you think about UI changes for that? we would need to change the way how frontend behaves (some kind of pipeline definition with quite simple data model behind)

**Comment by fivenp** [comment]
I was about to suggest the exact same array logic for our CRDs @exu :) 

On the UI this would translate most likely to something similar to this here where you can drag & drop tests around or add new ones (please take it as a concept for now :)): 
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/132332/192032112-4a775beb-46c0-4434-8880-255442df214f.png">

**Comment by exu** [comment]
I would suggest something like this one
<img width="624" alt="image" src="https://user-images.githubusercontent.com/30776/192217696-7ae57bb3-116a-4171-93fb-405c2184addc.png">


In terms of implementation messing with strings and arrays as data model will make it complex so let's keep array (it'll be just one element array which is quite simple to implement on UI)

**Comment by tkonieczny** [comment]
So, looks like the complete version :smile: 

For example, there is a testsuite:
```
{
	"name": "executors-smoke-tests",
	"description": "Executors smoke tests",
	"steps": [
		{"execute": {"name": "cypress-legacy-executor-smoke-electron"}},
		{"delay": {"duration": 1000}},
		{"execute": {"name": "cypress-10-executor-smoke-electron"}},
		{"execute": {"name": "cypress-10-executor-smoke-chrome"}},
		{"execute": {"name": "cypress-10-executor-smoke-firefox"}},
		{"execute": {"name": "cypress-9-executor-smoke-electron"}},
		{"execute": {"name": "cypress-9-executor-smoke-chrome"}},
		{"execute": {"name": "cypress-9-executor-smoke-firefox"}},
		{"execute": {"name": "cypress-8-executor-smoke-electron"}},
		{"execute": {"name": "cypress-8-executor-smoke-chrome"}},
		{"execute": {"name": "cypress-8-executor-smoke-firefox"}}
	]
}
```

So, the concurrent steps will look like this:
```{"execute": [{"name": "cypress-9-executor-smoke-electron"}, {"name": "cypress-9-executor-smoke-chrome"}]},```
?

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2356?planning-poker) with Zenhub @nicufk @vLia

**Comment by michal-kosikcz** [comment]
Hi, is there an estimate for this feature?

**Comment by vsukhin** [comment]
It was implemented, but frozen by product team for releasing. Ping @TheBrunoLopes for details

**Comment by TheBrunoLopes** [comment]
hey @michal-kosikcz we are working on making a final polish on it and will be available in the next release.

**Comment by TheBrunoLopes** [comment]
closing this issue. as it's done.
