### ISSUE TITLE
Dashboard script paths incorrect when Ingress is allowed with a PathPrefix

### ISSUE THREAD

**Issue by stand-sure** [kubeshop/testkube#2362]
**Describe the bug**
Dashboard fails to show content when an Ingress with a PathPrefix is used

**To Reproduce**
1. Override the Helm chart values to allow ingress for the dashboard
  - set ingress.enabled to true
  - set the first ingress.hosts.host to your host name
  - set the first ingress.hosts.host.paths.path to your path
  - set the first ingress.hosts.host.paths.pathType to Prefix
  - set testkube-dashboard.ingress.enabled to true
  - set testkube-dashboard.ingress.path as above
  - set testkube-dashboard.ingress.hosts as above
2. Navigate to the dashboard
3. The scripts referenced in the page to load the static resources have absolute path and will fail to be served, making the page blank
**Expected behavior**
The static resources should be loaded so that the app will work.

**Version / Cluster**
- Which testkube version? 
  - Helm Chart 1.5.68
  - Client Version 1.5.27
  - Server Version v1.5.30
  - Commit bd3d3fdb1c202cfc9d410013089648f47652cbdb
  - Built by goreleaser
  - Build date 2022-09-19T13:50:40Z
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  - RKE
- What Kubernetes version?
  - GitVersion:"v1.22.11"
  - 
**Screenshots**
![image](https://user-images.githubusercontent.com/11789693/191999340-ce06903f-552d-4b02-a6a7-3e7f2068bf93.png)
 
**Additional context**
NA

**Comment by vsukhin** [comment]
@Toxer10 is this UI issue?

**Comment by exu** [comment]
Looks like dashboard work only on root level paths, @Toxer10 can you confirm ?

**Comment by Toxer10** [comment]
Correct, @exu, I'll create a ticket to handle this use case. Hi, @stand-sure, thanks for reporting this bug. I'll notify you as soon as the bug is solved.
