### ISSUE TITLE
Measure aptly metrics

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#2369]
**Is your feature request related to a problem? Please describe.**
Right now we do not have any metrics regarding our aptly server: https://repo.testkube.io/

**Describe the solution you'd like**
We should enable them with https://www.aptly.info/doc/api/misc/ and visualize the numbers in our existing analytics dashboard // TODO: add link

**Additional context**
Would be great to see how many downloads are there, if there are any downtimes, etc.

**Comment by TheBrunoLopes** [comment]
working status:
- following up with kyle.
- changing repos
- count downloads script may be done by other teams

**Comment by vLia** [comment]
Metrics on apt server was not yet implemented. The process to migrate the new packages would have to include announcing apt users of the key change, will also investigate what the best way for this is.

**Comment by TheBrunoLopes** [comment]
closing this issue as stale.
