### ISSUE TITLE
Allow users to manage their Sources through the UI

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2377]
**Describe the enhancement you'd like to see**
We enabled users to abstract sources for their tests to a higher level to be able to reuse the same Tokens/Paths/Credentials across tests and become more DRY (#2186)

We would now like to add this functionality also the the UI.

1. We will have a separate page in the left navigation bar called `Sources` where the user can define a name for his source, his GitHub username, the reference to the secret token which is in the K8s store, and the repository he wants to be selected)

Ideally the user would be able to select from a list of repos which we can fetch for him with his credentials – if that's too complex to create we can use a text input for now :))

Please keep in mind – the user is not defining the branch and the path in here (he can do it in the CRD though) because research showed this belongs to the Test level 

https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=1438%3A51247

![image](https://user-images.githubusercontent.com/132332/192297858-ea1e7763-439c-4c9a-b87b-ac2f83f81de9.png)

2. We will have to adapt the test creation wizard and test settings to reference to the sources abstraction when users create / edit a git based test. The `Source` input gets extended with the list of sources from above :) 

Ideally we can prefill the Branches and Path options for the user since we can navigate through the repo for him  (but that might be a nice feature for an iteration later on)

https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=1371%3A48374

![image](https://user-images.githubusercontent.com/132332/192299206-91b3c5e6-bedf-4b87-8584-2d62c648e670.png)

**Comment by Toxer10** [comment]
Blocked by API, waiting for resolution of [this](https://github.com/kubeshop/testkube/issues/2481) ticket

**Comment by Toxer10** [comment]
Unblocked, continue working
