### ISSUE TITLE
Throttling homebrew-core PR submissions

### ISSUE THREAD

**Issue by chenrui333** [kubeshop/testkube#2383]
Hi 👋 , just to raise an issue here to notify some spam ban on the homebrew-core side, it would be nice that you folks can throttle the PR submissions. Thanks!

relates to 
- https://github.com/Homebrew/homebrew-core/pull/111524
- https://github.com/Homebrew/homebrew-core/pull/107721

**Comment by TheBrunoLopes** [comment]
Hello @chenrui333 thank you so much for making us aware of this.
I had no idea this was an issue. We'll fix ASAP.

**Comment by TheBrunoLopes** [comment]
AC: 
- Let's make it a weekly release. (do a cronjob that only posts to brew once a week)
- Allow to manually trigger this cron job if we need to make a manual deploy sonner, for cases where we need to release an urgent bugfix or for big releases.

**Comment by exu** [comment]
Additional requirement: publish new version only if it doesn't exist yet

**Comment by ypoplavs** [comment]
We can also create our own tap for often releases like we have for chocolatey. @TheBrunoLopes what do you say?

**Comment by vsukhin** [comment]
We have our own tap

**Comment by ypoplavs** [comment]
I created a separate flow for bumping formulae that is set to run once a week and can be run manually as well. It won't spam `homebrew-core` repo anymore.
