### ISSUE TITLE
Unable to run tests in parallel through testsuite

### ISSUE THREAD

**Issue by chandana194** [kubeshop/testkube#2387]
**Describe the bug**
Unable to run tests in parallel through testsuite open API even though the sync option is true

**To Reproduce**
Steps to reproduce the behaviour:

endpoint : /v1/test-suites/<testname>/executions
request body :
{
  "name": "testing 4 tests",
  "number": 1,
  "namespace": "testkube",
  "variables": {
    "var1": {
      "name": "var1",
      "type": "basic",
      "value": "value1"
    },
    "secret1": {
      "name": "secret1",
      "type": "secret",
      "value": "secretvalue1"
    }
  },
   "labels": {
"users": "3",
"prefix": "some-"
},
"executionLabels": {
"users": "3",
"prefix": "some-"
},
**"sync": true,** 
}

Could see that the tests are running sequentially

**Expected behavior**
if the sync is enabled, tests should run in parallel 

**Version / Cluster**
- Which testkube version? 
Client Version 1.5.20
Server Version v1.5.3
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
GKE

Please let me know if there is any other option to handle this scenario .
also, please let me know how can I use labels to run tests in parallel 

Tried through command line -f option as well. PFB screenshot for reference

<img width="748" alt="Screenshot 2022-09-27 at 2 06 30 PM" src="https://user-images.githubusercontent.com/113690498/192476566-6f41d53a-e5f8-4d75-a63c-26fc1a94e1de.png">

**Comment by vsukhin** [comment]
Hey, @chandana194 
We used Sync options for different purpose in both api calls for Tests and Test Suites
By default, api is called asychroniously and doesn't wait the end of test or test suite execution.
In this case, api call will return response only when the execution of test or testsuite is finished

But we have a feature request to support parallel test execution for test suite 
https://github.com/kubeshop/testkube/issues/2356
It's not yet planned, but we will start working on it shortly

Also, as you mentioned, we support parallel test execution for labeled tests. You will need to ceate all your tests with same label, for example,`--label parallel=test` and then all you need is just to execute `kubectl testkube run test --labe parallel=test`, you can set a level of concurrency (default it's 10)

**Comment by chandana194** [comment]
Thank you for the quick response. Will try running the tests with this option.

**Comment by vsukhin** [comment]
Okay, closing an issue. Feel free to reopen and follow #2356
