### ISSUE TITLE
Generate logs for all phases of Test Execution

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2396]
Before any test is executed we have something called "init container" that fetches the code and prepares the following container to be executed. However, if something fails during the init container phase. The user is not warned at all of what happened unless he goes into kubernetes to check the logs of the init container or in some other way.
To prevent that and to give better feedback to what's happening to the user. 
The first lines of the Test Logs should be follow this pattern:

- Initializing...
- Fetching test content from [source name] (in bold/colour)[source type] - branch name - etc...
- Copying data to the following dir
- Do an ls -laH of the files in that dir.
- Setting up environment variables...
- Print environment variables of type basic
- Setting up secret variables...
- Print the name of the variable of the type secret (only the key name, no values)
- In case the user specified a file to be uploaded at execution time, print the something like "doing --copy-file <filename>" as well.
- Test executing...
- Test Passed/Failed..
- Fetching Artifacts.. ☑️⤫

AC:
- Log stderr
- No logs won't happen for ANY test
<img width="949" alt="image" src="https://user-images.githubusercontent.com/13501228/194772431-1983f4dc-7099-4713-afd7-f2cebc93b43b.png">

ps: color code in different colours the logs not generated in the executor pod.

**Comment by TheBrunoLopes** [comment]
should solve: https://github.com/kubeshop/testkube/issues/2536

**Comment by fivenp** [comment]
here is what we do today: 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/132332/196151185-34b23e5d-cb66-45e2-822e-f70ef0000052.png">


here is an example of how a successful execution could look like: 

<img width="548" alt="image" src="https://user-images.githubusercontent.com/132332/196151125-6e6a521e-cf4e-403a-8522-d7c68459ee67.png">

and here are 2 examples of how an execution could fail: 

<img width="550" alt="image" src="https://user-images.githubusercontent.com/132332/196151288-b8c08e2b-2bf0-4678-bb92-afe52ad1add7.png">

<img width="546" alt="image" src="https://user-images.githubusercontent.com/132332/196151552-ead3bc11-0a97-4416-b29b-b22fd8857b48.png">

**Comment by TheBrunoLopes** [comment]
Also we could print the "work_dir"  in the logs at the start 🤔
cc: @vsukhin

**Comment by mtrin** [comment]
Is there any workaround on this one? Any tag we can build from for testing purposes?
thanks

**Comment by vLia** [comment]
Logs are visible in pod logs and on streaming.

They are not visible after an execution is finished. Will continue work on that in https://github.com/kubeshop/testkube/issues/3029
