### ISSUE TITLE
Gather all download events.

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2398]
- Make sure / verify if the package managers (brew,choco, apt) trigger github downloads.
- Build scrappers to fetch all the download metrics.

Scrape:
- [X] Homebrew Core stats (already scraped into PG database)
- [x] Chocolatey installs
      needs: "Measure downloads count for Internal Choco repository #2402"
      needs: "Measure downloads count for Official Choco repository #2403"
- [ ] APT installs 
      needs "Measure aptly metrics #2369"
- [X] Github downloads (curl, Homebrew Tap)
      already made in Databox 
- [x] Helm charts ? (is it possible to get install count?)
- [x] Docker images download counts

**Comment by olensmar** [comment]
We already scrape Helm Charts and Docker image downloads from DockerHub - the later are not very helpful since those images can be pulled from anywhere - not just Helm...

**Comment by TheBrunoLopes** [comment]
Closing this issue.
To be done as part of: https://github.com/kubeshop/testkube/issues/2369
