### ISSUE TITLE
Collect artifacts from executor 

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#240]
**Is your feature request related to a problem? Please describe.**
Kubtest should be able to collect artifacts passed from executors e.g. 
Cypress test recrds mp4 video from test. 

**Describe the solution you'd like**
Response should have links? to valid resources - api need to download and store them somewhere

**Additional context**
Solution should be generic to be able to store any artifact

**Comment by olensmar** [comment]
related to #247
