### ISSUE TITLE
K6 - git-dir shouldn't be default

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2400]
**Describe the bug**
K6 don't support running scripts from directory - setting `git-dir` shouldn't be possible. By default, when `--test-content-type` isn't set for K6 test the `git-dir` is used.

**To Reproduce**
1. Run:
```
tk create test --type k6/script --git-uri https://github.com/kubeshop/testkube.git --git-branch performance-tests --git-path "test/perf" --name perf-output-test-5
```
or
```
tk create test --type k6/script --git-uri https://github.com/kubeshop/testkube.git --git-branch performance-tests --git-path "test/perf" --name perf-output-test-5 --test-content-type git-dir
```
2. Run the test
3. Check result:
```
Status test execution failed:

⨯ k6 test script /data/repo/run not found
```

**Expected behavior**
- It shouldn't be possible to set `--test-content-type` to `git-dir` for K6 tests with CLI/Dashboard.
- `git-dir` shouldn't be the default option for K6

**Version / Cluster**
```
Client Version 1.5.32
Server Version v1.5.35
```

**Comment by cipribucur** [comment]
@tkonieczny  I encounter the same issue. My problem was caused by the path.. where I put just `/` because my initial test was in the root git repo. After I moved all my files into a single directory, it worked.

**Comment by tkonieczny** [comment]
I guess removing `/` at the beginning of path would also fix your problem

**Comment by cipribucur** [comment]
having the tests in the root of the the repo, I added that / and didn't work, I haven't try ignoring it altogether since blank it can't be, and . doesn't work  either. But I hope it helps you.

**Comment by tkonieczny** [comment]
Closing this issue after discussion with @vLia.
K6 don't support running scripts from directory, but there are real use-cases for K6 and `git-dir`. K6 only support running the single file, but support imports/modules/data-sources, etc. that may be needed during execution - it may be needed to checkout the whole directory. In this case the file that k6 should run should be specified with arguments.

Example: https://github.com/kubeshop/testkube/blob/main/test/k6/executor-tests/crd/other.yaml
