### ISSUE TITLE
Measure downloads count for Internal Choco repository

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2402]
Currently there is no Downloads count (`-1` value) in our Choco repository
```
      <d:DownloadCount m:type="Edm.Int32">-1</d:DownloadCount>
```

https://chocolatey.testkube.io/chocolatey/Packages

**Comment by olensmar** [comment]
I think we might need to get this from IIS log files on our repo server.. need to confirm

**Comment by olensmar** [comment]
confirmed - unless we can figure out if the DownloadCount can be configured in the choco server somehow

**Comment by TheBrunoLopes** [comment]
done
