### ISSUE TITLE
Measure downloads count for Official Choco repository

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2403]

**Comment by exu** [comment]
we can use goquery and scrape latest release downloads count from the site .

**Comment by olensmar** [comment]
afaik - we aren't using the official Choco repo because of the 3-4 week delays when publishing new releases - for our own repo I think we need to extract this from the IIS log files - since the downloadCount in the atom feed always seems to be -1

**Comment by TheBrunoLopes** [comment]
deprecated
