### ISSUE TITLE
Cypress executor images - "latest" tag pointing to random Cypress version

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2422]
**Describe the bug**
Multiple different cypress executor images with specific Cypress versions are available (Cypress 10, and legacy 9 and 8).
https://hub.docker.com/r/kubeshop/testkube-cypress-executor/tags?page=1&ordering=last_updated
Currently the `latest` tag points to the last built image - currently it's `1.1.9-cypress9`. So, the user using `latest` tag may get random Cypress version every time the images are updated.

**Expected behavior**
`latest` tag should always point to latest (non legacy) cypress version/executor version combination.

**Comment by TheBrunoLopes** [comment]
AC:
- We should pin fixed versions on the tags

**Comment by vsukhin** [comment]
Needs to be checked by @tkonieczny
