### ISSUE TITLE
Refactor test-crds usability 

### ISSUE THREAD

**Issue by abhipsnl** [kubeshop/testkube#2449]
**Describe the enhancement you'd like to see**
At present, any feature which is going to API or CLI is not directly available with `test-crds` command.

For example, we recently added `--copy-files` option with `testkube create test`, customers who are using argocd, are currently heavily dependent on `testkube generate tests-crds` and every time we need to raise separate issue requests to add those features.

Can we refactor this, it will be of big use for those using ArgoCD plugin which uses `tests-crds`

**Comment by TheBrunoLopes** [comment]
Hello @sharmajee1 
Good point, will investigate how to improve this for the next release and come back to you.

**Comment by TheBrunoLopes** [comment]
Action points:
- Have feature parity with testkube create test --generate-crd-only
- Explicitly document features that are not available on generate tests.
- ArgoCD workflow should be tested


it's more difficult to add the --copy-files to the CRD since the files are being stored in minio.
K8s doesn't allow to store big files inside the them. @sharmajee1 can you tell us more about your use case ?
Please feel free to book a call with us if that's easier, https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by sharmajee1** [comment]
Scheduled an meeting, will discuss on the meeting

**Comment by abhipsnl** [comment]
So the use case is, our tests need SSL files to be present in the test pod during execution, and unfortunately, those SSL contents are only supported via file and not variables.

When we use test cards we don't have any options to copy files into the containers. 

So the only solution I can imagine as of now is, read from secret and mount in pod.

        - name: secret-volume
          mountPath: /certs/
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret

Something like this 
--cooy-from-secret <secret-name> <mount_path>

**Comment by vsukhin** [comment]
Hey, @abhipsnl 

Yes, we proipose this generalsolution for such cases https://github.com/kubeshop/testkube/issues/2867
For example, you will be able to run a script with such a command `echo '$SSL_CERT' > $SSL_DIR` for any test

**Comment by abhipsnl** [comment]
> Hey, @abhipsnl
> 
> Yes, we proipose this generalsolution for such cases #2867 For example, you will be able to run a script with such a command `echo '$SSL_CERT' > $SSL_DIR` for any test

Yes, this can solve this.

**Comment by TheBrunoLopes** [comment]
Hey @abhipsnl we built a pre-run feature that should help you solve the certificate issue.
https://kubeshop.github.io/testkube/using-testkube/tests/tests-creating#executing-pre-run-script

Did you take a look at it and did it work for you ?

**Comment by TheBrunoLopes** [comment]
Hey @abhipsnl , small question for you.
The testkube create test command has a flag named --crd-only. Would this be valuable to use in ArgoCD instead of testkube generate tests-crds ?

**Comment by abhipsnl** [comment]
Hi, @TheBrunoLopes Sorry for the late response, let me test the pre-run feature. I don’t remember but seems like we already tried this ArgoCD plugin and didn’t work, I will cross-check this again.

**Comment by vsukhin** [comment]
Duplicated #3125
