### ISSUE TITLE
Add common interface for storing artifacts from tests

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#247]
**Describe the enhancement you'd like to see**
Some testing tools offer test result artifacts like e.g. videos or screenshots of test. 
As an engineer running test i would like to be able to download those artifacts. 

**Additional context**
Add some simple storage for files - for the beginning we could go with s3. 
store artifacts add artifacts to KubtestExecutionResult struct

**Comment by olensmar** [comment]
default should be something that requires no (or very little) configuration from the user !?

**Comment by olensmar** [comment]
it should also be possible to retrieve results via API/kubectl so we can display them in dashboard/etc

**Comment by jasmingacic** [comment]
This has been completed
