### ISSUE TITLE
Test `--negative-test` option for testing negative cases

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2482]
**Is your feature request related to a problem? Please describe.**
Testkube is already used for testing itself. One of the options to increase self-testing ability is to allow setting failure as an expected Test result. This feature probably won't be often used by users (they can just use standard negative asserts), but would make it way simpler to test negative cases.

**Describe the solution you'd like**
Possibly to set failure as expected Test result - for example `--negative-test` with CLI, or `negativeTest: true` (Test CRD). So, for this option enabled, if the runner returns `0` exit code, the test will be marked as failed, and in case of non-zero exit codes the test will be marked as passed.

**Comment by fivenp** [comment]
On the UI this will only require a simple checkbox in the general test settings: 

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/132332/213187738-df584f5a-48ac-47e1-a709-a7cb693fe27e.png">

Figma: 
https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=2162%3A79505&t=sSFkGeeVjDDBo5NK-4

**Comment by fivenp** [comment]
is this added to the frontend? :)

**Comment by tkonieczny** [comment]
@nicufk I just noticed this one:  `Test run was expected to fail, but it passed.`. Could you change it to something like: `Test run was expected to fail - the result will be reversed.`?

```
❌ Execution failed: process error: exit status 1
✅ Got Newman result successfully
✅ Mapped Newman result successfully
process error: exit status 1

Test run was expected to fail, but it passed.
```

**Comment by nicufk** [comment]
@tkonieczny, I updated the message, @pavloburchak I reopened it so it can be implemented on UI as well

**Comment by nicufk** [comment]
@pavloburchak negativeTest in the executionRequest https://kubeshop.github.io/testkube/openapi#tag/tests/operation/createTest

**Comment by TheBrunoLopes** [comment]
is this merged already ?

**Comment by fivenp** [comment]
yes :)
