### ISSUE TITLE
Change Testkube Log Storage

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2497]
- Currently the logs produced by the tests are stored in the MongoDB. However that's not very scalable and the log files can become quite huge.
- Lets save them in Minio (S3) instead and treat them as artifacts as well.

AC:
- All existing functionality should stay the same.
- In the artifacts tab, the logs for that execution will start appearing.
- Minio must work as reliably as mongoDB out of the box when Testkube is installed.
- If there's an issue with storing the logs, the UI and CLI must show an appropriate message.
- When it's using mongo, the logs should be stored in a different collection than the test execution

**Comment by vsukhin** [comment]
@TheBrunoLopes From user conversations I saw that many of them don't install minio. Shoukd we make an option where to store logs?

**Comment by exu** [comment]
Good point @vsukhin maybe let's allow to choose? But which one should be the default value?

**Comment by vsukhin** [comment]
If minio is installed,then we use minio, if it's not,then we fall back to Mongo

**Comment by exu** [comment]
We could store them as files in volume also as fallback?

**Comment by TheLeanMachine** [comment]
Hi all,

is this problem related?

When I scroll to the top-most position, _I don't see the the actual beginning of the log output..._
![Screenshot 2022-11-09 at 12 42 29](https://user-images.githubusercontent.com/3470837/200822228-52e44ce2-d297-4122-8048-a60e2ca06499.png)


(just saying "no" is a valid answer!)

**Comment by TheBrunoLopes** [comment]
AC2:
- Default is to store in minio if present. if not present falls back to mongo db
- There's an ENV var in the helm chart, that is True by default, but can be changed by the user so that the logs are stored only in MongoDB.

**Comment by TheBrunoLopes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2497?planning-poker) with Zenhub @nicufk @pavloburchak @vLia @vsukhin
