### ISSUE TITLE
Store files in storage instead of forwarding the contents as string

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#2501]
**Describe the enhancement you'd like to see**
In https://github.com/kubeshop/testkube/issues/2408 it came up that files are expected to have a higher size than what the current string-based `--copy-files` implementation supports.

As discussed in the team, we would change the implementation to store these files in minio, and get them on test execution. To make it consistent with other behaviours in Testkube, this would mean that only specifying files on execution would override them, otherwise the test would take the file from storage.

**Comment by chandana194** [comment]
Could you please let me know if any update on this ?

**Comment by vLia** [comment]
Hello @chandana194,
the implementation is in progress, but not released yet. Will let you know when it is ready to use.

**Comment by chandana194** [comment]
@vLia  Any update on this request ?

**Comment by vLia** [comment]
Hello @chandana194 & @f-helm, `--copy-files` for big files was released for test creation with Testkube v1.6.38. Please check and let me know if it works for your use cases. The files will be copied into `/data/uploads/`, for an example check these docs: https://kubeshop.github.io/testkube/using-testkube/tests/tests-creating#mapping-local-files
Thanks in advance!
