### ISSUE TITLE
running mvn test is failing for me, with this error: unable to access 'https://github.com/kubeshop/testkube-executor-maven.git/': Could not resolve host: github.com 

### ISSUE THREAD

**Issue by elikhodadadi** [kubeshop/testkube#2508]
**Describe the bug**
running the maven test is failing for me, it cannot connect to github.

**To Reproduce**
testkube create test --git-uri https://github.com/kubeshop/testkube-executor-maven.git --git-path examples/hello-maven-settings --type maven/test --name maven-example-test --git-branch main

testkube run test maven-example-test --copy-files "testkube-executor-maven/examples/hello-maven-settings/se
ttings.xml:/tmp/settings.xml" --args "--settings" --args "/tmp/settings.xml" -v "TESTKUBE_MAVEN=true"

expected successful test but it returns this error: 
⨯ process error: exit status 128
output: Cloning into 'repo'...
fatal: unable to access 'https://github.com/kubeshop/testkube-executor-maven.git/': Could not resolve host: github.com
![image](https://user-images.githubusercontent.com/21960072/195122655-9b5ff1c0-c3ad-43e5-a5c9-e5d82cfe7c3a.png)
 

so could you please tell me what is the issue for connecting to the github, if I try git clone https://github.com/kubeshop/testkube-executor-maven.git, is fine but it fails with testkube command. 
could you please help. 
thanks !

**Comment by exu** [comment]
Hi @elikhodadadi can you please pass additional info?


**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Comment by vsukhin** [comment]
We saw such issues in Minikube from time to time

**Comment by elikhodadadi** [comment]
> Hi @elikhodadadi can you please pass additional info?
> 
> **Version / Cluster**
> 
> * Which testkube version?
> * What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
> * What Kubernetes version?

using minikube cluster. 
Lubernetes version: v4.5.7
testKube version: Client Version 1.5.43
Server Version v1.5.45

**Comment by elikhodadadi** [comment]
> We saw such issues in Minikube from time to time

ok; and how it can be fixed?

**Comment by elikhodadadi** [comment]
upgraded all these, but still same issue

**Comment by vsukhin** [comment]
Sometimes it helps if you restart your computer, sometimes if you recreate kubernetes cluster, but at end, you might just switch to Kind,which doesn't have this issue

**Comment by elikhodadadi** [comment]
Sorry, i didn't get this "switch to Kind" what is this? can you describe better?Thanks!

**Comment by vsukhin** [comment]
It's other solution for local k8s cluster  https://kind.sigs.k8s.io/

**Comment by elikhodadadi** [comment]
Could you please someone add his config file which is located in .testkube folder?

**Comment by vsukhin** [comment]
{"apiURI":"","oauth2Data":{"enabled":false,"token":{"access_token":"","token_type":"bearer","expiry":"0001-01-01T00:00:00Z"},"clientID":"","clientSecret":"","providerType":"github","scopes":null}}
