### ISSUE TITLE
Artifacts download: `error trying to reach service: EOF`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2511]
**Describe the bug**
It's not possible to download test artifacts both with Dashboard and CLI

**To Reproduce**
1. Run test which will generate artifacts (cypress, soapui, etc.)
2. Try to download artifacts from Dashboard or with CLI
3. It's not possible to download the files
CLI fail with:
```
testkube download artifacts 633f3f7e35b4cdca189c9b63 --download-dir ~
Getting artifacts count = 3 

downloading file:  (error: error trying to reach service: EOF)
```
Dashboard:
![Screenshot_20221006_230449](https://user-images.githubusercontent.com/1473096/195294074-c0cfeebc-4b3d-4955-9715-477f55ec1e7b.png)

**Expected behavior**
It should be possible to download artifacts correctly

**Version / Cluster**
Client Version 1.6.9
Server Version v1.6.9

**Screenshots**

 
**Additional context**

**Comment by vsukhin** [comment]
SetStreamBody will close reader itself
