### ISSUE TITLE
Log Output WebSocket not immediate connection

### ISSUE THREAD

**Issue by Toxer10** [kubeshop/testkube#2523]
0. Open [this](https://deploy-preview-457--project4-dashboard.netlify.app/tests/executions/sanity) and demo.testkube.io/tests/sanity
1. Start a test using UI on demo cluster and go to the netlify tab
2. Press immediately on a newly added test execution in the list
3. Observe that there are no logs until the end of the execution. 

I noticed that if you don't press immediately on a newly added test execution but wait for the pod of the execution to be configured  (usually 5-7 second) there will be logs. Maybe this point can help.

**Comment by rangoo94** [comment]
I recall that this problem was fixed, so I'll close it, but now there are similar problems happening in https://github.com/kubeshop/testkube/issues/3801 anyway.
