### ISSUE TITLE
Have a `working_dir` parameter for tests

### ISSUE THREAD

**Issue by jdborneman-terminus** [kubeshop/testkube#2526]
**Describe the enhancement you'd like to see**
A handy thing for us would be to have a `working directory` type parameter for tests. This would be independent of the `path` parameter for `git-dir` tests in TestKube. The `working_dir` parameter would be the directory within the repo where tests should be executed from.
 
**Additional context**
Specifically in our context, we have a monorepo with all of our products AND our tests in the `apps/` folder. For example `/apps/app1-e2e` for `app1`'s e2e Cypress tests. But the node_modules dir lives in the `/` root of the repo, not in the working directory. So the whole monorepo needs pulled down, but the tests need executed from within the `working_dir`

**Comment by jdborneman-terminus** [comment]
More context down in this thread on Discord:
https://discord.com/channels/884464549347074049/885185660808474664/1030142758096228392

**Comment by exu** [comment]
Default value should be set to path: 
- if set just use path 
- if not set just use root path 
- if set use given value

**Comment by vsukhin** [comment]
https://github.com/cypress-io/cypress-test-nested-projects#cypress-test-nested-projects
