### ISSUE TITLE
Make test parametrization uniform

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2540]
## Context
We realised that for each Executor the Variables, Environment variables and Arguments are behaving differently.
So we need uniformization and to define a standard on what's the expected behaviour for all executors.
## Current Terminology
The terminology we are using today.
### Variables
There's Type basic and or secret and are used to pass variables to be used by the executor during the execution.
Are used in both container and non container executors. In container executors they will be "defined" in the pod as environment variables as well. 

### Arguments
They are arguments or flags used in the executor binary after the command for e.g., for the curl executor the arguments could be
--args "-C -I -some-flag -foo=bar ..."

### Envs
Environment variables that are defined in the pod during test execution. Work the same both on container and non-container executors.

## Proposed Specification
- Variables and Environment variables will be the same thing.
   - All variables will by in the pod as Envs.
   - Non-container executors are still able to use it internally for other purposes.
- Remove any end user behaviour that differs from container executors or non-container executors.
- Deprecrate Envs field. (envs should still work if present, but docs and example won't show envs)
- CLI shows deprecated message when using --env

## Desired Terminology
We don't use parameters as a synonym of arguments. We say "you can parametrize your tests using Variables or Arguments"
### Variables
Will be used as Environment variables and accessible by your Tests during Test Executions.
### Arguments
Extra arguments used by the executors command binary.

**Comment by exu** [comment]
@TheBrunoLopes I'm against merging vars and envs, as some testing frameworks distinguish them (Postman distinguish even more like here: 

<img width="199" alt="image" src="https://user-images.githubusercontent.com/30776/196937604-1e35e17e-d20e-49a7-853f-fa252913c115.png">
 

Additionally it creates some addition question:
- what should be the logic behind vars and envs merging?
- what is preferred one to be merged with another one?
- what naming for should they have (capitalized snake case?) 
- what in case of conflicting names?

**Comment by TheBrunoLopes** [comment]
> what is preferred one to be merged with another one?

I have the impression that you might not have understood the feature.
We will not merge the Envs and Variables that users inputs. There will be only one which we call variables. Envs will be deprecated. There will not be conflicting names or anything else. 

> what naming for should they have (capitalized snake case?)

We don't change any key names that user provides.

> what in case of conflicting names?

Any key value that the user defines as variables will be mounted as envs in the pods. there are no conflicts here.
makes sense ? @exu

**Comment by vsukhin** [comment]
So, this ticket is about deprecating env and probably sectet-env in favor of variables and secret variables
We need remove them from mark them as depricated in cli, api, crd
Make sure,that variables and secret variables provide same functionality both on api and executor levels

**Comment by tkonieczny** [comment]
One more case: https://github.com/kubeshop/testkube/issues/3097
