### ISSUE TITLE
Add PostHog analytics to Testkube Dashboard

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2550]
**Describe the enhancement you'd like to see**
We'd like to add [PostHog product analytics](https://posthog.com/docs/integrate/client/js) to our Dashboard. It will allow us to understand the dashboard usage better and enables us to retrospectively create events and evaluate journeys. 

PostHog does come with a second feature out of the box which we will use later on most likely – it allows us to manage FeatureFlags and trigger decisions based on them on the Frontend easily.

**We will need to make sure** 

* PostHog is only initialised if the user accepts the cookies
* PostHog is disabled if the user disables telemetry
* We do not want to enable PostHog on local development environments (and potentially on our own demo env?)
* We do not have a specific user so we can not call the `posthog.identify('USER')` command

Here is are some guides on how to implement it:

* [Default JS docs](https://posthog.com/docs/integrate/client/js)
* [React Example](https://posthog.com/tutorials/spa) (especially crucial is the tracking via router)
* [React Native](https://posthog.com/docs/integrate/client/react-native) (give us a good sample of the logic - the lib might have some different menthods though)
* [React Cookie Banner](https://posthog.com/tutorials/react-cookie-banner)
* [Tutorials](https://posthog.com/tutorials)

**Comment by fivenp** [comment]
The required API key is: 

`phc_DjQgd6iqP8qrhQN6fjkuGeTIk004coiDRmIdbZLRooo`

**Comment by Toxer10** [comment]
> The required API key is:
> 
> `phc_DjQgd6iqP8qrhQN6fjkuGeTIk004coiDRmIdbZLRooo`

Thanks!
