### ISSUE TITLE
Allow PersistentVolumeClaim (PVC) for storage backend

### ISSUE THREAD

**Issue by jcogilvie** [kubeshop/testkube#2622]
**Describe the enhancement you'd like to see**
Right now the storage backend is s3.  Can we use persistent volumes (claims) instead, as a k8s native solution for storage?

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2622?planning-poker) with Zenhub @nicufk @vLia

**Comment by TheBrunoLopes** [comment]
Hey, @jcogilvie sorry we didn't reply to this issue.
Only saw it now and realised it was opened a long time ago.
Do you still have a need to use PVCs to store artifacts directly?
I'm closing this issue since it doesn't appear to be a blocker. let us know and we can re-open the issue otherwise.
