### ISSUE TITLE
Improve CRD Codeblocks style + behaviour

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2626]
**Describe the enhancement you'd like to see**
Our Codeblocks currently look rather plain

<img width="693" alt="image" src="https://user-images.githubusercontent.com/132332/198135795-8c911ae6-ebe7-4228-88ee-9de592c4cda0.png">

We'd like to add some yaml color themeing to them:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/132332/198136206-8e6c0d33-9598-4834-b72b-d1c5681f9326.png">

**Additional context**
You can also look at the color styles we're currently using in our docs to match them: 
e.g.: https://kubeshop.github.io/testkube/using-testkube/metrics#installation

**Comment by pavloburchak** [comment]
Was added monospace font on this types of inputs. Colorising will be done later, took much more time than expected
