### ISSUE TITLE
Improve string based test content

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2627]
**Describe the bug**
Right now we're using a textarea to display string based test content: 

<img width="447" alt="image" src="https://user-images.githubusercontent.com/132332/198137024-2ba04993-5b50-4ab9-bd3b-04011f1b7f0b.png">

**Expected behavior**
1. We should use a code block style textarea (monospace font + spacing as in our code blocks)
2. Ideally we could auto-detect the syntax highlighting based on test type / content the user pastes
3. We should at least enable JS syntax highlighting for Cypress + K6 + Postman tests, XML for SoapUI, YAML for KubePug and Artillery, JSON for cURL, Go for Ginkgo and Java for Gradle + Maven

<img width="504" alt="image" src="https://user-images.githubusercontent.com/132332/198137469-c2b3a400-c102-4b8b-b09a-a1637867e496.png">

 
**Additional context**
You can also check the color scheme we're using in our docs for similar syntax highlighting

**Comment by pavloburchak** [comment]
Was added monospace font on this types of inputs. Colorising will be done later, took much more time than expected
