### ISSUE TITLE
Allow passing in multiple files or a directory of files when creating a test

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#2634]
**Describe the enhancement you'd like to see**

- I want to be able to pass in multiple files when using `test create` via `--file` or
- I want to be able to pass in a directory with files when using` test create`

When building an executor with a tool that uses multiple files, e.g. an xml file for the test template and a csv file that is injected into the xml with actual values then it is currently not possible to do so. Using `--copy-files` does not cut it because it is limited in size, and also works a different way than `--file`.

**Comment by TheBrunoLopes** [comment]
This makes sense.
@vLia is this not the current behaviour ? how much does the current implementation differ from this ?

**Comment by TheBrunoLopes** [comment]
Hey @f-helm we are about to release a version that removes the limitation around --copy-files.
Where they will be stored in Minio. Will this solve the issue ?
https://github.com/kubeshop/testkube/issues/2501
https://github.com/kubeshop/testkube/pull/2687

**Comment by f-helm** [comment]
I think this is comparable. I already circumvented it by reading my needed files from a git-repo, but for a solution using local files, this looks like it would be sufficient.

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2634?planning-poker) with Zenhub @nicufk @vLia

**Comment by TheBrunoLopes** [comment]
Hello @f-helm, is this issue solved for you ? 
Closing this issue for now. we'll reopen it again if there's an issue pending.
