### ISSUE TITLE
Need information on container executors

### ISSUE THREAD

**Issue by chandana194** [kubeshop/testkube#2637]
Hi 

I have a container image which takes care of some test executions. I would like to create it as a executor on testkube.

have gone through the below documentation but it is not having any commands which I can follow : Like command to create a executor with the help of yaml and how to run the test which points to this container !
https://kubeshop.github.io/testkube/test-types/container-executor

Could you please help me with the commands and steps that I need to follow ?

**Comment by vsukhin** [comment]
hey @chandana194 
As per docs, please:
1. Create an executor using `kubectl testkube create executor` command
2. Create a test using `kubectl testkube create test` command
3. Run above test using `kubectl testkube run test`

**Comment by chandana194** [comment]
Thank you for your response @vsukhin 
Was able to create a container executor and when I try to run the test I am getting only the below logs.
Do I need to take care any output options ?

 kubectl testkube get execution 63623e38e3e7bd7d82437241
ID:         63623e38e3e7bd7d82437241
Name        ui-testlng-command-1
Number:            1
Test name:         ui-testlng-command
Type:              k6-ui-seven/test
Status:            failed
Start time:        2022-11-02 09:54:00.112 +0000 UTC
End time:          2022-11-02 09:54:10.863 +0000 UTC
Duration:          00:00:10

Status test execution failed:

⨯ 
{"type":"event","content":"running test [63623e38e3e7bd7d82437241]"}
{"type":"line","content":"created content path: /data/test-content"}
{"type":"result","result":{"status":"running"}}

**Comment by chandana194** [comment]
Able get some error messages on cluster :

**failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "docker run --rm -v /data:/data -i dockerk6 run /data/test-content": stat docker run --rm -v /data:/data -i dockerk6 run /data/test-content: no such file or directory: unknown**

I am trying the mount the data directory. so that it can read the test scripts available under testkube /data/test-content

**Comment by vsukhin** [comment]
Hey @chandana194 /data volume is automatically mounted for testkube container executor. test-content file is created by init container, when pod is created, if test source is string data or uri

**Comment by chandana194** [comment]
Hi @vsukhin  
Yes I am aware of it. But When I issue a command for my container executor to run the test, it is unable to read /data/test-content
Example : **xk6 run /data/test-content** 
However, It displays a message saying content path created 

{"type":"event","content":"running test [6368bd39e3e7bd7d824372a2]"}
{"type":"line","content":"created content path: /data/test-content"}
{"type":"result","result":{"status":"running"}}

but on the POD logs it says no such file or directory !!

**Comment by vsukhin** [comment]
If it claims, that file was created, then it should be created. You can try to run some test image and just list /data directory content, I'm sure, it should be there. Can you provide your Dockerfile to look at?

**Comment by chandana194** [comment]
I tried "cd /data" command. It throws no such file or directory error. But when I list the directories- It shows data directory in the list
<img width="544" alt="Screenshot 2022-11-07 at 4 55 39 PM" src="https://user-images.githubusercontent.com/113690498/200298959-3de5fe46-d39a-4abc-ac8d-bd8d39b106b9.png">


attached Docker file for your reference : 
[Dockerfile.zip](https://github.com/kubeshop/testkube/files/9950942/Dockerfile.zip)

**Comment by chandana194** [comment]
As an alternative approach, I also tried downloading https://github.com/kubeshop/testkube-executor-k6 and updated the Dockerfile with additional installation steps and tried building the same. but this is also throwing the below error : 
<img width="779" alt="Screenshot 2022-11-07 at 5 34 08 PM" src="https://user-images.githubusercontent.com/113690498/200305929-aedbfcf5-a56b-4292-b6e6-1c24f60373b9.png">

Steps followed : 
Step1 : git clone https://github.com/chandana194/testkube-executor-k6.git
Step2 : Modified the Dockerfile. Modified Docker file : [Dockerfile.zip](https://github.com/kubeshop/testkube/files/9951251/Dockerfile.zip)
Step 2 : cd testkube-executor-k6/build/agent
Step 3: docker image build --tag chandana194/xk6-browser-executor:1.0 .
and then observed the above error

**Comment by vsukhin** [comment]
From above description,it looks like permission issue, because directory is listed, but you can't access it. Let's ask @povilasv who played with it. Might be, he has a qucik answer, if not, we will deeg deeper

**Comment by chandana194** [comment]
Thank you @vsukhin 
@povilasv  Could you please help us on this?

**Comment by chandana194** [comment]
@povilasv 
Tried executing ls /data/
Below is the error :

Error: failed to start container "636a1adfe3e7bd7d824372a5": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "ls /data/": stat ls /data/: no such file or directory: unknown

<img width="1048" alt="Screenshot 2022-11-08 at 2 31 50 PM" src="https://user-images.githubusercontent.com/113690498/200521386-72295bdc-d7af-4004-bfd8-ea61b3f60781.png">

**Comment by vsukhin** [comment]
Sounds like, we will need to investigate it a bit deeper. For some reason volume is not mounted for executor contaier

**Comment by chandana194** [comment]
> As an alternative approach, I also tried downloading https://github.com/kubeshop/testkube-executor-k6 and updated the Dockerfile with additional installation steps and tried building the same. but this is also throwing the below error : <img alt="Screenshot 2022-11-07 at 5 34 08 PM" width="779" src="https://user-images.githubusercontent.com/113690498/200305929-aedbfcf5-a56b-4292-b6e6-1c24f60373b9.png">
> 
> Steps followed : Step1 : git clone https://github.com/chandana194/testkube-executor-k6.git Step2 : Modified the Dockerfile. Modified Docker file : [Dockerfile.zip](https://github.com/kubeshop/testkube/files/9951251/Dockerfile.zip) Step 2 : cd testkube-executor-k6/build/agent Step 3: docker image build --tag chandana194/xk6-browser-executor:1.0 . and then observed the above error

@vsukhin 
Meanwhile, Can I get help on this ?

**Comment by vsukhin** [comment]
Created an executor

apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: cli-executor
  namespace: testkube
spec:
  types:
  - cli/test
  executor_type: container
  image: soleware/nx-cli:8.5.2
  command:
  - /bin/bash
  - -c
  - pwd; echo 'Navigate to content dir in /data'; cd /data; echo 'Checking...'; echo 'Who am I? - '; whoami; ls -lah /data; cat /data/test-content; echo 'Content dir - '; echo $RUNNER_DATADIR;  ls -lah $RUNNER_DIR; cat $RUNNER_DATADIR/test-content;


Created test

kubectl testkube create test --file test/postman/LocalHealth.postman_collection.json --name cli-test --type cli/test

Executed test

ID:         636a9324219490b7f7721ed3
Name        cli-test-3
Number:            3
Test name:         cli-test
Type:              cli/test
Status:            passed
Start time:        2022-11-08 17:34:28.902 +0000 UTC
End time:          2022-11-08 17:34:37.153 +0000 UTC
Duration:          00:00:08

{"type":"event","content":"running test [636a9324219490b7f7721ed3]"}
{"type":"line","content":"created content path: /data/test-content"}
{"type":"result","result":{"status":"running"}}
			"response": []
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "URI",
			"value": "http://localhost:8080"
		}
	]
}Content dir - 
/data
total 12K
drwxrwxrwx 2 root root 4.0K Nov  8 17:34 .
drwxr-xr-x 1 root root 4.0K Nov  8 17:34 ..
-rwxrwxrwx 1 root root  996 Nov  8 17:34 test-content
{
	"info": {
		"_postman_id": "3d9a6be2-bd3e-4cf7-89ca-354103aab4a7",
		"name": "Health",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Health",
			"event": [
				{
					"listen": "test",
					"script": {
						"exec": [
							"pm.test(\"Status code is 200\", function () {",
							"    pm.response.to.have.status(200);",
							"});"
						],
						"type": "text/javascript"
					}
				}
			],
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "{{URI}}/health",
					"host": [
						"{{URI}}"
					],
					"path": [
						"health"
					]
				}
			},
			"response": []
		}
	],
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "URI",
			"value": "http://localhost:8080"
		}
	]
}
Test execution completed with success in 8.251s 🥇

**Comment by chandana194** [comment]
@vsukhin Now it looks like I have issues with running the docker command. 
Locally I use below command to execute tests using the container image which I created:
docker run --rm -v <local/directory/containing/js/script>:<some/container/directory> -i docker-image-name run /some/container/directory/k6browsertesting.js

While creating the executor I am using the below command:
kubectl-testkube create executor --executor-type container --image chandana194/xk6:latest --image-pull-secrets myregistrykey1 --types k6-browser/test --name k6-browser-executor --command "docker run --rm -i -v /data:/data chandana194/xk6:latest run /data/test-content"

Do you see any issues here?

**Comment by vsukhin** [comment]
Why are you running docker inside docker? The command should be like 'xk6 run /data/test-content'

**Comment by chandana194** [comment]
> Why are you running docker inside docker? The command should be like 'xk6 run /data/test-content'

Tried that option but I got the same error:
Error: failed to start container "636b7600e3e7bd7d824372c3": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "xk6 run /data/test-content": stat xk6 run /data/test-content: no such file or directory: unknown

**Comment by vsukhin** [comment]
Okay, try to run above example to see, if it works for at your side. You can try both with your test and example one

**Comment by chandana194** [comment]
> Okay, try to run above example to see, if it works for at your side. You can try both with your test and example one. We need to check, if this problem related to your particular test or container executor image you use

Hi @vsukhin I tried the example which you have shared But I ran into below error:
 
**Error: failed to start container "636e04d9e3e7bd7d824372ce": Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/runner": stat /bin/runner: no such file or directory: unknown**

Executor YAMl file which I used:
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: cli-executor
  namespace: testkube
spec:
  executor_type: job
  # not best practice but for now we use latest
  image: soleware/nx-cli:8.5.2
  # image:: lreimer/testkube-k6-executor:latest
  command:
  - /bin/bash 
  - c 
  - pwd; echo 'Navigate to content dir in /data'; cd /data; echo 'Checking...'; echo 'Who am I? - '; whoami; ls -lah /data; cat /data/test-content; echo 'Content dir - '; echo $RUNNER_DATADIR; ls -lah $RUNNER_DIR; cat $RUNNER_DATADIR/test-content;
  types:
  - cli/test

**Comment by chandana194** [comment]
Thank you for the update... Let me try once after installing rosetta on my mac

**Comment by chandana194** [comment]
hi @vsukhin I tried building the image after installing rosetta software on my mac. But still I am facing the same issue !

**Comment by vsukhin** [comment]
I see, then let's wait till we add ARM support for all executor images

**Comment by vLia** [comment]
Hello @chandana194, a k6 executor docker image with the tag 0.0.18 has been released for the arm64 architecture. Could you please update and check if you get the same error? You can double-check the image version with `kubectl get executor k6-executor -o yaml -n testkube`

**Comment by vsukhin** [comment]
hey, @chandana194 Have you tried the latest release?

**Comment by vsukhin** [comment]
please let us know,if you still have this issue
