### ISSUE TITLE
Consolidate all error messages and scenarios a user might face

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2642]
**Why should it be implemented?**
We would like to optimise our current error messaging to the users across all interfaces he might interact with (CLI, API, Dashboard, etc)

**Describe the improvement**
We need to consolidate a list of all the error / warning messages and scenarios which we might return from the API to have a good overview to improve them going foward.

**Comment by TheBrunoLopes** [comment]
Closing this one duplicated: https://github.com/kubeshop/testkube/issues/3065
