### ISSUE TITLE
Add persistent, unique IDs to each DOM level element

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2649]
**Describe the enhancement you'd like to see**
To be able to do better debugging and improve usage analytics we need to have every element on the DOM have a unique ID (can be `id=xxx` or `data-id=xxx` or any other `data-` attribute for example) , which is persistent (stays the same across deployments, versions, etc). 

**Additional context**
Instead of adding manually ID's across each an all elements we could and should automate this. 
There is/was a plugin for babel which could do this for us: https://github.com/fullstorydev/fullstory-babel-plugin-annotate-react

I'm pretty sure there are other automated solutions for it to be fair :)

**Comment by TheBrunoLopes** [comment]
won't do
