### ISSUE TITLE
No secrets created with create testsource and create test 

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#2656]
**Describe the bug**
Secrets are not created with `testkube create test` and `create testsource` when using `--git-username-secret` and `--git-token-secret`. I provide only example for `create testsource` case, same behaviour with `create test`.

**To Reproduce**
1. Run `kubectl testkube create testsource -n repo --git-uri <some repo> --git-branch <some branch> --git-username-secret repo-username=<username> --git-token-secret repo-token=<token>`
2. Run `kubectl testkube get testsource repo`
3. Observe that username and token secret are present
6. Create some test with `-source repo` param
7. Run the test

**Expected behavior**
Repo can be pulled with defined secrets
When running `kubectl get secrets -n testkube`, the secrets are present

**Actual behavior**
init container throws  Error: secret "repo-username" not found
When running `kubectl get secrets -n testkube`, the secrets are not present

**Version / Cluster**
- Which testkube version? Client Version 1.6.28, Server Version v1.6.28
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) Rancher Desktop k3s
- What Kubernetes version? v1.24.4

**Comment by f-helm** [comment]
Not sure if this is related, but instead using `--git-username` and `--git-token` does create a secret when I believe it should not.

**Comment by vsukhin** [comment]
Hey @f-helm 
Current behaivour is as follows:
1. When you use git-token-secret and git-username-secret we just read these values from existing secrets. It was done to support GitOps flow, when you need to use your own kubernetes secrets
2. When you want to allow us to manage secrets fot you, then you need to use git-token and git-username options. We will create a secret for such a test and store these values there
