### ISSUE TITLE
Error when creating trigger

### ISSUE THREAD

**Issue by esebrei** [kubeshop/testkube#2663]
**Describe the bug**

Following error arises while trying to create a trigger with `kubectl apply -f`:

```
$ kubectl apply -f trigger.yml 
Error from server (InternalError): error when creating "trigger.yml": Internal error occurred: failed calling webhook "vtesttrigger.kb.io": failed to call webhook: Post "https://testkube-operator-webhook-service.testkube.svc:443/validate-tests-testkube-io-v1-testtrigger?timeout=10s": x509: certificate signed by unknown authority
```

**To Reproduce**
1. create trigger file `trigger.yml` (using example from doc: https://kubeshop.github.io/testkube/using-testkube/triggers#api)
2. Run `kubectl apply -f trigger.yml`
3. See error

**Expected behavior**
Trigger should be created and following message should be displayed:

`testtrigger.tests.testkube.io/testtrigger-example created`

**Version / Cluster**
- Which testkube version?
```
Client Version 1.6.28
Server Version v1.6.28
```

- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
official Kubernetes Version run on a private machine

- What Kubernetes version?
`v1.23.8`

 
**Additional context**
Creation of `tests`, `testsuites` and `container executors` works without a problem.

Creation of a trigger in `minikube` works also without a problem:
```
# minikube
minikube version: v1.25.1

# Testkube
Client Version 1.6.28
Server Version v1.6.28

# Kubectl
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1"
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1"
```

**Comment by dejanzele** [comment]
Hello @esebrei 

Can you please check which version of Helm chart is used for Testkube? You could try with `helm ls -n testkube` (assuming it is installed in `testkube` namespace)

Also, can you check the status of `webhook-cert-gen` and `webhook-cert-patch` jobs which are in charge of cert creation? You could try with `kubectl get jobs -n testkube` (assuming it is installed in `testkube` namespace)

If any of the jobs failed, please check the corresponding pod logs and paste them here.

Kind regards

**Comment by esebrei** [comment]
Helm chart version: `testkube-1.6.87`
But status is `FAILED`

`kubectl get jobs -n testkube` returns no jobs at all (testkube is installed in the namespace `testkube`).

I did install testkube with following command:
`helm install --namespace testkube testkube testkube/testkube --set mongodb.persistence.enabled=false`
(We have a problem with  NFS and MongoDB setup, therefore I disabled the persistance of MongoDB)

**Comment by dejanzele** [comment]
Hey @esebrei,

Can you please check a couple more things for me?
* Can you run `kubectl describe validatingwebhookconfiguration testkube-operator-webhook-admission -n testkube` and check is the `webhooks[0].clientConfig.caBundle` field set? It should be large string which starts with `LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t`
* Can you run `kubectl get secret webhook-server-cert --template={{.data}} -n testkube` and check does the `ca.crt` field match the `caBundle` in the `ValidatingWebhookConfiguration`? (check in the previous step)

**Comment by esebrei** [comment]
Hi @dejanzele,

the field `webhooks[0].clientConfig.caBundle` is not set. The field `webhooks` looks like this:

```
[...]
Webhooks:
  Admission Review Versions:
    v1
    v1beta1
  Client Config:
    Service:
      Name:        testkube-operator-webhook-service
      Namespace:   testkube
      Path:        /validate-tests-testkube-io-v1-testtrigger
      Port:        443
  Failure Policy:  Fail
  Match Policy:    Equivalent
  Name:            vtesttrigger.kb.io
  Namespace Selector:
  Object Selector:
  Rules:
    API Groups:
      tests.testkube.io
    API Versions:
      v1
    Operations:
      CREATE
      UPDATE
    Resources:
      testtriggers
    Scope:          *
  Side Effects:     None
  Timeout Seconds:  10
Events:             <none>
```

The field `ca.crt` for the second command is set and starts with `LS0tLS1CRUdJTiBDRVJUSUZJQ0`

**Comment by dejanzele** [comment]
@esebrei can you try to install the latest Helm chart (either v1.7.0 or v1.6.112 if you do not want to update to 1.7.x)?

This two jobs should create a self-signed certificate and patch the CRD and Webhook configs:
* https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/webhook-cert-create.yaml
* https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/webhook-cert-patch.yaml

It seems as they did not run for some reason.

One thing you could try is to first delete the `webhook-server-cert` and reinstall (ideally a newer version).
You could delete the secret by running `kubectl delete secret webhook-server-cert -n testkube`

**Comment by esebrei** [comment]
Thank you @dejanzele 

I could not upgrade the helm charts for testkube. But I deleted the helm charts and did install the latest helm charts. The status is now `deployed`.

The `webhooks[0].clientConfig.caBundle` does now exist and is identical to the  ` webhook-server-cert`.

Creating a trigger does now work as well.

But the jobs `webhook-cert-gen ` and `webhook-cert-patch` don't exist. So I can't verify if they did run successfully or not.

I think you can close this issue.
