### ISSUE TITLE
Stderr is missing in Dashboard for execution logs

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2669]
**Describe the bug**
Stderr is missing for Dashboard execution logs

**To Reproduce**
1. Check `artillery-executor-smoke-144` test at Demo: https://demo.testkube.io/tests/executions/artillery-executor-smoke/execution/63690d2d48e34f390b6ce283
![Screenshot_20221107_150354](https://user-images.githubusercontent.com/1473096/200330462-a67d632f-32b9-47e3-9053-afb8fca34d85.png)

3. Test failed, but the output in Dashboard looks exactly like the tests that passed
4. Check execution logs with CLI:
```
$ testkube get execution artillery-executor-smoke-144
ID:         63690d2d48e34f390b6ce283
Name        artillery-executor-smoke-144
Number:            144
Test name:         artillery-executor-smoke
Type:              artillery/test
Status:            failed
Start time:        2022-11-07 13:50:37.112 +0000 UTC
End time:          2022-11-07 13:50:53.303 +0000 UTC
Duration:          00:00:16
Labels:            core-tests=executors

Status test execution failed:

⨯ scrape artifacts error: minio failed to create a bucket 63690d2d48e34f390b6ce283: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.
Running scenarios...
Phase started: unnamed (index: 0, duration: 1s) 13:50:45(+0000)

Phase completed: unnamed (index: 0, duration: 1s) 13:50:46(+0000)

--------------------------------------
Metrics for period to: 13:50:50(+0000) (width: 0.474s)
--------------------------------------

http.codes.200: ................................................................ 1
...
```

**Expected behavior**
Complete execution log should be visible with Dashboard. Currently stderr part is missing: 
```
⨯ scrape artifacts error: minio failed to create a bucket 63690d2d48e34f390b6ce283: Storage backend has reached its minimum free drive threshold. Please delete a few objects to proceed.
```

**Version / Cluster**
Client Version 1.6.28
Server Version v1.6.28

**Comment by exu** [comment]
This error should be in errorMessage - for now we're missing it to show in Dashboard

**Comment by tkonieczny** [comment]
This issue isn't related to only "internal" error messages. Another case - If the curl test response code won't match the `expected_status` no error message is displayed in Dashboard.
In CLI:
```⨯ response statut don't match expected 418 got 200``` (btw. typo in `status`)

**Comment by vLia** [comment]
This should've been fixed, latest Testkube will not show "No logs". Please re-open in case the issue occurs again.
