### ISSUE TITLE
Add filters as query parameters on Tests and Test Suites

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2679]
**Describe the enhancement you'd like to see**
As a user I want to have a URL with query parameters whenever I select a Filter on the Tests or Test Suites overview (can be Search, Labels or Status) 

This would allow me to refresh the page easily or to share it with others and have those filters predefined

**Additional context**

A sample URL like `https://demo.testkube.io/tests?search=maven` would then allow me to directly have this view whenever I open the page: 

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/132332/200552307-5569dc8f-54d3-4c57-941b-99f39a191338.png">

**Comment by pavloburchak** [comment]
As an additional improvement here, I can see redesigning labels and status filters. Maybe labels can be a regular labels select component we already have, and status could be simpler as well. @fivenp what do you think?

**Comment by fivenp** [comment]
I love this idea @pavloburchak – shall we spin off a separate ticket for this? 

It will require way more effort for labels sadly – because you can also just filter by label KEY and our current label component is potentially not really able to handle keys only? 



![Image](https://user-images.githubusercontent.com/132332/200809418-d77bd437-8f56-460c-808f-ebb46eb28894.png)

**Comment by pavloburchak** [comment]
@fivenp yeah, it is not. Maybe lets really create separate issue and think more about it
