### ISSUE TITLE
Old executors cleanup

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2689]
- remove old executors that are not needed/not working anymore
- Add colour coding variable configuration if that executor supports it.

related issued: https://github.com/kubeshop/testkube/issues/1942

**Comment by vsukhin** [comment]
we just estimate "remove old executors that are not needed/not working anymore"

**Comment by vsukhin** [comment]
Related to #2422. Do we have any other cases @tkonieczny ?
