### ISSUE TITLE
How can we customise pod  initialise for test / IF you can locate path for deployment yaml for pod creation while executing test .

### ISSUE THREAD

**Issue by nizamkhazi87** [kubeshop/testkube#2720]
Hi ,

We want to now which template .yaml file we can change if we want to add any annotation for pod initialisation .yaml file .
I tried to search in git repo and gone through code not able to find any .

Can you please provide me a location of template which we can refer for a pod initialisation . Attaching sample pod inittialisation .yaml file which got created while running test ...

 
[podinit.txt](https://github.com/kubeshop/testkube/files/10012024/podinit.txt)

**Comment by vsukhin** [comment]
Hey, @nizamkhazi87 

thank you for using Testkube
we use this template from our helm chart https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/job-template.yml

It's passed to api server through env variable
You can either install Testkube from you local folder and change this template or you can always create a custom executor based on one of existed Testkube executors and provide path to your job template  file

**Comment by nizamkhazi87** [comment]
> Hey, @nizamkhazi87
> 
> thank you for using Testkube we use this template from our helm chart https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/job-template.yml
> 
> It's passed to api server through env variable You can either install Testkube from you local folder and change this template or you can always create a custom executor based on one of existed Testkube executors and provide path to your job template file

@vsukhin  Thanks for reply .
Can you point me to a helm template where this annotation is present .
metadata:
  annotations:
    cni.projectcalico.org/podIP: 
    cni.projectcalico.org/podIPs: 
    kubernetes.io/psp: 30-psp-testkube

**Comment by vsukhin** [comment]
These are not Testkube annotations. Calico is from your k8s cluster

**Comment by nizamkhazi87** [comment]
> cluster

I want to add couple more annotation for fetching pod metrics along with this . How can i add those extra annotation.

**Comment by vsukhin** [comment]
@TheBrunoLopes can help with call setuo

**Comment by nizamkhazi87** [comment]
> call

Thanks @vsukhin  

@TheBrunoLopes  Can you please set up a call .
emai id : khazi.nizam@gmail.com

**Comment by TheBrunoLopes** [comment]
Hello @nizamkhazi87 , thank you for reaching out!
I would love too, please book any time that fits you here -> https://calendly.com/bruno-at-kubeshop/30min-1
Looking forward to meeting you ;)

**Comment by vsukhin** [comment]
Let me know, if you still have questions
