### ISSUE TITLE
Getting error when running test through GIT url .

### ISSUE THREAD

**Issue by nizamkhazi87** [kubeshop/testkube#2730]
Tried running script using below step 
https://kubeshop.github.io/testkube/test-types/executor-k6/#running-a-k6-test

kubectl testkube create test --git-uri https://github.com/kubeshop/testkube-executor-k6.git --git-branch main --git-path examples --type "k6/script" --name k6-test-script-git

Error : 
⨯ k6 test script /data/repo/run not found

**Comment by vsukhin** [comment]
Hey, @nizamkhazi87 
K6 is filed based test, you will need to provide a filename of the script from your git repo for git based tests
See details below
https://github.com/kubeshop/testkube-executor-k6

**Comment by vsukhin** [comment]
Hope,it's clear now
