### ISSUE TITLE
Add support to download mochawesome reports with cypress tests

### ISSUE THREAD

**Issue by prasang03** [kubeshop/testkube#2752]
As a user, working with cypress, I am mostly working with moccawesome reports. I would like to be able to view and download moccawesome reports from testkube artifact's as well. 
This will help me in better reporting and understanding of my Cypress tests.

**Comment by exu** [comment]
@TheBrunoLopes @vsukhin Maybe we could think about something more "generic" like reporters abstraction, let's maybe brainstorm this idea as it could give quite a lot of power to our users.

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2752?planning-poker) with Zenhub @vLia @nicufk

**Comment by TheBrunoLopes** [comment]
Hello @prasang03 did you manage to generate the moccawesome reports ? 
We are working on a way to allow our users to customise this directly.

**Comment by prasang03** [comment]
Hello, that's good to know, as of now I am only relying on the testkube
dashboard to have some reports.

**Comment by vsukhin** [comment]
hey @prasang03 right now in 1.12 all Testkube pre-built executor support comand/args customization and scraping custom artifacts
