### ISSUE TITLE
Empty Testkube API endpoint in Dashboard

### ISSUE THREAD

**Issue by med502** [kubeshop/testkube#2779]
Dashboard POD does not produce logs

**To Reproduce**
1. Run kubeclt logs <dashboard-pod>
2. See empty output

**Expected behavior**
Pod should produce operational and debug logs

**Version / Cluster**
- Which testkube version? 1.7.5
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.21.4

**Screenshots**
N/a
 
**Additional context**
I had poblem with dashboard not loading list of executor types while creating new test, I wanted to troubleshoot reason but without logs it wasn't possible. Manual creation of executor and removal of it fixes the problem with I tried to troubleshoot.

**Comment by vsukhin** [comment]
Hey, @med502 Dashboard is technically a react application running in ngnx env. So, the only server logs we have are nginx logs.
Regarding this error, you need to check Dashboard setting, Testkube API Endpoint - http://localhost:8088/v1

**Comment by med502** [comment]
> Hey, @med502 Dashboard is technically a react application running in ngnx env. So, the only server logs we have are nginx logs. Regarding this error, you need to check Dashboard setting, Testkube API Endpoint - http://localhost:8088/v1

Hi @vsukhin  thanks for answer. Either way kubernetes does not see those logs.
BTW do you know if that API endpoint can be hardcoded so users do not have to fill that in?

**Comment by vsukhin** [comment]
Good point. It works generally, but in some cases, itt's not set. We tried to fix this, but users still face this issue. Let leave it as an open issue and let us try once again :)

**Comment by vsukhin** [comment]
So, we still have cases of empty Testkube API endpoints

**Comment by med502** [comment]
> So, we still have cases of empty Testkube API endpoints

It looks dashboard POD has ENV var TESTKUBE_API_SERVER_SERVICE_HOST with correct IP but it does not use it and asks for external link.

**Comment by PunkSage** [comment]
Hi @med502, do you still experience this issue?

**Comment by med502** [comment]
> Hi @med502, do you still experience this issue?

Hi @PunkSage  I need to make version upgrade and verify. I will work on that next week and get back to you

**Comment by tkonieczny** [comment]
@fivenp wrote a summary at Slack:
> the prio is pretty easy:
> if !localStorage => url param || env var  => save localStorage else use localStorage
> if still !localStorage => modal
> apiEndpoint param always overwrites localStorage


I think this time the only case that's not working is setting API endpoint with apiEndpoint
So, if I set it with http://localhost:8080/apiEndpoint?apiEndpoint=asdf:8088/v1 it won't work, but when I just open dashboard, go to api endpoint modal, and set it there it's configured correctly. And, I guess we missed it because almost every single time we use it this way http://localhost:8080/apiEndpoint?apiEndpoint=localhost:8088/v1 with testkube dashboard (port forward). So, everyone already had this one set in local storage in the correct way

**Comment by fivenp** [comment]
this is also related to #3289 (and could be done within one ticket?) :)
