### ISSUE TITLE
Arguments not working with jMeter executor

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#2783]
**Describe the bug**
Arguments specified with --executor-args are not passed correctly to jMeter executor

**To Reproduce**
1. Run 
```
kubectl testkube create test --file create-users.jmx --name jmeter-create-users --type jmeter/test \
--executor-args "-p" --executor-args "/data/uploads/create-users.properties" \
--copy-files create-users.properties:create-users.properties
```
or
```
kubectl testkube create test --file create-users.jmx --name jmeter-create-users --type jmeter/test \
--executor-args "-p /data/uploads/create-users.properties" \
--copy-files create-users.properties:create-users.properties
```
etc..

2. Run the test
3. See error: `{"type":"line","content":"An error occurred: Unknown arg: null\n"}`

**Expected behavior**
Any specified arguments are correctly passed to jMeter

**Version / Cluster**
- Which testkube version? 1.7.10 both
- What Kubernetes version? 1.22.6

**Comment by vLia** [comment]
Hello @f-helm, I am struggling to reproduce this issue, but will add some tests to the code to see if I can catch it. Will keep you updated.

**Comment by vLia** [comment]
Unfortunately I still cannot catch it with the tests added (https://github.com/kubeshop/testkube-executor-jmeter/pull/5)

**Comment by vsukhin** [comment]
hey @f-helm Can you please provide us your original create-users.properties and create-users.jmx files without private data to reproduce it on our side?

**Comment by vsukhin** [comment]
Please let us know if you still have any issues

**Comment by f-helm** [comment]
Retested and no issues so far, thanks!
