### ISSUE TITLE
Variables not working with jMeter executor

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#2784]
**Describe the bug**
Variables are not passed correctly to jMeter when specified with -v or --variable

**To Reproduce**
1. Run 
```
kubectl testkube create test --file create-users.jmx --name jmeter-create-users --type jmeter/test \
-v threads=10 -v rampup=0 -v loopcount=1 -v ip=sampleip -v port=1234
```

etc..

2. Run the test
3. See error: `{"type":"line","content":"An error occurred: Unknown arg:  -Jip=sampleip  -Jloopcount=1  -Jport=1234  -Jrampup=0  -Jthreads=10"}`

**Expected behavior**
Any specified variables are correctly passed to jMeter

**Version / Cluster**
- Which testkube version? 1.7.10 both
- What Kubernetes version? 1.22.6

**Comment by vsukhin** [comment]
Please lety us know, if you still have any issues

**Comment by f-helm** [comment]
Retested it and no issues so far!
