### ISSUE TITLE
Cypress executor - test configuration options - browser and package manager selection

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2788]
Cypress included images, which are base for new Cypress executor images, include:
- Chrome, Firefox, and Electron browsers
- Both NPM and YARN

Additionally, the images are built for specific Cypress versions.
That gives us the ability to provide easy to use browser and package manager selection on the test level using the single image. Without the need to build a huge grid of different cypress version/browser/package manager images.

**Old, custom images need to be dropped first**: https://github.com/kubeshop/testkube/issues/2787

**Comment by vsukhin** [comment]
We will provide a wozard in UI for selection oof
