### ISSUE TITLE
Direct client option doesn't seem to work

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#2806]
kubectl testkube get executors --client direct
api/GET-testkube.ServerInfo returned error: can't get problem from api response: invalid character 'C' looking for beginning of value, output: Cannot GET /api/v1/info

listing executors:  (error: api/GET-[]testkube.ExecutorDetails returned error: can't get problem from api response: invalid character 'C' looking for beginning of value, output: Cannot GET /api/v1/executors)

Client Version 1.7.10
Server Version v1.7.10

**Comment by vsukhin** [comment]
Hey, @blevinson How did you provide api-uri for direct client? It should be either in config or cli parameter

**Comment by blevinson** [comment]
Hello @vsukhin!
Thank you for your response. I followed these directions:
https://kubeshop.github.io/testkube/authentication/oauth-cli

Then added the clientId and secret via this:
kubectl testkube config oauth https://[serverurl]/api --client-id XXXXXXXXXX --client-secret XXXXXXXXXX

**Comment by blevinson** [comment]
I got it to work. Thank you!

**Comment by vsukhin** [comment]
Excellent news! Happy, that you solved it out;) Not a very frequent requsted feature, was always curious, if provided explanation is clear enough ;)

**Comment by blevinson** [comment]
@vsukhin, how is it typically done within a CI/CD pipeline?

**Comment by vsukhin** [comment]
This is how we do testing in Testkube itself https://github.com/kubeshop/helm-charts/blob/main/.github/workflows/helm-releaser-testkube-charts.yaml#L223
