### ISSUE TITLE
Test trigger for resource config map

### ISSUE THREAD

**Issue by esebrei** [kubeshop/testkube#2808]
**Is your feature request related to a problem? Please describe.**

It is not possible to trigger tests, when a config map is changed.

**Describe the solution you'd like**

The configuration of a test trigger should work the same way it does for other resources (i.e. deployment, pods). 
If a config map is modified, the tests registered with the trigger, should run automatically.

**Comment by TheBrunoLopes** [comment]
Seems like an easy addition. 
Included for the next release v1.9
I would love to understand better how your deployment/testing process to see how can Testkube help you and other users better. Could you spare a few minutes to ask a few questions: https://calendly.com/bruno-at-kubeshop/30min-1 ?

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2808?planning-poker) with Zenhub @nicufk @vLia
