### ISSUE TITLE
UI: Add Full fledged parallel test execution

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2809]
**Describe the enhancement you'd like to see**
This is the UI part of #2356 

Since we're going to allow for parallel test executions within a test suite we'll need a way to also visualise the pipeline.

* The user can SEE his pipeline in a nice way (e.g. `react-flow` might be a good tool to use here?)
![image](https://user-images.githubusercontent.com/132332/204284635-cc83c217-383c-4d96-a2b6-e949cd9ba1d1.png)

* The user can EDIT the pipeline through the YML below

**Additional context**
Figma file: 
https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=2269%3A81252&t=ZeulwV0WyVqKxxG9-4

**Comment by blevinson** [comment]
These mockups looks excellent! I would love to see them come to life.

**Comment by vsukhin** [comment]
hey, @blevinson Thank you and @fivenp for his work! It's planned for next release )
