### ISSUE TITLE
Test Suite and Test overview items jump around on every new execution

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2813]
**Describe the enhancement you'd like to see**
1. When looking at the test or test suite execution I see a list of Items. 
2. Once a test or suite gets executed the order of the items changes to display the last executed item first

We would like to slightly change this behaviour

1. The data INSIDE each card / item should ALWAYS be updated (as it does today)2. 
2. Once the user started scrolling the page we should NOT change the order of the items anymore

**Additional context**
I'd say it's up for discussion if we want to stop re-ordering only on scroll or all the time :)

**Comment by TheBrunoLopes** [comment]
won't do
