### ISSUE TITLE
jMeter executor - Git directory support

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#2821]
**Describe the enhancement you'd like to see**
I would like to be able to specify a git directory when creating a test with the jMeter executor because I want to be able to use custom properties files and other files referenced in the jMeter test plan like csv-files. The current executor lacks the flexibility for more complex jMeter test setups in a GitOps environment.

**Additional context**
This is currently possible only locally with `--copy-files` and then referencing the files with `--executor-args`,
e.g. 

```
testkube create test --file create-users.jmx --name jmeter-create-users --type jmeter/test \
--executor-args "-p /data/uploads/user.properties" \
--copy-files create-users.properties:create-users.properties \
--copy-files users.csv:users.csv
```

would be

`kubectl testkube create test --git-uri https://github.com/my-jmeter-git-dir --git-branch main --git-path create-users --type jmeter/test --name jmeter-create-users-git`

with a directory like this:

```
create-users
├── create-users.jmx
├── users.properties
└── users.csv
```

As an implementation suggestion, I think it makes sense to automatically detect the test plan file by extension `xml` and add it with the test plan parameter `-t` automatically.

For properties files, I think automatic detection is not really suited, since as a user I want to keep control if the properties are applied with `-q` or `-p`, however, jMeter has a great default to solve this:

Since a file called user.properties is automatically loaded by jMeter per default (https://jmeter.apache.org/usermanual/properties_reference.html#properties), it would be great if the files from the git repository were stored in run path of the jMeter binary. This way, if a user.properties file was placed in the git repo, no further specification would be required by `--execution-args` and this would further decouple the test resource from the actual test content.

Other files can be referenced inside the test plan, and do not need to be referenced by jMeter command line arguments (or can additionally by `--execution-args`, so storing them is sufficient.

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2821?planning-poker) with Zenhub @nicufk @vLia
