### ISSUE TITLE
envFrom for tests

### ISSUE THREAD

**Issue by amit-o** [kubeshop/testkube#2822]
**Is your feature request related to a problem? Please describe.**
envFrom is a very useful feature to map all keys in a secret/configmap to a pod, which is missing from testkube. It is pretty frustrating to migrate 8+ keys to secretKeyRef etc

**Describe the solution you'd like**
Ability to configure envFrom instead of just env with ref selector

**Comment by TheBrunoLopes** [comment]
Working on this issue as part of https://github.com/kubeshop/testkube/issues/2948
Closing this one to not have duplicates.
