### ISSUE TITLE
Metrics displayed in test's info panels don't reflect Artillery metrics shown in log.

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#2824]
Is it possible to get it to show the results sourced from the results of the tests?

![CleanShot 2022-11-30 at 11 28 22](https://user-images.githubusercontent.com/17077/204854720-eef66570-3d62-43ca-bdea-a64e6896de2b.png)

**Comment by vsukhin** [comment]
@TheBrunoLopes please check this out

**Comment by TheBrunoLopes** [comment]
Hello @blevinson at this point it's not possible for a specific test to set or generate metrics data to be used in our metrics dashboard. They are set by the text pass/fail ratios and execution duration.
that said, this use case is pretty interesting. We are planning a refactor of the executor at the start of next year so we will 
review how metrics are defined at that point.

**Comment by TheBrunoLopes** [comment]
I'll close this issue for now.
