### ISSUE TITLE
[Bugs] Creating Test and Executing is not working on Demo

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2840]
- Demo not working:
https://user-images.githubusercontent.com/13501228/205465855-126fb419-3034-4da5-a76e-f595fe67f2b6.mov

- Allow to create a test with empty content. 
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/13501228/205465998-80d36ebd-7a04-4d16-b413-c4bf274af46a.png">
(It works If I define it using yaml)
<img width="676" alt="image" src="https://user-images.githubusercontent.com/13501228/205466020-70cd161a-a7d0-45eb-8f11-51bbc088af5d.png">
So the CLI should also work as well.

**Comment by vsukhin** [comment]
cli will be fixed to allow empty content, fortio command syntax should be fixed in container definition `Error: unknown command  http://www.google.com`

**Comment by TheBrunoLopes** [comment]
thanks @vsukhin
