### ISSUE TITLE
API: Create an endpoint to list all available secret stores and their keys 

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2842]
We want to allow our users on the frontend to select an already existing secret key from the cluster (whichever secrets/keys the instance might have access to)

<img width="336" alt="image" src="https://user-images.githubusercontent.com/132332/205591993-f817116f-fc5a-4e3f-8f4c-9fa06cf34607.png">

An optimal response would look something like 
```json
{
  "secrets": {
    "store-name-1": ["KEY_1","KEY_2","KEY_3"],
    "store-name-2": ["KEY_1","KEY_2","KEY_3"],
    "store-name-3": ["KEY_1","KEY_2","KEY_3"],
    "GITHUB": ["GIT_USERNAME","GIT_TOKEN"]
  }
}
```

**Comment by tkonieczny** [comment]
https://kubeshop.slack.com/archives/C026SAW3LR0/p1696949169473819
