### ISSUE TITLE
Ability to abort execution of multiple tests

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#2852]
When multiple tests are run and are having issues, the UI only gives the ability to abort a single execution at a time. With this, it's very time consuming to abort each. It would be helpful to be able to abort all of them.
![CleanShot 2022-12-05 at 12 44 33](https://user-images.githubusercontent.com/17077/205706505-03a75c49-1ab8-42ae-a1c4-bf8a48831c08.png)

**Comment by vsukhin** [comment]
For @pavloburchak and @fivenp to find a best approach

**Comment by fivenp** [comment]
* We could have a hamburger menu icon (next to the Run button) which allows to `Abort all executions` 

<img width="222" alt="image" src="https://user-images.githubusercontent.com/132332/206006414-b3a98c7f-3d9d-4002-812a-68e7ce5b7f61.png">

* We would need to have the same hamburger menu icon also on the EntityList 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/132332/206006518-55da8cfe-dcfe-4798-8b12-7c06d731a414.png">

**Comment by pavloburchak** [comment]
Linked with #2925

**Comment by Toxer10** [comment]
@fivenp would not it be better to allow to select only SOME of the executions and perform an action on selected executions only? Of course we can add an ability to abort all the executions

**Comment by fivenp** [comment]
No… that would really be overkill right now - especially since we also want to abort all executions from the entity list view :)

**Comment by TheBrunoLopes** [comment]
@vsukhin is this possible to be done on the backend, to abort all running tests ?

**Comment by vsukhin** [comment]
Guess, it's done

**Comment by TheBrunoLopes** [comment]
great, so the last missing pieces would be to allow this on the CLI and UI ?
