### ISSUE TITLE
Minio cannot be disabled

### ISSUE THREAD

**Issue by emilycoco** [kubeshop/testkube#2855]
**Describe the bug**
The docs make it sound like testkube can be successfully run without minio. However, setting
`testkube-api:
        minio:
          enabled: false`

in the helm chart results in a non-functional deploy of testkube. The installation completes successfully, but when attempting to run a test, the execution fails with error:
```
⨯ could not check if bucket already exists for files: Get "http://testkube-minio-service-testkube:9000/test-create-pod/?location=": dial tcp: lookup testkube-minio-service-testkube on 10.96.0.10:53: no such host

```
Are there additional settings that need to be configured to turn off minio cleanly?

**To Reproduce**
1. Install testkube with minio.enabled = false
2.  create a test and try to run an execution
3.  check execution status

**Expected behavior**
Testkube works without minio.

**Comment by vLia** [comment]
Hello @emilycoco,
This is a bug indeed, I am looking at it right now.

Just to make sure, by disabling minio, you lose some features on artifacts and uploading files. That's fine for your use case, right?

**Comment by vLia** [comment]
Hey @emilycoco,
A fix was released for this issue. Could you please update your installation and check if the problem is still there?

**Comment by vsukhin** [comment]
please let us know, if you have any questions
