### ISSUE TITLE
UI: Hide github repo credentials in Sources section

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#2856]
After you create a new source, the credentials that you used remain visible. The enhancement is to hide them.
![CleanShot 2022-12-05 at 18 20 57](https://user-images.githubusercontent.com/17077/205765233-535d5e13-d2c2-4b22-8a43-3e3a3aeac8a3.png)

**Comment by pavloburchak** [comment]
@blevinson do you think it is worth hiding a username as well token?
