### ISSUE TITLE
Ginkgo executor secrets passed as flags to ginkgo

### ISSUE THREAD

**Issue by aczarkowski** [kubeshop/testkube#2872]
**Describe the bug**
When you define a secret or secretRef in Ginkgo test the ginkgo executor will convert them as flags rather than setting them up as environment variables

**To Reproduce**
1. Define secret or secretRef in any Ginkgo test
2. Run
3. You should see error message from executor saying "flag provided but not defined: <your secret variable>"

**Expected behavior**
secrets or variables should not be converted to flags but only set as environment variables

**Version / Cluster**
- testkube version 1.7.40
- What Kubernetes cluster? AKS
- What Kubernetes version? any

**Screenshots**
![image](https://user-images.githubusercontent.com/38211274/206217212-6eaabcb9-4da7-444e-9d84-4209ee9ab1b0.png)

**Comment by vsukhin** [comment]
Thank you @aczarkowski Definitely, will fix it in next release

**Comment by aczarkowski** [comment]
> Thank you @aczarkowski Definitely, will fix it in next release

Thanks. testkube is awesome btw.

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2872?planning-poker) with Zenhub @nicufk @vLia
