### ISSUE TITLE
UI: Move entity execution detail into a drawer

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#2877]
**Describe the enhancement you'd like to see**
We're currently using a 2 column layout on execution details. 

We'd like to move away from this and give the execution detail more space (especially for the logs) and focus. 
Our first test will be moving the detail into a drawer (keep the dedicated URL please :)) 

* The drawer should be ~ `85vw` wide (100vw on mobile :))
* The drawer should have a maxWidth of ~ `1200px` 
* Clicking outside of the drawer will close it
* We did also slightly improve the meta information below the execution name

![image](https://user-images.githubusercontent.com/132332/206455798-fed26cbb-6747-4b85-bfcc-24488b960a93.png)

**Additional context**
Figma: 
https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=2050%3A65451&t=3MxpE2fLuhMlJ4dn-4

**Comment by pavloburchak** [comment]
Will add a fullscreen option for log output
