### ISSUE TITLE
Kubetest installation with custom namespace fails

### ISSUE THREAD

**Issue by NiniiGit** [kubeshop/testkube#2886]
Kubetest helm chart does not create and install kubetest in custom namespace as stated in its official doc

**To Reproduce**
1. Run 'helm install --create-namespace my-testkube testkube/testkube'
2. Specify '--create-namespace' parameter as shown in above comand
3. See error: You would find that instead of creating a custom namespace and installing kubetest application inside it, above helm chart command install it in the namespace which you're accessing right now (I use [kubens](https://github.com/ahmetb/kubectx) utility to access and work in particular namespace)

**Expected behavior**
It should ideally install the kubetest app inside its above given namespace. It should create the custom namespace if does not exist prior

**Version / Cluster**
- Which testkube version? 
```
Client Version 1.7.12
Server Version v1.7.12
Commit 7aa4ee482a96331372acb18905ba411b0df3d6ae
Built by goreleaser
Build date 2022-11-25T13:00:29Z
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
EKS cluster

- What Kubernetes version?
```
➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

```

**Screenshots/CLI command output**
```
helm install --create-namespace my-testkube testkube/testkube
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/infracloud/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/infracloud/.kube/config
NAME: my-testkube
LAST DEPLOYED: Sun Nov 27 11:41:53 2022
NAMESPACE: backstage
STATUS: deployed
REVISION: 1
NOTES:
`Enjoy testing with testkube!`

```
 
**Additional context**

**Comment by vsukhin** [comment]
Hey, @NiniiGit This definitely needs to be retested and refactored. Probably, in next version @TheBrunoLopes?

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2886?planning-poker) with Zenhub @nicufk @vLia

**Comment by vsukhin** [comment]
hey, @NiniiGit 
Please use a bit different helm command
`helm install --create-namespace --namespace my-testkube testkube/testkube'`
Also,I tuned CLI a bit, so `--namespace my-testkube` flag should be used for all  CLI commands or set it as default namespace using `kubectl testkube config namespace my-testkube`
