### ISSUE TITLE
Webhooks don't specify the content type

### ISSUE THREAD

**Issue by scott-david-walker** [kubeshop/testkube#2904]
**Describe the bug**
Webhooks content is in json format but doesn't send content-type: application/json

**To Reproduce**
1. Create a web hook
2. Trigger web hook

**Expected behavior**
I would expect the content type to specify that it is of type application/json

**Version / Cluster**
- Which testkube version? client: 1.7.10, server 1.7.24
- What Kubernetes cluster? AKS

**Screenshots**
![image](https://user-images.githubusercontent.com/13588473/207608641-4e44f6b5-975b-47c9-abb6-9f8dd0c6106e.png)

**Comment by vsukhin** [comment]
thank you @scott-david-walker should be a quick fix
