### ISSUE TITLE
Latest test execution status on the test itself

### ISSUE THREAD

**Issue by sebagomez** [kubeshop/testkube#2906]
I need to use standard tools so I'd like to be able to get the latest status of a test with something like the following.

```bash
kubectl get test mytest -n testkube -o jonpath='{.status}'
```

Right now the CRD of the `Test` does not have a status. It would be helpful.

Is there an alternative? Maybe through the execution?

Thanks

**Comment by TheBrunoLopes** [comment]
Good request. Perhaps `testkube get test execution mytest --is-passing` or something like this ? 

cc: @fivenp

**Comment by vsukhin** [comment]
Hey, @sebagomez 
yes, we don't store last execution result in test CRD. all the execution results are stored in mongo DB. if you run 
`kubectl testkube get test <test name>`, it returns both test and latest execution result in CLI, but it's not json formatted.
So, one of the options is to use CLI command (and we will need to support json templates) or we might need to create CRD for execution results and store there always latest test execution

**Comment by TheBrunoLopes** [comment]
I see that storing the tests results in CRDs is a recurring topic. We decided not to for scaling purposes.
The best approach to me seems like creating a CLI command for this. that checks what's the status of the last test execution is. If there's one in progress, it waits for the completion of that one, and then returns if it passed or failed.

What do you think ?

**Comment by sebagomez** [comment]
We want to use Teskube in a fully automated zero-touch environment, with (when possible) no need to install additional plugins. In general, these are not tasks that will be manually run, so a proper CRD with the execution status would be the best option IMHO.

Also, the info is available, when I run `kubectl testkube get test` I get something like the following, wish is not easy to parse.

```bash
  NAME            | TYPE              | CREATED                       | LABELS                | SCHEDULE    | STATUS | EXECUTION ID              
------------------+-------------------+-------------------------------+-----------------------+-------------+--------+---------------------------
  my-test         | git-bash-cli/test | 2022-12-14 15:42:49 +0000 UTC | testkube.feature=test | 0 */1 * * * | passed | 6399f8eb330df416afc181dc  
```

Speaking of which, and this should probably be a different issue, when I use a different output from the testkube plug in, the output is not fully what I want.  
For instance, if I run `k testkube get test my-test -o json` I cannot pipe that into [jq](https://stedolan.github.io/jq/) because there's a header in the output that makes it impossible to parse (same with yaml output).  
I would expect the output to work as plain kubectl.

**Comment by vsukhin** [comment]
Then yes, execution CRD, one per test, with latest test result might be sufficient for this. I don't think we need to add execution info to test CRD, because of separation of concerns and in general test CRD is git based, can be easily sync by ArgoCD or any other tool

**Comment by sebagomez** [comment]
An extra CRD for the execution makes a lot of sense, but please have these considerations in mind.   
I'd like to easily grab the latest execution of a test an get its result, and by "easily grab" I want to be able to automate it with standard kubectl query selectors.  

This would allow me to easily grab all the executions from a particular test, get it's json (or yaml) and parse it.  

But, it would be also nice to have a quick glance of the "current" state of a `Test`. Right Tests don't have a [status](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#object-spec-and-status) and I think it would be a nice addition to use it. 

I agree that having every execution of a test on the same CRD (Test) would bring scalability issues, but I thought something like the following would make sense.

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  ...
spec:
  ...
status:
  lastExecution:
    time: # date time when last execution started 
    Id: 
    status: failed | passed | aborted
```

Let me know what you think

**Comment by vsukhin** [comment]
Yes, we will definitely add status section

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2906?planning-poker) with Zenhub @nicufk @vLia

**Comment by sebagomez** [comment]
Hello, I'm back from vacation and very excited to see this fixed, but I can't seem to see the implementation, don't know if I should open a new issue.
I currently have version 1.8.26

```bash
❯ testkube version

████████ ███████ ███████ ████████ ██   ██ ██    ██ ██████  ███████ 
   ██    ██      ██         ██    ██  ██  ██    ██ ██   ██ ██      
   ██    █████   ███████    ██    █████   ██    ██ ██████  █████   
   ██    ██           ██    ██    ██  ██  ██    ██ ██   ██ ██      
   ██    ███████ ███████    ██    ██   ██  ██████  ██████  ███████ 
                                           /tɛst kjub/ by Kubeshop


Client Version 1.8.25
Server Version v1.8.26
Commit 
Built by Homebrew
Build date 
```

And when I try to execute a test, I get the following error:

```bash
❯ kubectl testkube run test --namespace testkube ocs

starting test execution testkube/ocs (error: api/POST-testkube.Execution returned error: api server problem: can't create new test execution, can't insert into storage: could not check if bucket already exists for copy files: Get "http://testkube-minio-service-testkube:9000/testkube-logs/?location=": dial tcp: lookup testkube-minio-service-testkube on 198.19.0.10:53: no such host, context: null;
resp error:an error on the server ("unknown") has prevented the request from succeeding (post services testkube-api-server:8088))
```

Keep in mind I do NOT have MinIO enabled because I do not produce test artifacts, is MinIO required now?

Also, when I run the following command I do not see a status

```bash
❯ k get test -n testkube ocs -o yaml
```

Is it because the test has not run even once?

When I `kubectl explain` the test I do see the `TestStatus` reference.

```bash
❯ k explain test
KIND:     Test
VERSION:  tests.testkube.io/v3

DESCRIPTION:
     Test is the Schema for the tests API

FIELDS:
   apiVersion   <string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind <string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata     <Object>
     Standard object's metadata. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata

   spec <Object>
     TestSpec defines the desired state of Test

   status       <Object>
     TestStatus defines the observed state of Test
```

**Comment by sebagomez** [comment]
I finally enabled MinIO and the tests ran successfully, but, I still don't see the status in the test... am I missing something?

**Comment by vsukhin** [comment]
Welecome back @sebagomez !
We're fxiing minio issue https://github.com/kubeshop/testkube/issues/3036 now.
I could see test statuses for all tests we run. yes, it's a status of the latest execution 
kubectl testkube get tests postman-test --crd-only

**Comment by vsukhin** [comment]
Technically, status is only when execution is completed  - failed or passed

**Comment by vsukhin** [comment]
And make sure you have logs.storage = "mongo" in helm chart, if you don't use minio

**Comment by sebagomez** [comment]
Right now I do have MinIO and my tests have passed and some failed, but I don't see the status either with `kubectl get test -n testkube ocs -o yaml` (the command I'll be using) or `kubectl testkube get tests ocs --crd-only`

**Comment by vsukhin** [comment]
Do you use our latest helm chart, because we added new roles for updating status (calling k8s status api)?
Can you check `kubectl logs testkube-api-server.. -n testkube` logs after test is finished. Any errros?

**Comment by sebagomez** [comment]
No, I was not working with the latest version 🤦‍♂️
I need quite an amount of changes in my values file... let me get back to you once that's done. 

Sorry about that.

**Comment by vsukhin** [comment]
np. status is a special field in k8s and requires special api access

**Comment by sebagomez** [comment]
Everything is there! Thank you!

**Comment by TheBrunoLopes** [comment]
Hello @sebagomez I'm glad to see you using our latest version with the status on the CRD.
We would really appreciate it to understand your use case and needs better, and also to get some feedback from you to improve Testkube even more. Would you mind going on a quick call with us https://calendly.com/bruno-at-kubeshop/30min-1 whenever you are available?
