### ISSUE TITLE
Able to override git branch when running a test suite

### ISSUE THREAD

**Issue by scott-david-walker** [kubeshop/testkube#2911]
When running a test suite, I’d like to be able to decide on a test suite level what branch I’m taking these tests from. Specifically useful if I’m adding a new test in a branch that isn’t in main yet but want to run it in a test suite on a pr or something similar.

would be fantastic if it can be implemented in the same manner as variables are. E.G. Overriding them on a test suite level.

**Comment by vsukhin** [comment]
thank toy @scott-david-walker sound reasonable, we will plan it out
