### ISSUE TITLE
Cypress Test Run OOO

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#2915]
The user keeps getting this error when they run Cypress Tests:

`Failed to adjust OOM score of renderer with pid 1208: Permission denied (13)`

The number after pid changes randomly.

**Comment by TheBrunoLopes** [comment]
cc: @tkonieczny

**Comment by tkonieczny** [comment]
It's just a warning message that don't affect the execution - we also get it. For example, https://demo.testkube.io/tests/executions/cypress-default-executor-smoke-electron-testsource-git-dir/execution/639b51e64a6858babedcd7b2

**Comment by vsukhin** [comment]
yes, guess, users ask about it from time to time

**Comment by vsukhin** [comment]
closing for now
