### ISSUE TITLE
Testkube executor initcontainer "testkube-executor-init" tries to execute "chmod" and fails when uid is not "0"

### ISSUE THREAD

**Issue by crdnb** [kubeshop/testkube#2928]
**Describe the bug**
The Testkube executor initcontainer "testkube-executor-init" tries to execute "chmod" and fails when uid is not "0". This means, that Testkube does not work on OpenShift with scc "restricted", which is the default scc, or Kubernetes clusters where uid "0" is not allowed. The testkube executor initcontainer would run on OpenShift when scc "anyuid" would be allowed, but this is not the case in most clusters as this is a security issue.

`{"level":"info","ts":1671465831.2670317,"caller":"minio/minio.go:257","msg":"Getting the contents of buckets [test-curl-test]"}
{"level":"info","ts":1671465831.267091,"caller":"minio/minio.go:55","msg":"connecting to minio","endpoint":"testkube-minio-service:9000","accessKeyID":"minio","location":"","token":"","ssl":false}
{"level":"info","ts":1671465831.2713344,"caller":"minio/minio.go:268","msg":"Bucket test-curl-test does not exist"}
{"type":"line","content":"chmod: .: Operation not permitted\nchmod: .: Operation not permitted\n"}
{"type":"error","content":"process error: exit status 1"}`

**To Reproduce**
1. Run testkube on OpenShift or in a Kubernetes cluster, where uid "0" ist not allowed

**Expected behavior**
The initcontainer works also when run with an uid other than "0". Maybe there is a way to omit "chmod".

**Version / Cluster**
- Which testkube version?  1.8.2
- What Kubernetes cluster? Openshift
- What Kubernetes version? v1.23

**Screenshots**
See error message.
 
**Additional context**

**Comment by vsukhin** [comment]
hey, @crdnb how about using jobServiceAccount with necessary permissions https://github.com/kubeshop/helm-charts/blob/main/charts/testkube/values.yaml#L223?

**Comment by vsukhin** [comment]
@crdnb yes, you can prepare a volume using our templates.
for Testkube executors https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/job-template.yml#L33
or Container executors https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/job-container-template.yml#L54
they can be adjusted like there https://kubeshop.github.io/testkube/using-testkube/tests/tests-creating#changing-the-default-job-template-used-for-test-execution
We can make `chmod` command optional by adding a special flag to Test CRD

**Comment by crdnb** [comment]
Hi @vsukhin 

Thank you very much for the links to the docs!
I did not know about the job container template. But I already used the job template to specify cpu and memory resources on the job. What I was not able to do was to drop the whole "securityContext" block ("runAsUser" etc.).

Regarding `chmod`: Would it be possible to only execute `chmod` if the container / user has not enough permissions on the needed volume? With this solution, a flag would not be needed...

And could you tell me please, if `chmod` is run against the workdir (/data) or where else? I'm pretty sure our user has enough permission on this directory.

Thank you very much!

**Comment by vsukhin** [comment]
Welcome, @crdnb 
You can update job template as you need it
Not sure,  we can try to check if user has enough permissions for this dir, and  only then call chmod
We used it for the mounting point of the volume `/data`

**Comment by crdnb** [comment]
Hi @vsukhin 


> we can try to check if user has enough permissions for this dir, and only then call chmod

This would be great!
I'd be happy to test it then on OpenShift and give you feedback if it works.

> We use it for the mounting point of the volume /data

Thanks for clarification.

**Comment by vsukhin** [comment]
Ok, I will workon itt tmo

**Comment by vsukhin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2928?planning-poker) with Zenhub @nicufk @vLia

**Comment by vsukhin** [comment]
downgraded chmod error to warning

**Comment by crdnb** [comment]
Hi @vsukhin 
Thank you so much! Testkube is now running on OpenShift too, without higher privileges!

**Comment by vsukhin** [comment]
Welcome @crdnb. Glad it helped!
