### ISSUE TITLE
Triggers are always created in testkube namespace

### ISSUE THREAD

**Issue by stud0r** [kubeshop/testkube#2939]
**Describe the bug**
If the testkube deployment is not done in the namespace "testkube" a new trigger (cluster event) cannot be saved.

**To Reproduce**
1. Deploy testkube in a different namespace than "testkube"
2. Create a new trigger in the dashboard
3. The save action fails: "error reapplying triggers after clean: namespaces "testkube" not found"

**Expected behavior**
The behavior e.g. for Tests created through the dashboard are saved in the correct namespace.

**Version / Cluster**
- Tested with testkube version 1.8.6

**Comment by vsukhin** [comment]
Thank you for reporting @stud0r Will check it out

**Comment by vsukhin** [comment]
You can try to create trigger using yaml files and kubectl. Our frontend dev will check UI

**Comment by vsukhin** [comment]
Confiremd. `testkube` is hardcoded in UI, needs to be moved to config settings

**Comment by pavloburchak** [comment]
@stud0r fixed in the latest version
