### ISSUE TITLE
AWS S3 Integration Enhacement

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#2940]
With the current implementation of the AWS S3 integration, buckets are created with each execution. The issue with this solution is that the number of buckets would get very large and it would be difficult for others using the same S3 account to find their own bucket in the list. 

There are a couple ways (off the top of my head) that this could be enhanced:

1) Configure a specific bucket and optional directory in the helm chart where each execution would create a new directory in that bucket/directory.
2) Specify the ARN of the resource (in the helm chart or ServiceAccount) which would contain the bucket and optional directory/subdirectory where the execution directories would be written to: https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html

**Comment by crdnb** [comment]
Hi

We are facing the same problem here. We work in an enterprise environment and can only order a few buckets. We won't get permissions to create new buckets ourselfs. So we would much appreciate the suggested solution 1 (specifying a bucket where for each test a directory is created).

Many thanks!

**Comment by TheBrunoLopes** [comment]
cc: @dejanzele for awareness.

**Comment by kamilkrampa** [comment]
Is there any chance it'll be done soon? After a couple of weeks, we have already 4000 buckets in minio. Also, the minio instance started consuming a lot of memory (more than 10GB). I want to get rid of minio and switch to cloud but with a bucket per execution it's not feasible.

**Comment by TheBrunoLopes** [comment]
Hello @kamilkrampa thanks for raising this. We are working on this right now.
Should be done in a week.

**Comment by kamilkrampa** [comment]
@nicufk It doesn't work for container executor. It still creates a new bucket per execution.

**Comment by kamilkrampa** [comment]
@nicufk I'm able to download the file from the UI but the content of it is broken
```
{"type":"about:blank","title":"Internal Server Error","status":500,"detail":"minio DownloadFile error: minio Download File Stat error: The specified key does not exist., error from getting files from former bucket per execution: \u003cnil\u003e, context: null"}
```

I checked the file in minio and the content is correct there.
