### ISSUE TITLE
Add helm values to allow resource specification for all components

### ISSUE THREAD

**Issue by crdnb** [kubeshop/testkube#2943]
**Describe the enhancement you'd like to see**
Testkube is great and the helm values allow to configure many options already. For lots of components it is already possible to specify resources (cpu and memory limits and requests).

For the following components / pods there is no resource configuration possible within helm values at the moment (or at least I did not find it):
- pod "release-name-nats-test-request-reply"
- pod "testkube-api-server-test-connection"
- pod "testkube-operator-test-connection"
- sts "release-name-nats"
- deployment "release-name-nats-box"
- deployment "testkube-minio-col-testkube-test"
- deployment "testkube-operator-controller-manager"
- job "webhook-cert-patch"
- job "webhook-cert-create"
- job "mongodb-upgrade"
- jobtemplate for executor jobs
- jobtemplate for scraper jobs

It would be great to have the ability to configure compute resources also on these components, so that Testkube would also run on clusters where resource specification is mandatory.

Thank you very much for your great work!

**Comment by vsukhin** [comment]
thank you @crdnb totally makes sense. we also need to check that all of them are used, jobtemplate for executors are already supported by Test CRD, sounds like we need to add a CRD field for scraper template

**Comment by ypoplavs** [comment]
Hello @crdnb, 

We have added an option for resource specifications for the missing `Testkube` components. However, we rely on an external `NATS` chart that can be accustomed to your needs with `--set` option. You can provide your own values for `sts` and `deployment` entities, however the option is missing for `test-request-reply` pod. I opened an issue to add that: https://github.com/nats-io/k8s/issues/627 

Please let us know in case of any issues.

**Comment by crdnb** [comment]
Hi @ypoplavs 

Thank you so much for adding the options and for opening the issue for the nats components!

Minio resouce definition is working now.

Currently I'm still facing problems with specifying resources on the proxy container of the testkube-operator-controller-manager pod. Can you tell me how to specify the resources for this container please?

I also still have problems with the jobs "mongodb-upgrade" and "webhook-cert-create" but I'll double check these two tomorrow.

For test jobs I'm defining the resources via job-template currently, as I don't know a helm value to set their resources yet.

Thank you!

**Comment by ypoplavs** [comment]
Hello @crdnb,
We have updated `proxy` container of the `testkube-operator-controller-manager` pod so now you can find resource specification here:
```
testkube-operator:
  proxy:
    resources: {}
```
Please try and let me know about the results.

As for test jobs - yes, you have to define them via job-template.
