### ISSUE TITLE
Support for mounting configmaps and secrets as files into test containers

### ISSUE THREAD

**Issue by crdnb** [kubeshop/testkube#2948]
**Is your feature request related to a problem? Please describe.**
We have lots of container based tests and they all depend on configmaps and secrets. All of them need envFrom as already requested within this feature request: https://github.com/kubeshop/testkube/issues/2822
Lot's of them also have configmaps and secrets mounted as files into the container. 

**Describe the solution you'd like**
Support "envFrom" for all keys of secrets and configmaps
Support for mounting secrets and configmaps as files

**Describe alternatives you've considered**
Building the configmaps and secrets as files into the container image --> worst practice

**Additional context**
Add any other context, CLI input/output, etc. about the feature request here.

**Comment by TheBrunoLopes** [comment]
AC:
- Allow users to map secrets & config maps into the new refactored Variables.
- Allow mapping/coppying files from secrets/config maps as files inside the execution pod.
