### ISSUE TITLE
Test execution failing while using Secret Variable

### ISSUE THREAD

**Issue by oreintedvikas** [kubeshop/testkube#2955]
**Describe the bug**
We need to use postman collection and pass the uri using variables.
I used following command to execute the test:
kubectl testkube run test kubeshop-test-param --secret-variable ourteam="our-team"

And I am getting below error:
Test execution failed:

⨯ process error: exit status 1
newman

Kubeshop

→ Home
  ┌
  │ 'uri', undefined
  └
  GET https://kubeshop.io/ [200 OK, 45.51kB, 216ms]
  ✓  Body matches string

→ Team
  GET https://kubeshop.io/*****

**To Reproduce**
Commands provided in screenshots section

**Expected behavior**
Passed variable with test run command should be used in postman collection and replace with provided value.

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
**command to create test**
kubectl testkube create test --file .\kubeshop_requestParamvar.json --name kubeshop-test-param type postman/collection

**Definition in testkube UI:**
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: kubeshop-test-param
  namespace: testkube
spec:
  type: postman/collection
  content:
    type: string
    data: "{\n\t\"info\": {\n\t\t\"_postman_id\": \"78f82a7a-c347-4716-bef8-08f42108e727\",\n\t\t\"name\": \"Kubeshop\",\n\t\t\"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\"\n\t},\n\t\"item\": [\n\t\t{\n\t\t\t\"name\": \"Home\",\n\t\t\t\"event\": [\n\t\t\t\t{\n\t\t\t\t\t\"listen\": \"test\",\n\t\t\t\t\t\"script\": {\n\t\t\t\t\t\t\"exec\": [\n\t\t\t\t\t\t\t\"pm.test(\\\"Body matches string\\\", function () {\",\n\t\t\t\t\t\t\t\"    pm.expect(pm.response.text()).to.include(\\\"Accelerator\\\");\",\n\t\t\t\t\t\t\t\"});\"\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"type\": \"text/javascript\"\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"listen\": \"prerequest\",\n\t\t\t\t\t\"script\": {\n\t\t\t\t\t\t\"exec\": [\n\t\t\t\t\t\t\t\"console.log(\\\"uri\\\", pm.environment.get(\\\"kubeshop_uri\\\"));\"\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"type\": \"text/javascript\"\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t],\n\t\t\t\"request\": {\n\t\t\t\t\"method\": \"GET\",\n\t\t\t\t\"header\": [],\n\t\t\t\t\"url\": {\n\t\t\t\t\t\"raw\": \"https://kubeshop.io/\",\n\t\t\t\t\t\"protocol\": \"https\",\n\t\t\t\t\t\"host\": [\n\t\t\t\t\t\t\"kubeshop\",\n\t\t\t\t\t\t\"io\"\n\t\t\t\t\t],\n\t\t\t\t\t\"path\": [\n\t\t\t\t\t\t\"\"\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t},\n\t\t\t\"response\": []\n\t\t},\n\t\t{\n\t\t\t\"name\": \"Team\",\n\t\t\t\"event\": [\n\t\t\t\t{\n\t\t\t\t\t\"listen\": \"test\",\n\t\t\t\t\t\"script\": {\n\t\t\t\t\t\t\"exec\": [\n\t\t\t\t\t\t\t\"hostName1 = pm.environment.get(\\\"kubeshop_uri\\\");\",\n\t\t\t\t\t\t\t\"console.log(\\\"hostName1 is \\\", hostName1);\",\n\t\t\t\t\t\t\t\"pm.test(\\\"Status code is 200\\\", function () {\",\n\t\t\t\t\t\t\t\"    pm.response.to.have.status(200);\",\n\t\t\t\t\t\t\t\"});\"\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"type\": \"text/javascript\"\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"listen\": \"prerequest\",\n\t\t\t\t\t\"script\": {\n\t\t\t\t\t\t\"exec\": [\n\t\t\t\t\t\t\t\"\"\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"type\": \"text/javascript\"\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t],\n\t\t\t\"request\": {\n\t\t\t\t\"method\": \"GET\",\n\t\t\t\t\"header\": [],\n\t\t\t\t\"url\": {\n\t\t\t\t\t\"raw\": \"https://kubeshop.io/{{ourteam}}\",\n\t\t\t\t\t\"protocol\": \"https\",\n\t\t\t\t\t\"host\": [\n\t\t\t\t\t\t\"kubeshop\",\n\t\t\t\t\t\t\"io\"\n\t\t\t\t\t],\n\t\t\t\t\t\"path\": [\n\t\t\t\t\t\t\"{{ourteam}}\"\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t},\n\t\t\t\"response\": []\n\t\t}\n\t]\n}"

**command to execute test**
kubectl testkube run test kubeshop-test-param --secret-variable ourteam="our-team"
**Additional context**
If I create the variable in testkube UI. It works fine but we need to pass this variable with testkube run command as part of autmation testing.

**Comment by vsukhin** [comment]
Hey, @oreintedvikas From what I see in your test in this statetment `["console.log("uri", pm.environment.get("kubeshop_uri"));"]`, you didn't define `kubeshop_uri` variable, not `outstream` one

**Comment by oreintedvikas** [comment]
@vsukhin  Thanks for your reply. I will do the further corrections. We can resolve this now. But I think we got it now I needed to use --variable in test run command rather than  --secret-variable.
kubectl testkube run test kubeshop-test-param --variable ourteam="our-team"

→ Home
  ┌
  │ 'uri', undefined
  └
  GET https://kubeshop.io/ [200 OK, 45.51kB, 200ms]
  ✓  Body matches string

→ Team
  GET https://kubeshop.io/our-team [200 OK, 8.96kB, 175ms]
  ┌
  │ 'hostName1 is ', undefined
  └
  ✓  Status code is 200

┌─────────────────────────┬────────────────────┬────────────────────┐
│                         │           executed │             failed │
├─────────────────────────┼────────────────────┼────────────────────┤
│              iterations │                  1 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│                requests │                  2 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│            test-scripts │                  2 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│      prerequest-scripts │                  2 │                  0 │
├─────────────────────────┼────────────────────┼────────────────────┤
│              assertions │                  2 │                  0 │

**Comment by vsukhin** [comment]
Welcome @oreintedvikas Let us recheck secret variable case after holidays

**Comment by vsukhin** [comment]
reproduced,checking
