### ISSUE TITLE
Unable to open old execution details by URL

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#2962]

**Comment by PunkSage** [comment]
@pavloburchak Can you give a little bit more context on this issue?

**Comment by PunkSage** [comment]
Steps to reproduce:

1. Visit: https://demo.testkube.io/tests/executions/artillery-executor-smoke-negative (or any other test)
2. Change filter to Last 30 days
3. Go to the last page
4. Select the last execution
5. Open it up
6. It displays the execution correctly
7. Copy the url pointing to the execution
8. Open the url in the another tab

Expected result:

The same information about the execution should be displayed on another card

Actual result:

The error is thrown ‘Provided execution does not exist’

**Comment by PunkSage** [comment]
Ok, quick steps to reproduce:

1. Open https://demo.testkube.io/tests/executions/artillery-executor-smoke-negative
2. Change filter to Last 30 days
3. Go to the last page
4. Select the last execution
5. Open it up
6. It displays the execution correctly
7. Copy the url pointing to the execution
8. Open the url in the another tab

Expected result:

The same information about the execution should be displayed on another card

Actual result:

The error is thrown ‘Provided execution does not exist’
