### ISSUE TITLE
UI - Define process od extracting common parts od Testkube Cloud/OSS

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2983]
As currently we're working between Cloud and OSS UI by just copying the code from the OSS UI to Cloud UI. 

As it worked on the beginning of the project we would need to have more scalable process.

DoD: 
- Define process of of splitting the code into libraries/components
- Keep in mind that code injected from OSS must be easily adapted to incoming features e.g. adding new data to some tables, new additional fields on grids, additional validations, additional UI elements on views etc,

**Comment by haneabogdan** [comment]
Possible solutions:

1. Shared component library hosted in a remote registry:

- Separate git repository to host only the component library
- Component library within the OSS git repo. Using a monorepo to host both OSS and component library. The library can be built as an npm module and used by the cloud project. (using Lerna as monorepo solution)

2. Git submodules

3. bit.dev

OOTB solution to create a component library and manage dependencies. Can provide also hosting of the npm module ($$)

4. Microfrontends

We could treat the OSS UI (or parts of it) as a microfrontend, and integrate it into the cloud UI

**Comment by rangoo94** [comment]
Done with https://github.com/kubeshop/testkube/issues/3695
