### ISSUE TITLE
Setting variables in tests causes Artillery Executor to fail

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#3000]
Running an Artillery test after adding variables causes the following error:
![image](https://user-images.githubusercontent.com/17077/211119299-5b9c8a52-2a89-451c-9ebf-0c2445f3f6d8.png)

![image](https://user-images.githubusercontent.com/17077/211119314-9f55e714-76cf-4b0c-829e-1c4e06bfe248.png)

**Comment by vLia** [comment]
Thanks for reporting this, @blevinson !
Managed to reproduce it in my local environment. Looking into the code now, will let you know once it is fixed.

**Comment by vLia** [comment]
This bug should have been fixed on the newest version of the artillery executor (0.0.22), helm chart version 1.8.58. Please upgrade your installation and let us know if there are any further issues.

**Comment by blevinson** [comment]
This has been working for variables and secrets. Great job!
