### ISSUE TITLE
container executor: a slack message is not sent on the test failure

### ISSUE THREAD

**Issue by kamilkrampa** [kubeshop/testkube#3009]
**Describe the bug**
When using container execturo, a slack message is not sent on the test failure

**To Reproduce**
1. Create a test which uses container executor. 
2. Set slack config to send a message on `end-test-failed` on the test failure
3. Run the test. Make sure execution fails.
4. `end-test-success` is emitted despite the test execution failed. Slack messages is not send.

**Expected behavior**
end-test-failed should be emitted

**Version / Cluster**
- Which testkube version? 
1.8.19
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
GKE
- What Kubernetes version?
v1.24.2

**Comment by nicufk** [comment]
Hey @kamilkrampa can you check what version are the version components on the cluster, we had this bug before and it was fixed. Here: https://github.com/kubeshop/testkube/pull/2961

**Comment by kamilkrampa** [comment]
Server Version v1.8.19

**Comment by kamilkrampa** [comment]
https://github.com/kubeshop/testkube/blob/main/pkg/executor/containerexecutor/containerexecutor.go#L422 - isn't this sending success regardless of the test status?

**Comment by kamilkrampa** [comment]
Hey, any chance to have this merged soon?
