### ISSUE TITLE
Artifact for testsuite

### ISSUE THREAD

**Issue by yarden-slon** [kubeshop/testkube#3010]
When running a testsuite, I want to run a command of:
```
kubectl get artifacts <test_suite_execution_id>
```
And get all the artifacts that relate to that testsuite.
Currently, I need to go to every test in the testsuite and get the execution id of the test.

**Comment by vsukhin** [comment]
Thank you @yarden-slon. Definitely miised feature. Probably, we will add in next release @TheBrunoLopes?

**Comment by TheBrunoLopes** [comment]
Hey @yarden-slon this seems like a useful feature that's quick to implement. Will add for the next release.
