### ISSUE TITLE
Dashboard: edit my tests from the dashboard

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3018]
**Is your feature request related to a problem? Please describe.**
When I added a test from the UI, I made a mistake with the test definition. Then when it failed I had to create 5 new tests until I got it to work.

**Describe the solution you'd like**
I would love to be able to edit the test configuration (git repo, etc) and the test definition.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fivenp** [comment]
Figma mocks for this are available over here: 

https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=2511%3A81227&t=NFsOIoDNWrw0l8UJ-4
