### ISSUE TITLE
Once logged in in Cloud, provide a list of repos instead of having to introduce it myself

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3019]
**Is your feature request related to a problem? Please describe.**
When I logged in in Cloud, I had to use my Github account. 

But when creating a new test, I had to create a github token, had to copy git URL etc. when Testkube Cloud already has permission to my repo. 

<img width="454" alt="CleanShot 2023-01-12 at 12 42 43@2x" src="https://user-images.githubusercontent.com/27779735/212019241-611413a3-2c22-414d-b793-c40076637f81.png">

**Describe the solution you'd like**
I want to be able to select my repo from a dropdown like Monokle or Vercel so I don't have to do the steps (and make mistakes like I already did): 

<img width="659" alt="CleanShot 2023-01-12 at 12 37 36@2x" src="https://user-images.githubusercontent.com/27779735/212018084-6194a50c-5e86-48e4-918a-42f3e2d7f1a9.png">

<img width="719" alt="CleanShot 2023-01-12 at 12 37 57@2x" src="https://user-images.githubusercontent.com/27779735/212018172-82e4c329-eea4-418d-b25c-ad938267d346.png">

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by aabedraba** [comment]
Perhaps could be solved by using https://github.com/octokit/octokit.js/

**Comment by rangoo94** [comment]
Closing it here, as it's a part of our Cloud's roadmap.
