### ISSUE TITLE
Provide a retry agent connection button

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3020]
**Describe the enhancement you'd like to see**
Once I installed the Testkube agent in my cluster, in the Cloud Dashboard it still says that the agent is not connected. This makes me refresh the website every time.

I would love to have a retry connection button and a suggestion to wait for 2 minutes until the agent wakes up. Perhaps even put a link for documentation on how to debug the agent connection. 

<img width="1275" alt="CleanShot 2023-01-12 at 12 39 28@2x" src="https://user-images.githubusercontent.com/27779735/212019068-05ab28ff-d34b-48e2-b91e-1d7b87ce6a93.png">

**Comment by rangoo94** [comment]
I don't believe that there is a need to change the behavior, as we are checking the status in real time. @fivenp, should we just reword this message to mention somehow that we're checking that all the time?

**Comment by aabedraba** [comment]
Thanks for checking on an old ticket :) 

@fivenp I really like the suggestion. Any ideas on how we could word this?

**Comment by fivenp** [comment]
... successfully. We will automatically refresh this view once everything is fine.  Manage your.....
