### ISSUE TITLE
Remove fixed header and filters and add loader below tests list

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#3025]
* Make the header and filters on "Tests" and "Test Suites" not fixed to the top of the screen
* Add loader below "Tests" and "Test Suites" list, when the next entities are loading via Infinite Scroll

**Comment by rangoo94** [comment]
@pavloburchak, I would like to confirm if the scope of the task is:

* Make the filters on "Tests" and "Test Suites" not fixed to the top of the screen (below header)
* Add loader below "Tests" and "Test Suites" list, when the next entities are loading via Infinite Scroll

Is that right?

**Comment by pavloburchak** [comment]
@rangoo94 yes, exactly!

**Comment by rangoo94** [comment]
Thanks @pavloburchak, I updated the task description, and have already created the PR :)
