### ISSUE TITLE
Can't create TestTriggers in Testkube Dashboard

### ISSUE THREAD

**Issue by blevinson** [kubeshop/testkube#3027]
When I try to create a new trigger in the Testkube Dashboard, I get the following error:

![CleanShot 2023-01-13 at 02 18 56](https://user-images.githubusercontent.com/17077/212269562-1fd7ac50-6f2a-444a-ae16-750a2049eefb.png)

In the console, I get the following:

![CleanShot 2023-01-13 at 02 22 04](https://user-images.githubusercontent.com/17077/212270219-a7f93496-e93e-4386-ac8b-c41cdcbf3cfc.png)

**Comment by vsukhin** [comment]
At least, you should path trigger-name as a part of uri, `/v1/triggers/my-trigger`

**Comment by pavloburchak** [comment]
@blevinson could you please provide more details and steps to reproduce. But first, try to update `testkube`.
If error still happening, please provide what is in logs
`kubectl logs testkube-api-server -n testkube`

**Comment by pavloburchak** [comment]
@blevinson please let me know if you can still see this issue. For now I will close it.
