### ISSUE TITLE
Add support sub-path for work on a single domain

### ISSUE THREAD

**Issue by batazor** [kubeshop/testkube#3043]
**Describe the enhancement you'd like to see**

I want to use **testkube** by path `domain.com/testkube/*` and don't create a new domain for this service

**Additional context**
-

**Comment by rangoo94** [comment]
Hey, @batazor!

The dashboard container supports that, and the path is controlled with a `REACT_APP_ROOT_ROUTE` environment variable (i.e. `/testkube` in this case).

I'm not sure what is your setup, but if you're using our Helm charts - [**`ingress.path` value**]((https://github.com/kubeshop/helm-charts/blob/3ec9d60ffc567162f5765f882756e9ae4593a7b5/charts/testkube-dashboard/values.yaml#L105-L106)) could help you to configure it.

Does it help you?

**Comment by rangoo94** [comment]
Actually, looks like there is [**a bug**](https://github.com/kubeshop/testkube/issues/2952), and we are missing the `<base>` tag.

**Comment by batazor** [comment]
@rangoo94 I ended up running the service on a separate domain.
I think we can close this tab in favor of #2952
