### ISSUE TITLE
Show only the allowed Test source type that each executor allows

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#3050]
Right now we allow people to select a test type (executor) and select a source for their test when creating a test. 

The issue with this is that some executors DO NOT support specific test sources. 

E.g. 
* Cypress does NOT support Git File as a test source

## Fix

Let's just show the test sources which do work with the selected executor. 

E.g. 
* a user selects the Cypress executor
* that user can only select these test sources
  * Git source: (custom git source)
  * Git directory
  
  
## Matrix table 

We will need to fill this table – cc @tkonieczny + @aabedraba 

| Executor  | Custom Test Source | Git Directory | Git File | File | String |
|-----------|-------------|---------------|----------|------|--------|
| Custom executor   | X           | X             | X        | X    | X      |
| Cypress   | X           | X             | -        | -    | -      |
| Postman   | X           | X             | X        | X    | X      |
| K6        | X           | X             | X        | X    | X      |
| curl      | X           | X             | X        | X    | X      |
| SoapUI    | X           | X             | X        | X    | -?      |
| Artillery | X           | X             | X        | X    | -?      |
| KubePug   | X           | X             | X        | X    | -?      |
| Maven     | X           | X             | ?        | ?    | -?      |
| Gradle    | X           | X             | ?        | ?    | -?      |
| Ginkgo    | X           | X             | ?        | ?    | -?      |
| JMeter    | X           | X            | X        | X    | -?      |

**Comment by tkonieczny** [comment]
I filled in the table, but some of the values are still missing. If you have some valid cases for Git File, File, or String please extend it.

**Comment by vasireddi78** [comment]
Hi,

can you check Jmeter Executor supports Git or  Git-directory ? I am testing with latest version of testkube / Jmeter and getting following error in test execution:

✅ Initialization successful
0xc000917c30
🚚 Preparing test runner
🌍 Reading environment variables...
✅ Environment variables read successfully
RUNNER_ENDPOINT="testkube-minio-service-testkube:9000"
RUNNER_ACCESSKEYID="********"
RUNNER_SECRETACCESSKEY="********"
RUNNER_LOCATION=""
RUNNER_TOKEN=""
RUNNER_SSL=false
RUNNER_SCRAPPERENABLED="true"
RUNNER_GITUSERNAME="xxxxx"
RUNNER_GITTOKEN="********"
RUNNER_DATADIR="/data"
running test [xxxxx]
🚚 Running with config [scraperEnabled true dataDir /data SSL false endpoint testkube-minio-service-testkube:9000]
📦 Fetching test content from git...
❌ Unhandled content type: 'git'
unhandled content type: 'git'

I need to copy entire directory into \data folder as the Jmeter script has multiple input data files.

Thank you !

**Comment by tkonieczny** [comment]
Is the jmeter executor image up to date? We have a test with `git` content type - everything looks fine there:
https://demo.testkube.io/tests/executions/jmeter-executor-smoke

**Comment by tkonieczny** [comment]
@TheBrunoLopes I think we never tried running JMeter test with multiple files before. Similar "edge-case" as K6 and git directory.

**Comment by vasireddi78** [comment]
Hi @vsukhin 
Tested with latest image of Jmeter executor , but it is only copying one file and not copying the data files inside the git repo or folder.
