### ISSUE TITLE
Transition away from git-dir and git-file to git

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#3063]
**Describe the enhancement you'd like to see**
We want to move away from `git-dir` and `git-file` definitions towards having only `git` as a source.

To make this happen we will need (please make sure to have this ticket pass through all stages :)):

1. Backend to have synonyms working for all 3 options (to keep backwards compatibility)
2. Remove git-dir and git-file from any frontend piece and API call (e.g. test creation/edit select box + api call, sources creation/edit, etc)
3. Make sure all the executors will still work properly with git and then 
a) a folder passed as path and 
b) a file passed as path
4. Update documentation related to this topic and adapt to "git" only everywhere
5. Make sure new CRDs are fine

**Comment by TheBrunoLopes** [comment]
AC:
- don't break compatibility with git-dir and git-file.
- now there's only git shown for new tests.

**Comment by vsukhin** [comment]
@TheBrunoLopes @fivenp 
This ticket needs to be rethought. It's true, that for git it doens't matter either the source is file or dir
But it does really matter for executors a lot.
So from one side, it's a hint for our users, what exactly an executor expects from the test source,
from other side an executor has different implementation for git-file and git-dir processing.
And some executors support only git-dir like cypress, other ones only git-file like postman
The ones who support them both like k6, might have different logic for each case.
In fact, current classification is a compressed version of the real difference between sources

sourceType:
- string
- uri
- git

structureType:
- file (single object)
- dir (multiple object)

Becuase string and uri are always files, we just combined git with structure types: git-file and git-ditr

**Comment by TheBrunoLopes** [comment]
I'm not sure I understand the "really matter for executors a lot." point.
If the user specifies a directory in one field (path) why would he say it again that it's a directory in another field "git-dir/file". Our system can read whatever the user gives it and ascertain what it is. i.e., if it's a file or a dir.
Regarding the user knowing what's being expected for each executor. That's the job of tooltips and validations.
Do you agree ?

**Comment by tkonieczny** [comment]
Tests added in https://github.com/kubeshop/testkube/pull/3298
