### ISSUE TITLE
UI: Error page when running test via Dashboard after creation

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#3068]
**Describe the bug**
After creating a test via CLI, opening it in the dashboard and running the test with it an error page is displayed. This error page disappears after some time and reloading the page.

**To Reproduce**
1. Create a test with `testkube create test..`, e.g. in my case postman test with git file as content and various secret and basic variables
2. Open Dashboard
3. Click on newly created test
4. Click on run this test now
5. Error page appears, see screenshot below

**Expected behavior**
Standard page test is shown with running test

**Version / Cluster**
- Client Version 1.8.30
- Server Version v1.8.30

**Screenshots**
![grafik](https://user-images.githubusercontent.com/54187283/213397339-915fc02a-9a16-4baa-9686-4ad204612575.png)

**Comment by TheBrunoLopes** [comment]
I was also able to reproduce it just using the UI to create a test in demo.testkube.io

**Comment by tkonieczny** [comment]
I usually have to refresh the Dashboard even a dozen times after every test creation.

**Comment by TheBrunoLopes** [comment]
i think @pavloburchak was working on this last week.
How's this going ?
