### ISSUE TITLE
Test stuck in state running despite container and job completed

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#3070]
**Describe the bug**
After upgrading testkube from 1.8.16 to 1.8.29, my custom executor does not work correctly anymore. After the pod and job in the cluster are terminated/completed, the UI and CLI of Testkube show status "running".

**To Reproduce**
1. Upgrade testkube from 1.8.16 -> 1.8.29 or Testkube Helm Chart from 1.8.51 -> 1.8.100
2. Run a test with a executor based on executor template which was working correctly before
3. Test is stuck in state "Running" forever in CLI and UI and only stops after aborting

**Expected behavior**
Test is terminated and shows success/fail after pod and job is terminated

**Version / Cluster**
Could fix this problem after Downgrading to 1.8.16(Server Version)/1.8.51(Helm Chart Testkube)
Issue occured for me from 1.8.29 (Server)/1.8.100(Helm Chart) upwards (tested also with 1.8.30/1.8.104)

**Comment by vLia** [comment]
Hello @f-helm, thanks for reporting this issue.
There was a problem with Test statuses being computed from the logs when the logs are not in order in the pod. This issue has been fixed by checking the timestamps in the logs.
Just to make sure, in your custom executor, are you using `agent.Run(...)` from the latest Testkube version? Example: https://github.com/kubeshop/testkube-executor-soapui/blob/main/cmd/agent/main.go#L19

**Comment by vLia** [comment]
For what it's worth, I managed to reproduce the issue on the zap executor. I will add an additional check for the exit code of the pod to determine the status of an execution. Will let you know once that fix is out.

**Comment by f-helm** [comment]
HI @vLia, thanks for the reply and investigation. I am using the same code you provided from SOAPUI Executor with `agent.Run(..)` except of course I import my own runner. 
Will stay on the currently working testkube version for the time being.

**Comment by f-helm** [comment]
I did some investigating and upgraded the dependencies of my executor, including testkube to v1.8.31 and added the `GetType` Function to my runner ([found here](https://github.com/kubeshop/testkube-executor-template/blob/0aee794d870db842bc120e8b7c911cff6a2f7cc4/pkg/runner/runner.go#L58-L61)). 
This solved the issue and executor now works again with Testkube 1.8.31.

**Comment by f-helm** [comment]
I am not sure if I should close this ticket because breaking changes like this are expected and executors are to be updated regularly?

**Comment by tkonieczny** [comment]
@vLia I think there are 2 different cases here:
- Some of the tests keeps running forever, the result is unclear - this issue
- If the test isn't marked finished, and the result is unclear the TestSuite is still marked as successful: https://github.com/kubeshop/testkube/issues/3071

Even if these issues may be technically related I would keep them separate - just to make sure everything is tracked, and not to miss something.


**I was able to reproduce this issue** and we have multiple tests that are marked as `running` forever - both at demo, and Cloud:
- maven-executor-smoke-jdk18
- maven-executor-smoke-jdk11
- cypress-11-executor-smoke-firefox
- cypress-11-executor-smoke-chrome
- cypress-11-executor-smoke-electron

You can find CRDs for all of these here: https://github.com/kubeshop/testkube/tree/main/test
Additionally executor CRDs are here: https://github.com/kubeshop/testkube/tree/main/test/executors

**Comment by vLia** [comment]
Hello @tkonieczny and @f-helm,

Just released a fix for the status issue: Testkube version 1.8.33, helm-charts 1.8.118.

@tkonieczny I re-ran the tests on demo, but please double-check if this still persists.

**Comment by tkonieczny** [comment]
Everything looks ok now
