### ISSUE TITLE
Test and TestSuite results should default to `failed` - unless they are `success`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3072]
**Describe the enhancement you'd like to see**
Test and TestSuite results should **always** default to `failed` - unless everything is successful (to mark it as `success`). Test accidentally marked as failed may only be confusing/frustrating, but the one that failed marked as `passed` is critical.

The goal is to prevent issues like https://github.com/kubeshop/testkube/issues/3023 or https://github.com/kubeshop/testkube/issues/3071 from happening.
Additional tests for negative cases and edge-cases will be introduced after https://github.com/kubeshop/testkube/issues/2482

**Comment by TheBrunoLopes** [comment]
Appears to be done. Closing it
