### ISSUE TITLE
ZAP executor: execution fails

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#3082]
**Describe the bug**
Running the ZAP executor with the examples in the repository fails with error message.

**To Reproduce**
1. Clone official ZAP executor repo from [github](https://github.com/kubeshop/testkube-executor-zap)
2. Add executor as described in README `kubectl apply -f examples/zap-executor.yaml`
3. Add test in cluster with `kubectl testkube create test --file examples/zap-api.yaml --type "zap/api" --name api-test`
4. Run test 
5. See error log in container 
```
{"type":"event","content":"Running [ ./zap-api-scan.py [-t https://www.example.com/openapi.json -f openapi -c examples/zap-api.conf -d -D 5 -I -l INFO -n examples/context.config -S -T 60 -U anonymous -O https://www.example.com -z -config aaa=bbb -r api-test-report.html]]"}
{"type":"result","result":{"status":"failed","errorMessage":"could not start process: fork/exec ./zap-api-scan.py: no such file or directory"}}
```

**Expected behavior**
Execution is successful and container does not exit with error message

**Version / Cluster**
- Which testkube version? Client Version 1.8.30, Server Version v1.8.32

**Comment by vsukhin** [comment]
thank you @f-helm We didn't really test it out. Have plans about integrating it with standard list of Testkube executors in coming releases
