### ISSUE TITLE
Add "Reason" to trigger condition checks

### ISSUE THREAD

**Issue by scott-david-walker** [kubeshop/testkube#3092]
**Describe the enhancement you'd like to see**

As a part of #2905, a check is in place to see if a resource is "ready" before triggering a test(suite). This works well, but there is an issue with deployments in that if you have a minimum number of replicas, a pod is created before an old one is terminated. If this is the case then the deployment never leaves the "ready" state so it is triggered immediately.

It would be ideal to have another condition such as "reason" that allows us to determine exactly when a trigger should run. Perhaps even a delay field to ensure it doesn't pick the initial ready state?

**Comment by vsukhin** [comment]
@scott-david-walker delay is already implemented for triggers https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/tests.testkube.io_testtriggers.yaml#L82
reason is in progress
