### ISSUE TITLE
Dashboard lagging behind CLI - after Test Edit

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3105]
Dashboard is lagging behind CLI, and CRD. Until now, even if the test has been created with CLI using options not available in Dashboard it wasn't a problem - it was only possible to view/run this test in Dashboard after all. Now, when edit test feature is available it can cause issues.

Examples:
- `-git-commit`. In case of CLI and git-file/git-dir content type, `--git-branch`, or `--git-commit` can be set. In case of Dashboard only git branch can be set, and it's required. So, it can cause problems if I already set git commit while creating test with CLI #3157
- https://github.com/kubeshop/testkube/issues/3097
- CRON triggers for Test and Testsuite #3156
- prerun-script #3155

**Comment by fivenp** [comment]
some questions here: 

## `-git-commit` 

* Is it possible to use git branch AND git commit at the same time? (that doesn't really make sense?)
* What happens if I specify both? (if we don't fail – which one has priority?)

## CRON triggers for Test and Testsuite

do you have a sample CRD for this? 

## prerun-script 

do you have a sample CRD here? 
when does this script exactly get executed?

**Comment by tkonieczny** [comment]
It's not possible to use both git branch and git commit:
```
$ testkube create test --name jmeter-test-demo-8 --type jmeter/test --test-content-type git-file --git-uri https://github.com/kubeshop/testkube.git --git-branch main --git-commit 9e9553fd9f7f771cc3edb33910b68ce81a53ebea --git-path test/jmeter/executor-tests/jmeter-executor-smoke.jmx

validating passed flags (error: please pass only one of `--git-branch` or `--git-commit`)```

Cron triggers - test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: jmeter-test-demo-8
  namespace: testkube
spec:
  type: jmeter/test
  content:
    type: git-file
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/jmeter/executor-tests/jmeter-executor-smoke.jmx
  schedule: "*/1 * * * *"
```
Cron triggers - testsuite:
```
apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: executor-artillery-smoke-tests
  namespace: testkube
  labels:
    app: testkube
spec:
  description: "artillery executor smoke tests"
  steps:
  - execute:
      stopOnFailure: false
      name: artillery-executor-smoke
  - execute:
      stopOnFailure: false
      name: artillery-executor-smoke-negative
  schedule: "56 */4 * * *"
```

Prerun-script - I haven't tried it yet

**Comment by rangoo94** [comment]
@tkonieczny, looks like we have all points covered - should the ticket be closed?
