### ISSUE TITLE
`testkube create` with flag `--crd-only` should create CRDs from folders 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3125]
Current `testkube generate test-crds` works with Postman directories that have multiple tests.

This functionality might not be available for `testkube create test --crds-only`

Ideally we would want to only have `testkube create test --crds-only` and deprecate `testkube generate test-crds` once we have feature parity.

**Comment by aabedraba** [comment]
The user story: 
- Users want to use testkube commands in their GitOps pipelines to automatically generate tests once committing a specific test type to git

The problem:
- `testkube generate` is different from `testkube create`
- `testkube generate` only supports curl, K6 and Postman in *detection mode* (i.e. no way to specify the type with --type) 
- `testkube generate` is missing [`testkube create test` flags]( https://github.com/kubeshop/testkube/blob/main/cmd/kubectl-testkube/commands/crds/tests_crds.go#L25-L29), like `--name`, `--label`, `--prerun-script`, `--image`... 
- `testkube generate` doesn't support testsuites
**- `testkube create test --crds-only` output contains stuff other than the CRD.** 

The constraint: 
- As we have supported directory detection with `testkube generate`, some users started using it, so we need to keep it 

Possible solution: 
- We include directory detection to `testkube create test` and clean the output of `--crds-only`. We also deprecate `testkube generate`
- We add all functionality of `testkube create test` to `testkube generate`

**Comment by TheBrunoLopes** [comment]
cc: @fivenp

**Comment by fivenp** [comment]
I prefer  Option 2 quite a lot because it separates concerns and use cases clearly

If we'd go for Option 1 then we would always have mixed journeys. (e.g. I want to create a specific test vs. I want to create a test from a folder vs. I want to only have CRDs)
