### ISSUE TITLE
Github Oauth2 CORS support in Testkube

### ISSUE THREAD

**Issue by ypoplavs** [kubeshop/testkube#3129]
We have an option to enable GH Oauth2 to protect access to TK UI. However, GH Oauth2 doesn't support CORS which makes creation of tests to fail with the error:

`Access to fetch at 'https://github.com/login/oauth/authorize?approval_prompt=force&client_id=b526a903c0c801bd97a8&redirect_uri=https%3A%2F%2Foauth.testkube.io%2Foauth2%2Fcallback&response_type=code&scope=user%3Aemail&state=STWBNj9fJPS2Qhq7f6XlRGS_tIsXNxRBMTdVAmWwzEM%3A%2Fresults%2Fv1%2Ftests%2Fkjl%2Fexecutions' (redirected from 'https://oauth.testkube.io/results/v1/tests/kjl/executions') from origin 'https://oauth.testkube.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`

`GET https://github.com/login/oauth/authorize?approval_prompt=force&client_id=b526a903c0c801bd97a8&redirect_uri=https%3A%2F%2Foauth.testkube.io%2Foauth2%2Fcallback&response_type=code&scope=user%3Aemail&state=STWBNj9fJPS2Qhq7f6XlRGS_tIsXNxRBMTdVAmWwzEM%3A%2Fresults%2Fv1%2Ftests%2Fkjl%2Fexecutions net::ERR_FAILED
`

Open issue: [330](https://github.com/isaacs/github/issues/330)

We need to find a workaround to resolve this.
Possible solutions: 
https://stackoverflow.com/questions/42150075/cors-issue-on-github-oauth 
https://andreybleme.com/2018-02-24/oauth-github-web-flow-cors-problem/

**Comment by TheBrunoLopes** [comment]
Any updates on this issue ?

**Comment by TheBrunoLopes** [comment]
Oauth2 works as read only for OSS without CORS support.
