### ISSUE TITLE
MongoDB SSL Secret Certificate Keys

### ISSUE THREAD

**Issue by Carlosgova** [kubeshop/testkube#3140]
**Describe the enhancement you'd like to see**

Currently the keys in the Secret containing all the necessary information to establish an SSL connection to the MongoDB instance are expected to be:
```
  sslCertificateAuthorityFile: <base64 encoded root-ca.pem>
  sslClientCertificateKeyFile: <base64 encoded mongodb.pem>
  sslClientCertificateKeyFilePassword: <base64 encoded password> 
```
As I'm using cert-manager to generate that secret, the keys are different , and cannot be changed. I would like to be able to use the Certificate generated by cert-manager for this purpose.

I see two possible options:
1. Configure the testkube-api helm chart Deployment to include the possibility of mounting Volumes, and mount the generated secret directly into the container's [expected paths](https://github.com/kubeshop/testkube/blob/main/cmd/api-server/main.go#L388-L389).
2. Allow to configure the keys of the SSL Secret on testkube-api to be able to set other than the values above.

**Comment by vsukhin** [comment]
Thank you @Carlosgova Second option looks straightforward

**Comment by vsukhin** [comment]
@vLia worth to merge with #3116 changes
