### ISSUE TITLE
Dashboard: Adding/Modifying variables through the dashboard adds additional double quotes to basic type variables

### ISSUE THREAD

**Issue by zepeng811** [kubeshop/testkube#3154]
**Describe the bug**
After upgrading to the latest version of testkube, I noticed all the tests fails as soon as I add/modify variables directly through Settings -> Variables and Secrets tab.

**To Reproduce**
1. Run a successful test that have at least one variable set that is relevant to the test
2. Use the `Variables and Secrets` Tab in the dashboard to add a dummy variable
3. Run the test again and see it fails

**Troubleshoot**
Troubleshoot it by directly looking into the mongo database, query the `variables` field from `results` collection for the specific test:
```
db.results.find({"testname" : "my-test"},{"variables":1}).pretty().limit(2)
``` 

for the first document (test executed from step 1), here's an example basic type variable
```
"ENV" : {
	"name" : "ENV",
	"value" : "testing",
	"type_" : "basic",
	"secretref" : null
},
```
for the second document (test executed from step 3), here's the output for the same variable:
```
"ENV" : {
	"name" : "ENV",
	"value" : "\"testing\"",
	"type_" : "basic",
	"secretref" : null
}
```
notice the additional `\"` double quotes added for the value.

**Expected behavior**
Additional double quotes should not be added to basic type variables, this is causing unexpected behaviours within the test and causing tests to fail.

**Version / Cluster**
- Which testkube version? 
  * helm chart version `1.9.26`, which correspond to api-server version `1.9.4` and dashboard version `1.9.0`

- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  * EKS
- What Kubernetes version?
  * 1.22
 
**Additional context**
I was also able to reproduce this bug using the [k6-executor-smoke-git-dir](https://demo.testkube.io/tests/executions/k6-executor-smoke-git-dir) test that is available on the demo server. Specially note test execution [#698](https://demo.testkube.io/tests/executions/k6-executor-smoke-git-dir/execution/63e2ec9f4ed2f9d5a9e9d321) and [#699](https://demo.testkube.io/tests/executions/k6-executor-smoke-git-dir/execution/63e2ecdb4ed2f9d5a9e9d327)

In 698, I executed a test without making any changes, and the test passed as expected, with this specific line from the log to note:
```
k6 run -e K6_SYSTEM_ENV=K6_SYSTEM_ENV_value -e K6_ENV_FROM_PARAM=K6_ENV_FROM_PARAM_value test/k6/executor-tests/k6-smoke-test.js
```
And then I added a variable called `DUMMY` with the value `dummy` and executed 699, and the test failed, and output this line:
```
k6 run -e K6_SYSTEM_ENV="K6_SYSTEM_ENV_value" -e DUMMY="dummy" -e K6_ENV_FROM_PARAM=K6_ENV_FROM_PARAM_value test/k6/executor-tests/k6-smoke-test.js
```
Notice that the `K6_SYSTEM_ENV` have a pair of extra double quotes compared to 698.

Last but not least, I deleted the `DUMMY` variable that I added and executed 700, which also failed, and have similar output to 699 showing the extra double quotes.

**Comment by vsukhin** [comment]
thank you @zepeng811 We will check it out

**Comment by tkonieczny** [comment]
Probably related to this issue: https://github.com/kubeshop/testkube/issues/2451

**Comment by pavloburchak** [comment]
@zepeng811 fixed this in latest dashboard version

**Comment by zepeng811** [comment]
@pavloburchak I can confirm I'm no longer seeing the issue using the latest dashboard version. Thank you for the extremely quick response and turnaround!
