### ISSUE TITLE
Downloading artifacts doesn't work

### ISSUE THREAD

**Issue by kamilkrampa** [kubeshop/testkube#3160]
**Describe the bug**
It's not possible to download artifacts through both CLI and the dashboard. 

**To Reproduce**
Make sure your testkube instance uses the single bucket for all artifacts.
1. Run any tests which produces artifacts
2. Go to the dashboard and try downloading an artifact, or try downloading it through CLI

Result:
On the dashboard, the file is downloaded successfully but the content is wrong
```
{"type":"about:blank","title":"Internal Server Error","status":500,"detail":"minio DownloadFile error: minio Download File Stat error: The specified key does not exist., error from getting files from former bucket per execution: \u003cnil\u003e, context: null"}
```

By using CLI, there is the following error
```
Getting artifacts count = 1 

downloading file:  (error: an error on the server ("unknown") has prevented the request from succeeding (get services testkube-api-server:8088))
```

**Expected behavior**
The file should be correctly downloaded and should contain the valid content.

**Version / Cluster**
- Which testkube version? 1.9.4
- What Kubernetes cluster? GKE
- What Kubernetes version? 1.24

**Additional context**
It's probably related to https://github.com/kubeshop/testkube/issues/2940

**Comment by nicufk** [comment]
Hey @kamilkrampa, I am checking it right now, have you tried to download file using CLI with only the name of the file without the id that comes before? Like this:

```
tk get artifacts 63e0d3dddd9a529fe0fa44f0
server version not set
  NAME                                | SIZE (KB)  
--------------------------------------+------------
  63e0d3dddd9a529fe0fa44f0/report.jtl |       704  
```
```

tk download artifact 63e0d3dddd9a529fe0fa44f0 report.jtl .
server version not set
File report.jtl downloaded.

```

**Comment by kamilkrampa** [comment]
it doesn't work for me in any way. Maybe I need some additional configuraiton 🤔

**Comment by kamilkrampa** [comment]
Logs from the api 
```
{"level":"info","ts":1675859489.117339,"caller":"minio/minio.go:254","msg":"Download file","bucket":"testkube-artifacts","bucketFolder":"63e2735e57648d7324c5fa14","file":"63e2735e57648d7324c5fa14/junit.xml"}
{"level":"info","ts":1675859489.1198997,"caller":"minio/minio.go:220","msg":"downloadFile","bucket":"testkube-artifacts","bucketFolder":"63e2735e57648d7324c5fa14","file":"63e2735e57648d7324c5fa14/junit.xml"}
{"level":"error","ts":1675859489.1236794,"caller":"server/httpserver.go:76","msg":"minio DownloadFile error: minio Download File Stat error: The specified key does not exist., error from getting files from former bucket per execution: <nil>","status":500,"stacktrace":"github.com/kubeshop/testkube/pkg/server.(*HTTPServer).Error\n\t/build/pkg/server/httpserver.go:76\ngithub.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).GetArtifactHandler.func1\n\t/build/internal/app/api/v1/executions.go:335\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945\ngithub.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).AuthHandler.func1\n\t/build/internal/app/api/v1/handlers.go:47\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942\ngithub.com/gofiber/fiber/v2/middleware/cors.New.func1\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/cors/cors.go:141\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945\ngithub.com/gofiber/fiber/v2/middleware/pprof.New.func1\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/pprof/pprof.go:41\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942\ngithub.com/kubeshop/testkube/pkg/server.(*HTTPServer).Init.func1\n\t/build/pkg/server/httpserver.go:46\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*App).handler\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:159\ngithub.com/valyala/fasthttp.(*Server).serveConn\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/server.go:2372\ngithub.com/valyala/fasthttp.(*workerPool).workerFunc\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:224\ngithub.com/valyala/fasthttp.(*workerPool).getCh.func1\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:196"}
```

**Comment by nicufk** [comment]
> Logs from the api
> 
> ```
> {"level":"info","ts":1675859489.117339,"caller":"minio/minio.go:254","msg":"Download file","bucket":"testkube-artifacts","bucketFolder":"63e2735e57648d7324c5fa14","file":"63e2735e57648d7324c5fa14/junit.xml"}
> {"level":"info","ts":1675859489.1198997,"caller":"minio/minio.go:220","msg":"downloadFile","bucket":"testkube-artifacts","bucketFolder":"63e2735e57648d7324c5fa14","file":"63e2735e57648d7324c5fa14/junit.xml"}
> {"level":"error","ts":1675859489.1236794,"caller":"server/httpserver.go:76","msg":"minio DownloadFile error: minio Download File Stat error: The specified key does not exist., error from getting files from former bucket per execution: <nil>","status":500,"stacktrace":"github.com/kubeshop/testkube/pkg/server.(*HTTPServer).Error\n\t/build/pkg/server/httpserver.go:76\ngithub.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).GetArtifactHandler.func1\n\t/build/internal/app/api/v1/executions.go:335\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945\ngithub.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).AuthHandler.func1\n\t/build/internal/app/api/v1/handlers.go:47\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942\ngithub.com/gofiber/fiber/v2/middleware/cors.New.func1\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/cors/cors.go:141\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945\ngithub.com/gofiber/fiber/v2/middleware/pprof.New.func1\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/pprof/pprof.go:41\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942\ngithub.com/kubeshop/testkube/pkg/server.(*HTTPServer).Init.func1\n\t/build/pkg/server/httpserver.go:46\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132\ngithub.com/gofiber/fiber/v2.(*App).handler\n\t/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:159\ngithub.com/valyala/fasthttp.(*Server).serveConn\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/server.go:2372\ngithub.com/valyala/fasthttp.(*workerPool).workerFunc\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:224\ngithub.com/valyala/fasthttp.(*workerPool).getCh.func1\n\t/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:196"}
> ```

@kamilkrampa from the logs it seems that you are trying to get the files without removing the id from the name, but it is fixed now, only the names will be displayed/returned, check out the latest version and let us know if you still have problems

**Comment by kamilkrampa** [comment]
Hey, now it works fine. Thanks!
