### ISSUE TITLE
Testkube api server failed to start

### ISSUE THREAD

**Issue by luciantimar** [kubeshop/testkube#3185]
**Describe the bug**
Testkube API server failed to start just after the installation.
The only command that I run was teskube init

**To Reproduce**
Install teskube CLI
1. Run 'testkube init'

**Version / Cluster**
- Which testkube version? 1.9.11
- Client Version 1.9.11
Server Version  api/GET-testkube.ServerInfo returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"no endpoints available for service \"testkube-api-server:8088\"","reason":"ServiceUnavailable","code":503}
'
error: no endpoints available for service "testkube-api-server:8088"
Commit eece02a109c7b74d8e4bbe5a5dfd763ea2937e36
Built by goreleaser
Build date 2023-02-13T11:58:12Z

- What Kubernetes version? v1.22.9

**Describe pod testkube-api-server**

`  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  53s                default-scheduler  Successfully assigned testkube/testkube-api-server-5459d4869d-gn9ct to worker-8
  Normal   Pulled     48s                kubelet            Successfully pulled image "docker.io/kubeshop/testkube-api-server:1.9.11" in 3.088641956s
  Normal   Pulled     47s                kubelet            Successfully pulled image "docker.io/kubeshop/testkube-api-server:1.9.11" in 67.80443ms
  Normal   Pulled     34s                kubelet            Successfully pulled image "docker.io/kubeshop/testkube-api-server:1.9.11" in 114.582869ms
  Warning  BackOff    14s (x4 over 44s)  kubelet            Back-off restarting failed container
  Normal   Created    13s (x4 over 48s)  kubelet            Created container testkube-api
  Warning  Failed     13s (x4 over 47s)  kubelet            Error: failed to start container "testkube-api": Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "chdir to cwd (\"/root\") set in config.json failed: permission denied": unknown
  Normal   Pulling    13s (x4 over 51s)  kubelet            Pulling image "docker.io/kubeshop/testkube-api-server:1.9.11"
  Normal   Pulled     13s                kubelet            Successfully pulled image "docker.io/kubeshop/testkube-api-server:1.9.11" in 106.778507ms`
 
**Additional context**
kubectl -n testkube get pods
`NAME                                                        READY   STATUS             RESTARTS      AGE
pod/testkube-api-server-5459d4869d-gn9ct                    0/1     CrashLoopBackOff   5 (85s ago)   4m22s
pod/testkube-dashboard-78ffdbdb85-j5mtf                     1/1     Running            0             4m23s
pod/testkube-minio-testkube-6584cfff9-l6dss                 1/1     Running            0             4m23s
pod/testkube-mongodb-7f8fcbc8dd-wnbqx                       1/1     Running            0             4m23s
pod/testkube-nats-0                                         3/3     Running            0             4m22s
pod/testkube-nats-box-64cfb878f7-d2lsc                      1/1     Running            0             4m23s
pod/testkube-operator-controller-manager-6d9f9cddd4-mjhrw   2/2     Running            0             4m23s`

**Comment by vsukhin** [comment]
@luciantimar do you use OpenShift?

**Comment by luciantimar** [comment]
No, I don't use Openshift.
Is a k8s Rancher-based installation and as far as I know we don't have any security restrictions on the cluster.

I have had it installed since last year, and worked fine until yesterday when I tried to upgrade it.

**Comment by ypoplavs** [comment]
@luciantimar was the k8s cluster deployed on any cloud provider or on your physical servers? Also have you tried deploying TK on newer k8s versions?

**Comment by luciantimar** [comment]
> @luciantimar was the k8s cluster deployed on any cloud provider or on your physical servers? Also have you tried deploying TK on newer k8s versions?

Hi,
the k8s cluster is deployed on our physical/vm servers but is provided as is we as developers we don't have access to nodes or to control the k8s version.

But I have managed to run it by changing the security context to include runAsUser: 0, and I had to do it for TK deployment but alose for job template files
After these changes, everything was working but I am interested if I could do it without having to run the containers with root privileges. Alos, I need to change to add the securityContext manually in some files, because just changed securityContext, and podSecurityContext in values.yaml file didn't work completely. (maybe I did something wrong)

**Comment by ypoplavs** [comment]
Hi,
It sounds like an installation on Openshift cluster, which requires security context change and running
application as a root user.  Could you please specify which templates you had to update manually so we can provide an option in values file for this?

**Comment by luciantimar** [comment]
> Hi, It sounds like an installation on Openshift cluster, which requires security context change and running application as a root user. Could you please specify which templates you had to update manually so we can provide an option in values file for this?

Looks like an openshift installation but is not Openshift

I have attached here the changes I made. so far is working fine, but I am not sure if it is the right aproach,

[testkube.patch](https://github.com/kubeshop/testkube/files/10784034/testkube.patch)

**Comment by ypoplavs** [comment]
Thank you for sharing your changes.

Can you please try adding security context by using our `--job-template` option? 
https://docs.testkube.io/guides/tests/tests-creating/#changing-the-default-job-template-used-for-test-execution

**Comment by ypoplavs** [comment]
Running application as a root user is a security concern for sure. But as of now this is the only way to do it. We will invest more time in investigation on how to run Testkube on physical servers running as a non-root user.

**Comment by chlete** [comment]
Hi @ypoplavs  and @luciantimar :)

Idea 💡 I check other places which seem to have the same problem, not with TK, but generally. You may want to try the following:

```
securityContext:
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65534
```
Hope it helps!

**Comment by TheBrunoLopes** [comment]
seems like @chlete solution should work. 
@luciantimar let us know if it worked for you, we can re-open the issue if not.
