### ISSUE TITLE
Playwright executor support

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#3187]

**Comment by vLia** [comment]
Just checked https://demo.testkube.io/results/v1/executors, playwright is already available there. 
The docs are on the way in a PR: https://github.com/kubeshop/testkube/pull/3183

**Comment by pavloburchak** [comment]
@vLia super nice!

**Comment by pavloburchak** [comment]
So we basically need only icon from @fivenp and add it to FE
