### ISSUE TITLE
Unknown error in TestKube dashboard when trying to edit a test

### ISSUE THREAD

**Issue by jose-JSQ** [kubeshop/testkube#3193]
**Describe the bug**
Error "Unknown error, something went wrong" is shown when trying to Edit a Test in Dashboard.

**To Reproduce**
1. Create a Test
2. Click on test > Settings
3. Try to modify any part of test, for instance, adding a Description
4. Click Save

**Expected behavior**
It should update the test

**Version / Cluster**
- Which testkube version? 
testkube-dashboard:1.9.1
testkube-api-server:1.9.11 
testkube-operator:1.9.1 
 
- What Kubernetes cluster? 
aws:eks

- What Kubernetes version?
K8s Rev: v1.24.8-eks-ffeb93d 

**Screenshots**
![image](https://user-images.githubusercontent.com/92341897/218891284-f1a4e4b7-9724-4c74-9aaf-bd899ae6f9f4.png)
![image](https://user-images.githubusercontent.com/92341897/218891352-1138d715-ea38-4ca9-99f8-1fadd15ae411.png)

**Comment by vsukhin** [comment]
removed nginx ingress snipet
