### ISSUE TITLE
[multi-tenancy] Testkube OSS Cluster & Cloud Agent Installation in multi namespaces

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3208]
**Spec**
- Helm (top priority)
   - At the moment of installing Testkube the user can specify which namespace it's going to be used for the deployment of all the components.

**UX notes**
- The experience of a user of Testkube OSS installation that is already installed in a cluster should remain the same as it was. i.e., he doesn't need to specify any namespace name when creating, running, or editing resources.

**Comment by TheBrunoLopes** [comment]
note: needs CLI work

**Comment by ypoplavs** [comment]
Helm part is done and merged.

**Comment by TheBrunoLopes** [comment]
@fivenp @vsukhin seems like the CLI is the missing part. 
Appears that the ticket is blocked

**Comment by TheBrunoLopes** [comment]
done
