### ISSUE TITLE
Time to live parameter for test execution and it's artifacts

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubeshop/testkube#3218]
Nowadays if we run tests with artifacts request artifacts are stored till are not deleted by user manually. Sometimes we reach a storage limit for out minio instance and new artifacts are not stored (as there is no more space left on device).

Add a support for add a time to live (TTL) parameter for artifacts/test executions so after requested time will be deleted.

**Comment by vLia** [comment]
There's an option to set this on object-level in minio, so implementation should be not too complex: https://min.io/docs/minio/linux/administration/object-management/object-lifecycle-management.html#object-expiration

**Comment by TheBrunoLopes** [comment]
Allowing helm values to configure this.
