### ISSUE TITLE
Ginkgo tests fail with `Found no test suites` when running with `-v GinkgoParallel=""`

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#3220]
**Describe the bug**
Ginkgo tests fail when GinkgoParallel is set to empty string

**To Reproduce**
1. Create test: `kubectl testkube create test --git-uri https://github.com/kubeshop/testkube-executor-ginkgo.git --git-path examples/testkube-api --type ginkgo/test --name ginkgo-example-test --git-branch main`
2. Run test: `tk run test ginkgo-example-test -v GinkgoParallel=""`
3. See error:
```
ginkgo run failed
  Found no test suites
 ```

**Expected behavior**
No error

**Version / Cluster**
- Which testkube version? v1.9.14
- What Kubernetes cluster? kind
- What Kubernetes version? go1.17.7

**Additional context**
[Was reported by user on Discord](https://discord.com/channels/884464549347074049/1077263789713530941). It is a blocker.

**Comment by vLia** [comment]
Fix released in `kubeshop/testkube-ginkgo-executor:0.0.23`

**Comment by JinoArch** [comment]
this is working. Confirmed. thanks a lot
