### ISSUE TITLE
unable to run testkube cli commnand : setting up client type (error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable)

### ISSUE THREAD

**Issue by orilani** [kubeshop/testkube#3262]
**Describe the bug**
we're spinning up pod with kubectl + testkube cli, pod attached service account with clusterrole allowing kubectl on all namespaces.
when trying to trigger testkube cli we're getting `setting up client type (error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable)`

**To Reproduce**
1. Run '...'
2. Specify '...'
3. See error

**Expected behavior**
able to use testkube cli and trigger tests run from that specific pod.

**Version / Cluster**
- Which testkube version? - Latest
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) - EKS version 1.23
- What Kubernetes version? - 1.23.0

**Screenshots**
`testkube get tests

setting up client type (error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable)
` 
**Additional context**

**Comment by vsukhin** [comment]
@orilani As Imntioned in Discord, it's necessary either to have proper kube/config in place to access your k8s cluster or use exposed testkube api server using direct connection

**Comment by TheBrunoLopes** [comment]
Hey @orilani if you are having troubles we would be more than glad to assist you with this configuration.
Feel free to schedule a quick call with us. https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by vsukhin** [comment]
So, closing it for now. kubernetes context shoud be set for cli
