### ISSUE TITLE
OSS: Change release Model

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3267]
AC:
- Features only get released at end of each Minor release after being tested. Unless we deem it critical and there's no breaking changes.
- Bugfixes can be released right away
- Each release is properly tagged on all the relevant repos (testkube, testkube-dashboard, testkube-helm)
- Each patch and minor has an automatically generated change log, that contains the PRs/issues that are relevant for that release. this should be True for all the repos mentioned above.
![Image](https://user-images.githubusercontent.com/13501228/221543265-8cb4d1e6-fb5c-48c7-a7c0-99d5074cf938.png)

**Comment by rangoo94** [comment]
@ypoplavs, isn't the new release model already completed? 🙂
