### ISSUE TITLE
Deprecate Arguments, only the command is used for that executer on the container

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3271]
AC:
- Compatibility should not be broken
- The Arguments should be merged with command for all official executors
- The exact command that is going to run is shown on the UI at the moment of test creation, on test edit, and when seeing what past executions it should be present on the logs, what was the exact command run.
- Please raise any issues if you detect that this change might break any ongoing magic.
- Executor is able to define default command. Command is able to be overridden at test definition and test execution.

**Comment by fivenp** [comment]
1. Yes – let's remove the Arguments from the Test UI section "Variables + Arguments"
2. We need to add a new section called "Execution" which includes all the available commands (Pre-Run, Run, etc)

![image](https://user-images.githubusercontent.com/132332/221879821-ba0be1b5-4c7e-4271-8428-2a688f516efc.png)


Figma:
https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?node-id=2570%3A96441&t=SMGaHzNBGWh2uESv-4

**Comment by vsukhin** [comment]
Actually, args atre kubernetes native for container definition, why should we deprecate them @fivenp @TheBrunoLopes ?
They are used differently in k8s container

**Comment by vsukhin** [comment]
I don't think we need to deprecate args, but we need to allow to change default command and args for pre-built executor. But it's a different task

**Comment by vsukhin** [comment]
I bit of documentation. 
K8s docs:
https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#container-v1-core
Our docs:
https://github.com/kubeshop/testkube/blob/develop/docs/docs/articles/creating-tests.md#redefining-the-prebuilt-executor-command-and-arguments

So, if we want to improve UI, it's one issue, if we want to change api, crd spec, we need to check carefully how it's done in k8s

**Comment by tkonieczny** [comment]
https://kubeshop.slack.com/archives/C026SAW3LR0/p1685527833839009?thread_ts=1685524144.008829&cid=C026SAW3LR0

**Comment by tkonieczny** [comment]
Tested (command/arg overwrite) - everything looks fine
