### ISSUE TITLE
Dashboard - incorrect Name validation - `.` not allowed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3278]
**Describe the bug**
Name validation rules are incorrect in Dashboard - `.` character can't be used for Test/TestSuite/Container Executor names.

**To Reproduce**
1. Try to create a Test/TestSuite/Container Executor with `.` - for example `some-name-1.1`
2. Error message is displayed despite the name being correct and matching these rules:
![Screenshot_20230227_182450](https://user-images.githubusercontent.com/1473096/221636268-ffb8cfb8-32e7-4529-ba95-9b8f54c71816.png)

**Expected behavior**
It should be possible to use `.` in the Test, TestSuite and Container Executor names based on the rules.

**Comment by rangoo94** [comment]
will be done in https://github.com/kubeshop/testkube/issues/3816
