### ISSUE TITLE
Update open source project to Golang 1.20.1

### ISSUE THREAD

**Issue by dejanzele** [kubeshop/testkube#3313]
**Why should it be implemented?**
It is recommended that we update our open source project from Golang 1.18 to the latest version, which is Golang 1.20.1. According to the official policy of Golang, each major Go release is supported until there are two newer major releases. Go 1.18 is no longer supported, and thus we are missing out on security fixes and critical updates.

**Describe the improvement**
By upgrading to Golang 1.20.1, we can take advantage of the latest features, optimizations, and security improvements, while also ensuring that our project is up-to-date with the latest version of the language. This update will also allow us to maintain compatibility with other projects that have already made the switch to the latest version.

Furthermore, Golang 1.20.1 is the latest stable release, which means that it has undergone rigorous testing and has been deemed ready for production use. We can therefore expect a more stable and reliable runtime environment with fewer bugs and crashes.

**Additional context**
Overall, updating our project to Golang 1.20.1 is a necessary step to keep our project secure and up-to-date with the latest advancements in the language. It will also help us to maintain compatibility with other projects and provide a more stable and reliable runtime environment for our users.

**Comment by kelvinwijaya** [comment]
Any plan to bump this up? Our latest test case required kube client-go api that requires higher version of go

**Comment by vsukhin** [comment]
yes, we will do it  soon

**Comment by kelvinwijaya** [comment]
Thanks @vsukhin for the quick update
