### ISSUE TITLE
GKE Kubernetes clusters upgrade - alpha/beta apis deprecated

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#333]
Looka at those: 

Kubtest Clusters: (bright-airport-323312)
- kubtest-dev
- kubtest

find all alpha/beta + check what need to be updated

email: 

Migrate to use the Stable (generally available) API versions before your clusters are upgraded to Kubernetes v1.22.Hello Google Kubernetes Engine (GKE) Customer,We are writing to let you know that as part of the Open Source Kubernetes lifecycle, previously deprecated Beta APIs in v1.22 have been removed in GKE. As Kubernetes evolves, alpha and beta APIs can be changed on a minor version boundary. When the v1 APIs graduate, the older alpha and beta APIs are deprecated and eventually removed. The beta APIs removed in 1.22 were deprecated in favor of their generally available replacements between 2018 and August 2020.What do I need to know?As of Kubernetes 1.22, API clients will no longer be able to use previously deprecated Beta API versions. Manifests using those versions will no longer be able to be applied. Note that all previously persisted objects remain functional.They can be read and updated via the new API versions, before and after the Kubernetes 1.22 upgrade.This change is part of the project’s policy that once the v1 APIs graduate to the next level, the old alpha and beta APIs are deprecated and eventually removed.Software known to be impacted, but not limited, by these removed APIs include:Anthos Service Mesh 1.10.3 and belowIstio 1.9 and belowThe GKE release schedule outlines the cluster upgrade schedule.If we are able to detect usage of deprecated beta APIs in Kubernetes v1.22, we will pause automatic upgrades until March 2022 for GKE clusters v1.21 to ensure seamless transition from previously deprecated beta APIs in v1.22 to generally available (GA) APIs.Please note, regardless of whether your cluster is enrolled in a release channel or not, normally cluster control planes are always upgraded on a regular basis. For an additional level of control over when an auto-upgrade can occur (or must not occur), you can configure maintenance windows and exclusions.Even if your clusters are running older Kubernetes versions, we urge you to start migrating to v1 stable APIs that are available in earlier Kubernetes versions as outlined in this email.What do I need to do?Migrate to use the GA API versions before your clusters are upgraded to Kubernetes v1.22 to ensure your API clients and resource manifests can access and update API resources without interruption. More information is available from the GKE v1.22 deprecated API documentation and from the Kubernetes project. Clusters with Google's Cloud Operations suite enabled can use Admin Activity log query to show the use of 1.22 APIs.For Anthos Service Mesh upgrades, see Anthos Service Mesh version 1.10 documentation for version-specific upgrade instructions.For Istio, migrate to the Google-supported Anthos Service Mesh or see Istio upgrade instructions at istio.io.Your projects below use the deprecated beta APIs and will require you to migrate to the GA API versions before your clusters are upgraded to Kubernetes v1.22:Kubtest Clusters: (bright-airport-323312)kubtest-devkubtestmy-first-cluster-1Need more information or help?You can learn more about how cluster upgrades work here. More information is also available from the GKE v1.22 deprecated API documentation and from the Kubernetes project.If you have any questions or require assistance, please reply to this email to contact Google Cloud Support.Thanks for choosing Google Kubernetes Engine.
--

**Comment by fog1985** [comment]
The main cluster we are using now (testkube-dev) has been upgraded to `v1.21.3-gke.2001`.  And all v1beta1 APIs were changed to v1 across all Helm Charts. For the future upgrades to 1.22.
