### ISSUE TITLE
API: Add `parent` field to test/suite execution

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#3344]
**Is your feature request related to a problem? Please describe.**

The idea was because our operator is failiing because of too long object names: 
```json
{"L":"ERROR","T":"2023-03-05T20:38:48.219Z","M":"Reconciler error","controller":"testtrigger","controllerGroup":"[tests.testkube.io](http://tests.testkube.io/)","controllerKind":"TestTrigger","testSuite":{"name":"executor-container-playwright-smoke-tests","namespace":"testkube"},"namespace":"testkube","name":"executor-container-playwright-smoke-tests","reconcileID":"72b73dc4-da1a-4833-a5b5-dde0ad28fbe1","error":"CronJob.batch \"executor-container-playwright-smoke-tests-test-suites\" is invalid: metadata.name: Invalid value: \"executor-container-playwright-smoke-tests-test-suites\": must be no more than 52 characters","S":"[sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem](http://sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:273\[nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2](http://nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/internal/controller/controller.go:234"}
```

Instead of merging name for executions as TESTSUITE + TEST we could just add additonal field with `parent` metadata: e.g.:

- for running test suites each test execution would get info about Testsuite which triggered test execution 
- for running test from schedule test execution would get info abot schedule who was responsible for running given test

**Comment by exu** [comment]
cc @TheBrunoLopes @fivenp

**Comment by exu** [comment]
in UI would be nice to render links to particular pages (e.g. test suite definition, schedule definition/list)

**Comment by fivenp** [comment]
We do have a ticket which relates to exactly this topic "what triggered this execution?" -> #3269

**Comment by rangoo94** [comment]
Looks like it's not relevant after https://github.com/kubeshop/testkube/issues/3269.
