### ISSUE TITLE
Teams integration

### ISSUE THREAD

**Issue by robinsmedberg** [kubeshop/testkube#3374]
We are currently using Teams and would like to be notified when tests are failing.

Teams accepts incoming messages using [Incoming Webhooks](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet).
But messages need to be in [Adaptive Cards](https://adaptivecards.io/) formatted json.

I would like to create a webhook in Testkube and specify message format as Adaptive card.

**Comment by TheBrunoLopes** [comment]
Hey @robinsmedberg we are currently evaluating the use of [Botkube](https://botkube.io/) a way user's could integrate Testkube with Teams and other types of chats. Do you think this would work for you ?

**Comment by robinsmedberg** [comment]
@TheBrunoLopes seems like a good approach
