### ISSUE TITLE
Slack message not updated for some test, test suite trigger

### ISSUE THREAD

**Issue by nivhty** [kubeshop/testkube#3376]
**Describe the bug**
Slack message not updated for some test, test suite trigger

**To Reproduce**
1. Create a test via API.
2. Create a test suite including the test you've just created via API.
3. Trigger the test suite via API.

**Expected behavior**
Slack message got sent when the test suite is started and updated after the suite is finished

**Version / Cluster**
- Which testkube version? 
Client Version 1.9.25
Server Version v1.9.27

- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
EKS

- What Kubernetes version?
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.14-eks-ffeb93d", GitCommit:"96e7d52c98a32f2b296ca7f19dc9346cf79915ba", GitTreeState:"clean", BuildDate:"2022-11-29T18:43:31Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

**Screenshots**
Test suite finished event fired:
![image](https://user-images.githubusercontent.com/49474736/223677627-af15d9e6-bde6-4e21-b21b-6264d410d18a.png)

Test suite finished (from dashboard):
![image](https://user-images.githubusercontent.com/49474736/223677595-4e34e15e-6bac-42d8-9e05-1340a00f2588.png)

Slack message not updated:
![image](https://user-images.githubusercontent.com/49474736/223677564-70a4a059-3833-4185-8fee-9b43e4e9cdcd.png)

 
**Additional context**
Logs of `testkube-api` after the test suite finished event fired:

```JSON
{"level":"info","ts":1678267145.3464606,"caller":"event/emitter.go:174","msg":"listener notified","listen-on":["start-test","end-test-success","end-test-failed","end-test-aborted","end-test-timeout","start-testsuite","end-testsuite-success","end-testsuite-failed","end-testsuite-aborted","end-testsuite-timeout"],"queue-group":"slack","selector":"","metadata":{"events":"[start-test end-test-success end-test-failed end-test-aborted end-test-timeout start-testsuite end-testsuite-success end-testsuite-failed end-testsuite-aborted end-testsuite-timeout]","name":"slack","selector":""},"id":"c8b487e4-987b-445d-8280-4d7fef2f04e1","type":"start-test","executionId":"640853084bb1a8cdf1f2b71c","executionName":"eh-get-requests-19","labels":""}
{"level":"info","ts":1678267222.206249,"caller":"client/job.go:384","msg":"execution ended, saving result","executionID":"640853084bb1a8cdf1f2b71c","type":"sync","executionId":"640853084bb1a8cdf1f2b71c","status":"passed"}
{"level":"info","ts":1678267222.283535,"caller":"event/emitter.go:128","msg":"event published","id":"483ae935-b747-4136-893f-fcc54749e0e2","type":"end-test-success","executionId":"640853084bb1a8cdf1f2b71c","executionName":"eh-get-requests-19","labels":"","error":"nats: maximum payload exceeded"}
{"level":"info","ts":1678267223.0349758,"caller":"scheduler/test_scheduler.go:117","msg":"test started","executionId":"640853084bb1a8cdf1f2b71c","status":"passed"}
{"level":"info","ts":1678267223.0681283,"caller":"event/emitter.go:128","msg":"event published","id":"dcb30ad8-d27a-418d-be16-a6f23035ec27","type":"end-test-success","executionId":"640853084bb1a8cdf1f2b71c","executionName":"eh-get-requests-19","labels":"","error":"nats: maximum payload exceeded"}
{"level":"info","ts":1678267223.1401598,"caller":"event/emitter.go:128","msg":"event published","id":"7a8f8866-feb7-40e3-a1a2-6be91b51bc64","type":"end-testsuite-success","executionId":"640853084bb1a8cdf1f2b71a","executionName":"ts-eh-2","labels":"","error":"nats: maximum payload exceeded"}
```

**Comment by nicufk** [comment]
Hey @nivhty Hey, can you try to modify the nats.maxPayload in the helm charts and see if you can still reproduce it?

**Comment by nicufk** [comment]
nats maxPayload should be increased

**Comment by nivhty** [comment]
Increase nats.limits.maxPayload to 64MB (default 8MB) in Helm value fixed the problems. Thanks @nicufk.
```YAML
nats:
  # NATS container settings
  nats:
    limits:
      # -- Max payload
      maxPayload: 64MB
```
