### ISSUE TITLE
Jmeter: HTML artifact support

### ISSUE THREAD

**Issue by JinoArch** [kubeshop/testkube#3403]
**Is your feature request related to a problem? Please describe.**

while testing jmeter I see only jtl files are generated by the test run as artifacts. It will be good to see html formatted artifacts after jmeter test run

like the one gets generated via the below command
``` jmeter ... -f -e -o ./result/html ```

**Describe the solution you'd like**
I would like to see the html files available in artifacts so that user can download from UI itself.

**Describe alternatives you've considered**
NA

**Comment by TheBrunoLopes** [comment]
Hey @JinoArch, thank you for the feature request.
We took this as high priority and we will release this feature in a day or two tops.

**Comment by TheBrunoLopes** [comment]
looping in @dejanzele to check

**Comment by JinoArch** [comment]
can you please provide an example in doc too ? if possible?
