### ISSUE TITLE
CLI argument to show only the log of a test for 'testkube get execution <ID>'

### ISSUE THREAD

**Issue by esebrei** [kubeshop/testkube#3404]
**Is your feature request related to a problem? Please describe.**
I have a custom executor running Python test scripts. The log messages are in JSON. 
To analyze an error, it is fairly easy to use `jq` to pretty print a log message.

But `jq` does not work, when a line does not start with `{`. For a workaround I can pipe the output lines into `egrep` and filter for lines starting with `{`. 
So, in general, this command works for `passed` tests, but not for `failed`:

```bash
testkube get execution <ID> | egrep "^\{" | jq
```
It looks like, that the problem is the red icon `x`, that is displayed on the CLI output on a `failed` test.  
The lines before the `x` (`ID`, `Name`, `Number`, ...) are omitted successfully, but the `x` is still visible and the log lines after that are not pretty printed.

**Describe the solution you'd like**

An additional argument like `--show-only-logs` for the command `testkube get execution <ID>`.

So the above command would look like this:

```bash
testkube get execution <ID> --show-only-logs | jq
```

**Additional context**
Should be fairly easy to reproduce:
1. Create a custom executor with a test script, that logs in JSON
2. Let the test fail
3. Above command should not work for a `failed` test

**Comment by vsukhin** [comment]
Thank you @esebrei We do have statuses with latest execution results for both Test and TestSuite, but it doesn't container  error details. Guess, it's useful improvement. @TheBrunoLopes will checkit out

**Comment by vsukhin** [comment]
hey, @esebrei 
we're printing failed error message and log output to stdErr.do you need to print them to StdOut or you can use something like 2> >(egrep "^\{" | jq )?

**Comment by esebrei** [comment]
Thank you @vsukhin for that idea, but it did not work and the `x` is still visible:

![image](https://user-images.githubusercontent.com/117629565/227452794-7d109e2d-11e5-4f49-818f-d1778955b9f5.png)

**Comment by vsukhin** [comment]
Ok, we will add this option
