### ISSUE TITLE
Dashboard - test edit - impossible to remove the test Path

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3410]
**Describe the bug**
It's not possible to remove the test Path while editing the test.

**To Reproduce**
1. Create a test with non-empty Path
2. Go to test edit, and try to edit it - remove the Path and save
3. "Test source was successfully updated." message is displayed, but Path isn't updated to the empty one.

**Comment by TheBrunoLopes** [comment]
fixed

**Comment by rangoo94** [comment]
Should be fixed with https://github.com/kubeshop/testkube-dashboard/pull/575
