### ISSUE TITLE
Support kubent (similar and more up to date than kubepug)

### ISSUE THREAD

**Issue by nitrocode** [kubeshop/testkube#3432]
**Is your feature request related to a problem? Please describe.**
I'd like to check if an existing cluster has any deprecations. This can be done by kubepug but kubepug hasn't been updated in some time. There is a new tool that is more up to date called kubent.

https://github.com/doitintl/kube-no-trouble
https://github.com/rikatz/kubepug

**Describe the solution you'd like**
Please support kubent checks

**Describe alternatives you've considered**
Using older kubepug checks

**Additional context**
N/A

**Comment by vsukhin** [comment]
Thank you @nitrocode Good idea! @TheBrunoLopes please checkit out and prioritise

**Comment by aabedraba** [comment]
Hey @nitrocode I added some docs to be able to run kubent with Container Executor. 

Please try it out and let me know what you think: https://github.com/kubeshop/testkube/pull/4008
