### ISSUE TITLE
Support Github Deploy keys for Git Tests

### ISSUE THREAD

**Issue by AndrewUnderwoodAtFanatics** [kubeshop/testkube#3443]
**Is your feature request related to a problem? Please describe.**
Today in order to create a test that pulls from Git you must supply a Github Access token with permissions to read the repository.  However, it is not possible scope a Github token to only read a single repository.  If that token is compromised the attacker will be able to read any repository that the user who generated it has access to.

**Describe the solution you'd like**
Testkube should support the usage of [Deploy keys](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys) as a method for authenticating to Git.  A deploy key only allows read actions and it only applies to a specific git repository.  Where a Github token represent a specific user and will attribute actions taken with that token to the user who generated it in the Github Audit logs.  Deploy keys can have a name like "Testkube - Dev" associated with them are much better at representing a "service" such as Testkube.

The ability to use Deploy keys aligns with [the GitOps principals already put forward by FluxCD.](https://fluxcd.io/flux/installation/#github-and-github-enterprise)

**Comment by vsukhin** [comment]
Thank you @AndrewUnderwoodAtFanatics Nice improvement! We do care about security @TheBrunoLopes please prioritise

**Comment by vsukhin** [comment]
cool. we will discuss it in any case
