### ISSUE TITLE
JMeter tests are stuck in running

### ISSUE THREAD

**Issue by MattiasRexby01** [kubeshop/testkube#3463]
**Describe the bug**
When running JMeter tests <60 sec, the execution never leaves status "running" even when using "watch execution" prints that is is done. This hinders from getting the results out. 
[[](url)](https://media.discordapp.net/attachments/885185660808474664/1087298881836023808/image.png?width=1308&height=483)

**To Reproduce**
1. Create a JMeter test with a execution time of more than 60 sec, it seams not to matters what other settings are.
3. See error:

{"level":"error","ts":1679311948.5969632,"caller":"client/job.go:389","msg":"Update execution result error","executionID":"641843bb2eee119c2e0daaf7","type":"async","error":"an inserted document is too large","stacktrace":"github.com/kubeshop/testkube/pkg/executor/client.(*JobExecutor).stopExecution\n\t/build/pkg/executor/client/job.go:389\ngithub.com/kubeshop/testkube/pkg/executor/client.(*JobExecutor).updateResultsFromPod.func1\n\t/build/pkg/executor/client/job.go:306\ngithub.com/kubeshop/testkube/pkg/executor/client.(*JobExecutor).updateResultsFromPod\n\t/build/pkg/executor/client/job.go:333\ngithub.com/kubeshop/testkube/pkg/executor/client.(*JobExecutor).Execute.func1\n\t/build/pkg/executor/client/job.go:190"}

**Expected behavior**
Test ends and presents results in CLI, results are also possible to get using the CLI.

**Version / Cluster**
- Version
Client Version 1.10.3
Server Version v1.9.37
Commit a5b98a37e78b19238b490fb26c2c1d84e285fa62
Built by goreleaser
Build date 2023-03-17T10:37:44Z
- What Kubernetes cluster? OpenShift
- What Kubernetes version? 4.12.6

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
https://cdn.discordapp.com/attachments/1087298881903149107/1087392670860722226/testkubepodlogsapiserver.txt

https://cdn.discordapp.com/attachments/1087298881903149107/1087340477986119750/testkubepodlog.txt

https://cdn.discordapp.com/attachments/1087298881903149107/1087332459416399953/testkubelogs.txt

**Comment by vLia** [comment]
Hey @MattiasRexby01,
a fix was released that trims the output when persisting it into MongoDB in Testkube version 1.10.23. In case the entirety of the logs is needed, please consider using MinIO for logs storage: https://docs.testkube.io/guides/logging/
Please also let us know if there are any further issues with this.
