### ISSUE TITLE
Remove the amount of success toast notifications

### ISSUE THREAD

**Issue by fivenp** [kubeshop/testkube#3469]
We currently use a lot of "Success" toast notifications in different situations. 

### 2nd we should try to remove them from obvious places 

* When an entity was created and the user gets redirected to that entity detail we do NOT need to show a Success toast
* When a user clicks a save button on a Settings Card – we SHOULD show a Success toast

Feel free to start with consolidating a list of events/places where we trigger success toasts.

**Comment by rangoo94** [comment]
### OSS

* After deleting the test/test suite
  * User gets redirected to the list though
* After updating any of the test/test suite settings
* After updating the executor's configuration
* After updating the API endpoint in the settings
* After updating the Test Source
* After updating the triggers

### Additional success toasts on the Cloud

* After deleting the API token for the user
   * The deletion is reflected on the list on the same page though
* After inviting a new member
   * The change is reflected on the list too
* After resending the invitation to a new member

I don't see success toast for creating a new entity though, as mentioned in the ticket. @fivenp, could you advise which we should get rid of?

**Comment by fivenp** [comment]
To be honest – I do NOT feel that we would need to delete ANY of the success toasts.... None of them feel like "super bad anti pattern and useless"
