### ISSUE TITLE
Enhance Labeling of Kubernetes Jobs promoting association with Tests

### ISSUE THREAD

**Issue by AndrewUnderwoodAtFanatics** [kubeshop/testkube#3478]
**Describe the enhancement you'd like to see**
To make it easier to trace the relationship between Kubernetes jobs and their originating tests in Testkube, it would be beneficial to include additional labels when creating jobs. Currently, the executor adds a 'job-name' label with the test execution ID. By expanding the labeling system to also include the test name, users can more effectively associate Jobs and their Pods with the tests that initiated them.

Additional labels such as the test type and executor could add helpful context as well.

**Additional context**

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2023-03-21T19:54:37Z"
  generation: 1
  labels:                                       ## Add Test name here
    controller-uid: 662a4ed1-eef3-40ad-b1fb-fcc5cdb7c385
    job-name: 641a0b7d0d53c275b4e668d6
  name: 641a0b7d0d53c275b4e668d6
  namespace: testkube
  resourceVersion: "175346638"
  uid: 662a4ed1-eef3-40ad-b1fb-fcc5cdb7c385
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 662a4ed1-eef3-40ad-b1fb-fcc5cdb7c385
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:                                     ## Add Test name here
        controller-uid: 662a4ed1-eef3-40ad-b1fb-fcc5cdb7c385
        job-name: 641a0b7d0d53c275b4e668d6
```

**Comment by AndrewUnderwoodAtFanatics** [comment]
To give a more specific user story for how I am trying to use this data, I am trying to overlay Test Start and Test Stop Kubernetes events over time series metric data in Datadog.  This will make it very clear when looking at performance data to see which tests were running at that time.

Note the event overlay query at the bottom.  Today this query will show `Jobs` executed in the `testkube` namespace but there is no "test name" available on these events.

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/110694107/226726755-8d3655b1-e295-4098-b138-e7d4fa62f780.png">

**Comment by vsukhin** [comment]
guess @TheBrunoLopes has some ideas about labeling for jobs

**Comment by vsukhin** [comment]
Guees, we can do it together with this issue https://github.com/kubeshop/testkube/issues/3270

**Comment by TheBrunoLopes** [comment]
Hello @AndrewUnderwoodAtFanatics! this one seems like a quick thing and useful thing. Thank you also for all your info.
We will release on 1.11 (this release)
