### ISSUE TITLE
tests on testkube requires create executor for each test because of passing env variables issue

### ISSUE THREAD

**Issue by PawDenst** [kubeshop/testkube#3485]
Custom container executor can be created to run tests for all smoke tests. All tests are running using the same command:

**run_tests -t $TESTNAME**

so it should be possible to use one executor and each test should only set TESTNAME env variable.

But it doesn't work.

_This is part of the test file:_
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: basic-cps
spec:
  type: pythonsdk-tests/test-cps
  executionRequest:
    args:
    - $(TESTNAME)
    envs:
      TESTNAME: basic_cps
      PYTHONPATH: $PYTHONPATH:/data/repo/basic_configuration_settings/$TESTNAME
      ONAP_PYTHON_SDK_SETTINGS: "basic_cps_configuration"
_This is part of the executor file:_
command:
    - /bin/bash
    - -c
    - PYTHONPATH=$PYTHONPATH:/data/repo/basic_configuration_settings/$TESTNAME ONAP_PYTHON_SDK_SETTINGS="basic_cps_configuration" run_tests -t $TESTNAME
    
And I want to pass $TESTNAME variable to test, so I can be able to use this variable and run test using this command in one executor, instead of passing name of the test to every single executor.
**run_tests -t $TESTNAME**.

**Version / Cluster**
- testkube version - Client Version 1.9.3, Server Version v1.9.37
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- Kubernetes version - Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16"

Testkube does not support the use of such environment variables and this is a bug or what is the problem?

**Comment by vsukhin** [comment]
This test works for me
                                            
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: env-executor
  namespace: testkube
spec:
  types:
  - env/test
  executor_type: container
  image: soleware/nx-cli:8.5.2
  command:
  - /bin/bash
  - -c
  - pwd; echo ${TEST};

kubectl testkube create test --name env-test --variable TEST=cool --type=env/test
kubectl testkube run test env-test -f

/app
cool

Test execution completed with success in 6.405s 🥇
