### ISSUE TITLE
Postman Environment file upload while creating a postman Test

### ISSUE THREAD

**Issue by MerwinRod89** [kubeshop/testkube#3508]
While creating a Test related to Postman and uploading the json file, i observed that even though i have environment files created on postman already I need to create the variables here again.

The likely solution this would be if the user is allowed to upload the environment files too instead of having to create the variables

Once the environment files are uploaded user should be allowed to use the environment file as an argument i.e. -e "envfile.json"

**Comment by vsukhin** [comment]
hey @MerwinRod89 We have this options in cli to support postman env file
--variables-file string                      variables file path, e.g. postman env file - will be passed to executor if supported

**Comment by vsukhin** [comment]
Hope, existing feature enough, please reopen an issue, if it's not
