### ISSUE TITLE
There's no executor to choose (ex: k6, jmeter)

### ISSUE THREAD

**Issue by Jim0530** [kubeshop/testkube#3518]
**Describe the bug**
I got three question. I've been installing testkube in an air-gapped env through helm installation. and yet I successfully installed it without using minio.
1. after i port forwarded into testkube-dashboard service, when i access the dashboard through browser, it pop out a message of "Setting ur TESTKUBE API Endpoint" which i don't know how to set my endpoint for that. 
2. Second question is when i want to create test by dashboard , and found out there's no test tpye to select. it's empty
3. Should i pre-pulled those jmeter, cypress image into my environment into my environment?

**Comment by Jim0530** [comment]
When Creating Custom Executor i get unknown error

**Comment by Jim0530** [comment]
i got these log from testkube-api-server , when i try to use testkube cli tools to connect api-server it doesn't work. wonder if there's problem in testkube-api-server

**Comment by vsukhin** [comment]
hey @Jim0530 
1.2. You need to have proper API endpoint in setting, for port forwarded dashboard ` http://localhost:8088/v1`. Go to the Dashboard setting in bottom right corner
3. Executors are automatically pulled with each test execution, if you didn't block access to Internet, you don't need to prepull them

**Comment by Jim0530** [comment]
@vsukhin  Thanks, where can i change the settings of the executor image url?? cuz i we have blocked access to internet

**Comment by Jim0530** [comment]
i saw it! i guess it's in the executor json

**Comment by Jim0530** [comment]
`segment 2023/03/28 05:12:38 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io on 172.16.0.10:53: server misbehaving `
now my testkube is working on my airgapped env. but i've been receiving these error messages in my testkube-api-server logs.
And sometimes my testkube-api-server pods get OOMKilled.
I check my cpu mem usage and get info down below. Is it normal??? 
`testkube-api-server-599768465f-zj45l                    23m          1010Mi`

**Comment by vsukhin** [comment]
You can disable telemetry by running `kubectl testkube disable telemetry`
This is what I see on our server
testkube-api-server-96744c4cc-6jr2w                     14m          315Mi
@tkonieczny have you seen OOM for api server?

**Comment by Jim0530** [comment]
i change my pod resource limit memory to 2048mi and it works.

**Comment by vsukhin** [comment]
might be some peak usage

**Comment by vsukhin** [comment]
if eveything works, then closing it

**Comment by Jim0530** [comment]
@vsukhin  Thanks!
