### ISSUE TITLE
The dashboard is stuck or unresponsive when showing successful execution with maven tests

### ISSUE THREAD

**Issue by dr-zeta** [kubeshop/testkube#3522]
**Describe the bug**
When you click on a successful execution of a maven test the dashboard seems stuck and unresponsive.
Sometimes you got a popup from Chrome asking if you want to wait or terminate the loading.
Also If you succeed to access the execution results the interface is very unresponsive.

I have recreated the issue in your own demo environment
https://demo.testkube.io/tests/executions/maven-example/execution/64217ab34afc10c4911b05c6
But it can be easily obtained on any k8s clusters.

**To Reproduce**
- Create a test (from GUI o from CR) starting from the testkube official maven demo.
```apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: maven-example-test
  namespace: testkube
  labels:
    app.kubernetes.io/instance: testkube-testing
spec:
  type: maven/test
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube-executor-maven.git
      branch: main
      path: examples/hello-maven
  executionRequest:
    variables:
      TESTKUBE_MAVEN:
        name: TESTKUBE_MAVEN
        value: "true"
        type: basic
```
- Execute a test
- Click on the successful execution
- Wait for the detail view
- Experience unresponsive UI

**Expected behavior**
See test results details and navigate through tabs (logs, CLI commands, variables) without any issues.

**Version / Cluster**
- Which testkube version? official testkube demo environment
- What Kubernetes cluster? official testkube demo environment
- What Kubernetes version? official testkube demo environment

**Screenshots**
https://demo.testkube.io/tests/executions/maven-example/execution/64217ab34afc10c4911b05c6
 
**Additional context**

**Comment by vsukhin** [comment]
hey @dr-zeta thank you for reporting it. we will ask our front end team @pavloburchak @rangoo94 to checkit out

**Comment by rangoo94** [comment]
The fix has been merged. You may see the results in the demo environment's [**link from the ticket**](https://demo.testkube.io/tests/executions/maven-example/execution/64217ab34afc10c4911b05c6). It will be available in the next release.

Once again, thanks @dr-zeta for the report!
