### ISSUE TITLE
Test CRD openapi schema is lacking enum for content.type

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3535]
**Describe the enhancement you'd like to see**

As a testkube CR test author
In order to get inline documentation and completion when authoring Test CR in my prefered IDE
I need the Test.tests.testkube.io/v3 crd to specify valid values for `content.type`

**Current behavior**

![image](https://user-images.githubusercontent.com/4748380/228315328-52614f3c-707f-486b-bb3d-31ba149f1859.png)
![image](https://user-images.githubusercontent.com/4748380/228315390-fd1f0d88-2417-474e-943a-458a235a030f.png)

**Workaround**

Look at source code

https://github.com/kubeshop/testkube/blob/2074e2d0310c357dfc6a6ab5dd326b4877d2eadf/docs/docs/contributing/development/crds.md?plain=1#L76-L81

https://github.com/kubeshop/testkube/blob/2074e2d0310c357dfc6a6ab5dd326b4877d2eadf/pkg/api/v1/testkube/model_test_content_extended.go#L8-L15

https://github.com/kubeshop/testkube/blob/2074e2d0310c357dfc6a6ab5dd326b4877d2eadf/api/v1/testkube.yaml#L2950-L2972

or read documentation which contain example CR (relates to https://github.com/kubeshop/testkube/issues/3444)
https://github.com/kubeshop/testkube/blob/2074e2d0310c357dfc6a6ab5dd326b4877d2eadf/docs/docs/test-types/container-executor.mdx#L283-L296

**Additional context**
Add any other context, CLI input/output, etc. about the enhancement here.

**Comment by vsukhin** [comment]
merci bien @gberche-orange good point, definitely!

**Comment by vsukhin** [comment]
completed in https://github.com/kubeshop/helm-charts/pull/442

**Comment by gberche-orange** [comment]
awesome, thanks a lot @vsukhin, this will much help me in my discovery of TestKube CRDs !
