### ISSUE TITLE
UI: Not possible to scroll while cursor is on Sider

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#3539]
**Describe the bug**

Because the content is not a full page, when the cursor is on side navigation, it's not possible to scroll by swipe.

**To Reproduce**

1. Go to "Tests" page with many tests
2. Move cursor to the side navigation
3. Try to scroll (with wheel or swipe)
4. The list of tests is not scrolling

**Expected behavior**

It should scroll the whole page, keeping the sider on the left side

**Comment by rangoo94** [comment]
@fivenp, I think that it's more convenient to scroll the whole page then, but could you confirm if that's desired behavior?

**Comment by fivenp** [comment]
I love it @rangoo94
