### ISSUE TITLE
Ability to add additional files/directories to an execution

### ISSUE THREAD

**Issue by scott-david-walker** [kubeshop/testkube#3565]
We currently have a set of tests that run using Karate (tests not currently in Testkube). We'd like to migrate them but we're unable to due to the fact that we have a directory structure with input files, output files and other logic.

**Describe the solution you'd like**
Be able to upload or mount a set of files to the container running the tests.

**Describe alternatives you've considered**
We could use Git but then we don't have the the actual merge branch. We've seen the "copy-files" option but it appears that you have to specify each file which is unrealistic if we have any more than 10 files

**Comment by vLia** [comment]
Hello @scott-david-walker,

We do not have a feature to mount in folders into the containers right now. For production flows we recommend using either Git directories (you mentioned this is not option), or the [container executor](https://docs.testkube.io/test-types/container-executor), and creating your own Docker image with the files baked in. This way you could also keep track of the different versions between the files using different tags on the image, and could further customize it to fit the additional logic you mentioned.

Do you see any reason why this would not solve your use case?

**Comment by scott-david-walker** [comment]
We create environments per pull request so if we were to go down the image route then we'd end up with potentially hundreds of executors being created. It's absolutely doable but feels very much like a workaround. 

Git would be viable if we could grab the merge commit from the pull request but, as far as I'm aware, that's not possible

**Comment by TheBrunoLopes** [comment]
Hey @scott-david-walker was wondering if you tried @vLia suggestion. Please let us know if it worked for you :)
closing the issue for now, will re-open if it didn't work.
