### ISSUE TITLE
K6 Executor Update

### ISSUE THREAD

**Issue by AndrewUnderwoodAtFanatics** [kubeshop/testkube#3574]
**Describe the enhancement you'd like to see**
The current K6 executor looks to be on version 0.41.0 but version [0.43.1](https://github.com/grafana/k6/releases/tag/v0.43.1) is available and has some enhancements available., namely [tracing support](https://k6.io/docs/javascript-api/k6-experimental/tracing/).  Is there a typical cycle on which the out-of-the-box executors are updated?

**Comment by AndrewUnderwoodAtFanatics** [comment]
I took a look at contributing this change myself but with the way things are in the repo I was expecting the current k6 version to be 0.36. It's not quite clear to me how the executor image gets built.

**Comment by vsukhin** [comment]
hey, @AndrewUnderwoodAtFanatics Fork testkube repo and open pr with your changes for https://github.com/kubeshop/testkube/blob/main/contrib/executor/k6/build/agent/Dockerfile

**Comment by AndrewUnderwoodAtFanatics** [comment]
Thanks for the pointer!  Here's my PR https://github.com/kubeshop/testkube/pull/3586
