### ISSUE TITLE
Testkube API & Testkube Dashboard Token/Account Management

### ISSUE THREAD

**Issue by Jim0530** [kubeshop/testkube#3576]
**Is your feature request related to a problem? Please describe.**
We hope to create a  testing platform which will be around like 1000 users. Here's comes a question testing management could be a problem. Cuz there will be some credential info in the testing yaml!

**Describe the solution you'd like**
Is there any Account/Token Management in using Testkube Dashboard, Testkube API

**Comment by vsukhin** [comment]
yes, we support secret variables for tests. their values will be automatically stored in k8s secrets
please checkit out https://docs.testkube.io/concepts/secrets

**Comment by Jim0530** [comment]
@vsukhin hi thank you for the support and answering questions. i've been using testkube for a while. it's really a great testing platform for Kubernetes. I was wondering whether it's possilbe for limiting users to trigger specific test or not?

**Comment by vsukhin** [comment]
thank you @Jim0530 for your good words. we have solution for this. @TheBrunoLopes can share you details

**Comment by TheBrunoLopes** [comment]
Hello @Jim0530 good to see that you are finding Testkube useful for your testing needs in Kubernetes.
We have a very interesting solution that allows you to manage different levels of authorization for each member of your teams. I would love to walk you through it. Feel free to book a quick call with me at your convenience https://calendly.com/bruno-at-kubeshop/30min-1

**Comment by vsukhin** [comment]
it's Enterprise feature
