### ISSUE TITLE
Add limits for simultaneous test executions

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#3584]
To help me ensure that I'm not overloading my cluster I would like to be able to configure
- max number of total simultaneous test executions
- max number of simultaneous executions per test  

When any of those limits are met - the Run button in the UI should be disabled with a corresponding warning message - "simultaneous test execution limit of XX reached" (or something like that)

**Comment by TheBrunoLopes** [comment]
I would prefer to queue tests if there are not available resources to execute them. 
I'm not a big fan of adding any of the limits mentioned above

**Comment by olensmar** [comment]
sure - either could be possible/configurable - let the user decide

**Comment by ahmedimf1** [comment]
I would like to see this feature as well (or a queue as Bruno suggests), it is important for me to limit the number of test pods running concurrently to avoid resource exhaustion.

**Comment by TheBrunoLopes** [comment]
Action plan: We Implement global value for Testkube api.

**Comment by rangoo94** [comment]
@TheBrunoLopes, would we really like to have it only globally? Even we are encountering problems now because of the lack of the concurrency configuration on the test & test suite level.

**Comment by TheBrunoLopes** [comment]
yeah, we can also have it at the Test / Suite level.

**Comment by TheBrunoLopes** [comment]
@exu @rangoo94 @jmorante-ks to review architectural changes.

**Comment by vsukhin** [comment]
duplicated #5463
