### ISSUE TITLE
Investigate zustand usage for local state

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#3619]
**Why should it be implemented?**

* Right now for store management we use React's Contexts, Redux (RTK), local states, and global storages (`localStorage`)
* We consider replacing Redux and bigger Contexts with [**zustand**](https://github.com/pmndrs/zustand)

**Describe the improvement**

As part of this task, we would like to replace `EntityDetailsContext` with Zustand's store.
 
**Additional context**

In the Cloud version, we will investigate [**zustand**](https://github.com/pmndrs/zustand) for a global state (like auth, organizations or environments)

**Comment by vsukhin** [comment]
investigation was completed in Cloud
