### ISSUE TITLE
Improve documentation links in dashboard

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#3629]
@aabedraba 
 - review current state of documentation links
 - define places that missing documentation and when it is required to create new documentation page

@pavloburchak
 - add or replace links where it is needed
 - create an enum for all documentation links across the app and use it in `ExternalLink` component

**Comment by aabedraba** [comment]
@pavloburchak updated all the links in https://github.com/kubeshop/testkube-dashboard/pull/662
