### ISSUE TITLE
Display current kube container image and helm chart version in kube-dashboard

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3641]
**Is your feature request related to a problem? Please describe.**

As a testkube user
In order to ease interacting with the testkube community when testing new builds or reporting issue
I need the testkube dashboard to display its kube container image  and helm chart version in kube dashboard

**Comment by TheBrunoLopes** [comment]
@fivenp sync with @vsukhin and @rangoo94 for mockups.

**Comment by fivenp** [comment]
We can attach a new Settings Card to the bottom of the settings which would have "About" information.

We could list all different versions in there: 
* Dashboard Version
* API Version
* Helm Chart
* Container img
etc....


![image](https://github.com/kubeshop/testkube/assets/132332/f239c111-ef91-483c-a7db-9772de4355cb)

**Comment by vsukhin** [comment]
@gberche-orange @fivenp is dasboard version not enough, do we really  need a path to registry?

**Comment by gberche-orange** [comment]
> @gberche-orange @fivenp is dasboard version not enough, do we really need a path to registry?

I understand from https://github.com/kubeshop/helm-charts/blob/373da35df84e0355974822fbc9efc44387c26381/charts/testkube/Chart.yaml#L7-L28 that dasboard version is'nt sufficient to fully identify testkube version 

Therefore, I believe displaying the helm chart version in the UI would be quite useful to users reporting bugs.

**Comment by vsukhin** [comment]
Yes, we will show helm chart version, but not registry pathes
