### ISSUE TITLE
Executor images don't use imageRegistry value

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubeshop/testkube#3642]
**Describe the bug**
When testkube was deployed using helm and global.imageRegistry value is set when user execute any test that value is not taken and executor images are used as set on testkube-api-server ConfigMap

**To Reproduce**
1. Run testkube with helm global.imageRegistry value set on environment which has no access to docker.io registry
2. Run any test using predefined executors (e.g. curl executor)
3. See error that image cannot be pulled as docker.io registry is not available

**Expected behavior**
imageRegistry value should be considered during executor images pull

**Version / Cluster**
- Which testkube version? 1.10.336
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) local cloud kubernetes instance
- What Kubernetes version? v1.23.16

**Comment by vsukhin** [comment]
Thank you @michal-jagiello-tmpl Sounds like, we need to add registry parameter to job templates. As fow now they are not a part of helm chart templates. So we need toi pass via api env var
