### ISSUE TITLE
Dashboard - Custom container executor - command is required - can't be removed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3661]
**Describe the bug**
When custom command is set for custom container executor it's not possible to remove it.
![Screenshot_20230411_155836](https://user-images.githubusercontent.com/1473096/231187074-a3cef8d2-9020-4344-a428-5b0860d74466.png)

**To Reproduce**
1. Create custom container executor
2. Set command, save it
3. Try to remove command (to use the default one)

**Expected behavior**
Custom ommand shouldn't be required - it should be possible to remove it.

**Comment by Pravesh-Sudha** [comment]
Hey @tkonieczny, I would like to contribute to it.

**Comment by Pravesh-Sudha** [comment]
Can I know the exact location of the file above?

**Comment by rangoo94** [comment]
@Pravesh-Sudha, not a problem - the form above is available in this file: [**`src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx`**](https://github.com/kubeshop/testkube-dashboard/blob/main/src/components/pages/Executors/ExecutorDetails/ExecutorSettings/CommandAndArguments/Command.tsx)

**Comment by Pravesh-Sudha** [comment]
@rangoo94 a small question where I have to push on kubeshop/testkube or kubeshop/testkube-dashboard?

**Comment by rangoo94** [comment]
@Pravesh-Sudha, we have the UI in the [**testkube-dashboard**](https://github.com/kubeshop/testkube-dashboard), so that would be the appropriate place.

Worth to note, that to contribute you have to [**fork the repository**](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and create the PR from your fork into the original repository.

**Comment by Pravesh-Sudha** [comment]
@rangoo94 sir, I have created a PR for this issue on the testkube/dashboard. Could you please review it?
