### ISSUE TITLE
Unable to change Testkube api server port

### ISSUE THREAD

**Issue by Jay-Patel-22** [kubeshop/testkube#3668]
I am installing testkube using values.yaml and passing it to testkube init --values=./values.yaml command 
below is the content of values.yaml

``` testkube-api:
  service:
    type: LoadBalancer
    port: 8080
    annotations:
      cloud.google.com/load-balancer-type: External

testkube-dashboard:
  service:
    type: LoadBalancer
    port: 80
    annotations:
      cloud.google.com/load-balancer-type: External

testkube-operator:
  apiPort: 8080 
```

But unfortunately my testkube api server pod is not running, when described the pod got the below error

![image](https://user-images.githubusercontent.com/82871116/231457180-73383556-4b65-43ff-8675-e7cfc1545fc4.png)

it is taking testkube api server default port (i.e. 8088), i guess it has been hard coded in testkube api deployment template of the helm chart

**Comment by vsukhin** [comment]
@ypoplavs liveness probe is hardcoded to 8088

**Comment by vsukhin** [comment]
we also need to store service name and port in cli config

**Comment by ypoplavs** [comment]
hi @Jay-Patel-22 for now it's not possible to use any other port than 8088 for TK API. We have already created an [issue](https://github.com/kubeshop/testkube/issues/3670) to fix that and will priotize it soon.

**Comment by ypoplavs** [comment]
We have updated the helm-charts so you can know easily expose TK endpoints with LoadBalancer. 

Also please update the API port from CLI using the following instruction: https://docs.testkube.io/reference/cli/testkube_config_api-server-port/

This is essential for interaction with Testkube API from cli.

**Comment by Jay-Patel-22** [comment]
okay thanks !
