### ISSUE TITLE
CDEvents: Testkube Produces CDEvents

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3681]
Read the CDEvents spec defined by @olensmar  in this PRs https://github.com/cdevents/spec/pull/105/files
https://github.com/cdevents/spec/pull/126
(feel free to add/suggest changes at your discretion)

It should be possible for external systems to receive/read these events.

cc: @olensmar @vsukhin to define how this integration should look like?

Questions to be answered:
- How should external systems receive/read these events. Webhooks, subscribe to a message queue ? etc...
- How should a user configure which events should be produced ? cc: @fivenp

**Comment by olensmar** [comment]
My understanding is that we would POST these events using HTTP to a user-configurable endpoint - in line with the Cloud-Events HTTP Binding - https://github.com/cloudevents/spec/blob/main/cloudevents/bindings/http-protocol-binding.md

**Comment by fivenp** [comment]
I'm not 100% sure if a user should be able to customise which events are going to be emitted by testkube – but rather just configure in their application / endpoint which one they want to listen/react to?

**Comment by olensmar** [comment]
If the user configures an external endpoint I suggest we simply emit all events to start with..

**Comment by exu** [comment]
Usually it's a good practice to choose events which you want receive. 
As getting all simply is not scaling well. 
e.g. Stripe has almost 100 events, so getting all of them will be just wasting of compute resources.
