### ISSUE TITLE
CDEvents: Testkube Listens to CDEvents, then Triggers tests/suites based on conditions

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3682]
Listen to CDevents produced by a CI/CD system https://github.com/cdevents/spec/blob/v0.2.0/core.md
and allow a user to define "TestTriggers" based on these events.

Questions to be answered:
- How should a user configure where/what to listen too ?

**Comment by TheBrunoLopes** [comment]
cc: @olensmar @vsukhin @fivenp

**Comment by fivenp** [comment]
Now that we're close to migrate our triggers ui to the multi-view interface we could start distinguishing / adding more trigger sources in there :) 

The concept would be very much the same as cluster events – just with different fields

![image](https://github.com/kubeshop/testkube/assets/132332/badfc424-dc4a-4fb4-bb1c-ca32fc21a4b7)

**Comment by TheBrunoLopes** [comment]
won't do for now.
