### ISSUE TITLE
Executor Refactor: Executor Versions and Configuration

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3698]
AC:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/13501228/232773249-a447de4b-8669-4797-8948-b4d29c3c3e55.png">

- As user I shouldn't need to create a different executor in order to use a new version of the tool.
- The version should be a parameter that has a sane default, but can be changed on test creation or set globally.
- Depending on the executor, the user may want to use different dependencies or extra common configurations. For example for the cypress executor one user may want to use npx instead of npm, or want to use chromium browser for testing instead of firefox. These changes should be possible to parametrise without the need to create a new executor.
- Testkube upgrades shouldn't break executor versions.
- This change doesn't break capability of container executors
- These capabilities should be an extension to container executors.

Deliverable:
- Make a solution proposal.
- Write Yaml spec of executor
- Describe user journey from two standpoints:
   - From a user of an executor (someone that is trying to use different tool versions for the same executor)
   - From a user/dev that is building a new executor that supports multiple configurations/versions.
- Add documentation for Executor CRD

**Comment by TheBrunoLopes** [comment]
cc: @tkonieczny @fivenp to validate from UX standpoint

**Comment by fivenp** [comment]
As an example journey of what a competitor is doing from a user/developer perspective: 

1. You select your the registry for the executor (e.g. Dockerhub + Credentials if private)
2. You define the image
3. The SYSTEM is pulling all available versions / images for this image straight from Dockerhub and lets me select it

**Comment by vsukhin** [comment]
It looks more like wizard for creating container executor CRD

**Comment by fivenp** [comment]
> It looks more like wizard for creating container executor CRD

I agree.... but we would need to define those container executors as "official" ones (and change the way we handle them on the UI in some places) :)

**Comment by TheBrunoLopes** [comment]
Scoped changed, look into notion and start investigation.

**Comment by vsukhin** [comment]
So, I checked both Notion and this issue, and we have 2 tasks linked to this issue:
1. Redefine entrypoint.sj for container executor - it's already planned for 1.14
2. Prepare API method to return a list of available versions for particluar dickerhub image and use in UI Wizard to select it for container executor. User should also be able manually to provide image:version. I can also suggest to prepare a list of aliases to dockerhub images for most popular testing framework
