### ISSUE TITLE
Failure to resolve host when cloning repository (from private GitHub server)

### ISSUE THREAD

**Issue by walsm232** [kubeshop/testkube#3732]
**Describe the bug**
We have a privately hosted GitHub server for our repositories. When using the Cypress executor we are consistently running into an issue where the domain is failing to resolve when attempting to checkout a repository with Cypress tests. This can happen for 20 or 30+ attempts in a row before having a successful checkout. 
```
Initializing...
Fetching test content from git...
could not fetch test content: failed to fetch git: process error: exit status 128
output: Cloning into 'repo'...
fatal: unable to access 'https://<PRIVATE_GITHUB_SERVER>.com/michael-walsh/MyTestsExample.git/': Could not resolve host: <PRIVATE_GITHUB_SERVER>
 
Failed to fetch git: process error: exit status 128
output: Cloning into 'repo'...
fatal: unable to access 'https://<PRIVATE_GITHUB_SERVER>.com/michael-walsh/MyTestsExample.git/': Could not resolve host: <PRIVATE_GITHUB_SERVER>
 
Could not fetch test content: failed to fetch git: process error: exit status 128
output: Cloning into 'repo'...
fatal: unable to access 'https://<PRIVATE_GITHUB_SERVER>.com/michael-walsh/MyTestsExample.git/': Could not resolve host: <PRIVATE_GITHUB_SERVER>
```

I am able to issue **dig** and **nslookup** commands to this GitHub server without any issues from other pods, it only seems to be the TestKube pods which have issues with DNS resolution. 

**Service Mesh: Istio**
**DNS Server: CoreDNS**

**To Reproduce**
1. Checkout a code repository from a private GitHub server via Cypress executor.

**Expected behavior**
The code should checkout from the Git repository every single time instead failing 20 or 30+ times before a successful one.

**Version / Cluster**
- Which testkube version? - **testkube-1.10.400**
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) - **Kubernetes on AWS instances (not managed EKS)**
- What Kubernetes version? - Client version: **v1.22.16**, Server version: **v1.21.9**

**Screenshots**
N/A
 
**Additional context**
To provide some additional context we are using Istio for our Service Mesh in this cluster and also CoreDNS for the DNS server.

**Comment by vsukhin** [comment]
hey @walsm232 
Do you have anything from below:
- ndots configuration in CoreDNS, as that could affect DNS resolution, but don't know how if it already works in other pods
- enabling logs in CoreDNS and pasting us the error when the init container reaches to CoreDNS if it reaches at all.
- checking for errors in the Istio Sidecar and pasting the logs
?

**Comment by vsukhin** [comment]
also would be great to run alpine/git <git_command>

**Comment by walsm232** [comment]
**CoreDNS ndots Configuration**
```
$ cat /etc/resolv.conf

nameserver 192.168.128.10
search default.svc.cluster.local svc.cluster.local cluster.local us-west-2.compute.internal
options ndots:5
```

**CoreDNS Logs**
```
 ~  kc logs coredns-coredns-5b76d55984-9d28n -n kube-system | grep '<PRIVATE_SERVER>.com'                                                                             
 
[INFO] plugin/auto: Inserting zone `<PRIVATE_SERVER>.com.' from: /etc/coredns/zones/..2023_04_26_10_09_15.139418801/db.<PRIVATE_SERVER>.com
[INFO] plugin/file: Successfully reloaded zone "<PRIVATE_SERVER>.com." in "/etc/coredns/zones/db.<PRIVATE_SERVER>.com" with 1682505013 SOA serial
[INFO] plugin/file: Successfully reloaded zone "<PRIVATE_SERVER>.com." in "/etc/coredns/zones/db.<PRIVATE_SERVER>.com" with 1682519413 SOA serial
```

Even while Istio is disabled in that namespace the same issue occurs (see failure log below with no Istio sidecar injected)
```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  67s   default-scheduler  Successfully assigned testkube/6449472e7037e2c8ff143917-lrjs7 to <IP>.us-west-2.compute.internal
  Normal  Pulled     66s   kubelet            Container image "kubeshop/testkube-executor-init:1.10.45" already present on machine
  Normal  Created    66s   kubelet            Created container 6449472e7037e2c8ff143917-init
  Normal  Started    65s   kubelet            Started container 6449472e7037e2c8ff143917-init
```

```
 ~  kc get pod 6449472e7037e2c8ff143917-lrjs7 -n testkube
NAME                             READY   STATUS       RESTARTS   AGE
6449472e7037e2c8ff143917-lrjs7   0/1     Init:Error   0          2m19s
```

```
 ~  kc logs 6449472e7037e2c8ff143917-lrjs7 -n testkube -c 6449472e7037e2c8ff143917-init

{"type":"line","content":"📦 Fetching test content from git...","time":"2023-04-26T15:45:57.038203714Z"}
{"type":"line","content":"❌ Failed to fetch git: process error: exit status 128\noutput: Cloning into 'repo'...\nfatal: unable to access 'https://<PRIVATE_SERVER>.com/michael-walsh/MyTestExample.git/': Could not resolve host: <PRIVATE_SERVER>.com\n","time":"2023-04-26T15:46:02.057342092Z"}
```

**Comment by walsm232** [comment]
**Alpine Git**
```
 ~  kc exec alpine -c git-cloner -- git version
git version 2.36.3
```

```
 ~  kc exec alpine -c git-cloner -- git clone https://michael-walsh:<PERSONAL_ACCESS_TOKEN>@<PRIVATE_SERVER>.com/michael-walsh/MyExampleRepo.git/
Cloning into 'MyExampleRepo'...
```

```
 ~  kc exec alpine -c git-cloner -- ls MyExampleRepo
README.md
cypress
cypress.config.ts
package.json
renovate.json
reports
scripts
tsconfig.json
yarn.lock
```

**Comment by walsm232** [comment]
I just tested this on a separate pod / container in **default** namespace in our cluster. Did you want me to edit the Helm template to point to Alpine Git and test that so that it is used when the TestKube pod is created and code checked out?

**Comment by vsukhin** [comment]
We just switched to alpine/git for init pod container. It should be releasedin20 mins. Let's see, if it helps

**Comment by vsukhin** [comment]
Just released a alpine/git based init container. Can you upgrade Testkube and try it out?

**Comment by walsm232** [comment]
Have had 3 successful Cypress test runs in a row without any DNS resolution errors since upgrading to the new release. Will try it a few more times and confirm it has been resolved and then we might be good to close this one out.

**Comment by vsukhin** [comment]
Sounds cool! Thank you!

**Comment by walsm232** [comment]
```
❌ Failed to fetch git: could not start process with command: git, exited with code:128  error: exit status 128
output: Cloning into 'repo'...
fatal: unable to access 'https://<PRIVATE_SERVER>.com/michael-walsh/MyTestsExample.git/': Could not resolve host: <PRIVATE_SERVER>.com
```
Ah, just started to hit the issue again. I ran it a few more times, see the order of success vs. failures below:
:white_check_mark: :white_check_mark: :white_check_mark: :x: :x: :white_check_mark: :x: :x: :x: :x: :x: :x: :x: :white_check_mark: :x:
Still seeing a large amount of failures but it is significantly better than before as we were seeing far more failures prior to the change.

I see this thread here discussing that DNS resolution issues seem to be pretty common with Alpine images: https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes
Does Alpine in particular need to be used for this? I can test it out with a Debian / Ubuntu based image and see if it improves

**Comment by vsukhin** [comment]
It can be any image with git, it's only job is to clonning repo. Please try other options

**Comment by walsm232** [comment]
What would be the correct way to test this out via a test run with the Ubuntu based image? Is there somewhere in the Helm chart that I can point to a different image to use for this Git cloning or where is that referenced? I can test it out with the Ubuntu image that way also if that is the case

**Comment by vsukhin** [comment]
This is realy weird. But you can update image for init container in executors.json file in Helm chart for testing

**Comment by walsm232** [comment]
Since switching to Ubuntu image I've been able to get 10 successful runs in a row without any DNS resolution issues.
✅ ✅ ✅ ✅ ✅ ✅ ✅ ✅ ✅ ✅ 

Tested by building a new image with Ubuntu as the base and installing **ca-certificates** and **git** on top, pushed image to our registry and then pointed to it in the **executors.json** file in the Helm chart for the init executor.
```
    {
        "name": "executor-init",
        "executor": {
            "executorType": "init",
            "image": "<PRIVATE_REGISTRY>/ubuntu-cloner:latest",
            "types": []
        }
    }
```

I've opened a PR for this change here if you are happy to go ahead with it: https://github.com/kubeshop/testkube/pull/3749

**Comment by walsm232** [comment]
#3749

**Comment by walsm232** [comment]
Will close this now if that's alright as #3749 has now been merged.
