### ISSUE TITLE
Bug: container executor stores json as logs

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#3736]
**Describe the bug**

Custom executor logs are stored as JSON 

<img width="866" alt="image" src="https://user-images.githubusercontent.com/30776/234837251-9480194f-3dff-41c3-9569-e8a2b8c083a5.png">

To reproduce try to run this one on demo 
https://demo.testkube.io/tests/executions/jacek-container-exec-test

**Comment by rangoo94** [comment]
@exu, is there a chance to unify the responses/websocket contract related to logs from OSS and Cloud backends? At the moment I think that they differ.

**Comment by exu** [comment]
How they are different? 

This issue is about backend bug with custom container executors
This bug looks the same in OSS and cloud

**Comment by exu** [comment]
my example was removed but looks like we have bunch of json for all of them 
https://demo.testkube.io/tests/executions/container-executor-cypress-v12.7.0-smoke-git-dir/execution/64b7a4e5e8ce04777005e910
