### ISSUE TITLE
GitHub link on download page (https://testkube.io/download) redirects to Discord

### ISSUE THREAD

**Issue by hks1** [kubeshop/testkube#3747]
**Describe the bug**

GitHub link on download page (https://testkube.io/download) redirects to Discord

**To Reproduce**

Open https://testkube.io/download and click Github link at the top of the page

**Expected behavior**

should redirect to github page of testkube like it does if you click this link from the testkube home page

**Version / Cluster**

N/A - current running website version

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by vLia** [comment]
Hello @hks1,
Thanks for reporting this, the team responsible for the website was announced and will fix this

**Comment by vLia** [comment]
Closing as it is fixed now
