### ISSUE TITLE
Cron is created and running fine, but once I stop the cron through UI not able to create any new cron for any test

### ISSUE THREAD

**Issue by naveenreddymanukonda** [kubeshop/testkube#3751]
Cron is created and running fine, but once I stop the cron through UI not able to create any new cron for any test

**To Reproduce**

1. Create a job from UI and schedule it, cron will be created.
2. Now remove the scheduling from UI
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40488776/235929078-d113a494-c0e2-4261-9039-51215178aa40.png">
3. From now we will not be able to create any test with cron functionality

**Expected behavior**
Cron should stop working when we request from UI and should be able to create a new cron

**Comment by naveenreddymanukonda** [comment]
I didn't try with CLI, I tried from API and from UI both results are on same line

**Comment by vsukhin** [comment]
This works for me:
kubectl testkube create test --git-branch main --git-uri https://github.com/kubeshop/testkube-example-cypress-project.git --git-path "cypress" --name cj-test --type cypress/project --schedule "*/5 * * * *"
kubectl get cronjobs -n testkube
kubectl testkube delete test cj-test
kubectl testkube create test --git-branch main --git-uri https://github.com/kubeshop/testkube-example-cypress-project.git --git-path "cypress" --name new-test --type cypress/project --schedule "*/5 * * * *"
kubectl get cronjobs -n testkube
kubectl testkube delete test new-test

**Comment by naveenreddymanukonda** [comment]
@vsukhin I want to create this through API, but will try with CLI as well

**Comment by vsukhin** [comment]
sure thing. but cli is an api client in general

**Comment by naveenreddymanukonda** [comment]
@vsukhin Please check the below Screenshots and please suggest how can I move further

In the below image, I am hitting through the API

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/40488776/235973163-e08d6558-6edf-4e10-90ed-ba178aaa92fb.png">

The test is created on the test tube 

<img width="888" alt="image" src="https://user-images.githubusercontent.com/40488776/235974293-ddbc090d-46f2-4b17-8f21-44cfdf8f4060.png">

I am able to see the schedular

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/40488776/235974422-c46ca2fd-dd56-442b-b3ec-6e9eecece1ec.png">

But when I see the command prompt it is not shown

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/40488776/235973764-f7eaaed2-deb7-4ed9-804f-2d1f8cef53ab.png">

**Comment by vsukhin** [comment]
needs to ask our front end devs to check @rangoo94 @pavloburchak it out

**Comment by rangoo94** [comment]
Hi @naveenreddymanukonda!

The fix is merged to the `develop` branch, so we will release it soon, in the next stable version. I will inform you there when it will be packaged.

**Comment by rangoo94** [comment]
Hi @naveenreddymanukonda! Sorry, that it took so long, but unfortunately this release is pretty heavy, and we had to test it precisely.

The fix has been released with the latest Helm chart ([**1.11.213**](https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.11.213)). It should work fine after updating Testkube to the latest version.

**Comment by naveenreddymanukonda** [comment]
@rangoo94 thanks for the update
Great job guys
will check and let you know with the latest helm chart cheers :)
