### ISSUE TITLE
Add spinner on `testkube init`

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3752]
Why observing multiple users install Testkube, they all thought the installation got stuck when they reach the Helm installation section of the screenshot below: 

<img width="608" alt="CleanShot 2023-05-03 at 16 40 05@2x" src="https://user-images.githubusercontent.com/27779735/235949950-e391c17d-2bde-49c3-b75f-51adbbacf2d3.png">

We could add a spinner improving the UX of the installation and/or providing some sense of progress on the installation.

**Comment by Sindhuinti** [comment]
Hi @aabedraba I would like to work on this issue.

**Comment by Sindhuinti** [comment]
Closes #3788 @aabedraba

**Comment by aabedraba** [comment]
> Closes #3788 @aabedraba 

Thanks so much!!!
