### ISSUE TITLE
Check Zap Executor to release it officially

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3797]
AC: 
- make sure it's the **already** created executor is ready to be merged in the monorepo 
- merge executor in monorepo

**Comment by rangoo94** [comment]
Cc: https://github.com/kubeshop/testkube/issues/1157

**Comment by tkonieczny** [comment]
Looks like examples are outdated: https://github.com/kubeshop/testkube/blob/4520ac3e58e482ac109a5eb72658979e8a3187ec/contrib/executor/zap/README.md?plain=1#L29

**Comment by tkonieczny** [comment]
Additional examples will be needed for tests checked out from repository (when copy files isn't used):
https://github.com/kubeshop/testkube/blob/4520ac3e58e482ac109a5eb72658979e8a3187ec/contrib/executor/zap/examples/zap-tk-api.yaml#L11

**Comment by vsukhin** [comment]
@vLia please check it out

**Comment by tkonieczny** [comment]
Rechecked after fix - everything looks fine now
