### ISSUE TITLE
Websocket no longer streaming log lines

### ISSUE THREAD

**Issue by donaldoakes** [kubeshop/testkube#3801]
**Describe the bug**
Previous api server version (specifically 1.10.16) streamed individual log lines at e.g.: `ws://localhost:8088/v1/executions/645a806aa995da0b1de187c2/logs/stream`. After upgrade to 1.11.18, individual log lines are no longer streamed; only `result` type entries. Before and after screenshots attached for [postman-test](https://docs.testkube.io/test-types/executor-postman#b-creating-a-test-with-git-file).

**To Reproduce**
1. Run `kubectl testkube dashboard`
2. Add postman-test as per: https://docs.testkube.io/test-types/executor-postman#b-creating-a-test-with-git-file
3. Run postman-test
4. Observe websocket streamed messages no longer include log lines.

**Expected behavior**
Log line should be included in /v1/executions/{executionId}/logs/stream.

**Version / Cluster**
- Which testkube version?  1.11.18
- What Kubernetes cluster? Docker Desktop MacOS
- What Kubernetes version? v1.25.4

**Screenshots**
**1.10.16**  
<img width="2032" alt="testkube-1 10 16-postman" src="https://github.com/kubeshop/testkube/assets/19718743/7a9397d6-408e-4245-8f3d-d45f0c2954c2">
**1.11.18**  
<img width="2032" alt="testkube-1 11 18-postman" src="https://github.com/kubeshop/testkube/assets/19718743/6ee593dc-82e2-4d56-9704-43a04f1ecdd2">

**Comment by donaldoakes** [comment]
This seems to be an issue with the server, and not with the UI. Logs are not being streamed to the websocket listener. Tested with postman-test and with curl-test.

**Comment by nicufk** [comment]
Hey @donaldoakes I tried to reproduce it on my side and it is working fine with the latest changes, I checked in our demo cluster as well and it is working as you can see [here](https://demo.testkube.io/tests/executions/postman-executor-smoke-testsource-git-file/execution/645b61907ccc9872354e59de) and the version of the testkube is https://demo.testkube.io/results/v1/info.

There might be something else that is affecting logs on your side

**Comment by nicufk** [comment]
@donaldoakes, yes I see, I will investigate it

**Comment by TheBrunoLopes** [comment]
@nicufk seems like the PR is open https://github.com/kubeshop/testkube/pull/4212
should we merge it ?

**Comment by nicufk** [comment]
> @nicufk seems like the PR is open #4212 should we merge it ?

Merged!

**Comment by tkonieczny** [comment]
![Screenshot from 2023-08-28 12-25-18](https://github.com/kubeshop/testkube/assets/1473096/c77cf36f-0e3c-4673-99cb-64507633f5c0)
