### ISSUE TITLE
401 Unauthorized on Git Validation on dev.testkube.io

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#3802]
**Describe the bug**

When running the Git source validation (`POST https://dev.testkube.io/results/v1/repositories`), there is 401 Unauthorized error.

**To Reproduce**

1. Go to some test settings
2. Update i.e. branch
3. See network or warning next to the Git repository

**Expected behavior**

It should validate the repository.

**Comment by vsukhin** [comment]
@ypoplavs please check nginx snippet

**Comment by ypoplavs** [comment]
NGINX allows POST requests in our config:
```
  if ( $request_method = POST ){
    set $methodallowed "true";
  }
```
Additionally, I added the path as well:
```
  if ( $request_method = POST ){
    set $methodallowed "true";
    set $pathallowed "true";
  }

  if ( $uri ~ "^/results/v1/repositories$" ){
    set $pathallowed "true";
  }
```
but it still returned the error. is there anything else we can check that could block it?

**Comment by vsukhin** [comment]
I guess, we don't need to add pathallowed to method check
But uri can be checked   ^(.*)/repositories$
Also please check ingress logs, they should have some hints

**Comment by ypoplavs** [comment]
thanks Vlad! actually the config I posted above works, I checked badly at the first time.

**Comment by ypoplavs** [comment]
[PR](https://github.com/kubeshop/helm-charts/pull/504).
