### ISSUE TITLE
Testkube API server loses track of running testsuite / test after restart

### ISSUE THREAD

**Issue by xin-hedera** [kubeshop/testkube#3807]
**Describe the bug**

Testkube API server will lose track of running testsuite / test if the pod the execute request was sent to gets killed, this results in testsuite / test executuion status stuck in `running`. In addition, in our use case we have a custom k6 executor and the test case is defined to save a markdown report to the artifact volume, at the end, due to the issue, the artifact will not be uploaded since Testkube API server won't create the scraper Job.

**To Reproduce**
1. Install testkube with testkube-api replica set to 1
2. Run a test case with artifact upload, the test case should run long enough to allow step 3 to complete
3. Scale the testkube-api deployment replica to 0, then back to 1
4. Once the test job completes, check the test execution status, it should be still `running`, and verify there's no artifact uploaded 

**Expected behavior**
The new testkube-api pod should be able to resume polling status of the testsuite / test execution, and when the test pod completes, create the scraper Job to scrape and upload the artifact if configured so.

**Version / Cluster**
- Which testkube version? helm chart v1.11.174
- What Kubernetes cluster? GKE
- What Kubernetes version? 1.25.7-gke.1000

**Screenshots**
 
**Additional context**

**Comment by vsukhin** [comment]
hey, @xin-hedera thank you for reporting. yes, we're pllaning to improve existing architecture in order to make reconciliation, still ETD is not defined yet

**Comment by rangoo94** [comment]
Possible duplicate: https://github.com/kubeshop/testkube/issues/1231

**Comment by rangoo94** [comment]
Related issue: https://github.com/kubeshop/testkube/issues/3167

**Comment by vsukhin** [comment]
We use reconciler for checking test statuses every 5 mins
