### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by ahmedimf1** [kubeshop/testkube#3808]
**Describe the enhancement you'd like to see**
I would like to deploy Testkube in an IPv6-only cluster. Most components deploy correctly except for the Testkube Dashboard. 

**Additional context**
In the `testkube-api-server` container, we can see the following binds: 
```sh
Pod: testkube/testkube-api-server-68cf4b5f8b-tlssz | Container: testkube-api 

/root $ netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 :::8070                 :::*                    LISTEN      1/app
tcp        0      0 :::8088                 :::*                    LISTEN      1/app
```

However, in the `testkube-dashboard` container:
```sh
Pod: testkube/testkube-dashboard-8d577fdf5-znwf8 | Container: testkube-dashboard 

/usr/share/nginx/html # netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1/nginx: master pro 
```
This leads to the following events when describing the testkube-dashboard pod:
```
Events:
  Type    Reason  Age                    From     Message
  ----    ------  ----                   ----     -------
  Normal   Started    13m (x2 over 13m)     kubelet            Started container testkube-dashboard
  Normal   Killing    13m                   kubelet            Container testkube-dashboard failed liveness probe, will be restarted 
  Warning  Unhealthy  12m (x12 over 13m)    kubelet            Readiness probe failed: Get "http://[2406:da14:53e:4101:a4c2::d]:8080/": dial tcp [2406:da14:53e:4101:a4c2::d]:8080: connect: connection refused
  Warning  Unhealthy  12m (x6 over 13m)     kubelet            Liveness probe failed: Get "http://[2406:da14:53e:4101:a4c2::d]:8080/": dial tcp [2406:da14:53e:4101:a4c2::d]:8080: connect: connection refused   
```

**Comment by ahmedimf1** [comment]
@vsukhin I created this issue as discussed

**Comment by vsukhin** [comment]
thank you @ahmedimf1 we will add it to our feature list!

**Comment by rangoo94** [comment]
Reopening, as we've got [**a regression**](https://github.com/kubeshop/testkube/issues/3846) with that, as when IPv6 is not available, the `nginx` will not start.

@vsukhin, what do you think about similar approach as [**nginx-proxy**](https://github.com/nginx-proxy/nginx-proxy#ipv6-support) - enable IPv6 only when [**requested by `ENABLE_IPV6` variable**](https://github.com/nginx-proxy/nginx-proxy/pull/719/files)?

**Comment by vsukhin** [comment]
yes, I thought, that we might add a var to helm to provide such env var for dashboard nginx
