### ISSUE TITLE
It's not possible to change only Git token or Git username for Test Source

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#3814]
**Describe the bug**

When both username and token secrets, are set, `PATCH`ing with `token: ""` or `username: ""` resets both.

**To Reproduce**

1. Create a test source with username and token secrets
2. Patch the token via API
3. See that none of secrets are attached

**Expected behavior**

It should apply only expected changes.

**Comment by tkonieczny** [comment]
Issue found while testing this one: https://github.com/kubeshop/testkube/issues/3934
