### ISSUE TITLE
Dashboard: When saving Variables & Secrets, save button is not disabled

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3815]
![image](https://github.com/kubeshop/testkube/assets/27779735/c4c36ce3-f543-4430-bf87-fc43b851fbb0)

Testkube's default behavior is removing the "Cancel" button and Disabling the Save button, as follows: 

![image](https://github.com/kubeshop/testkube/assets/27779735/5f9b60a0-8a26-47d0-a041-c816a63f256c)

![image](https://github.com/kubeshop/testkube/assets/27779735/35a65006-1845-45a9-b405-6408887b469e)

**Comment by rangoo94** [comment]
Actually, it's happening for most of the tabs in the test and test suite settings at the moment. The button fades when the test or test suite is updated.

It should update the "Save" button immediately instead though, but it's a relatively minor issue and could be later handled globally.
