### ISSUE TITLE
Dashboard: when scrolling in logs, don't autoscroll for new logs

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3823]
### Describe your issue

While a test is running, and I open the logs, I try to scroll to the first logs of the execution. But as new logs are created, the logs automatically scroll down, losing many times what I'm looking for. 

### Describe a solution 

When manual scroll applied, do not autoscroll.

When scrolling back to the bottom, enable autoscroll again. 

This is similar to how terminal scrolling works.

**Comment by rangoo94** [comment]
It has been fixed with https://github.com/kubeshop/testkube-dashboard/pull/810.
