### ISSUE TITLE
TestKube 1.11.213 IPV6 regression on IPv4 system

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3846]
**Describe the bug**

testkubedashboard pods fails to start on K8S clusters with only IPV4 enabled with message

```
2023/05/16 16:13:19 [emerg] 1#1: socket() :8080 failed (97: Address family not supported by protocol)                                                                                                              
nginx: [emerg] socket() :8080 failed (97: Address family not supported by protocol) 
```

This seems to be caused by https://github.com/kubeshop/testkube-dashboard/pull/663 contributed as part of https://github.com/kubeshop/testkube/issues/3808

**Comment by vsukhin** [comment]
if we can't make nginx config uiversal, then  need to add a var to helm to manage ipv6 support

**Comment by gberche-orange** [comment]
great, thanks @rangoo94 for the prompt fix. Succesfully tested in [1.11.220](https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.11.220) in a IPV4 system.
