### ISSUE TITLE
Bugs and possible UI improvements on XYZ

### ISSUE THREAD

**Issue by Toxer10** [kubeshop/testkube#3852]
1. Wrong text size in execution:
<img width="200" alt="image" src="https://github.com/kubeshop/testkube/assets/25991946/3e40ed9a-5777-4d92-90bb-4dd0fea69335">

2. Wrong text size in no envs component:
<img width="539" alt="image" src="https://github.com/kubeshop/testkube/assets/25991946/c8e950e7-0d20-4426-9c06-ff52710461fd">

3. Could not add any steps to test suite, probably something is wrong with request payload.

4. Timeout did not work in test.

**Comment by rangoo94** [comment]
@Toxer10, could you create separate issues for each issue?

śr., 17 maj 2023, 16:39 użytkownik Toxer10 ***@***.***>
napisał:
