### ISSUE TITLE
Logs are not streaming correctly

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#3854]
**Describe the bug**

Details on video: 

https://github.com/kubeshop/testkube/assets/30776/2e9488fa-709a-4ed1-82d2-8fda0d0dfc20

**Comment by artem-zherdiev-ingio** [comment]
We have similar issue. During testkub run --watch logs just not appear at all.

**Comment by TheBrunoLopes** [comment]
Thanks for reporting it @artem-zherdiev-ingio 
@vsukhin @exu  do you know if the logs are still not stream correctly ?
