### ISSUE TITLE
testkube same values-demo.yaml nginx.ingress.kubernetes.io/server-snippet breaks new test run executions

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3861]
**Describe the bug**

When trying to run a new test from the dashboard, the execution fails with `Unknown error, something went wrong"

Turning on nginx ingress controller debugging traces, this seems to come from the `nginx.ingress.kubernetes.io/server-snippet` improperly parsing the POST request onto https://testkube-ui-00-core-connectivity-k8s.domain.org/tests/executions/02-testkube-sample-tests-kuttl-test-git-repo and returns a 401, which in turn translated into a 302 response by the nginx oauth ingress rules

https://github.com/kubeshop/helm-charts/blob/9f7fa970edd44be43e77f9af14f8044f928576ec/charts/testkube/values-demo.yaml#L167-L169

Folllowing is the related ngninx debug trace

```
2023/05/19 15:22:11 [debug] 29#29: *1183 http script regex: "^(.*)/tests/(.*)/executions$"
2023/05/19 15:22:11 [notice] 29#29: *1183 "^(.*)/tests/(.*)/executions$" does not match "/_external-auth-L3Jlc3VsdHMvKHZcZC8uKik-Prefix", client: 127.0.0.1, server: testkube-ui-00-core-connectivity-k8s.domain.org, request: "POST /results/v1/tests/test-website/executions HTTP/1.1", subrequest: "/_external-auth-L3Jlc3VsdHMvKHZcZC8uKik-Prefix", host: "testkube-ui-00-core-connectivity-k8s.domain.org", referrer: "https://testkube-ui-00-core-connectivity-k8s.domain.org/tests/executions/test-website"


2023/05/19 15:22:11 [notice] 29#29: *1183 "^(.*)/test-suite-executions/(.*)$" does not match "/_external-auth-L3Jlc3VsdHMvKHZcZC8uKik-Prefix", client: 127.0.0.1, server: testkube-ui-00-core-connectivity-k8s.domain.org, request: "POST /results/v1/tests/test-website/executions HTTP/1.1", subrequest: "/_external-auth-L3Jlc3VsdHMvKHZcZC8uKik-Prefix", host: "testkube-ui-00-core-connectivity-k8s.domain.org", referrer: "https://testkube-ui-00-core-connectivity-k8s.domain.org/tests/executions/test-website"
2023/05/19 15:22:11 [debug] 29#29: *1183 http script if
2023/05/19 15:22:11 [debug] 29#29: *1183 http script if: false
2023/05/19 15:22:11 [debug] 29#29: *1183 http script complex value
2023/05/19 15:22:11 [debug] 29#29: *1183 http script var: "true"
2023/05/19 15:22:11 [debug] 29#29: *1183 http script copy: "+"
2023/05/19 15:22:11 [debug] 29#29: *1183 http script var: ""
2023/05/19 15:22:11 [debug] 29#29: *1183 http script set $condition
2023/05/19 15:22:11 [debug] 29#29: *1183 http script var
2023/05/19 15:22:11 [debug] 29#29: *1183 http script var: "true+"
2023/05/19 15:22:11 [debug] 29#29: *1183 http script value: "true+true"
2023/05/19 15:22:11 [debug] 29#29: *1183 http script not equal
2023/05/19 15:22:11 [debug] 29#29: *1183 http script if
2023/05/19 15:22:11 [debug] 29#29: *1183 http finalize request: 401, "/_external-auth-L3Jlc3VsdHMvKHZcZC8uKik-Prefix?" a:1, c:2
```

What is the rationale for this snippet, is there dangerous unprotected endpoint in the api server that needs to be protected ?

If so, is there any possibility to harden the api-server to simplify this nginx snippet code ? 

If this snippet is required for security hardening, shouldn't it be in the templates part of the helm chart rather than only in the sample values-demo.yaml ?

**To Reproduce**

Run a new test from dashboard

**Expected behavior**

Success

**Version / Cluster**
- Which testkube version? 1.11.220
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**

![image](https://github.com/kubeshop/testkube/assets/4748380/7eef3df5-7b48-413a-ba33-c84ca2e3b658)
 
**Additional context**

**Comment by vsukhin** [comment]
hey @gberche-orange values-demo are for Testkube demo dashboard. We don't expect, that you will use it)

**Comment by gberche-orange** [comment]
thanks @vsukhin for looking into this ?

What is the rationale for this nginx.ingress.kubernetes.io/server-snippet for the testkube demo dashboard which is internet-facing AFAIK ? Is there dangerous unprotected endpoint in the api-server that needs to be protected ?

If so, is there any possibility to harden the api-server to simplify this nginx snippet code ?

If this snippet is required for security hardening, shouldn't it be in the templates part of the helm chart rather than only in the sample values-demo.yaml ?

**Comment by gberche-orange** [comment]
@vsukhin my bad, the demo dashboard instance is likely a read-only instance, with some api verbs being intentionally forbidden/disabled
