### ISSUE TITLE
Executor for additional frameworks - Robot Framework, Pytest, TestNG

### ISSUE THREAD

**Issue by surevs** [kubeshop/testkube#3862]
**Describe the enhancement you'd like to see**
Addition of support to Runner Enhancement so that Robot Framework, pytest, testng scripts also can be executed

**Additional context**
the way we have cypress integration - if we add up or provide more flexibility for pytest, robot framework testng natively available, it will help majority of folks for an easy shift and will help to run these tests at scale.

**Comment by aabedraba** [comment]
Thanks @surevs for the suggestion! 

Could you tell me what you mean exactly with "Runner Enhancement"? Is that a feature that's blocking you from adding new Runners?

**Comment by surevs** [comment]
we wish to have the runners added to testkube as we are in love the way it is executing cypress tests!

**Comment by surevs** [comment]
@aabedraba  - i see that all executor repo's are archived ( e.g: https://github.com/kubeshop/testkube-executor-cypress) and the readme documentation still refers to these archives. . is there any latest documentation which i could refer to and collaborate on this one ?
