### ISSUE TITLE
Jmeter reports without download them

### ISSUE THREAD

**Issue by kfirfer** [kubeshop/testkube#3864]
Hello

Currently if we want to see jmeter dashboards, we need to download it
it would be great if we could see the reports in under some nginx or some other way without download it

**Comment by vsukhin** [comment]
thank you @kfirfer nice idea! copying @aabedraba @TheBrunoLopes

**Comment by kfirfer** [comment]
@aabedraba Thanks !

**Comment by gberche-orange** [comment]
/CC @gberche-orange self-tracking this issue, duplicated by #4029

**Comment by vsukhin** [comment]
it might be good cloud feature @fivenp @TheBrunoLopes @rangoo94

**Comment by TheBrunoLopes** [comment]
Yes. Seems like we can extract and analyse Junit reports from the artifacts and have a section in the results dedicated to the Junit reports (or other type of standard reports in the future). What do you think ?

**Comment by rangoo94** [comment]
> Yes. Seems like we can extract and analyse Junit reports from the artifacts and have a section in the results dedicated to the Junit reports (or other type of standard reports in the future). What do you think ?

That is kind of a different feature, and that would be easily achievable. Downloading a single file (like `junit.xml`) and processing it is very simple, so we would be able to do it on the front-end, without any back-end work.

This ticket is much more complex, as it requires displaying a complete website from artifacts, that may consist of many assets, that link themselves together (i.e. HTML file with links to other HTML files, running some JS, displaying some tables and images)

**Comment by vsukhin** [comment]
Guess, both features should go to the cloud/enterprise

**Comment by vsukhin** [comment]
it's available in Po edition
