### ISSUE TITLE
Manage code CI/CD pipeline

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#387]
It's global task for tracking progress of work
on tag we want to have
- [x] release created with changelog (it’s done by goreleaser now)
- [x] build code
- [x] build docker images / push them
- [x] build helm charts / push them
- [x] inform on slack that new shiny version is ready
….. next steps ………..
- [x] deploy helm version on some cluster
- [x] inform on slack that test^3 is on cluster
- [x] run e2e test suite
- [x] inform on slack that e2e is completed with success/error (+what was fucked up)

**Comment by fog1985** [comment]
it has been done.
