### ISSUE TITLE
json output is not json

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#3871]
**Describe the bug**

![image](https://github.com/kubeshop/testkube/assets/30776/976232bf-5bac-489f-9298-f5c78fcffbeb)

It's not JSON output - those are a lot of lines with 2 separate json strings

**Expected behavior**

```
{
"test": {}
"latestExecution: {} 
}
```

**Comment by vsukhin** [comment]
{"id":"667567a8f73542a8004711a3","testName":"jmeterd-executor-smoke-slaves","testNamespace":"testkube","testType":"jmeterd/test","name":"jmeterd-executor-smoke-slaves-7","number":7,"command":["\u003centryPoint\u003e"],"args":["-n","-j","\u003clogFile\u003e","-t","\u003crunPath\u003e","-l","\u003cjtlFile\u003e","-o","\u003creportFile\u003e","-e","\u003cenvVars\u003e","-t","/data/repo/$JMETER_SCRIPT"],"variables":{"JMETER_SCRIPT":{"name":"JMETER_SCRIPT","value":"test/jmeter/executor-tests/jmeter-executor-smoke.jmx","type":"basic"},"SLAVES_COUNT":{"name":"SLAVES_COUNT","value":"2","type":"basic"}},"content":{"type":"git","repository":{"type":"git","uri":"https://github.com/kubeshop/testkube.git","branch":"main","path":"test/jmeter/executor-tests/jmeter-executor-smoke.jmx"}},"startTime":"2024-06-21T11:44:40.186Z","endTime":"2024-06-21T11:45:14.076Z","duration":"00:00:33","durationMs":33889,"executionResult":{"status":"passed","output":"🚚 Initializing...\n📦 Fetching test content from git...\nGit parameters: clone -b main --depth 1 --filter blob:none --sparse **************************************** repo\n✅ Test content fetched to path /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx\n📂 Fetching uploads from object store testkube-minio-service-testkube:9000...\n📂 Placing files from buckets into /data/uploads/ []\n📂 Getting the contents of bucket folders [test-jmeterd-executor-smoke-slaves execution-613b8bfc-b8a2-4d27-9848-4e093899c8da]\n{\"level\":\"info\",\"ts\":\"2024-06-21T11:44:43Z\",\"caller\":\"minio/minio.go:159\",\"msg\":\"listing files\",\"bucket\":\"testkube-artifacts\",\"bucketFolder\":\"test-jmeterd-executor-smoke-slaves\"}\n{\"level\":\"info\",\"ts\":\"2024-06-21T11:44:43Z\",\"caller\":\"minio/minio.go:159\",\"msg\":\"listing files\",\"bucket\":\"testkube-artifacts\",\"bucketFolder\":\"execution-613b8bfc-b8a2-4d27-9848-4e093899c8da\"}\n📂 Setting up access to files in /data\n🔬 Executing in directory /data: \n $ chmod \n✅ Execution succeeded\n✅ Access to files enabled\n✅ Initialization successful\n🚚 Preparing test runner\n✅ Uploading artifacts using MinIO Uploader\n✅ Environment variables read successfully\nRUNNER_ENDPOINT=\"testkube-minio-service-testkube:9000\"\nRUNNER_ACCESSKEYID=\"********\"\nRUNNER_SECRETACCESSKEY=\"********\"\nRUNNER_REGION=\"\"\nRUNNER_TOKEN=\"\"\nRUNNER_BUCKET=\"testkube-artifacts\"\nRUNNER_SSL=false\nRUNNER_SCRAPPERENABLED=\"true\"\nRUNNER_GITUSERNAME=\"\"\nRUNNER_GITTOKEN=\"\"\nRUNNER_DATADIR=\"/data\"\nRUNNER_COMPRESSARTIFACTS=\"true\"\nRUNNER_WORKINGDIR=\"/data/repo\"\nRUNNER_EXECUTIONID=\"667567a8f73542a8004711a3\"\nRUNNER_TESTNAME=\"jmeterd-executor-smoke-slaves\"\nRUNNER_EXECUTIONNUMBER=\"7\"\nRUNNER_CONTEXTTYPE=\"user-cli\"\nRUNNER_CONTEXTDATA=\"\"\nRUNNER_APIURI=\"http://testkube-api-server:8088\"\nRUNNER_CLUSTERID=\"clusterb153e5c17d2a36b0f73405a2f4d7216f\"\nRUNNER_CDEVENTS_TARGET=\"\"\nRUNNER_DASHBOARD_URI=\"\"\nRUNNER_CLOUD_MODE=\"false\" - DEPRECATED: please use RUNNER_PRO_MODE instead\nRUNNER_CLOUD_API_TLS_INSECURE=\"false\" - DEPRECATED: please use RUNNER_PRO_API_TLS_INSECURE instead\nRUNNER_CLOUD_API_URL=\"\" - DEPRECATED: please use RUNNER_PRO_API_URL instead\nRUNNER_CLOUD_API_KEY=\"\" - DEPRECATED: please use RUNNER_PRO_API_KEY instead\nRUNNER_CLOUD_CONNECTION_TIMEOUT=10 - DEPRECATED: please use RUNNER_PRO_CONNECTION_TIMEOUT instead\nRUNNER_CLOUD_API_SKIP_VERIFY=\"false\" - DEPRECATED: please use RUNNER_PRO_API_SKIP_VERIFY instead\nRUNNER_PRO_MODE=\"false\"\nRUNNER_PRO_API_TLS_INSECURE=\"false\"\nRUNNER_PRO_API_URL=\"\"\nRUNNER_PRO_API_KEY=\"\"\nRUNNER_PRO_CONNECTION_TIMEOUT=10\nRUNNER_PRO_API_SKIP_VERIFY=\"false\"\nrunning test [667567a8f73542a8004711a3]\n🚚 Running with config [scraperEnabled true dataDir /data SSL false endpoint testkube-minio-service-testkube:9000]\n🚚 Running in distributed mode\n❌ Could not find file $JMETER_SCRIPT in the directory, error: stat /data/repo/$JMETER_SCRIPT: no such file or directory\n🚨 Failed to resolve absolute directory for /data, using the path directly\n🚀 Creating slave pods: 2\nSuccessfully resolved slave pods IP addresses\n🌍 Using arguments: [-j output/jmeter.log -l output/report.jtl -o output/report -e -t /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx -n -R 10.244.2.196,10.244.2.197]\n🚀 Test run command /executor_entrypoint.sh -j output/jmeter.log -l output/report.jtl -o output/report -e -t /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx -n -R 10.244.2.196,10.244.2.197\n🔬 Executing in directory : \n $ /executor_entrypoint.sh -j output/jmeter.log -l output/report.jtl -o output/report -e -t /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx -n -R 10.244.2.196,10.244.2.197\nExecuting custom entrypoint script at /entrypoint.sh\n\n********************************************************\n*              Installing JMeter Plugins               *\n********************************************************\n\n\nNo user plugins provided as directory ./plugins is not present\n\n\nFile user.properties not present in .\n\n\nFile user.properties not present in ./properties\n\n\n********************************************************\n\n*            Initializing JMeter Master                *\n\n********************************************************\n\n\n\nSetting dynamically heap size based on available resources JVM_ARGS=-Xmn883m -Xms3535m -Xmx3535m\n\nAvailable memory: 4419 MB\n\nConfigured JVM_ARGS=-Xmn883m -Xms3535m -Xmx3535m\n\n\n********************************************************\n\n*                Executing JMeter tests                *\n\n********************************************************\n\n\nExecuting command: jmeter -j output/jmeter.log -l output/report.jtl -o output/report -e -t /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx -n -R 10.244.2.196,10.244.2.197 -Jserver.rmi.ssl.disable=true \n\n\nStarted CMD\n\nJun 21, 2024 11:45:01 AM java.util.prefs.FileSystemPreferences$1 run\nINFO: Created user preferences directory.\n\nCreating summariser \u003csummary\u003e\n\nCreated the tree successfully using /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx\n\nConfiguring remote engine: 10.244.2.196\n\nConfiguring remote engine: 10.244.2.197\n\nStarting distributed test with remote engines: [10.244.2.197, 10.244.2.196] @ 2024 Jun 21 11:45:01 UTC (1718970301788)\n\nRemote engines have been started:[10.244.2.197, 10.244.2.196]\n\nWaiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445\n\nsummary +      1 in 00:00:02 =    0.5/s Avg:  1878 Min:  1878 Max:  1878 Err:     0 (0.00%) Active: 2 Started: 2 Finished: 0\n\nsummary +      1 in 00:00:00 =   15.4/s Avg:  1989 Min:  1989 Max:  1989 Err:     0 (0.00%) Active: 0 Started: 2 Finished: 2\n\nsummary =      2 in 00:00:02 =    0.9/s Avg:  1933 Min:  1878 Max:  1989 Err:     0 (0.00%)\n\nTidying up remote @ 2024 Jun 21 11:45:04 UTC (1718970304364)\n\n... end of run\n\nEND Finished JMeter test on Fri Jun 21 11:45:10 UTC 2024 for test \n\n\n********************************************************\n*           JMeter test executions finished            *\n\n********************************************************\n\n\n✅ Execution succeeded\n📂 Getting report output/report.jtl\n✅ Mapped JMeter results to Execution Results...\n🚚 Running scraper to scrape for the following directories: [output] with masks: []\n{\"level\":\"info\",\"ts\":\"2024-06-21T11:45:10Z\",\"caller\":\"scraper/filesystem_extractor.go:52\",\"msg\":\"scraping artifacts in directory: output\"}\n{\"level\":\"info\",\"ts\":\"2024-06-21T11:45:10Z\",\"caller\":\"scraper/filesystem_extractor.go:122\",\"msg\":\"creating artifacts tarball with 129 files\"}\n{\"level\":\"info\",\"ts\":\"2024-06-21T11:45:10Z\",\"caller\":\"scraper/minio_uploader.go:49\",\"msg\":\"MinIO loader is uploading file\",\"file\":\"artifacts.tar.gz\",\"folder\":\"667567a8f73542a8004711a3\",\"size\":1013750}\n✅ Tests artifacts scrapped successfully!\n💡 Cleaning up slave pods after test run: jmeterd-executor-smoke-slaves-7-slave-2-667567a8f73542a8004711a3\n💡 Cleaning up slave pods after test run: jmeterd-executor-smoke-slaves-7-slave-1-667567a8f73542a8004711a3\ntest execution finished [667567a8f73542a8004711a3]\nExecuting custom entrypoint script at /entrypoint.sh\n********************************************************\n*              Installing JMeter Plugins               *\n********************************************************\n\nNo user plugins provided as directory ./plugins is not present\n\nFile user.properties not present in .\n\nFile user.properties not present in ./properties\n\n********************************************************\n*            Initializing JMeter Master                *\n********************************************************\n\nSetting dynamically heap size based on available resources JVM_ARGS=-Xmn883m -Xms3535m -Xmx3535m\nAvailable memory: 4419 MB\nConfigured JVM_ARGS=-Xmn883m -Xms3535m -Xmx3535m\n\n********************************************************\n*                Executing JMeter tests                *\n********************************************************\n\nExecuting command: jmeter -j output/jmeter.log -l output/report.jtl -o output/report -e -t /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx -n -R 10.244.2.196,10.244.2.197 -Jserver.rmi.ssl.disable=true \n\nStarted CMD\nJun 21, 2024 11:45:01 AM java.util.prefs.FileSystemPreferences$1 run\nINFO: Created user preferences directory.\nCreating summariser \u003csummary\u003e\nCreated the tree successfully using /data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx\nConfiguring remote engine: 10.244.2.196\nConfiguring remote engine: 10.244.2.197\nStarting distributed test with remote engines: [10.244.2.197, 10.244.2.196] @ 2024 Jun 21 11:45:01 UTC (1718970301788)\nRemote engines have been started:[10.244.2.197, 10.244.2.196]\nWaiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445\nsummary +      1 in 00:00:02 =    0.5/s Avg:  1878 Min:  1878 Max:  1878 Err:     0 (0.00%) Active: 2 Started: 2 Finished: 0\nsummary +      1 in 00:00:00 =   15.4/s Avg:  1989 Min:  1989 Max:  1989 Err:     0 (0.00%) Active: 0 Started: 2 Finished: 2\nsummary =      2 in 00:00:02 =    0.9/s Avg:  1933 Min:  1878 Max:  1989 Err:     0 (0.00%)\nTidying up remote @ 2024 Jun 21 11:45:04 UTC (1718970304364)\n... end of run\nEND Finished JMeter test on Fri Jun 21 11:45:10 UTC 2024 for test \n\n********************************************************\n*           JMeter test executions finished            *\n********************************************************\n\n\n","outputType":"text/plain","steps":[{"name":"Testkube - HTTP Request","duration":"1.878s","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request","status":"passed"}]},{"name":"Testkube - HTTP Request-0","duration":"253ms","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request-0","status":"passed"}]},{"name":"Testkube - HTTP Request-1","duration":"895ms","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request-1","status":"passed"}]},{"name":"Testkube - HTTP Request-2","duration":"723ms","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request-2","status":"passed"}]},{"name":"Testkube - HTTP Request","duration":"1.989s","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request","status":"passed"}]},{"name":"Testkube - HTTP Request-0","duration":"294ms","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request-0","status":"passed"}]},{"name":"Testkube - HTTP Request-1","duration":"1.1s","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request-1","status":"passed"}]},{"name":"Testkube - HTTP Request-2","duration":"589ms","status":"passed","assertionResults":[{"name":"Testkube - HTTP Request-2","status":"passed"}]}],"reports":{}},"labels":{"executor":"jmeterd-executor","test-type":"jmeterd-test"},"bucketName":"613b8bfc-b8a2-4d27-9848-4e093899c8da","runningContext":{"type":"user-cli"},"slavePodRequest":{"resources":{"requests":{"memory":"256Mi"},"limits":{"memory":"256Mi"}}}}
