### ISSUE TITLE
Test description updates in UI are not persisted

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3888]
**Describe the bug**

Seems that the Test description feature is not currently implemented in the backend, and therefore dashboard requests to update it are noop

**To Reproduce**
1. Update the description for a test
![image](https://github.com/kubeshop/testkube/assets/4748380/d9092017-b95b-4765-84b5-2965150169df)

2. Reload the page: no description is displayed
![image](https://github.com/kubeshop/testkube/assets/4748380/29988774-eb82-4b26-8806-0d99300f8622)

The API request sets `executionRequest.description` in the REST API, but this field is not available in the swager schema associated to create request https://docs.testkube.io/openapi/#tag/api/operation/createTest

![image](https://github.com/kubeshop/testkube/assets/4748380/7c3a725d-5f1f-4185-8719-1fad863adba2)

Also no `description` field  in the CRD  https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/tests.testkube.io_tests.yaml#L445-L445

**Expected behavior**

Ability to set and display test descriptions

**Version / Cluster**
- Which testkube version? 1.11.220
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Comment by vsukhin** [comment]
@gberche-orange yes, we don't have this field. should we add it @aabedraba @TheBrunoLopes

**Comment by aabedraba** [comment]
@gberche-orange thanks for the bug report! 

@vsukhin we should definitely add!

**Comment by pavloburchak** [comment]
@vsukhin any update on this one?

**Comment by vsukhin** [comment]
Low priority for now
