### ISSUE TITLE
UI: Filters dropdown looks bad

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#3908]
**Describe the bug**

After some of the recent changes, the filters dropdown started looking bad. It's most likely related to some changes for the dropdowns.

**Expected behavior**

It should look as before. @fivenp, could you confirm?

**Screenshots**

| [Before](https://testkube-dashboard-git-pavlo-global-settings-testkube-cloud.vercel.app/tests) | [After](https://dev.testkube.io/tests) |
|-|-|
| <img width="476" alt="Zrzut ekranu 2023-05-29 o 13 34 06" src="https://github.com/kubeshop/testkube/assets/3843526/daf7de88-b49b-4fb7-950e-e617d053e93b"> | <img width="355" alt="Zrzut ekranu 2023-05-29 o 13 33 47" src="https://github.com/kubeshop/testkube/assets/3843526/0b12aaab-4983-49f9-98da-a7bbeafd8d3b"> |

**Comment by fivenp** [comment]
100% agree
