### ISSUE TITLE
UI: allow to edit YAML 

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3923]
AC: 
All the pages that need to support it:

- Test Source
- Test
- TestSuite
- Webhook (no definition right now)
- TestTrigger (no definition right now)

At the moment, we start with something simple and once we need a more complex solution we might move to Monaco.

**Comment by aabedraba** [comment]
Figma files: https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?type=design&t=FlAmEDsLeDdoOlW9-0

**Comment by fivenp** [comment]
I personally would like to see 2 POCs to be able to say whether it's worth to go with a custom build solution or not.... 

1 – attach monaco with some autocomplete in one PR
2 – create a more lighter experience (with some autocomplete?) in another PR

then we can really "feel" if it's worth the effort or if monaco feels as slick as the other solution


> perhaps we can only lazy load monaco when the "edit mode" is on, which should improve things

Keep in mind – edit mode will be automatically on for everyone who navigates to the definition of a resource on OSS

**Comment by rangoo94** [comment]
@aabedraba, sure, we may see how Monaco Editor will integrate. If we will not encounter problems, it's an option.

To do that:
* We need to integrate Monaco Editor (with lazy load)
* We need to test `yaml` official language or Monokle's unofficial [`monaco-kubernetes`](https://www.npmjs.com/package/monaco-kubernetes) custom language
* We need to test if [**schemas**](https://microsoft.github.io/monaco-editor/typedoc/interfaces/languages.json.DiagnosticsOptions.html#schemas) will be able to validate our CRDs

It has a few obvious downsides:
* it's **big**, editor solely will weight 10x what our whole application does
* it's complex and not lightweight

**Comment by rangoo94** [comment]
@fivenp,

> 1 – attach monaco with some autocomplete in one PR
> 2 – create a more lighter experience (with some autocomplete?) in another PR

To be fair, if we want to have autocomplete and validation - we need to either make our own solution or use Monaco.

Own solution will take ~1 week (up to 2 weeks with improvements/fixes), Monaco - it depends on how smoothly it will go. Because of that, I would suggest trying Monaco, and only if we will decide that it's not possible or it's wrong idea - spend effort on our solution.

Alternatively, as a "lightweight" solution we could use something like `react-ace` or other libraries, but I don't know of any that would provide us with autocomplete/validation.

**Comment by aabedraba** [comment]
@fivenp can you provide the Figma designs for this?

**Comment by fivenp** [comment]
https://www.figma.com/file/asfUPepLHtyutWWR0pNGfK/Testkube-V2?type=design&node-id=3377-118885&t=q8U95cYwuybBBntz-4

**Comment by aabedraba** [comment]
@fivenp do you have an idea of what the UI should look like **before** updating?

**Comment by rangoo94** [comment]
@aabedraba, what do you mean by *before updating*?

**Comment by aabedraba** [comment]
@fivenp when landing in the _Definitions_ tab, I don't know if I'd offer the user the possiblity to directly edit the YAML. Instead I'd give them a "Edit" button (that's what I mean with _before updating_). Hopefully this can also help not loading Monaco ahead of the editing experience.

**Comment by fivenp** [comment]
I'd like to try out the approach of enabling Monaco right away – whenever you go to a definition page. 

I know it'll be overhead – and potentially slow – but from a UX perspective this is the slickest experience if you want to edit
I simply hope we'll not have too many loading implications with Monaco and it will still feel smooth :)

**Comment by rangoo94** [comment]
The feature has landed in `v1.13.0`. You may run `testkube upgrade` command to install the latest version.
