### ISSUE TITLE
Ingress-NGINX documentation error: Ingress.extensions "testkube-dashboard-testkube" is invalid

### ISSUE THREAD

**Issue by emomicrowave** [kubeshop/testkube#3930]
**Describe the bug**
I am currently following the documentation for [exposing the api and dashboard via an ingress.](https://docs.testkube.io/articles/exposing-testkube-with-ingress-nginx). Using the command provided under *Exposing testkube dashboard* to create a new deployment fails with the error message:

```log
user@machine:~/folder$  helm install testkube kubeshop/testkube --set testkube-dashboard.enabled="true" --set testkube-dashboard.ingress.enabled="true" --set testkube-api.ingress.enabled="true" -n testkube

Error: INSTALLATION FAILED: 1 error occurred:
        * Ingress.extensions "testkube-dashboard-testkube" is invalid: spec: Invalid value: []networking.IngressRule(nil): either `defaultBackend` or `rules` must be specified
```

**To Reproduce**
Probably could skip these first steps, but anyway
1. Install testkube on ubuntu
2. run `testkube init`
3. Notice there are no ingresses
4. Follow the documentation
    1. `helm repo add kubeshop https://kubeshop.github.io/helm-charts && helm repo update`
    2. `helm upgrade testkube kubeshop/testkube --set testkube-api.ingress.enabled="true"`
    3. This does not create an ingress
    4. `helm uninstall testkube`
    5. `helm install testkube kubeshop/testkube --set testkube-dashboard.enabled="true" --set testkube-dashboard.ingress.enabled="true" --set testkube-api.ingress.enabled="true"`
    6. Get error message

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
  - client version 1.11.7
  - commit c30d3514e2c2cf1ba041e592855d0cbd06fb450c
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  - minikube v1.30.1
- What Kubernetes version?
  - Kubernetes v1.26.3 on docker 23.0.2

**Screenshots**
 
**Additional context**

Since I am using the helm charts to create ingresses, any invalid configurations should be from the repo.

**Comment by aabedraba** [comment]
@ypoplavs I believe you wrote the docs for this one. 

Mind revising the instructions to see if it's a failure from our side?

**Comment by ypoplavs** [comment]
Hello @emomicrowave,

Please note that you need to specify hosts in your `values.yaml` file before you try to create Ingresses and keep in mind that hosts have to be identical for the dashboard and the api with different paths though:

```
testkube-dashboard:
   ingress:
        path: /
        hosts:
            - dns.testkube.io

testkube-api:
   uiIngress:
        path: path: /results/(v\d/.*)
        hosts:
            - dns.testkube.io
```
Also please do not forget about the annotations and TLS settings if you need to have secure connection. 
Please use our values file file as a reference:  https://github.com/kubeshop/helm-charts/blob/main/charts/testkube/values-demo.yaml#L334

We will update our docs to make this clearer.

**Comment by ypoplavs** [comment]
hi all, 
we have updated our docs for Ingress configuration: https://docs.testkube.io/articles/exposing-testkube-with-ingress-nginx/
Please let us know if anything is missing or unclear.
