### ISSUE TITLE
Dashboard - Create Test dialog - git username/token inputs are disabled, it's not possible to set them

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3934]
**Describe the bug**
Git username/token inputs are disabled in dashboard, it's not possible to set them during test creation.

**To Reproduce**
1. Try to create a test from private repo
2. Try to set git credentials
![Screenshot from 2023-05-31 14-19-29](https://github.com/kubeshop/testkube/assets/1473096/12334b1d-398c-4ae7-b833-77f3a371f897)

**Environment**
Integration/staging, Demo

**Comment by tkonieczny** [comment]
It's fixed in dev, but not merged to the release branch

**Comment by Toxer10** [comment]
Implemented [here](https://github.com/kubeshop/testkube-dashboard/pull/709).
