### ISSUE TITLE
Supporting concept of parallel execution of multiple instances of tests for scale test frameworks (k6, artillert, jmeter)

### ISSUE THREAD

**Issue by narioinc** [kubeshop/testkube#3939]
**Is your feature request related to a problem? Please describe.**
Frameworks such as k6, artillery and jmeter can take advantage of distributed compute orchestration provided by kubernetes to run tests at scale by running the same tests with some form of "parallelism". I would like to propose to the team to create a "parallelism" attribute for certain test case types. Currently i can see that Testkube is seemless in terms of creating one instance of such scale tests but I couldnt find a mechanism to run multiple instances of the scale tests to increase throughput to APIs being tested.

**Describe the solution you'd like**
If there is a attribute called "parallelism" introduced for certain test types (k6, jmeter, artillery) then it would allow teams to scale out their test cases to multiple pods and use the availably kubernetes resources to test out larger scale test scenarios. 

I do see some challenges here for testkube like result reconciliation if tests run in multiple pods and also showcasing the tests in the dashboard (showing 1 test in the dashboard vs showing "parallel instances" of tests) but I guess this wont be a problem for QA teams as they can reconcile their results from individual pods by shipping their results to DBs like prometheus.    

I can also see that if the team opens up the test suite feature to allow "parallel" executions of each test then it might be a good way to work around this problem. but again, since i am not sure of the internal result reconciliation workflow, i dont want to recommend something that might break existing system,  

**Describe alternatives you've considered**
I was thinking that i could use the test suite feature to create a "parallel" execution of multiple instances of the same test. For example, create 4 k6 tests with the same script and just create a suite that runs these 4 tests in parallel, but from the documentation i can see that the tests are more synchronous and wait for each of the test suite steps to complete to trigger the next test. I might be wrong if i overlooked something that allows parallel execution of tests, please do correct me here. 

**Additional context**
K6 operator is a good example how k6 allowed creating multiple instances of their tests which can run on multiple pods, and allow using the available k8s compute resources effectively: https://github.com/grafana/k6-operator

**Comment by narioinc** [comment]
Team, my bad i can see that TEst sub sets allow this feature request for now.
I can see that there was a pretty neat PR open which has some examples for this feature: https://github.com/kubeshop/testkube/pull/3135

Closing this issue for now.

**Comment by vsukhin** [comment]
hey @narioinc yes, thank you for such a detailed request. we should merge that PR in next releaseeeeeee

**Comment by narioinc** [comment]
@vsukhin thanks for addressing this.
One issue that might be something to look towards for the Testkube team is a documentation showcasing the "batch" API within the test Kube suite APIs. I came to know of the feature only when snooping around for the same in the repo. Having this officially documented in the online documentation and the API Objects (TestSuiteStep object in this scenario) would be great. 

I am planning to get some Medium article to spread the work about the awesome work this project is accomplishing ! :)

**Comment by vsukhin** [comment]
Sure, @narioinc Yes, we're working on improving docs, but we still have a lot to improve
Awesome, thank you! Feel free to share it with us @aabedraba @alelthomas

**Comment by narioinc** [comment]
@vsukhin 

Was just curious, when the "batch" feature going to be released ? I saw the API docs and TestSuiteStep API object still doesnt show a "batch" json object within it. thanks.

**Comment by vsukhin** [comment]
hey, @narioinc we should start working on this feature this week, can't give you a precise ETA, but it's 1-2 week work
