### ISSUE TITLE
unable to upload cypress artifact to s3 bucket

### ISSUE THREAD

**Issue by orilani** [kubeshop/testkube#3941]
**Describe the bug**
unable to upload cypress artifact to s3 bucket

**Expected behavior**
uploading cypress artifacts include screenshots + videos to s3 bucket

**Version / Cluster**
- Which testkube version?  - 1.11.222
- What Kubernetes cluster? - eks 
- What Kubernetes version? - 1.26

**Screenshots**
{"level":"error","ts":1685607267.8358946,"caller":"server/httpserver.go:76","msg":"failed to list artifacts for execution 64784e93e0d21f7987eff2e2: storage client could not list files 301 Moved Permanently","status":500

**Additional context**
set all necessary values for iam role using on minio.serviceAccountName & testkube-api.jobServiceAccountName & leave empty minioRootUser + minioRootPassword & testkube-api.storage.accessKeyId/accessKey empty and set for testkube-api.endpoint s3.amazonaws.com

any idea why artifact are not even trying to uploaded to s3 bucket? what am i missing?

**Comment by nicufk** [comment]
Hey @orilani, you have to add the arn to the `testkube-api.serviceAccount.annotations`, I updated thedocumentation in the PR from above.

**Comment by orilani** [comment]
hey @nicufk i've updated the values file and not im getting this line on the api-server:
{"level":"info","ts":1685865678.6662037,"caller":"minio/minio.go:189","msg":"listing files","bucket":"*-testkube-artifacts","bucketFolder":"647c447eeee571740e1931ed"} but no files on the s3 bucket being uploaded.
