### ISSUE TITLE
creating test scripts - detect test type

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#395]
**Describe the enhancement you'd like to see**
Currently I can create test which is curl test with invalid type (e.g. when omit test type there is default postman/collection passed) 

We want to autodetect test type based on content 
we could parse json files in case of postman and curl file based content 

in case of git ? we should discuss it - git is chcked out in executor so in API we don't have any file contents - so we would need to check it out again and test for content. OR maybe moving data to API is a case with minion or something ?

**Comment by exu** [comment]
@jasmingacic @nicufk what do you think about this issue any thoughts ?

**Comment by jasmingacic** [comment]
It is doable. Probably we will have to some format for tests to make it simpler for us.
