### ISSUE TITLE
When I create an executor from the CLI it doesn't appear in the dashboard

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3951]
I ran this command: 

```sh 
$ testkube create executor --name example --types example -- image node:18-alpine

Executor created example 🥇
```

When I open the dashboard it doesn't appear: 
 
![CleanShot 2023-06-02 at 09 37 50](https://github.com/kubeshop/testkube/assets/27779735/a6eba343-519d-4d82-a510-fcd13b1bfe14)

But I can see it part of the request: 

![CleanShot 2023-06-02 at 09 38 29](https://github.com/kubeshop/testkube/assets/27779735/693bd54b-c84c-45fd-b490-05946909bb6a)

**Comment by rangoo94** [comment]
There are two problems with the command:

* There is a whitespace between `--` and `image`, so the image is not set (`-- image`)
* There is missing `--executor-type container` parameter

The final command should be:
```
$ testkube create executor --executor-type container --name example --types example --image node:18-alpine
```

I'm not sure though yet, what should be the behavior when the custom `job` executor is created - on the one hand we don't support its configuration on the UI, on the other it's not visible in the "Official" section too.

Probably it should be mentioned on the `Custom Executors` page, just as read-only.

**Comment by rangoo94** [comment]
There are two problems with the command:

* There is a whitespace between `--` and `image`, so the image is not set (`-- image`)
* There is missing `--executor-type container` parameter

The final command should be:
```
$ testkube create executor --executor-type container --name example --types example --image node:18-alpine
```

I'm not sure though yet, what should be the behavior when the custom `job` executor is created - on the one hand we don't support its configuration on the UI, on the other it's not visible in the "Official" section too.

Probably it should be mentioned on the `Custom Executors` page, just as read-only.

Cc: @fivenp

**Comment by aabedraba** [comment]
Thanks @rangoo94 for debugging. 

@fivenp as Dawid described, we don't show custom pre-built executors in the dashboard. Is that intentional?

**Comment by fivenp** [comment]
thats def. not intentional - and we should show them all :)

**Comment by rangoo94** [comment]
Thanks @fivenp. Should there be any settings page for the pre-built executors?

**Comment by fivenp** [comment]
thats where the problems come into play.... since we dont consolidate executors in a single view yet - this will become problematic...

can we see the fix for this issue being the story where we want to consolidate all executors into one - non tabbed view?

**Comment by aabedraba** [comment]
Will close this and follow up in a different ticket.
