### ISSUE TITLE
unable to upload cypress artifact to s3 bucket

### ISSUE THREAD

**Issue by orilani** [kubeshop/testkube#3960]
Describe the bug
unable to upload cypress artifact to s3 bucket

Expected behavior
uploading cypress artifacts include screenshots + videos to s3 bucket

Version / Cluster

Which testkube version? - 1.11.222
What Kubernetes cluster? - eks
What Kubernetes version? - 1.26
Screenshots
{"level":"info","ts":1685865678.6662037,"caller":"minio/minio.go:189","msg":"listing files","bucket":"*-testkube-artifacts","bucketFolder":"647c447eeee571740e1931ed"}

Additional context
set all necessary values for iam role using on minio.serviceAccountName & testkube-api.jobServiceAccountName & leave empty minioRootUser + minioRootPassword & testkube-api.storage.accessKeyId/accessKey empty and set for testkube-api.endpoint s3.amazonaws.com
 updated the values.yaml per @nicufk comment here https://github.com/kubeshop/testkube/issues/3941

any idea why artifact are not even trying to uploaded to s3 bucket? what am i missing?

**Comment by orilani** [comment]
also im seeing this error in the testkube api-server :`{"level":"error","ts":1685876914.4363723,"caller":"containerexecutor/logs.go:44","msg":"can't get pod logs, pod failed: testkube/647c6da4eee571740e1931fc-szmpz","podNamespace":"testkube","podName":"647c6da4eee571740e1931fc-szmpz","podStatus":{"phase":"Failed","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-06-04T10:55:36Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2023-06-04T11:08:28Z","reason":"PodFailed"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2023-06-04T11:08:28Z","reason":"PodFailed"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-06-04T10:55:32Z"}],"hostIP":"10.5.2.4","podIP":"10.5.2.175","podIPs":[{"ip":"10.5.2.175"}],"startTime":"2023-06-04T10:55:32Z","initContainerStatuses":[{"name":"647c6da4eee571740e1931fc-init","state":{"terminated":{"exitCode":0,"reason":"Completed","startedAt":"2023-06-04T10:55:33Z","finishedAt":"2023-06-04T10:55:35Z","containerID":"containerd://f37caad2189eccb8d223bb0aba35390d71764626660420e44bc6eb75876271aa"}},"lastState":{},"ready":true,"restartCount":0,"image":"docker.io/kubeshop/testkube-init-executor:1.11.29","imageID":"docker.io/kubeshop/testkube-init-executor@sha256:0d43c2d539022294e218c5d03b50f0f7ab4c5c325c3a9576f2756b400db58dae","containerID":"containerd://f37caad2189eccb8d223bb0aba35390d71764626660420e44bc6eb75876271aa"}],"containerStatuses":[{"name":"647c6da4eee571740e1931fc","state":{"terminated":{"exitCode":1,"reason":"Error","startedAt":"2023-06-04T10:55:37Z","finishedAt":"2023-06-04T11:08:27Z","containerID":"containerd://f483b2b299fa7468b32c3d51d83367c68323ec2cb54be93b8ac763852d881359"}},"lastState":{},"ready":false,"restartCount":0,"image":"docker.io/kubeshop/testkube-cypress-executor:cypress12","imageID":"docker.io/kubeshop/testkube-cypress-executor@sha256:9b61ee7601ce8efa4440e9b0de0f9c68f7ab6e40dd92d1210e2a6dfa1774b0a4","containerID":"containerd://f483b2b299fa7468b32c3d51d83367c68323ec2cb54be93b8ac763852d881359","started":false}],"qosClass":"BestEffort"},"stacktrace":"github.com/kubeshop/testkube/pkg/executor/containerexecutor.TailJobLogs\n\t/home/runner/work/testkube/testkube/pkg/executor/containerexecutor/logs.go:44\ngithub.com/kubeshop/testkube/pkg/executor/containerexecutor.(*ContainerExecutor).Logs.func1\n\t/home/runner/work/testkube/testkube/pkg/executor/containerexecutor/containerexecutor.go:188"}
`

**Comment by vsukhin** [comment]
hey @orilani any logs in your minio pod?

**Comment by orilani** [comment]
@vsukhin nothing other the startup logs:
`Formatting 1st pool, 1 set(s), 1 drives per set.
13
WARNING: Host local has more than 0 drives of set. A host failure will result in data becoming unavailable.
12
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
11
MinIO Object Storage Server
10
Copyright: 2015-2023 MinIO, Inc.
9
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
8
Version: RELEASE.2023-06-02T23-17-26Z (go1.19.9 linux/arm64)
7
6
Status:         1 Online, 0 Offline.
5
S3-API: http://*:9000  http://127.0.0.1:9000
4
Console: http://*:9090 http://127.0.0.1:9090
3
2
Documentation: https://min.io/docs/minio/linux/index.html
1
Warning: The standard parity is set to 0. This can lead to data loss.
 `

**Comment by vsukhin** [comment]
Hmm, it looks weird, we use same credentials for both logs and artifacts, might be networking issues, the real difference between them is size. Do you see any errors in the executor pod 98765... when it's finished?

**Comment by orilani** [comment]
@vsukhin the executer itself finished the cypress testing with error... but noting in the logs that look related to artifacts upload or artifacts at all...

**Comment by orilani** [comment]
@vsukhin  for example:
`frontend-e2e:   │ ✔  workspace/users.spec.ts                  00:13        1        1        -        -        - │
frontend-e2e:   └────────────────────────────────────────────────────────────────────────────────────────────────┘
frontend-e2e:     ✖  15 of 35 failed (43%)                    08:49       35       20       15        -        -  
frontend-e2e: ----------------------------------------------------------------------------------------------------
frontend-e2e:   Having trouble debugging your CI failures?
frontend-e2e:   
frontend-e2e:   Record your runs to Cypress Cloud to watch video recordings for each test, 
frontend-e2e:   debug failing and flaky tests, and integrate with your favorite tools.
frontend-e2e:   >> https://on.cypress.io/cloud-get-started
frontend-e2e: ----------------------------------------------------------------------------------------------------

 

 >  NX   Running target e2e for project frontend-e2e failed

   Failed tasks:
   
   - frontend-e2e:e2e`

**Comment by vsukhin** [comment]
Artifacts might not be ready in case of failure. Are you sure, that your files were generated?

**Comment by orilani** [comment]
@vsukhin yes theres and screentshots and videos outputs that i can see in the executer pod

**Comment by nicufk** [comment]
Hey @orilani have you tried to use the api-server ServiceAccount in testkube-api.jobServiceAccountName

**Comment by TheBrunoLopes** [comment]
closing this issue for now.
please report if this issue is still ongoing so we can reopen and investigate.
