### ISSUE TITLE
Implement remaining work on Test Suites V3

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#3969]
Current pain points with the v2 and/or v3 yaml are:

- There's fields that are present but don't work. such has the namespace field in the yaml inside a test step. We should allow the tests to run in the according namespace (if feasible) or remove the field entirely if not.
- We introduced the batch & items object that go inside each step of the execution which make the yaml more verbose and complex.
This is the current V2 yaml

![Image](https://github.com/kubeshop/testkube/assets/13501228/495004b3-2ff0-4511-8c87-822aa2088281)

instead of adding the objects batch and items in each step (sorry don't have an v3 examples to put here)

Could it instead look something like this:

![Image](https://github.com/kubeshop/testkube/assets/13501228/dc08e7c2-4e25-4966-815f-212963a3e86f)

(yaml for illustration purposes, sintax may not be 100% correct)

note: name is changed to test. there's no support for both.

- Is there any other field we should change ?

**Action points:**

- Review yaml and refactor accordingly.
- Implement UI seen in the mockup and change CLI as needed.
- v2 test suites should still be supported

**Comment by vsukhin** [comment]
it will be a bit more structured, like
- execute:
  - test:[name: test1], delay:[duration: 100], test:[name:test2]

**Comment by TheBrunoLopes** [comment]
what's the use case for having an array inside the test object ?
having` test:[name: test1]` -> instead of `test: "some_name"` seems more complicated.
