### ISSUE TITLE
Running test image in container executor - [Testkube]

### ISSUE THREAD

**Issue by HIMSAI724** [kubeshop/testkube#3979]
**Is your feature request related to a problem? Please describe.**

In order to run the test , we would like to containerise the test files and run as standalone. These test are integration test which sometime part of the product code. There are some e2e tests which are individual which can also be containerise and run.

**Describe the solution you'd like**
Expecting a test input type as "image" along with git, file, string options in Testkube and empty runner which supports Testkube apis. 

**Describe alternatives you've considered**

I have thought to create custom executor which has only docker image installed and have arg with docker pull and run command. I have created test as input string which has only image tag. Now when i run this test on custom docker container then ideally it should pick the image and run the docker pull/run command. Somehow i was facing issue to start docker instance in conatiner to run those command. And also i was not sure if this is correct approach or not. Docker in docker is not recommended as some says. 

So here i am opening the feature request to address this requirement.

Thanks.

**Comment by vsukhin** [comment]
thank you @HIMSAI724 we will think about it

**Comment by ili-shmidt-wib** [comment]
I am supporting this use-case. 
Each of our tests are written as a standalone-container and we want to run it without creating an executor with this image in advance.

**Comment by vsukhin** [comment]
@TheBrunoLopes @aabedraba please plan it out

**Comment by vsukhin** [comment]
So, this feature iis already in place.
Create an empty container executor

apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: empty-runner
  namespace: testkube
spec:
  types:
  - empty/test
  executor_type: container

Then you can use it for any tests and any images, any command and args, for example
Everything can be customized

apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: empty-test
  namespace: testkube
spec:
  type: empty/test
  executionRequest:
    image: soleware/nx-cli:8.5.2
    command:
    - "/bin/bash"
    - "-c"
    - "pwd; echo 'hello world!'"
