### ISSUE TITLE
Make grace-period configurable for executor

### ISSUE THREAD

**Issue by f-helm** [kubeshop/testkube#3985]
**Describe the enhancement you'd like to see**

Add an option to customize the --grace-period on an executor basis for test abortion. Currently, grace-period is set to 0 when a test is aborted making it impossible to catch a SIGTERM signal in the executor.

Setting a custom grace-period would enable a graceful shutdown for the executor and for example make it possible to scrape artifacts before executor pod is terminated. Could be set in CRD via spec.gracePeriod for example.

**Comment by f-helm** [comment]
Not sure if it would make sense to also add this on a per test-basis, since a graceful shutdown only makes sense if it is implemented in the executor, but would allow more flexibility if implemented.

**Comment by vsukhin** [comment]
thank you @f-helm looks like an interesting idea

**Comment by vsukhin** [comment]
guess, it will be possible after implementation  of this ticket https://github.com/kubeshop/testkube/issues/4043
