### ISSUE TITLE
Plane text credentials used in value.yaml [Testkube Helm chart]

### ISSUE THREAD

**Issue by HIMSAI724** [kubeshop/testkube#3990]
**Is your feature request related to a problem? Please describe.**
There are couple of credentials and access key are defined as plain text in testkube value.yml file. some are as follows
minioRootUser, minioRootPassword, accessKeyId, accessKey

Instead of hard coding these we want to take the credentials from secret manager.

**Describe the solution you'd like**
Taking data from secret instead. 

I want to take data from aws secret manager. So need implementation in way that secret is mounted in the pod. 

https://aws.amazon.com/ko/blogs/security/how-to-use-aws-secrets-configuration-provider-with-kubernetes-secrets-store-csi-driver/

**Comment by ypoplavs** [comment]
PR was merged https://github.com/kubeshop/helm-charts/pull/557 and will be released by the of the week.

**Comment by ypoplavs** [comment]
hi @HIMSAI724!
We have added an option to use secrets and volumes so now you should be able to grab data from aws secrets manager. Please upgrade Testkube and let us know about the results.
