### ISSUE TITLE
UI: Download All Artifacts Button in Tab "Artifacts"

### ISSUE THREAD

**Issue by saadisfy** [kubeshop/testkube#4003]
**Is your feature request related to a problem? Please describe.**
My Tests generate multiple artifacts, which also have an underlying directory structure. Downloading in the current way means going file by file and clicking the corresponding download button. This also destroys the original directory structure and renames the original file names. 
This is troublesome if the generated Report is for example an HTML report, and the underlying directory contain important assets.

**Describe the solution you'd like**
Instead of downloading each file one by one, a button downloading everything at once (as an archive maybe) would be easier. 

**Describe alternatives you've considered**
Some kind of directory-based downloads, so that the downloaded Artifacts keep their original (relative) path or enabling an option to zip some selected files before downloading them.

**Additional context**

More detailed example:

The Test generates an HTML-Report. Using the default Artifact Scraper. I scrape everything from the directory "target" with a structure like this:
```
|- target
    |-surefire-reports
       |- res  # directory containing bootstrap files
       ... # other HTML based files using the directory res
```
       
In the Testkube Dashboard's Tab "Artifact" all files would shown in the same directory level:
```
|- Artifact 
    |-fileA.html
    |-fileB
    ...
    |-surefire-reports/res/fileC
    
```

Downloading from the UI would result in all files being in the same directory level, and the files in the directory "res" would be renamed to` "surefire-reports_res_fileC" `destroying the paths used for the HTML-based Report file.

**Comment by vsukhin** [comment]
thank you @saadisfy !
