### ISSUE TITLE
Secrets are not created as SecretRefs

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#4005]
## Details: 

https://github.com/kubeshop/testkube/assets/27779735/94b108d2-8bd5-4383-aa4b-ae272c2bfbc9

## Acceptance Criteria: 
- secrets should be created as SecretRefs

## Testing Criteria: 
- as this is a regression, a test case should be created for it.

**Comment by rangoo94** [comment]
Looks like it's an API bug, as it's not always reproducible.

1. Given: a test from the previous version, that had a secret converted to secret ref
2. Added a new secret - it was converted to secret ref too
3. Deleted all secret refs
4. Added a new secret - it stays as a secret

It has to be connected to the previous version though - when I created a new test, with some custom secret ref, these scenario didn't work - it stays as a secret all the time.
