### ISSUE TITLE
Dashboard UI: Creation of tests fails with TestSource ref.

### ISSUE THREAD

**Issue by Svensson11** [kubeshop/testkube#4009]
**Describe the bug**
When trying to use the Dashboard UI for creating any type of test with the reference to an existing testsource the creation fails with the following error:

![image](https://github.com/kubeshop/testkube/assets/40796616/878a1516-df18-4370-9e81-f052d0720d49)

**To Reproduce**
1. Open the Dashboard
2. Create a new testsvia UI & select an existing testsource as the source
3. See error

**Expected behavior**
Proper Test resource is created with the testsource as a reference inside the spec.

**Version / Cluster**
- 1.12.4
- AKS 
- 1.24.6

**Comment by rangoo94** [comment]
Thank you @Svensson11 for the report! I will try to fix it shortly 👍

**Comment by rangoo94** [comment]
Hi @Svensson11, sorry for the inconvenience, and once again thanks for the report! The fix has been released, you may update your Testkube cluster with the `testkube install` or `testkube upgrade` command.
