### ISSUE TITLE
Trigger new test execution from CR

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#4017]
**Is your feature request related to a problem? Please describe.**

As a testkube user 
In order to trigger a test execution from a gitops K8S controller (as a workaround for #4007 and #3712)
I need testkube to offer a way to trigger a test from a k8s resource

**Describe the solution you'd like**

A new TestExecution CRD that can trigger a testexecution + provide status on its execution

**Describe alternatives you've considered**

Use the tk rest api or tk cli. 

* With fluxcd, the generic webhook notification https://fluxcd.io/flux/components/notification/provider/#generic-webhook don't seem to allow for the required http request transformation to match the tk api. A testkube [flux provider](https://fluxcd.io/flux/components/notification/provider/) could be developped in go
* With kapp controller, would require instead running a Job with the tk cli being invoked. 

**Additional context**

https://discord.com/channels/884464549347074049/1113808657843507200/1116703138469138503

**Comment by vsukhin** [comment]
thank you @gberche-orange

**Comment by aabedraba** [comment]
@gberche-orange we've looked at it and I don't think we understand fully your request. 
Mind having a quick call to discuss it: https://calendly.com/bruno-at-kubeshop/15-minute-meeting

**Comment by vsukhin** [comment]
will start working on it

**Comment by tkonieczny** [comment]
`postman-executor-smoke` Test triggered with `testexecution-postman-test` TestExecution:

- runningContext - incorect type is returned (`testsuiteexecution`)
- Trigger is empty in UI
![Screenshot from 2023-08-24 11-30-56](https://github.com/kubeshop/testkube/assets/1473096/8960b131-ecc9-46a1-bacd-0832670452ab)

**Comment by ghostsquad** [comment]
How do you trigger a new execution? The docs say that you need to update the CR in some way. Like a timestamp perhaps or an annotation/label of the associate gitsha that's being deploy?
