### ISSUE TITLE
Serve web artifacts within dashboard (e.g. junit.html report)

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#4029]
**Describe the enhancement you'd like to see**

As a testkube user
In order to display test reports within the testkube dashboard
I need most artifacts http request to include a `content-type` header to be detected from their extensions 

**Additional context**

Currently, artifacts served from the testkube rest api such as https://testkube-ui.mydomain.org/results/v1/executions/648893c862b70b1853b6a8e9/artifacts/junit.html?testName=test-kuttl-data return a `Content-Type: text/plain; charset=utf-8` header

As a result, artefacts can not be browsed inline within the tk dashboard

Given multiple artefacts with relative links such as a junit.html with linked css/js/images files, then the report can not be browsed within the dashboard ui

![artefact](https://github.com/kubeshop/testkube/assets/4748380/bc066d54-413d-4e2f-a30e-efe1a0f9da57)

** workaround **

publish an archive file (e.g. a zip or tgz) that the user need to download and expand on their local computer before visualizing.

**Comment by vsukhin** [comment]
guess, we have similar issue https://github.com/kubeshop/testkube/issues/3864

**Comment by gberche-orange** [comment]
thanks @vsukhin, I did not see #3864, therefore closing as duplicate
