### ISSUE TITLE
UI: autocomplete for test filter labels

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#4031]
**Describe the enhancement you'd like to see**

As a test kube user
In order to regularly use the test filters with label name and value
I need autocompletion of label names and label values from history

**Additional context**

As of 1.12.8 , no autocomplete is proposed 

![filter-autocomplete-2](https://github.com/kubeshop/testkube/assets/4748380/6b144fe8-48f7-4d5f-8b6a-d289f3d26045)

**Comment by rangoo94** [comment]
@vsukhin, do we have API to get the list of labels?

**Comment by vsukhin** [comment]
No, it was a low priority till now, up to @TheBrunoLopes to make it a bit more important

**Comment by TheBrunoLopes** [comment]
looks good to me, bumped it to high

**Comment by vsukhin** [comment]
ok, will work after template crd

**Comment by rangoo94** [comment]
Looks like there is already an API endpoint to get the list of labels:
```
curl https://demo.testkube.io/results/v1/labels
```

So it's strictly front-end task. Marking as "Ready" to do.

**Comment by pavloburchak** [comment]
@fivenp I remember we wanted to refactor this labels filter to reuse UI component we have. Do you have some ideas according it?

**Comment by fivenp** [comment]
I think for this first iteration we can just allow to autocomplete the key and the value. 

I think the initial behaviour will be -> a user can select a key but when they type a value they will see all available values (it is not bound to the key context)
