### ISSUE TITLE
Test status not updated correctly

### ISSUE THREAD

**Issue by VishwasSomasekhariah** [kubeshop/testkube#4034]
The final test status is not set to failed when thresholds are breached. 

**Steps to reproduce**
- Set threshold on 'http_req_failed', in my case 'rate < 0.01'.
- Implement an assertion to check the response status and mark any requests other than 200 response code as a failed request. 
- During the test execution kill the pod running the application that the load is being generated on.

**Expected behavior**
- All the redirected HTTP requests should now be marked as failed.
- 'http_req_failed' count should increase.
- If we see a failure rate of more than 1% then mark the test as failed.

**Version / Cluster**
- Testkube version: 1.12.3
- EKS Cluster
- Kubernetes version: 1.23

**Screenshots**
![image](https://github.com/kubeshop/testkube/assets/115732758/7e03cca1-3f6e-4049-8c03-6dff5b568ba4)
You can see in the error message that some thresholds have failed but the status is still set to passed.

**Comment by vLia** [comment]
Thank you @VishwasSomasekhariah for reporting this issue. As I was trying to reproduce it, I created a failing threshold test using the string:
```
import http from 'k6/http';

export const options = {
  thresholds: {
    http_req_failed: ['rate<0.01'], // http errors should be less than 1%
    http_req_duration: ['p(95)<200'], // 95% of requests should be below 200ms
  },
};

export default function () {
  http.get('https://test-api.k6.io/public/crocodiles/101/');
}
```
I did indeed get the line marking one `test step` of the test as passed:
```
$ kubectl logs -f jobs/649030528e9505f6cba40858 -n testkube

time=\"2023-06-19T10:39:18Z\" level=error msg=\"thresholds on metrics 'http_req_failed' have been breached\"\n","outputType":"text/plain","errorMessage":"some thresholds have failed","steps":[{"name":"default: 1 iterations for each of 1 VUs (maxDuration: 10m0s, gracefulStop: 30s)","duration":"00m00.4s/10m0s","status":"passed"}]},"time":"2023-06-19T10:39:18.228908585Z"}
```
The status of the Testkube test was still `failed`:
```
$ testkube get tests | grep threshold

k6-test-threshold-failing | k6/script      | 2023-06-19 10:33:50 +0000 UTC | executor=k6-executor,          |          | failed | 649030528e9505f6cba40858
```

Could you please double-check if the status of the test shown with `testkube get tests` is `passed`?

**Comment by VishwasSomasekhariah** [comment]
Thank you for getting back to me. What do you mean by the "test step of the test as passed"?

**Comment by avinashkna4** [comment]
@vLia Thanks for the response. you are right, we are indeed getting the "executionResult":{"status":"failed"..... We will utilize this field for now.

**Comment by vLia** [comment]
Perfect, please let us know if anything else comes up. Closing this issue now.

**Comment by VishwasSomasekhariah** [comment]
Hi @vLia, you are correct that for our use case, we only worry about the final result of the whole test run. As @avinashkna4 mentioned, we can confirm that the `Status` field of the `ExecutionResult` is being set correctly as failed and we can make use of it for now. 
Thank you for the assist again.
