### ISSUE TITLE
UI: Support mobile display

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4073]
**Why should it be implemented?**

The UI is not usable at all on mobile devices. We would like to make sure, that the User is able to see our demo application on mobile, or log in to Cloud.

**Describe the improvement**

* Use proper `meta[name=viewport]`
  * Probably `width=device-width,initial-scale=1,shrink-to-fit=no` will be fine for us
* Set up properly `minItemWidth` for the `EntityGrid` items
   * This way, we will have the grid automatically changing the size
* Use (probably global) `(max-width: XXXpx)` media queries, make the website look well on mobile devices
  * It will be cheap and fast (`min-width` will take more time, and will be mobile-first)
  * This way we will achieve a desktop-first experience (as we do now), having a graceful degradation for mobile devices

**Comment by rangoo94** [comment]
* It would be best to do it incrementally, with regular PRs (i.e. 1 per day, or 2 per day)
* We should verify all changes if these work well in both Cloud and Open Source
* We have an initial threshold for 2 days of work

**Comment by tkonieczny** [comment]
I think full test names should be displayed:
![Screenshot_20230823-202455](https://github.com/kubeshop/testkube/assets/1473096/00fdf617-a58d-464f-b09c-68a08c1936ec)
Filters aren't adjusted:
![Uploading Screenshot_20230823-202541.png…]()

**Comment by rangoo94** [comment]
This task was mostly meant to make the application usable on the mobile devices.

> Filters aren't adjusted:

What do you mean by that? On this page the only filter is for the timeframe, and it looks like it works fine for me:

<img width="738" alt="Zrzut ekranu 2023-08-24 o 17 14 02" src="https://github.com/kubeshop/testkube/assets/3843526/a8f567eb-cdae-45b9-9c9b-d6b8384b545f">

**Comment by tkonieczny** [comment]
Looks like I uploaded the wrong screenshot:
![Screenshot_20230823-202541](https://github.com/kubeshop/testkube/assets/1473096/c3a8e1bf-73a3-4c0c-b21b-bfe3f68db7fe)
