### ISSUE TITLE
UI Sidebar for Testsuite Execution Doesn't Scroll

### ISSUE THREAD

**Issue by HaneyHamdy** [kubeshop/testkube#4076]
**Describe the bug**
The UI Sidebar for Testsuite Execution Doesn't Scroll if there are more tests in the testsuite than the viewport can show. 

**To Reproduce**
1. Create a testsuite with a bunch of tests in it, the ui doesn't appear to allow you to scroll through them 

**Expected behavior**
I'd expect this sidebar to allow a scrolling effect to view all tests within the panel. 

**Version / Cluster**
- Which testkube version? 
1.12.1

**Screenshots**
<img width="1913" alt="Screen Shot 2023-06-20 at 10 31 13 AM" src="https://github.com/kubeshop/testkube/assets/22298745/2db82b64-0c57-44f5-b6ac-34802ba19212">

**Comment by rangoo94** [comment]
The fix has landed in `v1.13.0`. You may run `testkube upgrade` command to install the latest version.
