### ISSUE TITLE
Dashboard logs for tests executed outside of timeframe: 7 days

### ISSUE THREAD

**Issue by ahmedimf1** [kubeshop/testkube#4083]
**Describe the bug**

Although I have executed a test before, the test execution page on the dashboard says:
> Trigger your first run
> Your test has no past executions. Trigger the first run!

This behaviour happens for any test that was not executed recently (outside of 7 days timeframe). Also, the timeframe selector is invisible. 

**To Reproduce**
1- Execute a test
2- wait more than 7 days
3- try to find the old logs -> not found because the default timeframe is 7 days.
4- try to find the “Timeframe” drop-down -> not found 

Example:
https://demo.testkube.io/tests/executions/custom-curl 

**Expected behavior**

- For tests that have been executed at any point in time, the user can browse test execution logs

- The message:

> Your test has no past executions. Trigger the first run!

is not shown/could be less misleading

**Version / Cluster**

same as:
https://demo.testkube.io/tests/executions/custom-curl

**Comment by rangoo94** [comment]
Hi @ahmedimf1 , thank you for the report! I started code cleanup for that view, so I'll fix it during that.

@fivenp , should we rephrase that information, or handle that differently? I think that we could rephrase it and add button "Search for all time", that would simplify the flow.
