### ISSUE TITLE
Dashboard UI: Log output full screen mode

### ISSUE THREAD

**Issue by haneabogdan** [kubeshop/testkube#4100]
**Describe the bug**

**To Reproduce**
1. Open a test execution
2. Click on Full screen button

**Expected behavior**
Execution details shouldn't be visible at all and only the log output should be displayed.

**Screenshots**
<img width="1663" alt="Screenshot 2023-06-29 at 08 36 44" src="https://github.com/kubeshop/testkube/assets/10533775/77edeebd-701d-4bf4-8199-0905db8fa690">

 
**Additional context**

**Comment by rangoo94** [comment]
Fixed with https://github.com/kubeshop/testkube-dashboard/pull/754.

The fix has landed in `v1.13.0`. You may run `testkube upgrade` command to install the latest version.
