### ISSUE TITLE
ArgoCD Sidecar implementation

### ISSUE THREAD

**Issue by Plork** [kubeshop/testkube#4102]
**Why should it be implemented?**
The configMap plugin method  as described [here](https://docs.testkube.io/articles/argocd-integration#6-configure-argocd-to-use-the-testkube-plugin) will be deprecated in ArgoCD 2.7.

https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#configmap-plugin

**Describe the improvement**
Provide a ArgoCD CMP sidecar container that can be configured in ArgoCD to use testkube in gitops way of working.
 
**Additional context**
https://argo-cd.readthedocs.io/en/stable/operator-manual/config-management-plugins/#sidecar-plugin

**Comment by opsroller** [comment]
Why is this relevant at all? I deploy all kinds of CRD's via ArgoCD without the need for any plugins.

**Comment by Plork** [comment]
The documentation from TestKube is explaining a depricated way to install the integration. So either remove it ... or change it I would say.

**Comment by ypoplavs** [comment]
Hello @Plork!
We have updated documentation on how to use Testkube as a sidecar. Please try and let us know about the results:
https://testkube.io/blog/a-gitops-powered-kubernetes-testing-machine-with-argocd-and-testkube
