### ISSUE TITLE
Cucumber executor

### ISSUE THREAD

**Issue by hobti01** [kubeshop/testkube#4114]
**Is your feature request related to a problem? Please describe.**
Our testers would like to create tests with cucumber that run in TestKube

**Describe the solution you'd like**
We'd love to see a Cucumber executor for TestKube

**Describe alternatives you've considered**
We're thinking of a custom executor but this would be our first attempt at a custom executor and we're wary of getting it right within a reasonable timeframe.

**Additional context**
We're already using other executors, but need this additional framework for our testers.

**Comment by vsukhin** [comment]
thank you @hobti01 let's @TheBrunoLopes to check it out

**Comment by vsukhin** [comment]
@hobti01 do we need to support any particular language or framework?

**Comment by hobti01** [comment]
Hi @vsukhin , thanks for asking the question.  I have been able to talk to our testing group and in fact they are using playwright to drive the tests - so we don't actually need anything with regards to cucumber and we can use the playwright executor.  Thanks for your attention and apologies for the noise!

**Comment by vsukhin** [comment]
you're welcome, @hobti01 any questions are welcome :)

**Comment by hobti01** [comment]
Hi @vsukhin, there was a misunderstanding on our side.  Actually the request here is to run [cucumber-js](https://github.com/cucumber/cucumber-js).  It looks like the expectation is to run this via `npm`.

So I'm not sure this would be different than any framework where we need to run `npm install; npm run XYZ`.  Do you plan to have an "npm executor" like you have for maven or would we need to create a custom executor in this case?

**Comment by vsukhin** [comment]
I would suggest to check our container executor feature http://docs.testkube.io/test-types/container-executor

**Comment by hobti01** [comment]
Yep ok, we'll do that thanks!
