### ISSUE TITLE
Error starting tests managed by Flux

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4116]
**Describe the bug**
I see the below error on the Dashboard when running a test managed by Flux. I have a Git Repo hosting the Tests, Test Suites, Sources, and Executors CRDs and have Flux reconcile and apply them. 
```
failed to execute test: execution failed: can't create new test execution, can't insert into storage: write exception: write errors: [Document can't have '.' in field names: kustomize.toolkit.fluxcd.io/name], context: null
```

**Version / Cluster**
- Which testkube version? 1.12.11
- What Kubernetes cluster? AWS EKS
- What Kubernetes version? 1.24
 
**Additional context**
The same tests run without any errors if they are not managed by Flux and manually applied to the cluster. I use AWS DocumentDB 5.0 engine version.

**Comment by vsukhin** [comment]
hey @michaelsatish Interesting bug, it's MongoDb issue https://stackoverflow.com/questions/22192197/uncaught-exception-cant-have-in-field-names
Where do you have `kustomize.toolkit.fluxcd.io/name`, is label, annotation or something else?

**Comment by michaelsatish** [comment]
@vsukhin Flux adds the below 2 labels 

```
kustomize.toolkit.fluxcd.io/name
kustomize.toolkit.fluxcd.io/namespace
```
Thanks for sharing the link. I am not well-versed in using MongoDB. Are they suggesting inserting it as sub-documents?
```json
{ "$set": { 
    "fields": {
        "kustomize": {
            "toolkit": {
                "fluxcd": {
                    "io/name": "test"
                }
            }
        }
    }
}
```

**Comment by vsukhin** [comment]
Because, Mongo is json native, it treats such labels as json pathes, which in fact they are not.
Technically, we have 2 options, either we escape such labels on Testkube side and replace dots by underscores, something like `kustomize_toolkit_fluxcd_io` or you can? do it o Flux side

**Comment by rangoo94** [comment]
Dots are common for labels/annotations, so we should rather support that. We could i.e. replace dots with `U+FF0E` (`．`), and convert back to dot on retrieval.

**Comment by michaelsatish** [comment]
I see support for field names with periods with MongoDB version 5.0
https://www.mongodb.com/docs/manual/core/dot-dollar-considerations/#field-names-with-periods--.--and-dollar-signs----

Periods are common on labels. I doubt Flux has option to avoid those labels
