### ISSUE TITLE
JUnit Report - Additional Tab

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4120]
**Is your feature request related to a problem? Please describe.**
A single Testkube Test will most likely run many project tests. If testkube can visually show the JUnit report in a separate tab, it will allow for quick access to the statuses of the individual tests instead of going through logs or using API to fetch the steps. 

![image](https://github.com/kubeshop/testkube/assets/20645040/3b7ecfe3-486c-4263-b58c-b462fd6e39ef)

Example tabular representation of individual tests.

<img width="1284" alt="image" src="https://github.com/kubeshop/testkube/assets/20645040/e91230cb-ed52-438e-b29b-41a430c4e46f">

**Comment by vsukhin** [comment]
thank you @michaelsatish good idea!

**Comment by vsukhin** [comment]
@fivenp So, we have some junit parsed data for our pre-built executors in API response, we can use this data or we can start collecting junit report as a file to make it similatr with junit report from container executors

**Comment by vsukhin** [comment]
dupicated #4887
