### ISSUE TITLE
Opt-out from calls to public URLs for testkube instances deployed in local K8s clusters

### ISSUE THREAD

**Issue by swacongne** [kubeshop/testkube#4135]
**Describe the enhancement you'd like to see**
Calls to app.posthog.com and google-analytics contain potentially confidential information (test names in test URLs, etc.). 
Would it be possible to add an opt-out option in the values.yaml for those external calls?

**Additional context**
N/A

**Comment by vsukhin** [comment]
hey @swacongne  you can disable telemtry for all Testkube components, we have helm char var for this https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml#L622 . @rangoo94 can elaborate more about UI

**Comment by rangoo94** [comment]
Hi @swacongne!

These external calls are multi-level opt-in:
* You need to accept the cookie consent on the dashboard
* You need to have telemetry enabled on the Testkube cluster
  * Even if you opt-in on the user consent, but the cluster has disabled telemetry, so does the dashboard

If you want to force disabled telemetry on installation, you may either:
* use `disableTelemetry: false` Helm variable to disable front-end telemetry, or
* disable the telemetry in the cluster - @vsukhin, could you guide as per https://github.com/kubeshop/testkube/issues/3622?

**Comment by swacongne** [comment]
Thanks.
@vsukhin We need to have the telemetry disabled in the cluster too: what should we update in the `values.yaml` for that? It's not clear for me what to do event after reading issue #3622 .

**Comment by vsukhin** [comment]
Yes, we have a variable `analyticsEnabled: false` in values file

**Comment by vsukhin** [comment]
hope, it works for you
