### ISSUE TITLE
Artifact Scraper generic artifacts storage

### ISSUE THREAD

**Issue by koenekle** [kubeshop/testkube#4153]
**Describe the enhancement you'd like to see**
We are currently evaluating testkube and have tested deploying testkube with minio and with an other S3 compliant storage solution. 

I was surprised that the form of the artifacts differs whether I use minio or supply preexisting access keys.
With minio: 
- artifacts do not get zipped

When supplying access keys:
- artifacts are placed within an archive "artifacts.tar.gz"

I would love to have the same functionality with exisiting storage keys as with minio, as this enables selecting the artifacts I want to download from the Dashboard and not downloading all the artifacts.

**Additional context**

Tested with:

-  https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.12.26
-  https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.12.1

Configuration: 
 https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml#L402-L404

**Comment by vsukhin** [comment]
Hey, @koenekle Yes, minio has a feature for archiving files on the fly, but it's not supported by all cloud providers.
Still both UI and CLI allows you to download a single artifacts file or all them in zipped archive, for example, https://demo.testkube.io/tests/executions/jmeter-executor-smoke-env-and-property-values/execution/64abc639136d53366f6b5a16

**Comment by koenekle** [comment]
Hey @vsukhin, 
Yes I saw the Dashboard with minio and I thought it is awesome. Your Demo is setup with minio, correct?

With an other storage backend however, I would prefer having them still as seperate files and not having the possibility to download them as a zipped archive.

If I have understood you correctly currently this is the case: 
`
minio-scraper --> upload single files to minio --> dashboard display   --> single file display
                                                                                                                     --> dynamic archive creation
`
other cloud providers:

`
generic-scraper --> upload archive file --> dashboard display   -->   NO single file display
                                                                                                           -->  download pre-zipped archive
`


I think however it would make more sense, not to try to mimic the "nice feature" of minio or having a parameter to change the following behaviour:
`
generic-scraper --> upload single files -->  dashboard display   -->  single file display
                                                                                                            --> NO zipped-archive display
`

I am suggesting this, as I also have other UIs for accessing my S3 buckets, but they now only have a folder with a single zip archive, which I have to download as a whole. My other UI has also the possibility to download the folder as an archive.
