### ISSUE TITLE
UI: no horizontal scrollbar on test view forbid access to left part when large chart is displayed

### ISSUE THREAD

**Issue by davidB** [kubeshop/testkube#4165]
**Describe the bug**

When lot of run test are displayed in the bar chart, the with of frame is larger than the windows and it's impossible to scroll to left to access settings and other buttons (no horizontal scrollbar on the frame, no possibility to select text and move to left to force scrolling)

**To Reproduce**

Launch lot of tests (200 in my case) in short period of time (less than day). (eg with a every minutes schedule)

**Expected behavior**

- being able to access buttons, and the left part whatever the number of tests displayed (or the width of the displayed elements)
- possibilities:
  - width of the chart aligned to the width of the parent window and not on the content + a horizontal
  - having the horizontal scrollbar on the windows
  - allow to select in the time window: the `last 1h` or the `last 10 executions`

**Version / Cluster**
- Which testkube version? docker.io/kubeshop/testkube-dashboard:1.13.0
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.23

**Screenshots**

![imagen](https://github.com/kubeshop/testkube/assets/10675/783e2bfe-53db-4e6f-abbe-81d5d19c427b)

 
**Additional context**

I'm exploring/playing with testkube for 2 days. And I misconfigured the cron instead of `0 */3 * * *`(every 3h), I setup every minutes during 1h every 3h `* */3 * *` and it ran during the night. I was able to edit the setting by modifying the k8s manifest directly.

Thanks for your great tool. (I'll not have to create custom cronjobs, tests reporter, ...)

**Comment by vsukhin** [comment]
thank you @davidB we will ask our front end team to check this out @rangoo94 @pavloburchak

**Comment by davidB** [comment]
Another way to reproduce, or to see it: reduce the width of the browser window to be smaller than the chart. you can try with https://demo.testkube.io/tests/executions/postman-executor-smoke-negative

![imagen](https://github.com/kubeshop/testkube/assets/10675/0161251c-97af-41b5-a838-9805c1c754e9)

**Comment by rangoo94** [comment]
Hi @davidB, sorry for the delay - the fix is already released in the latest version. To upgrade Testkube, you may run `testkube upgrade` command.

Thanks for the report!

**Comment by davidB** [comment]
Thanks for the quick reply and fix, I'll upgrade via our helm chart.
