### ISSUE TITLE
Docs: Section for 'Jenkins' in CI/CD Integration

### ISSUE THREAD

**Issue by khirzer** [kubeshop/testkube#4177]
Can you please add a section on integration with Jenkins in documentation (CI/CD Integration - https://docs.testkube.io/articles/cicd-overview)?

Thanks!

**Comment by vsukhin** [comment]
thank you @khirzer  not sure, we ever tried out. we have examples of Github integration, might be @ypoplavs can take a look how to call Testkube cli from Jenkins

**Comment by ypoplavs** [comment]
Hello @khirzer,
 
As of now we do not have a Jenkins plugin in place to call Testkube. However, you may install TK cli and create and run tests in a shell step of you pipeline: https://www.jenkins.io/doc/book/pipeline/pipeline-best-practices/#running-shell-scripts-in-jenkins-pipeline

**Comment by khirzer** [comment]
Thank you @ypoplavs for this hint!

**Comment by khirzer** [comment]
@vsukhin 

Why this issue was closed although the requested documentation in https://docs.testkube.io/articles/cicd-overview/ is still missing?

**Comment by vsukhin** [comment]
ok, let's reopen it and add documentaion page

**Comment by vsukhin** [comment]
http://docs.testkube.io/articles/jenkins
