### ISSUE TITLE
Create Python Executor

### ISSUE THREAD

**Issue by TheBrunoLopes** [kubeshop/testkube#4188]
AC:
- Should be container executor
- Use the latest version of Python
- Should have Pipenv, Poetry and Conda. If it gets too big, we can remove poetry and/or conda.
- Docs:
    - Should include Dockerfile
    - Steps on how to use a python test and examples of tests using pytest, requirements.txt, Pipfile, etc...
    - Suggestion on what a user should do if they need to change python version, etc...

**Comment by 123371** [comment]
If this helps, I created my own Python executor and have been using it for some time. 

```go
// runner.go

lockFile := filepath.Join(runPath, "Pipfile.lock")
_, err := executor.Run(runPath, "pipenv", nil, "install", "--deploy", "--system")

args := []string{"--junitxml", "junit.xml"}
args = append(args, execution.Args...)

output.PrintEvent("Running", "pytest with args", args)
out, err := executor.Run(runPath, "pytest", nil, args...)
```

```dockerfile
# Dockerfile
FROM golang:1.20.5-alpine3.18 AS builder

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN set -ex \
    && go mod download \
    && go mod verify

COPY . .
RUN set -ex \
    && CGO_ENABLED=0 GOOS=linux go build -a -o runner ./cmd/agent

FROM python:3.8.17-alpine3.18 as runner

RUN set -ex \
    && python3 -m pip install --upgrade --no-cache-dir pip \
    && python3 -m pip install \
        --no-cache-dir \
        --upgrade pipenv

COPY --from=builder --chown=$USER_UID:$USER_GID --chmod=775 /usr/src/app/runner /bin/runner
ENTRYPOINT ["/bin/runner"]
```

There should be an executor image for all supported python versions.
https://devguide.python.org/versions/

**Comment by TheBrunoLopes** [comment]
thanks a lot @123371 
I notice that that type of executor is prebuilt, if you don't mind sharing, what made you decide not to go with Container executor. Was there anything lacking ?

**Comment by michaelsatish** [comment]
Commenting back from my Github profile 

If this helps, I created my own Python executor and have been using it for some time. 

    ```go
    // runner.go

    lockFile := filepath.Join(runPath, "Pipfile.lock")
    _, err := executor.Run(runPath, "pipenv", nil, "install", "--deploy", "--system")

    args := []string{"--junitxml", "junit.xml"}
    args = append(args, execution.Args...)

    output.PrintEvent("Running", "pytest with args", args)
    out, err := executor.Run(runPath, "pytest", nil, args...)
    ```

    ```dockerfile
    # Dockerfile
    FROM golang:1.20.5-alpine3.18 AS builder

    WORKDIR /usr/src/app

    COPY go.mod go.sum ./
    RUN set -ex \
        && go mod download \
        && go mod verify

    COPY . .
    RUN set -ex \
        && CGO_ENABLED=0 GOOS=linux go build -a -o runner ./cmd/agent

    FROM python:3.8.17-alpine3.18 as runner

    RUN set -ex \
        && python3 -m pip install --upgrade --no-cache-dir pip \
        && python3 -m pip install \
            --no-cache-dir \
            --upgrade pipenv

    COPY --from=builder --chown=$USER_UID:$USER_GID --chmod=775 /usr/src/app/runner /bin/runner
    ENTRYPOINT ["/bin/runner"]
    ```

    There should be an executor image for all supported python versions.
    https://devguide.python.org/versions/

**Comment by michaelsatish** [comment]
Commenting back from my correct profile. 

If this helps, I created my own Python executor and have been using it for some time. 

    ```go
    // runner.go

    lockFile := filepath.Join(runPath, "Pipfile.lock")
    _, err := executor.Run(runPath, "pipenv", nil, "install", "--deploy", "--system")

    args := []string{"--junitxml", "junit.xml"}
    args = append(args, execution.Args...)

    output.PrintEvent("Running", "pytest with args", args)
    out, err := executor.Run(runPath, "pytest", nil, args...)
    ```

    ```dockerfile
    # Dockerfile
    FROM golang:1.20.5-alpine3.18 AS builder

    WORKDIR /usr/src/app

    COPY go.mod go.sum ./
    RUN set -ex \
        && go mod download \
        && go mod verify

    COPY . .
    RUN set -ex \
        && CGO_ENABLED=0 GOOS=linux go build -a -o runner ./cmd/agent

    FROM python:3.8.17-alpine3.18 as runner

    RUN set -ex \
        && python3 -m pip install --upgrade --no-cache-dir pip \
        && python3 -m pip install \
            --no-cache-dir \
            --upgrade pipenv

    COPY --from=builder --chown=$USER_UID:$USER_GID --chmod=775 /usr/src/app/runner /bin/runner
    ENTRYPOINT ["/bin/runner"]
    ```

    There should be an executor image for all supported python versions.
    https://devguide.python.org/versions/

**Comment by michaelsatish** [comment]
@TheBrunoLopes It is not prebuild. I'd built a custom job executor type and using it in my organization.

**Comment by michaelsatish** [comment]
@TheBrunoLopes My bad I didn't read your question carefully and assumed prebuilt as in out-of-the-box executors. If I recall correctly, the container executors enforce the test artifacts are created in a specific directory on a dynamically created volume. I run an AWS EKS Fargate cluster that does not support dynamic volume provisioning. So never went down the container route and ended up scraped the artifacts using the prebuilt. Having said this, If there is a workaround, I'd change to container executor as it is the recommended approach. 

```go
ctx := context.Background()
scraper, err := factory.GetScraper(ctx, r.Params, factory.ArchiveFilesystemExtractor, factory.MinIOUploader)
```

https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/dynamic_provisioning/README.md#dynamic-provisioning

**Comment by TheBrunoLopes** [comment]
I see @michaelsatish 
Thank you for your feedback!
We are exploring solutions to make container executors as flexible as possible so people can do all the things that they are doing currently with the pre-built ones. We will look into how to improve the artefacts handling in the container executors as well 👌
