### ISSUE TITLE
Test cases are skipped when run in parallel

### ISSUE THREAD

**Issue by naveenreddymanukonda** [kubeshop/testkube#4193]
When we tried Testkube for the first time, we had a small machine configuration with 2 CPUs and 16 GB of RAM. At that time, we were only able to run 2 tests in parallel. Later, we upgraded the machine to 8 CPUs and 32 GB of RAM, but we found that we could still only run 10 tests in parallel. When I attempt to run more than 10 tests in parallel, all the test cases are skipped, even though they work as expected when run individually.

Can we configure the queue mechanism instead of skipping the test cases?

**Comment by vsukhin** [comment]
hey @naveenreddymanukonda we have a parameter to define conucrency level. you can either supply it with Testsuite CRD or when you run your testsuite using CLI option. Have you tried it out?
`--concurrency int                            concurrency level for multiple test suite execution (default 10)`

**Comment by naveenreddymanukonda** [comment]
@vsukhin I deployed testkube through helm charts, can you please provide me with the documentation where we can add concurrency value?
Do we have any slack or Telegram channel to communicate on testkube-related items

**Comment by naveenreddymanukonda** [comment]
@vsukhin we are not able to join the discord channel you mentioned
we want to run a max of 3 tests in parallel, which we didn't create any suite we want to run only 3 tests in parallel we done this configuration from helm can you please help us with where we can update concurrency value, it would be really helpful

**Comment by Anveshd** [comment]
Hi @vsukhin 

Is there any way to maintain a queue mechanism for **Tests** in Testkube? As I have 8 CPUs, I am able to run 8 Cypress tests concurrently. If there are more than 8 test cases, they will be skipped in each test.

**Comment by vsukhin** [comment]
ok, I will provide an example of TestSuite CRD @naveenreddymanukonda

**Comment by vsukhin** [comment]
@Anveshd you mean for each single Testkube cypress test you have 8 cypress test cases?

**Comment by Anveshd** [comment]
Oh Sorry. Type error

I have 10 Cypress tests, and each test has 10 test cases. When I execute 8 tests in parallel, I do not face any issues. However, when I try to execute all 10 tests at the same time, all test cases are skipped in each test.

**Comment by vsukhin** [comment]
I guess, it's a bit confusion, we do have parallel tests for Testkube testsuite and you can define concurrency level as in cli command like above for Testkube tests. Testkube tests are placed in the queue. Cypress test can also have multiple test cases, you can run them parallely using `--parallel` option https://docs.cypress.io/guides/cloud/smart-orchestration/parallelization . But you can't control concurreny level for Cypress test. If you need it, you can create Testkube testsuite and and create a Testkube test for each Cypress test case and define concurrency level for Testkueb testsuite

**Comment by naveenreddymanukonda** [comment]
@vsukhin any update on how to provide CRD value for limiting parallel execution in testkube for executing cypress Tests

**Comment by vsukhin** [comment]
hey, @naveenreddymanukonda I   can suggest an approach above, becuase cypress doesn't support this limit. You can create 1 Testkube test = 1 cypress test and create Testkube testsuite, last one supports number of parallel tests

**Comment by naveenreddymanukonda** [comment]
hey @vsukhin does the below code snippet work if we add this in the testkube-api file
parallelExecution:
  maxParallelExecutions: 10

**Comment by vsukhin** [comment]
no, where did you take it?

**Comment by vsukhin** [comment]
It's Cypess related feature,  which is not supported by Cypress, please create Testkube test suites

**Comment by TheBrunoLopes** [comment]
Hey @naveenreddymanukonda seems like you have an interesting case with Cypress tests
I would love to know more about your testing process
Would you like to hop on a quick call ? here's my callendly link for your convinience ;)
https://calendly.com/bruno-at-kubeshop/30min-1
