### ISSUE TITLE
Unable to use pm.IterationData with Postman

### ISSUE THREAD

**Issue by quanglee** [kubeshop/testkube#4197]
Hi guys,

I successfully integrated Testkube into our K8S cluster along with our CI flow. Everything is working well.

Regarding postman, I used this syntax to run without testkube
```
newman run “./collections/SAMPLE.json” -e “./env/SAMPLE_ENV.json” -d “./data/SAMPLE_DATA_USE_FOR_ITERATION.json”
```
This is a sample in my SAMPLE_DATA_USE_FOR_ITERATION.json

```json
[
    "authentication" : {
         "username" : "username",
         "password" : "password"
    }
]
``` 

This is a Pre-request Script in Postman
```
let dataObject = pm.iterationData.get("authentication");
var username = dataObject.username;
var password = dataObject.password ;
pm.variables.set("username",username);
pm.variables.set("password", password);
```

Would be better if we have a -d option in testkube which is similar to -d one in Postman?

PS: Actually I can use to create a test. However, it seems that testkuke executed newman command cannot read this file.
```
--executor-args "-d /data/test-content/Data.json" \
```

To be honest, it would be great it we have an option --iteration-data flags in testkube which is similar to --variables-file. 

Thanks

**Comment by vsukhin** [comment]
hey @quanglee 
We have multiple ways to pass your data file to newman 
1. You can store your postman collection in git repo together with data.json, they will be automatically downloaded to /data/repo folder
2. You can pass your data file using CLI option `--copy-files stringArray                     file path mappings from host to pod of form source:destination` and it will be stored in /data/uploads folder
3. You can provide prerun script and download it using wget and store in data folder

**Comment by quanglee** [comment]
Thanks @vsukhin ,

I already tried the third option :)

For first option, I didn't know /data/repo, but I will try it

Much appreciated your support.

PS: Testkube is great bro ;)

**Comment by vsukhin** [comment]
welcome, bro)
