### ISSUE TITLE
jmeter executor fails when the report.jtl file is in xml format

### ISSUE THREAD

**Issue by vignesh77l** [kubeshop/testkube#4200]
Hi Testkube Team,

jmeter executor by default generates the execution report.jtl in CSV format, but for our use case, we are setting the jmeter to generate the report.jtl file in XML format via jmeter.properties , due to this the the jmeter executor fails just before 
`✅ Mapped JMeter results to Execution Results` stage 
with below parse error in executor pod logs` 2023/07/21 15:28:16 parse error on line 1, column 15: bare " in non-quoted-field`
<img width="719" alt="image" src="https://github.com/kubeshop/testkube/assets/140182118/3e3132eb-0fda-4162-ad19-6cfd9df15583">
<img width="432" alt="image" src="https://github.com/kubeshop/testkube/assets/140182118/55933cad-b8a1-49b5-aa6e-a1d5aff74efc">

looks like this due to https://github.com/kubeshop/testkube/blob/develop/contrib/executor/jmeter/pkg/runner/runner.go#L177

could you please help in fixing this issue to support download/copy of report.jtl file when it is in XML format as well

Many thanks in advance for your suppport

Regards,
Vignesh Loganathan

**Comment by vsukhin** [comment]
hey, @vignesh77l could you please provide for testing your list of arguments?

**Comment by vignesh77l** [comment]
Hi @vsukhin, 
```
🌍 Using arguments: [-n -j /data/output/jmeter.log -t /data/repo/24.0/REGRESSION/GR-Alarms.jmx -l /data/output/report.jtl ]
🚀 Test run command /executor_entrypoint.sh -n -j /data/output/jmeter.log -t /data/repo/24.0/REGRESSION/GR-Alarms.jmx -l /data/output/report.jtl 
🔬 Executing in directory /data:
```

`below working yaml to be added to UI after creating new executor myjmeter-executor
----------------------------------------------------------------------------------
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: myjmeter-executor
  namespace: testkube
spec:
  executor_type: job
  image: kubeshop/testkube-jmeter-executor:1.13.3
  imagepullsecrets: []
  command:
  - <entryPoint>
  args:
  - -n
  - -j
  - <logFile>
  - -t
  - <runPath>
  - -l
  - <jtlFile>
  - <envVars>
  types:
  - myjmeter/test
  uri: ""
  content_types:
  - string
  - file-uri
  - git-file
  - git-dir
  - git
  jobtemplate: ""
  labels: {}
  features:
  - artifacts
  meta:
    iconuri: jmeter
    docsuri: https://kubeshop.github.io/testkube/test-types/executor-jmeter
    tooltips: {}
executions: null`

args:
  - -n
  - -j
  - <logFile>
  - -t
  - <runPath>
  - -l
  - <jtlFile>
  - <envVars>
