### ISSUE TITLE
Info message in execution description for failed execution because the deadline was reached

### ISSUE THREAD

**Issue by esebrei** [kubeshop/testkube#4204]
**Describe the enhancement you'd like to see**

There is no info in the execution output, if an execution does fail because the configured deadline timeout was reached:

```bash
testkube get execution [execution_id]

[omitted...]

Test execution failed:

pods "64bf6c36d3bdfa9a749420b4-7fvms" not found
```

I have to look into the Kubernetes events to figure out, that the jobs was killed because of a timeout:

```bash
kubernetes -n testkube get events
16s         Normal    SuccessfulCreate       job/64bf6c36d3bdfa9a749420b4         Created pod: 64bf6c36d3bdfa9a749420b4-7fvms
0s          Normal    SuccessfulDelete       job/64bf6c36d3bdfa9a749420b4         Deleted pod: 64bf6c36d3bdfa9a749420b4-7fvms
0s          Normal    Killing                pod/64bf6c36d3bdfa9a749420b4-7fvms   Stopping container 64bf6c36d3bdfa9a749420b4
0s          Warning   DeadlineExceeded       job/64bf6c36d3bdfa9a749420b4         Job was active longer than specified deadline
```

Is it possible to display a message in the execution description, in case the deadline was reached?

**Comment by tkonieczny** [comment]
`pods "6526560151476cbbdca45170-dqnfc" not found`
https://demo.testkube.xyz/tests/expected-fail-jmeter-timeout/executions/6526560151476cbbdca45170
