### ISSUE TITLE
Improve documentation webhook

### ISSUE THREAD

**Issue by jerem0808** [kubeshop/testkube#4245]
**Describe the enhancement you'd like to see**
In the documentation for the webhook it's not clear if we can have other option for the template than {{ .Id }}.
[Webhooks](http://docs.testkube.io/articles/webhooks)
If we can have only .Id we should be able to display other information. At minimum the test case name. 
We want to send the alarm to our opsgenie instance and we should easily find the test case which failed. 

**Additional context**
Add any other context, CLI input/output, etc. about the enhancement here.

**Comment by djonesz** [comment]
For anybody trying to figure out the webhooks, I figured that the model is here -https://github.com/kubeshop/testkube/blob/develop/pkg/api/v1/testkube/model_event.go

Probably the most useful thing you'll want is TestExecution, which uses the model here - https://github.com/kubeshop/testkube/blob/develop/pkg/api/v1/testkube/model_execution.go

Particularly .TestExecution.TestName, .TestExecution.ExecutionResult.Status, and .TextExecution.Id have been the most useful to me.

This is an example I set up with a Teams integration:
```
{"text": "# Test {{ .TestExecution.TestName }} - **{{ .TestExecution.ExecutionResult.Status }}** \n\n [View test details](<my-ingress-uri>/tests/executions/{{ .TestExecution.TestName }}/execution/{{ .TestExecution.Id }})"}
```

**Comment by jerem0808** [comment]
Thanks @djonesz that's exactly what i was looking for!
If i have some time i'll try to improve the documentation

**Comment by TheBrunoLopes** [comment]
hey @jerem0808 we just improved the docs for webhooks.
Please check https://docs.testkube.io/articles/webhooks and let us know if you like it or if there's anything missing

**Comment by jerem0808** [comment]
Hi @TheBrunoLopes 
that's great thanks
