### ISSUE TITLE
Unable to upload postman collection file of size >10MB

### ISSUE THREAD

**Issue by rohithkumarpusarla** [kubeshop/testkube#4250]
**Describe the bug**
Unable to upload a postman collection file of size >10MB. Getting an error 502 Baggataway: Client could not create test: Request entity too large: limit is 3145728: context:null
**To Reproduce**
1. Create a new Test of type "postman/collection" 
2. And Upload the postman collection file of size >10MB.

**Expected behavior**
Expected that testkube creates a test with the postman collection provided

**Version / Cluster**
- Which testkube version? 
1.13.0 
- What Kubernetes cluster? 
Local
- What Kubernetes version?
1.24

**Screenshots**
![image](https://github.com/kubeshop/testkube/assets/138758710/7df6d8d3-788b-4ff1-a0a5-129de97a1f7a)

**Comment by vsukhin** [comment]
hey, @rohithkumarpusarla this is Kubernetes constraint in your cluster for the CRD size. For big collection we suggest to follow GitOps approach similar to our smoke tests https://github.com/kubeshop/testkube/tree/develop/test/postman/executor-tests And store collections in git having small crd with git reference

**Comment by vsukhin** [comment]
hey, @rohithkumarpusarla did it help, any other questions?

**Comment by vsukhin** [comment]
closing, please reopen if it's stll unclear
