### ISSUE TITLE
Enabling clusterName in v1.13.6 causing slack notification issues.

### ISSUE THREAD

**Issue by srujansagi** [kubeshop/testkube#4253]
**Describe the bug**
I have testkube v1.12.21 running on AKS 1.25.5 with two tests and slack integration works just fine. When I try to update the testkube v1.13.6 to use clusterName we are not receiving any slack notifications from the cluster

**To Reproduce**
1. Run - ```Enable the clusterName on v.1.13.6 and execute any test and verify if you receive any slack notifications```
2. Specify '...'
3. See error ``` msg":"error while executing slack template","error":"template: message:125:8: executing "message" at <.ClusterName>: can't evaluate field ClusterName in type slack.MessageArgs","template":"{\ ```

**Expected behavior**
Should receive the slack notification with cluster name in the message

**Version / Cluster**
- Which testkube version? v.13.6
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) AKS
- What Kubernetes version? 1.25.5

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
Additional details can be find in Testkube discord link here https://discord.com/channels/884464549347074049/885185660808474664/1133454743872749578

**Comment by vsukhin** [comment]
thank you @srujansagi we will fix it out

**Comment by vsukhin** [comment]
hey, @srujansagi can you provide your Slack template? We have this field in the list

**Comment by vsukhin** [comment]
You don't have cluster name in args list "args":{"ExecutionID":"64cd4480f98df7a18d7b959f","ExecutionName":"kuma-global-test-2","EventType":"start-test","Namespace":"testkube","Labels":"argocd.argoproj.io/instance=testkube, executor=postman-executor, notification-target=kaas, test-type=postman-collection","TestName":"kuma-global-test","TestType":"postman/collection","Status":"running","FailedSteps":0,"TotalSteps":0,"StartTime":"2023-08-04 18:33:36.954653114 +0000 UTC","EndTime":"0001-01-01 00:00:00 +0000 UTC","Duration":""}}

**Comment by vsukhin** [comment]
Sonds like you don't use latest API version. Check kubectl describe pod testkube-api-server... -n testkube

**Comment by vsukhin** [comment]
closing, looks like upgrading bug, reopen if you have it for latest version
