### ISSUE TITLE
Need to test kubectl get <resource>

### ISSUE THREAD

**Issue by Naresh240** [kubeshop/testkube#4305]
**Describe the enhancement you'd like to see**
Need to test kubectl get gitrepo is showing READY state as True or False and helm release state as True or False

**Additional context**
kubectl get gitrepo

![image](https://github.com/kubeshop/testkube/assets/58024415/4c528304-3d2d-4ce0-852b-53c01887f73e)

Please help me how to test with testkube

**Comment by vsukhin** [comment]
hey @Naresh240 
I suggest to follow this way https://stackoverflow.com/a/51737180
you need to create a container executor http://docs.testkube.io/test-types/container-executor
and provide necessary RBAC permissions to jobServiceAccount for these tests

**Comment by vsukhin** [comment]
solved https://discordapp.com/channels/884464549347074049/1146402638146043955
