### ISSUE TITLE
Improve Webook to allow proper integration to Alerting API's like Opsgenie

### ISSUE THREAD

**Issue by ig12** [kubeshop/testkube#4306]
**Describe the enhancement you'd like to see**
I would like to see an Enhancement of the Webhook API, it should allow go templating in the Uri field and be extended with a event to react on like "`changed to success`"

**Additional context**
I'm trying to integrate the continuous tests from testkube with the alerting platform Opsgenie.
The creation of alerts already works fine using the Webhook acting on the event `end-test-failed`. Even de-duplication of the alert works based on providing an alias in the`payloadTemplate` referencing the ` "{{ .TestExecution.TestName }}"`.

But I not only need to open alerts, but also close them after a successful run of a Testcase. Unfortunately the go templating seems not to work in the `uri` filed of the Webhook API. To close an alert by the Opsgenie API it requires a identifier unique to the alert, in the specific case that would be the `{{ .TestExecution.TestName }}`". If activated the webhook could call the Opsgenie API with an uri like that `"https://api.opsgenie.com/v2/alerts/{{ .TestExecution.TestName }}/close?identifierType=alias"` and close the alert once a run of the testcase is succesful.
As reference the Opsgenie API doc https://docs.opsgenie.com/docs/alert-api#close-alert

To make it perfect I'd like to instruct testkube to only send Webhook to Opsgene if a test is changing from failed to successful - for that reason the request for a new event type - if it does not exist I would need to use the event `end-test-success`, which would be sent out after each successful run of any test in testkube. I have not tested that yet so I don't know how Opsgenie would handle that.

Thanks for your help by enabling that use-case

**Comment by vsukhin** [comment]
thank you @ig12 nice suggesstion and easy to implement
