### ISSUE TITLE
UI: State of the Configuration Card is not updated after submition

### ISSUE THREAD

**Issue by pavloburchak** [kubeshop/testkube#4319]
Describe the enhancement you'd like to see:

Refactor ConfigurationCard component, so the state of buttons is updated after submit. 

![Image](https://github.com/kubeshop/testkube/assets/25755402/c850e0a4-6d38-4839-92b2-187d8fdf2339)

**Comment by rangoo94** [comment]
It is already done with [**CardForm**](https://github.com/kubeshop/testkube-dashboard/pull/847) since 22nd August.
