### ISSUE TITLE
Jenkins Plugin

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#4334]
As Jenkins continuous to grow (https://cd.foundation/announcement/2023/08/29/jenkins-project-growth/?) it would be great to have an official Jenkins plugin for Testkube to make it easier for teams using Jenkins to adopt Testkube.

The plugin should make it straight-forward to run Tests/Testsuites from inside a Jenkins pipeline - with UI for common settings and  support for Jenkins parameters, etc.

**Comment by vsukhin** [comment]
done
