### ISSUE TITLE
Test clusters - `nodeSelector`/`Node affinity` isn't set - "core" services at spot instances

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4340]
Test clusters don't have "core" Testkube pods (including api-server) assigned to "standard" clusters. Because of that, they are often assigned to spot instances, and terminated.

```
Name:             testkube-api-server-747cb79ccb-89pf2
Namespace:        testkube
Priority:         0
Service Account:  testkube-api-server
Node:             gke-testkube-develop-e2-standard-4...
...
Status:           Failed
Reason:           Terminated
Message:          Pod was terminated in response to imminent node shutdown.
```

```
cloud.google.com/gke-provisioning=spot
```

**Describe the improvement**
Test clusters (develop, integration, demo) -  `nodeSelector`/`Node affinity` for "core" services

**Comment by vsukhin** [comment]
good insight, @tkonieczny ! @ypoplavs please fix

**Comment by ypoplavs** [comment]
added node labels, merged in this [PR](https://github.com/kubeshop/helm-charts/pull/625)
