### ISSUE TITLE
Triggers/Webhooks - `disable` option

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4341]
**Describe the enhancement you'd like to see**
Currently, it's not possible to easily disable trigger, or webhook. The only option to temporary "disable" them, is to edit them and temporary change the condition. The idea is to introduce an additional `disable` option to allow doing it in the easier way.

**Comment by vsukhin** [comment]
@tkonieczny @jmorante-ks @TheBrunoLopes for yesterday's swisscom meeting

**Comment by vsukhin** [comment]
done by @vLia for Webhooks
