### ISSUE TITLE
Dashboard - CLI Commands aren't namespace-aware

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4342]
**Describe the bug**
All CLI commands in Dashboard aren't namespace-aware. CLI defaults to `testkube` namespace, so if Testkube is installed in different one it need to be specifically set. Correct namespace is returned by API (for example `/info`)

![Screenshot from 2023-09-07 12-39-16](https://github.com/kubeshop/testkube/assets/1473096/ae2a62ee-f339-4829-a27e-281ef0bb3ffc)

**Expected behavior**
`--namespace` should be displayed, and set to the correct namespace (if different than the default `testkube`):
```
- Test->CLI Commands
- Execution->CLI Commands
- TestSuite->CLI Commands
```

**Comment by rangoo94** [comment]
Fixed with https://github.com/kubeshop/testkube-dashboard/pull/888
