### ISSUE TITLE
Dashboard - multiple labels with the same key can be added

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4348]
**Describe the bug**
It's possible to add multiple labels with the same key in Dashboard while creating/editing the test, only the last one will be saved. Adding more than one label with the same key shouldn't be allowed in UI, as it's allowed by K8s.

**Comment by rangoo94** [comment]
Done in https://github.com/kubeshop/testkube/issues/4358. It's not possible now to have duplicates. Already released to the production as v1.14.2.
