### ISSUE TITLE
Additional label for the metrics

### ISSUE THREAD

**Issue by jerem0808** [kubeshop/testkube#4350]
We would like to have more labels inside the metric testkube_test_executions_count. 
I would think that having the list of labels of the test case would help to create better dashboard. 
As the metric is a count as soon as we run a test testkube will add this test to the metric. 
But if we are in development it would be great to show easily certain production ready tests. 
We could overcome this with the name of the test case but i would say that having the labels in the metric would help. 

Thanks
Jéremy

**Comment by vsukhin** [comment]
So, we will have one more field, "labels": "label1, label2, label3" for execution count metric
