### ISSUE TITLE
Error during test creation

### ISSUE THREAD

**Issue by fvogl** [kubeshop/testkube#4375]
**Describe the bug**
During test creation with testkube-dashboard:1.14.1 and testkube-api-server:1.14.4 I get the below error in the Browser.

12:28:26.142 instrument.ts:132 TypeError: Cannot read properties of undefined (reading 'reduce')
    at jO (utils.ts:2:17)
    at onFinish (TestCreationForm.tsx:80:15)
    at onFinish (Form.js:69:9)
    at useForm.js:812:11
(anonymous) @ instrument.ts:132
12:28:28.180 DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
12:28:34.158 instrument.ts:132 TypeError: Cannot read properties of undefined (reading 'reduce')
    at jO (utils.ts:2:17)
    at onFinish (TestCreationForm.tsx:80:15)
    at onFinish (Form.js:69:9)
    at useForm.js:812:11
(anonymous) @ instrument.ts:132
(anonymous) @ captureconsole.ts:74
(anonymous) @ index.js:103
(anonymous) @ useForm.js:815
Promise.then (async)
submit @ useForm.js:808
onSubmit @ Form.js:122
Ae @ react-dom.production.min.js:54
ze @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
Lr @ react-dom.production.min.js:105
Dr @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
ll @ react-dom.production.min.js:273
je @ react-dom.production.min.js:52
Ur @ react-dom.production.min.js:109
Kt @ react-dom.production.min.js:74
Wt @ react-dom.production.min.js:73
s @ helpers.ts:98

**Version / Cluster**
- Which testkube version?
  testkube-dashboard:1.14.1 and testkube-api-server:1.14.4
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  OpenShift
- What Kubernetes version?
  OCP 4.13.11 (K8s 1.26.7)

**Comment by vsukhin** [comment]
thank you @fvogl let's our front end team to check it out @rangoo94

**Comment by rangoo94** [comment]
Hi @fvogl, thanks for the report!

The issue has been already fixed in https://github.com/kubeshop/testkube-dashboard/pull/877. We will try to release it soon - today or tomorrow. I will inform you there when it happens.

**Comment by rangoo94** [comment]
Hi @fvogl! The fixes have been released in Testkube Dashboard v1.14.2 (Helm chart: v1.14.8).

Sorry for the inconvenience, and once again, thanks for the report!
