### ISSUE TITLE
Update option for `create` command.

### ISSUE THREAD

**Issue by jmorante-ks** [kubeshop/testkube#4397]
We would like to have an enhancement at the `create` command to allow overwrite in case the test already exists, instead of fail as it happens today.

The solution could work in the following way:
- When the `create` command is executed on an already existing test, the customer could get a message saying "Test already exist, do you want to overwrite it?" with a Y/N selector and triggering the desired outcome (overwrite OR cancel)
- Allow to force the overwrite with `--update` parameter, to skip the prompt asking for confirmation.

**Comment by tkonieczny** [comment]
:heavy_check_mark: 
```
~/bin/kubectl-testkube create test --name k6-example-update --type k6/script --test-content-type git --git-uri https://github.com/kubeshop/testkube.git --git-branch main --git-path test/k6/executor-tests/k6-smoke-test-without-envs-some-incorrect-file.js --namespace testkube-integration --label example=label1 --update

Context:  (999.0.0-53f63d20e)   Namespace: testkube-integration
---------------------------------------------------------------
Test updated testkube-integration / k6-example-update 🥇
```
