### ISSUE TITLE
Allow SoapUI and all the other executor to support directories as sources and user can provide the file to run

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#4402]
**Describe the enhancement you'd like to see**
A clear and concise description of what you want to happen, and why.

**Additional context**
Add any other context, CLI input/output, etc. about the enhancement here.

**Comment by tkonieczny** [comment]
:heavy_check_mark: 
https://demo.testkube.xyz/tests/curl-directory-test/executions/652553f151476cbbdca44e64
