### ISSUE TITLE
Add direct link to dashboard from slack message

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4420]
Slack message contains

![image](https://github.com/kubeshop/testkube/assets/8971839/79582a4d-e2fb-47f3-8266-81ac61f90a3f)

i will be better to have a direct link to the dashboard uri

maybe by using then `dashboardUri` values

**Comment by vsukhin** [comment]
hey, @ademar59  yes, good suggestion. in fact weuse them for CDEvenst and Metrics. Worth to add it to Salck message

**Comment by ademar59** [comment]
coul be nice to have the seame feature in job logs too 

usefull to show link in ci tools: see an example from Gitlab

![image](https://github.com/kubeshop/testkube/assets/8971839/e990f653-b91c-4bc7-b48b-e2c6c79e955c)

**Comment by vsukhin** [comment]
cli technically provides a cli command to see the logs. it's supposed you use cli

**Comment by ademar59** [comment]
In Gitlab Gui, when you have any url in log file you can click on it and have a direct link 

If you add url on your logs, people have a link from gitlab to testkube without using kubectl

**Comment by vsukhin** [comment]
ok, will add it to the logs

**Comment by ademar59** [comment]
and maybe artifacts link too if exists

**Comment by vsukhin** [comment]
ok
