### ISSUE TITLE
Dashboard - Trigger creation dialog - no error message if trigger with that name already exists, dialog is just closed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4427]
**Describe the bug**
Trying to create a trigger with the name that already exists, API returns 502 and `failed to create test trigger test-trigger-1: client could not create test trigger: testtriggers.tests.testkube.io \"test-trigger-1\" already exists, context: null`. But, in Dashboard the trigger creation dialog is then closed without any error message.

**To Reproduce**
1. Trigger with specific name (for example `test-trigger-1`) already exists
2. Try to create a trigger with the same name (`test-trigger-1`)
3. Trigger creation dialog is closed without any error message

**Expected behavior**
- Error message should be displayed, probably in the same way as in case of Test creation dialog:
![Screenshot from 2023-10-03 17-17-29](https://github.com/kubeshop/testkube/assets/1473096/bd68e5ef-269d-4289-9dc6-9b3a5efe9bc5)

- Creation dialog shouldn't be closed, so user will be able to change the name without setting everything else again

**Version / Cluster**
Noticed at Dev, TODO: check other env

**Comment by jmorante-ks** [comment]
This requires status code change at API, plus proper handle of error in UI.
