### ISSUE TITLE
Container Executor Artifact - Allow Selector and Access Mode in PersistentVolumeClaim

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4430]
**Describe the enhancement you'd like to see**
I am running an AWS EKS Fargate Cluster with AWS EFS CSI Driver, and unfortunately this setup does not support dynamic persistent volume provisioning. 

If selector and access mode can be added to the PersistentVolumeClaim that collects the test artifacts, I can use the container executor. I am using a custom prebuilt testkube executor to scrape and would love to move away from it and use the container executor as it is the recommended approach to run custom images. 

**links**
https://github.com/kubeshop/testkube-operator/blob/develop/api/tests/v3/test_types.go#L122
https://docs.testkube.io/test-types/container-executor/#collecting-test-artifacts
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/multiple_pods/README.md

**Comment by vsukhin** [comment]
Sure, closing for now, feel to reopen if 1.15 doesn't solve your request
