### ISSUE TITLE
testkube jmeter executor pod image to be configured with scp,sftp,ssh,sshpass binaries by deafult

### ISSUE THREAD

**Issue by vignesh77l** [kubeshop/testkube#4439]
testkube jmeter executor pod image to be configured with below 4 binaries by deafult as this would help us in transferring the reports do different vm for post processing

1. scp
2. sftp
3. ssh
4. sshpass

**Comment by vsukhin** [comment]
thank you @vignesh77l for @TheBrunoLopes to review and prioitise!

**Comment by vignesh77l** [comment]
Hi Testkube Team, could you please let us know the tentative date/release in which we can expect this fix
Many Thanks in advance for your support! 👍

**Comment by vsukhin** [comment]
@TheBrunoLopes or @jmorante-ks should help with priorities

**Comment by michaelsatish** [comment]
Just out of curiosity and I am on a similar boat, if the use case is moving files from containers to local or a remote location, would the following approaches work.

1. Using `kubectl cp` https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp 
2. If using minio to scrape the output artifacts, use `mc cp` command or use events in minio to move the file to a remote location for post processing.

**Comment by vignesh77l** [comment]
@vsukhin 
FYI currrntly th curl binary present inside the jmeter executor pod is not supporting sftp protocol, i am thinking if this is curl binary is updated to a version which supports sftp protocol it might solve the problem

below outputs captured from jmeter executor pod:

**curl 7.79.1** (x86_64-alpine-linux-musl) **libcurl/7.79.1** OpenSSL/1.1.1o zlib/1.2.12 nghttp2/1.41.0

Release-Date: 2021-09-22
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL TLS-SRP UnixSockets

**curl: (1) Protocol "sftp" not supp
orted or disabled in libcurl**

❌ Execution failed: process started with command: /bin/sh, exited with code:1  error: exit status 1
output: curl 7.79.1 (x86_64-alpine-linux-musl) libcurl/7.79.1 OpenSSL/1.1.1o zlib/1.2.12 nghttp2/1.41.0
Release-Date: 2021-09-22

<img width="686" alt="image" src="https://github.com/kubeshop/testkube/assets/140182118/a8692770-ef01-4ede-94c7-3d4543e65333">
