### ISSUE TITLE
Bug Report: Empty Username Persists in YAML Definition After Removal in Testkube UI"

### ISSUE THREAD

**Issue by saadisfy** [kubeshop/testkube#4447]
**Describe the bug**

While creating a Testkube Test from a Git source via the UI, I encountered an issue with the handling of the username field. 

Story:
During the creation of a Testkube Test through the UI, I initially input some text into the username textfield. However, upon realizing that the Git Repository is public and there is no need for a username, I promptly remove the entered text and proceed to click on the "Create" button.

Upon checking the Test Definition in Test > Settings > Definition, the YAML code displays an empty value for the username (refer to the attached screenshot). Attempting to remove this empty username through the UI in Test > Settings > Definition results in a success notification. However, upon switching to another section and returning to the Definition, the empty username persists.

**To Reproduce**

1. Navigate to Testkube UI.
2. Create a Test.
3. Click on the username text field, enter and then remove text.
4. Click on "Create."

**Expected behavior**

- Removal of text from the username text field should result in a non-null value in the YAML definition.
- Modifying the YAML definition to remove the username should reflect in the UI with a success notification. In case of an error, an appropriate notification should be displayed.

**Version / Cluster**
- Which testkube version: API version v1.14.1, Dashboard version v1.14.0
- What Kubernetes cluster: tested on different version but also  local Minikube instance

**Screenshots**
<img width="1894" alt="image" src="https://github.com/kubeshop/testkube/assets/29105087/d478c645-7f62-4656-8691-b1bb2effbddf">

**Comment by vsukhin** [comment]
thank you @saadisfy our Front End team will check it out

**Comment by rangoo94** [comment]
@vsukhin, I recall it was API bug, but if you wish I can check it next week.

**Comment by vsukhin** [comment]
ok, i can check api

**Comment by vsukhin** [comment]
I tried it on demo and it went fine https://demo.testkube.io/tests/username-test/settings/definition

**Comment by vsukhin** [comment]
Sounds like not nil username structure submitted

kubectl testkube get tests test-username --crd-only

Context:  (999.0.0-dev)   Namespace: testkube
---------------------------------------------
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-username
  namespace: testkube
spec:
  type: curl/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      usernameSecret:
