### ISSUE TITLE
Testtrigger resourceSelector regex

### ISSUE THREAD

**Issue by AlessioDiama** [kubeshop/testkube#4450]
**Describe the enhancement you'd like to see**
When defining a testtrigger the CRD allows to specify the name and the namespace of the k8s resource to monitor.
In the case of events, when the event is NOT generated by hand, the event name gets an ID attached at the end of the string. 

Taking one of the testkube events as an example:

```
apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-10-09T13:00:10Z"
involvedObject:
  apiVersion: batch/v1
  kind: Job
  name: hourly-e2e-test-suites-28280940
  namespace: testkube
  resourceVersion: "1199306902"
  uid: e650e3b5-7a3b-4de4-a65f-c56bdf78f4d1
kind: Event
lastTimestamp: "2023-10-09T13:00:10Z"
message: Job completed
metadata:
  creationTimestamp: "2023-10-09T13:00:10Z"
  **name: hourly-e2e-test-suites-28280940.178c71ea52cf403e**
  namespace: testkube
  resourceVersion: "1199307181"
  uid: 901f7f7b-9c8c-4815-8fd9-435ec37cee69
reason: Completed
reportingComponent: ""
reportingInstance: ""
source:
  component: job-controller
type: Normal
```

It would be great if we could specify a regex instead of the exact string name so that the match would work for all the possible IDs ( hourly-e2e-test-suites-28280940.xxxxxxx ). Taking as reference the example above, I would like to be able to create a test trigger similar to the following:

```
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  annotations:
  name: test-testrigger
  namespace: testkube
spec:
  action: run
  event: created
  execution: test
  resource: event
  resourceSelector:
    name-regex: "hourly-e2e-test-suites.*"
    namespace: testkube
  testSelector:
    [...]
```

Thanks in advance for the support

**Comment by vsukhin** [comment]
thank you @AlessioDiama nice idea, will add it to the queque

**Comment by AlessioDiama** [comment]
Thanks @vsukhin for the prompt answer. Do you have any idea for the timeline?

**Comment by vsukhin** [comment]
welcome! @TheBrunoLopes can help with planning
