### ISSUE TITLE
Bug Gradle executor: environment variables in system properties are not evaluated

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#4456]
**Describe the bug**
See conversation in Discord: https://discord.com/channels/884464549347074049/1160975216458072134

**To Reproduce**
Create test:
```bash
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  labels:
    executor: gradle-executor
    test-type: gradle-test
  name: gradle-test
  namespace: testkube
spec:
  content:
    repository:
      branch: gradle-tests
      path: gradle-example/hello-gradle
      type: git
      uri: https://github.com/vlia/testkube-tests.git
    type: git
  executionRequest:
    args:
    - -Dtestkube=$TESTKUBE
    - -i
    variables:
      TESTKUBE:
        name: TESTKUBE
        type: basic
        value: "true"
        valueFrom: {}
  type: gradle/test
```
Run test:
```
tk run test gradle-test
```

**Expected behavior**
Test is successful.

**Actual behavior**
Test fails due to the variable not being evaluated.

**Version / Cluster**
- Which testkube version? 
Client Version 1.14.6
Server Version 1.14.6
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
kind
- What Kubernetes version?
Client Version: v1.28.2
Server Version: v1.26.3

**Comment by vsukhin** [comment]
this is more an enhancement

**Comment by vsukhin** [comment]
yes, I agree, it's a nice improvement and shold work for all executors

**Comment by vLia** [comment]
Created follow-up: https://github.com/kubeshop/testkube/issues/4458
