### ISSUE TITLE
UI: Git source is not displayed in Test Settings

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4470]
**Describe the bug**

Git source is not displayed in Test Settings

**To Reproduce**

1. Create a test using "Test Source"
2. Go to "Test Details" > "Settings" > "Test"
3. See "Source" section

**Expected behavior**

It should display a test source.

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
<img width="1982" alt="Zrzut ekranu 2023-10-17 o 11 52 15" src="https://github.com/kubeshop/testkube/assets/3843526/9c787cea-ed0a-4db4-9a0a-f9806a5cb773">

**Comment by devcatalin** [comment]
fixed this
