### ISSUE TITLE
[Distributed Jmeter] Ensure all OS env variables are propagated to all pods.

### ISSUE THREAD

**Issue by jmorante-ks** [kubeshop/testkube#4473]
**Describe the bug**
It seems that OS env variables are not properly propagated to pod runners of Distributed Jmeter

**To Reproduce**
Objective of this issue is to confirm if this is happening or not, in case it is not working it should be fixed.

**Expected behavior**
OS Env variables should be available in all pods.

**Additional context**
Required so OS Env variables can be used at pre and post scripts.

**Comment by dejanzele** [comment]
this will close the issue https://github.com/kubeshop/testkube/pull/4541
