### ISSUE TITLE
Jmeter variables for Distributed Jmeter should be applied with "-G" instead of "-J"

### ISSUE THREAD

**Issue by jmorante-ks** [kubeshop/testkube#4474]
**Describe the bug**
Distributed Jmeter is currently defined variables in the same way that the normal Jmeter executor, the consequence is that variables are not propagated to slave nodes.

**Expected behavior**
Jmeter variables for Distributed Jmeter should be applied with "-G" instead of "-J", so they are propagated to the slaves.

**Comment by dejanzele** [comment]
This is closed by https://github.com/kubeshop/testkube/pull/4503
