### ISSUE TITLE
Run pre and post script from git

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4485]
**Describe the enhancement you'd like to see**
Pre & post script must be located in the working dir when we create or run test.
The content of the script is stored in text in the test definition

`postRunScript: "#!/bin/sh\n\necho \"Generating html report ....\"\ncd /data/repo\nnode ./html-report/cucumber-html-report.js"`

I should be usefull to run the script from the cloned project.
With that feature we can run same test from differents projects without dupplicate!

**Comment by vsukhin** [comment]
hey, @ademar59 yes, we will work on it this week https://github.com/kubeshop/testkube/issues/4476
