### ISSUE TITLE
Npm install failed on postman executor: permissions missing

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4487]
**Describe the bug**
I use a pre run script to install newman reporter but it failed due to permissions

```
Execution completed 
+ npm install
npm ERR! code EACCES
npm ERR! 
syscall mkdir
npm
 ERR! 
path /.npm
npm
 ERR! errno EACCES
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR!
 previous versions of npm which has since been addressed.
npm
 ERR! 
npm ERR!
 To permanently fix this problem, please run:
npm
 
ERR!
   sudo chown -R 1001:0 "/.npm" 
```

could we have a changement of owner to nmp to have the feature of npm install

**To Reproduce**
1. have a pre script with
```
#!/bin/sh

echo "Install html report ...."
cd /data/repo
npm install -g newman-reporter-html
npm install -g newman-reporter-htmlextra
```
 
2. run postman tests with executor args `--reporters cli,json,htmlextra` 

**Expected behavior**
have newman htmlreport

**Version / Cluster**
- 1.15

**Comment by vsukhin** [comment]
thank you @ademar59 for @TheBrunoLopes to confirm

**Comment by vsukhin** [comment]
hey @TheBrunoLopes i tried to build a Docker image with above deps, increase from 232mb to 347mb
