### ISSUE TITLE
Upgrade K6 executor to use latest version of K6

### ISSUE THREAD

**Issue by DerDee** [kubeshop/testkube#4488]
**Describe the enhancement you'd like to see**
As far as I could find, the K6 executor is running at version 0.36.0, which is over 2 years old. 
Found here: https://github.com/kubeshop/testkube/blob/develop/contrib/executor/k6/build/agent/Dockerfile 
We are running into issues with gRPC calls being fixed in the latest versions. 

An upgrade of K6 to the latest version 0.47.0 would be preferable. 

I'm inexperienced in the building procedure so this finding might be incorrect. I've been searching for hours to get the version of K6 that is used by Testkube, but I only found this. As a result of asking this in Discord, I created this "feature request"

**Additional context**
N/A

**Comment by vsukhin** [comment]
thank you @DerDee will prepare a fix

**Comment by AndrewUnderwoodAtFanatics** [comment]
I was just looking at this to figure out why the k6 version went down when I upgraded testkube.  Previously K6 `0.44.0` was being included but it looks like this change was reverted [here](https://github.com/kubeshop/testkube/pull/3729/files#diff-f3ce3ce832ad558cc229b888aeb28c04b0978dad3b9a3435e2a90ec167fc19c7R9), possibly by accident.

**Comment by AndrewUnderwoodAtFanatics** [comment]
Looks like a proper fix to this will involve switching away from the loadimpact image for fetching the k6 binary.

https://hub.docker.com/r/loadimpact/k6

> THIS IMAGE IS DEPRECATED and its support will be discontinued after Dec 31, 2023. This image has been replaced by [grafana/k6](https://hub.docker.com/r/grafana/k6).
Please update your scripts to use [grafana/k6](https://hub.docker.com/r/grafana/k6) to continue using the latest version of k6.

**Comment by vsukhin** [comment]
Thank you @AndrewUnderwoodAtFanatics We will check it out
