### ISSUE TITLE
Utilize the test ID and test number when passing arguments to the k6 binary

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [kubeshop/testkube#4499]
**Is your feature request related to a problem? Please describe.**

I wish to have the capability to utilize the test ID and test number when passing arguments to the k6 binary. My specific need arises from my intention to transmit k6 data via the statsd protocol. Within the argument settings, I have the option to include tag parameters. It would be highly beneficial if I could find a way to extract and pass the current test ID or test number as one of these arguments.

**Describe the solution you'd like**
Within the argument section, it would be valuable to employ certain keywords such as {{test-id}} or equivalent, which would allow us to obtain this information.

**Describe alternatives you've considered**

**Additional context**
Thanks for this amazing product

**Comment by marcportabellaclotet-mt** [comment]
```
    args:
      - "--out"
      - "statsd"
      - "--tag"
      - "job_name=test-from-testkube-{{testid}}"
      - "--tag"
      - "test_run_id=test"
  ``

**Comment by marcportabellaclotet-mt** [comment]
An alternative approach could involve incorporating the test ID or test number as an environment variable within the pods executing the tests. This approach would facilitate the addition of tags within the k6 test script, achieved by accessing OS variables using JavaScript.

**Comment by vsukhin** [comment]
hey, @marcportabellaclotet-mt techically, we pass these fields as an input parameter in test execution pod 
```Command:
      /bin/runner
      {"id":"65329cfb01c70039491c71c6","testName":"k6-executor-smoke","testNamespace":"testkube","testType":"k6/script","name":"k6-executor-smoke-198","number":198,"command":["k6"],"args":["\u003ck6Command\u003e","\u003cenvVars\u003e","\u003crunPath\u003e","-e","K6_ENV_FROM_PARAM=K6_ENV_FROM_PARAM_value"],"variables":{"K6_SYSTEM_ENV":{"name":"K6_SYSTEM_ENV","value":"K6_SYSTEM_ENV_value","type":"basic"}},"content":{"type":"git","repository":{"type":"git","uri":"https://github.com/kubeshop/testkube.git","branch":"main","path":"test/k6/executor-tests/k6-smoke-test.js"}},"startTime":"2023-10-20T15:30:03.833132775Z","endTime":"0001-01-01T00:00:00Z","executionResult":{"status":"running"},"labels":{"core-tests":"executors","executor":"k6-executor","test-type":"k6-script"},"bucketName":"13461a81-26be-4bee-9cf7-8f6e5b06e223","runningContext":{"type":"user-cli"}}
```
not sure, it's easy to access, so it might be a good idea to have some additional env var

**Comment by marcportabellaclotet-mt** [comment]
Thanks for the fast response!
I was also exploring this option, and find a ugly workaround:
```
cat /proc/1/cmdline |awk -F '"name":"' '{print $2}' |awk -F '"' '{print $1}' >/tmp/test
```
As a pre-execution command, and then use javascript to read the file.

However, it would be great to share this info as env variable. 

Thanks again!!

**Comment by vsukhin** [comment]
Yeah, sounds like too many frictions, worth to make it simplier

**Comment by marcportabellaclotet-mt** [comment]
Thanks again.
Meanwhile I was able to read the testid and other parameters via parsing /proc/1/cmdline.

Would it be also possible to share the context as env var? I would like to export to statsd the context of a test-suite: 
```
 "runningContext":{"type":"testsuite","context":"ts-k6-parallel-example-2"
```

**Comment by vsukhin** [comment]
yes, we can add
