### ISSUE TITLE
Script execution

### ISSUE THREAD

**Issue by jasmingacic** [kubeshop/testkube#450]
**Describe the bug**
If a script is created in for example namespace default and it is started job is started in testkube namespace

**To Reproduce**
1. Run 
```
# go run cmd/kubectl-testkube/main.go scripts  --client direct start jobd1 --namespace default
```
```
# kubectl get jobs -A 
NAMESPACE                           NAME                                                             READY   STATUS      RESTARTS   AGE
testkube                            617929adcaac8c698d492e0a-d47bf                                   1/1     Running             0          3s
```

**Expected behavior**
If the script is created in a given namespace execution should be happening in the same namespace. Right now namespace parameter is used to identify which CR to execute.

```
# kubectl get scripts -A 
NAMESPACE   NAME    AGE
default     jobd1   7m27s
testkube    jobd1   7m5s
```

**Comment by exu** [comment]
Yeah, namespace should be only for creating scripts and getting them
