### ISSUE TITLE
Test Argocd Testkube plugin

### ISSUE THREAD

**Issue by ypoplavs** [kubeshop/testkube#4513]
Please follow the instruction steps in here: https://docs.testkube.io/articles/argocd-integration/
to makes sure integration works as expected.

**Comment by tkonieczny** [comment]
https://docs.testkube.io/articles/argocd-integration/
1 and 3 (testkube installation) steps are almost the same (testkube installation)

5. Set up a Git Repository containing some Postman collections.
I think this `hello-kubernetes.json` should also be included in this example repository

9. Run the initial ArgoCD sync and check your cluster.
(I just used the example from docs: https://github.com/kubeshop/testkube-argocd.git)

```Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = postman-collections: app path does not exist:```
path: postman-collections -> examples/postman-collections
repo URL: https://github.com/kubeshop/testkube-argocd.git


11. Run ad-hoc tests from the CLI.
`testkube get tests` (example `hello-kubernetes` test is missing - there are 2 other ones)
I'm also not sure what are the commands from the example:
- `kubectl-testkube tests list` -> `testkube get tests`
- `testkube tests run hello-kubernetes` -> `testkube run test hello-kubernetes`
- ` testkube tests execution EXECUTION_ID` -> `testkube get execution EXECUTION_ID`
