### ISSUE TITLE
option --download-artifacts dont work when job failed

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4539]
**Describe the bug**

screenshot of a postman test OK

![image](https://github.com/kubeshop/testkube/assets/8971839/552c03fa-7bce-4b2f-96a3-5e16d8f30e18)

screenshot of a postman test KO

![image](https://github.com/kubeshop/testkube/assets/8971839/94e56ccf-6faf-4b75-a8d8-daa58039ba9f)

**Comment by vsukhin** [comment]
thankk you @ademar59

**Comment by ademar59** [comment]
same for testsuite
