### ISSUE TITLE
ARM64 images are created but they're actually x86_64

### ISSUE THREAD

**Issue by adrien-f** [kubeshop/testkube#4550]
**Describe the bug**

Let's take for example `kubeshop/testkube-postman-executor:1.15.9`:

For example on the Docker hub and reading the manifest, we can see there are two platforms:

![image](https://github.com/kubeshop/testkube/assets/781688/9d9a9d72-6db1-46da-9f39-5f695836d1cc)

Or 

```
❯ docker buildx imagetools inspect kubeshop/testkube-postman-executor:1.15.9
Name:      docker.io/kubeshop/testkube-postman-executor:1.15.9
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:f35bd43d28d11b8b677c4b497084b60dd9c88b6847aecf7ae4f3c42f56abd2fe

Manifests:
  Name:      docker.io/kubeshop/testkube-postman-executor:1.15.9@sha256:594ef33e08d48d8c9ed22beda81053aa4e2c19a80ae6c12ee8eb69d7ceb7849a
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      docker.io/kubeshop/testkube-postman-executor:1.15.9@sha256:130460ac0fed62dea2654cde10de4b5edc6a0a83ce56e285cb198b0c040a649f
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```

But if you run the `linux/arm64` image you will see it's not arm64:

```
❯ docker run --platform linux/arm64 -u root --entrypoint sh -it kubeshop/testkube-postman-executor:1.15.9 "-c" "uname -a"
Linux 9ff81be8c397 6.1.55-0-virt #1-Alpine SMP Sun, 24 Sep 2023 23:14:02 +0000 x86_64 Linux
```

And this cause issues in Kubernetes when running on arm64 nodes:

```
🔬 Executing in directory : 
 $ newman run /data/repo/tests/newman/spinak-events.postman_collection.json -e /tmp/testkube-tmp267193812 --reporters cli,json --reporter-json-export /tmp/testkube-tmp1054819397.json
❌ Execution failed: could not start process with command: newman  error: fork/exec /usr/local/bin/newman: exec format error
output: 
❌ Could not get Newman result: open /tmp/testkube-tmp1054819397.json: no such file or directory
✅ Mapped Newman result successfully
could not start process with command: newman  error: fork/exec /usr/local/bin/newman: exec format error
output: 
```

**To Reproduce**
1. Run '...'
2. Specify '...'
3. See error

**Expected behavior**

ARM64 images are indeed arm64 images.

I'm seeing the https://github.com/kubeshop/testkube/pull/4374 PR but it looks like it was only for `jmeterd
 
**Additional context**

Thank you in advance and let us know if we can help

**Comment by vsukhin** [comment]
thank you @adrien-f pleae check it out @ypoplavs

**Comment by ypoplavs** [comment]
Hello @adrien-f!
Yes, we build Testkube images to support both platforms, however, the base image for `postman` executor - `postman/newman` has `amd` support only.  
<img width="699" alt="Screenshot 2023-10-31 at 12 21 29" src="https://github.com/kubeshop/testkube/assets/45286051/de824a5f-556e-4cf8-8b7a-c9f1c3dffd02">

We will consult with the team on how we can replace the base image, because it is quite old.

**Comment by ypoplavs** [comment]
Dear @adrien-f @edouard-lopez!
We have replaced base Postman image with the one that support ARM: https://github.com/kubeshop/testkube/blob/develop/contrib/executor/postman/build/agent/Dockerfile#L2

It will be available in our next release.

**Comment by edouard-lopez** [comment]
> It will be available in our next release.
Do you mean one of your weekly-ish release or something bigger that will happen in several weeks?

**Comment by guiyomh** [comment]
I'm also interested in this new image. When do you plan to deploy this image?

**Comment by ypoplavs** [comment]
Hello @guiyomh @edouard-lopez!
It has been released, please try the new image and let us know in case of any issues.

**Comment by guiyomh** [comment]
@ypoplavs 🎉 it works, 
many thanks
