### ISSUE TITLE
--update dont remove postRunScript 

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4582]
**Describe the bug**
I have created a test with options --postrun-script

I have created with --update the same script without this option
postRunscript is still in definition

**Comment by vsukhin** [comment]
hey @ademar59 our update command works in a patch mode. it means, if somethigng is skipped, it's not changed. you can provide --postrun-script emptyfile and it will be cleaned

**Comment by ademar59** [comment]
This operation is not trivial for a user.
Couldn't it be improved?

**Comment by vsukhin** [comment]
we can add somethng like --clear-postrun-scipt and ---clear-prerrun-script flags

**Comment by ademar59** [comment]
it won't be simpler

**Comment by vsukhin** [comment]
ok, I will allow to have --postrun-script=""  in order to clean it

**Comment by vsukhin** [comment]
closing then
