### ISSUE TITLE
add --silent option for testsuite run CLI

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4584]
**Describe the enhancement you'd like to see**
During testsuite run, logging is too large 

![image](https://github.com/kubeshop/testkube/assets/8971839/4f3960c7-e9ec-4d9d-b876-c44a0cb08d55)

**Comment by ademar59** [comment]
At usage, i dont know if the current version is not with options --verbose

I think that this excess of logs risks bothering more than one ...

**Comment by vsukhin** [comment]
ok, I just implemented --silent option
