### ISSUE TITLE
Out of date executor

### ISSUE THREAD

**Issue by ornell** [kubeshop/testkube#4612]
**Describe the bug**
Currently your executor breaks due to non updated images. Tracetest server is currently at 0.14.6 while your executor is at CLI version 0.13.10.

**Version / Cluster**
- Which testkube version? v1.15.18
- What Kubernetes cluster? GKE
- What Kubernetes version? v1.27.4-gke.900

**Screenshots**
<img width="1135" alt="Screenshot_2023-11-07_at_15 42 19" src="https://github.com/kubeshop/testkube/assets/2592716/d7166476-2184-43e0-9c28-88a66c7955ea">

**Comment by vsukhin** [comment]
thank you @ornell should be a quick fix @ypoplavs

**Comment by ypoplavs** [comment]
Hello @ornell!
Our Testkube API includes the latest Tracetest version - `v0.14.6`. Could you please upgrade the **helm chart** in the k8s cluster to latest one: https://github.com/kubeshop/helm-charts/releases/tag/testkube-1.15.25 and let us know about the results?
