### ISSUE TITLE
HPA for testkube-api and testkube-dashboard cannot sync in ArgoCD

### ISSUE THREAD

**Issue by Zaur-T** [kubeshop/testkube#4617]
**Describe the bug**
When enabling HPA for testkube-api or testube-dashboard in helm-chart via `values.yaml`, ArgoCD cannot sync `spec.metrics.resource` path in HPA

**To Reproduce**
1. Enable autoscaling for either testkube-api or testkube-dashboard in helm chart values
2. ArgoCD cannot sync successfully target `memory` and `cpu` utilization, you can see the `diff` from ArgoCD in the screenshot below

**Workaround**
To get this working, you need to edit upstream template `hpa.yaml` file and swap the blocks `{{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}` and `{{- if .Values.autoscaling.targetCPUUtilizationPercentage }}`

**Expected behavior**
ArgoCD syncs successfully

**Version / Cluster**
- Which testkube version? v1.10.6
- What Kubernetes cluster?  Openshift
- What Kubernetes version? v4.13
- ArgoCD version? v2.6.11

**Screenshots**
<img width="1808" alt="image" src="https://github.com/kubeshop/testkube/assets/56491125/22143559-d9fe-463c-845d-0c03ab2ec2e2">
 
**Additional context**
This bug makes helm chart upgrading little bit cumbersome, since it would require manual intervention to upstream chart each time

**Comment by ypoplavs** [comment]
@Zaur-T we have added a workaround to tackle this issue. Could you please try to upgrade testkube chart version and check if the issue still persists?

**Comment by vsukhin** [comment]
closing for now
