### ISSUE TITLE
Argument in simple quote cannot be update

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4627]
**Describe the bug**
when we add an argument in simpe quote, this is not reusable

![image](https://github.com/kubeshop/testkube/assets/8971839/984b92d7-3fd5-488e-8f5a-7a52f2d67dd9)

good in 
```
executor-binary
run --project <projectPath> --env TAGS='@test' --browser chrome
```

but cleaned here

```
run
--project
<projectPath>
--env
TAGS=
--browser
chrome
```

**Comment by vsukhin** [comment]
thank you  @ademar59 will ask front end team to fix it

**Comment by ademar59** [comment]
the problem is that cypress syntax with TAGS -(and, or) not works
https://github.com/TheBrainFamily/cypress-cucumber-example/tree/master#usage-of-and

the CRD is strange

```
    args:
      - "run"
      - "--project"
      - "<projectPath>"
      - "--env"
      - "TAGS='@test"
      - "or"
      - "@coucou'"
      - "--browser"
      - "chrome"
```

**Comment by rangoo94** [comment]
The fix has landed in the Cloud already, we will release OSS fix this week.
