### ISSUE TITLE
testkube cli self signed cert as a ingress

### ISSUE THREAD

**Issue by joelcomp1** [kubeshop/testkube#4633]
**Describe the bug**
When running Test Kube in a cluster with self signed cert, when I connect to the address using the correct URL I get a:

tls: failed to verify certificate: x509: certificate signed by unknown authority)

error and from what i can see there is no --insecure or --tls-no-verify etc arg to pass to allow it to proceed. 

**To Reproduce**
1. Install Test Kube in K8s and use a self signed cert to terminate the ingress SSL
2. Try to connect to the service using the DNS URL
3. See tls: failed to verify certificate: x509: certificate signed by unknown authority)

**Expected behavior**
Should provide a cmd line switch to overwrite that error.

**Version / Cluster**
- Which testkube version: 1.15.18
- What Kubernetes cluster? K3D (K3S)
- What Kubernetes version: v1.25.9

**Screenshots**
testkube -a https://testkube.bcp.local/results --client direct  get artifact test

results in:

no test or test suite execution was found with the following id (error: Get "https://testkube.bcp.local/results/v1/test-suite-executions/fa": tls: failed to verify certificate: x509: certificate signed by unknown authority)

**Comment by vsukhin** [comment]
thank you @joelcomp1 good suggestion, we will add the flag
