### ISSUE TITLE
Testsuite execution with delays - incorrect test result is returned during the execution

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#4641]
**Describe the bug**
Testsuite with 2hr delay don't process other step
https://demo.testkube.dev/test-suites/testsuite-1/executions/655b3afe14c8558abe6f465d

**To Reproduce**
1. Run 'Testsuite with multiple steps'
2. Specify 'have 2hr delay on first step'
3. See error 'Test suite finished after first step'

**Expected behavior**
Testsuite should be processed properly 

**Version / Cluster**
- Which testkube version? 1.15.7
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) GKE
- What Kubernetes version? 1.24

**Comment by vsukhin** [comment]
closed in favor of #4646

**Comment by tkonieczny** [comment]
> closed in favor of #4646

That's a different one

**Comment by tkonieczny** [comment]
Adding a summary here:
First the first "stage" is executed and the testsuite is incorrectly marked as `passed`. Then (after 20-30 seconds), testsuite is marked as `running` again, and stage 2, and then 3 are executed. The testsuite is then marked as `failed` after the execution is really finished.
https://demo.testkube.dev/test-suites/testsuite-delay-test/executions/655c9457dbce59953d84c252

![ts1](https://github.com/kubeshop/testkube/assets/1473096/7328341e-a3e2-4558-9651-b678bb3253a0)
![ts2](https://github.com/kubeshop/testkube/assets/1473096/c53fb1b9-f6e7-41d8-bcf2-1dbf4582f18d)
![ts3](https://github.com/kubeshop/testkube/assets/1473096/356a55ce-1376-42c1-a5df-cd2b89299d99)
