### ISSUE TITLE
Add parameters --git-username-secret-reference and --git-token-secret-reference to CLI

### ISSUE THREAD

**Issue by ademar59** [kubeshop/testkube#4666]
**Describe the enhancement you'd like to see**
Add the features to manage git username and token in kubernetes secrets

This is more secure and add the feature to use same account for many projects.

**Comment by vsukhin** [comment]
thank you @ademar59 we will plan it out

**Comment by vsukhin** [comment]
hey @ademar59 
we have
--git-token-secret stringToString            git token secret in a form of secret_name1=secret_key1 for private repository (default [])
--git-username-secret stringToString         git username secret in a form of secret_name1=secret_key1 for private repository (default [])

is it enough?

**Comment by ademar59** [comment]
yes

**Comment by vsukhin** [comment]
thank you! cool!, then closing this issue, feel free to reopen it, if you have additional questions
