### ISSUE TITLE
No documentation about artifacts usage

### ISSUE THREAD

**Issue by sylock** [kubeshop/testkube#4667]
**Describe the bug**
We have created a bash custom executor. I would like to be able to save artifacts generated by the script. I don't understand how and there is no documentation about it. There are only pages related to the CLI (to download existing artifacts) and to configure an external S3 storage. But not how to produce/store them from a test. Or did I missed it?

**The test**
```bash
echo "test artifact" > /data/myartifact.txt
```

**The executor**
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: awx-executor
  namespace: testkube
spec:
  types:
  - bash/custom
  executor_type: container
  image: python:latest
  command:
  - "/bin/sh"
  - "-c"
  content_types:
  - string
```

**My question**
Can you help me in storing artifacts with custom executor?

**Version / Cluster**
- Which testkube version? Chart v1.15.28
- What Kubernetes cluster? Openshift v 4.12.41

**Comment by vsukhin** [comment]
hey @sylock what about this http://docs.testkube.io/test-types/container-executor#collecting-test-artifacts?

**Comment by sylock** [comment]
It helped (did not found this piece of doc - searching on "artifact" in the search box does not show this page) -> shouldn't it be in the "Concepts" entry like the other foundations concepts like variable etc?

![2023-11-23_13h14_55](https://github.com/kubeshop/testkube/assets/2362405/3efa1f3e-93f8-47b4-a307-9577acee6276)

**Comment by sylock** [comment]
Another question: is it possible to make the configuration of the artifacts instance-wide? or Executor-wide? So there is a default for all tests? The default /data/artifacts does not work on openshift due to storageClassName: standard does not exists but must be 
storageClassName: lvms-local-disks

**Comment by vsukhin** [comment]
yeah, docs can be alwaays impoved :)
we don't have executor level defaults for artifacts now, feel free to open a feature request

**Comment by sylock** [comment]
Still I think there is an issue in the documentation that says about artifacts:
"You have to define the storage class name, volume mount path and directories in this volume with test artifacts. Default volume mount path is /data/artifacts and directory is ."

But I don't see that defaul in the job-container-template.yml
So from my understanding, or you define the complete artifact block, or there is nothing by default. Correct?

## test config of artifact
```yaml
spec:
  executionRequest:
    artifactRequest:
      storageClassName: standard
      volumeMountPath: /share/artifacts
      dirs:
        - .
```

## job-container-template.yml
```yaml
          containers:
          - name: "{{ .Name }}"
            image: {{ .Image }}
            imagePullPolicy: Always
            {{- if gt (len .Command) 0 }}
            command:
            {{- range $cmd := .Command }}
            - {{ $cmd -}}
            {{- end }}
            {{- end -}}
            {{- if gt (len .Args) 0 }}
            args:
            {{- range $arg := .Args }}
            - {{ $arg -}}
            {{- end }}
            {{- end }}
            {{- if .WorkingDir }}
            workingDir: {{ .WorkingDir }}
            {{- end }}
            volumeMounts:
            - name: data-volume
              mountPath: /data
            {{- if .CertificateSecret }}
            - name: {{ .CertificateSecret }}
              mountPath: /etc/certs
            {{- end }}
            {{- if .ArtifactRequest }}
              {{- if .ArtifactRequest.VolumeMountPath }}
            - name: artifact-volume
              mountPath: {{ .ArtifactRequest.VolumeMountPath }}
              {{- end }}
            {{- end }}
            {{- range $configmap := .EnvConfigMaps }}
            {{- if and $configmap.Mount $configmap.Reference }}
            - name: {{ $configmap.Reference.Name }}
              mountPath: {{ $configmap.MountPath }}
            {{- end }}
            {{- end }}
            {{- range $secret := .EnvSecrets }}
            {{- if and $secret.Mount $secret.Reference }}
            - name: {{ $secret.Reference.Name }}
              mountPath: {{ $secret.MountPath }}
            {{- end }}
            {{- end }}
          volumes:
          - name: data-volume
            emptyDir: {}
          {{- if .CertificateSecret }}
          - name: {{ .CertificateSecret }}
            secret:
              secretName: {{ .CertificateSecret }}
          {{- end }}
          {{- if .ArtifactRequest }}
            {{- if and .ArtifactRequest.VolumeMountPath .ArtifactRequest.StorageClassName }}
          - name: artifact-volume
            persistentVolumeClaim:
              claimName: {{ .Name }}-pvc
            {{- end }}
          {{- end }}
          {{- range $configmap := .EnvConfigMaps }}
          {{- if and $configmap.Mount $configmap.Reference }}
          - name: {{ $configmap.Reference.Name }}
            configmap:
              name: {{ $configmap.Reference.Name }}
          {{- end }}
          {{- end }}
          {{- range $secret := .EnvSecrets }}
          {{- if and $secret.Mount $secret.Reference }}
          - name: {{ $secret.Reference.Name }}
            secret:
              secretName: {{ $secret.Reference.Name }}
          {{- end }}
          {{- end }}
```
