### ISSUE TITLE
Setting nodeSelector and Tolerations for JobExecutor

### ISSUE THREAD

**Issue by angelokurtis** [kubeshop/testkube#4684]
Hey all,

We're using Testkube to validate some components of our solution, and in our environment, we have the need to set `nodeSelector` and `tolerations` for the JobExecutor. Currently, is there a way to configure these options?

**Comment by vsukhin** [comment]
yes, http://docs.testkube.io/articles/creating-tests#changing-the-default-job-template-used-for-test-execution
