### ISSUE TITLE
Aggregation stage not supported: '$lookup on multiple join conditions and uncorrelated subquery.

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4697]
**Describe the bug**
Unable to reopen #4680 

I am getting a new error after upgrading to version 1.16.9

```sh
failed to list tests with executions: could not get latest executions: could not get latest executions for tests [....] sorted by start time: Aggregation stage not supported: '$lookup on multiple join conditions and uncorrelated subquery', context: null
```
Version / Cluster

Testkub API: 1.16.9
Testkube Dashboard: 1.16.1
Testkube Operator: 1.16.0

![image](https://github.com/kubeshop/testkube/assets/20645040/6e0fe2d4-8f6d-4bd1-9d90-acfc9bc669cb)

There is a new warning on API logs 

```sh
{"level":"warn","ts":1701207900.3493106,"caller":"api-server/main.go:276","msg":"failed to apply MongoDB migrations: failed to apply MongoDB migrations: failed to save '01_create_indexes' migration state to database: write exception: write errors: [Document can't have '.' in field names: testsuite.name]"}
```

**Comment by vsukhin** [comment]
thank you @michaelsatish will think about it

**Comment by rangoo94** [comment]
Hi @michaelsatish!

Sorry for the problems. I will set up AWS DocumentDB today to ensure that all works fine in this flavor.

**Comment by michaelsatish** [comment]
@rangoo94 No worries. Thank you so much for looking into this.
