### ISSUE TITLE
feach artifacts from the last test

### ISSUE THREAD

**Issue by HILLJAY1019** [kubeshop/testkube#4708]
When i run testsuits, can i feach artifacts generated by the last test which store in the s3.For now,it seems like i can only upload the special dir's file to the s3 and i can't download it ?

**Comment by vsukhin** [comment]
hey, @HILLJAY1019 
yes, http://docs.testkube.io/articles/creating-test-suites#passing-test-suite-artifacts-between-steps

**Comment by vsukhin** [comment]
` /data/downloaded-artifacts/{execution id}` folder

**Comment by vsukhin** [comment]
hope, that helps
