### ISSUE TITLE
[TKC-1009] Linear - GitHub Integration test

### ISSUE THREAD

**Issue by jmorante-ks** [kubeshop/testkube#4726]
This will the description created from Linear.

<sub>From [SyncLinear.com](https://synclinear.com) | [TKC-1009](https://linear.app/kubeshop/issue/TKC-1009/linear-github-integration-test)</sub>

**Comment by TheBrunoLopes** [comment]
Hello Bruno here

**Comment by jmorante-ks** [comment]
Testing from GitHub

**Comment by vsukhin** [comment]
It's mine

**Comment by jmorante-ks** [comment]
Testing from Linear

**Comment by TheBrunoLopes** [comment]
hello

**Comment by TheBrunoLopes** [comment]
should work now

**Comment by jmorante-ks** [comment]
Just checking that after Bruno created the sync, it is still working for me too (comment from GitHub)

**Comment by jmorante-ks** [comment]
Just checking that after Bruno created the sync, it is still working for me too (comment from Linear)

**Comment by exu** [comment]
Hello!

**Comment by exu** [comment]
Hello from Linear!

**Comment by rangoo94** [comment]
linear to gh again

**Comment by rangoo94** [comment]
gh to linear

**Comment by rangoo94** [comment]
gh to linear again

**Comment by jmorante-ks** [comment]
From GH to Linear.

**Comment by rangoo94** [comment]
gh to linear

**Comment by vLia** [comment]
Testing the integration

**Comment by vLia** [comment]
Testing the integration from GitHub - with code sample because I am curious:
```
this is code
```
🟪

**Comment by vLia** [comment]
Testing it normally from GitHub

**Comment by jmorante-ks** [comment]
New test from GH to Linear

**Comment by jmorante-ks** [comment]
New test from Linear to GitHub

**Comment by jmorante-ks** [comment]
New test from GH to Linear

**Comment by jmorante-ks** [comment]
Tried to redeploy again. Comment from GH to Linear.

**Comment by nicufk** [comment]
Test

**Comment by nicufk** [comment]
Test from Linear
