### ISSUE TITLE
Named test runs include number of execution.

### ISSUE THREAD

**Issue by jmorante-ks** [kubeshop/testkube#4770]
**Describe the bug**
The option "-name" for test runs is not working as expected, because, in addition to the specified name, it includes the number of execution of the test.

**To Reproduce**
1. Execute CLI command "testkube run test --name=custom-run-name my-test"
2. Test will run properly but the execution name will be "custom-run-name-_number_", where _number_ is the counter of executions of the executed test.

**Expected behavior**
The test run name should be "custom-run-name".

NOTE: If there is a conflict because name already exists and it requires to be unique, in that case it could make sense that Testkube includes execution number.
 
**Additional context**
It would be good to double check if this works for test suites (I haven't checked it).

**Comment by 3keyroman** [comment]
This works well on testsuites. Running `testkube run testsuite my-test-suite --name custom-name`:

```
Context:  (1.16.13)   Namespace: testkube
-----------------------------------------
Name          : my-test-suite
Execution ID  : 657ab9b5588768b17f450f1b
Execution name: custom-name
Status        : running
```

And then I can get the execution result using `testkube get testsuiteexecution custom-name`.
