### ISSUE TITLE
Testkube crashing and behaving abnormally, when increasing the load and duration of execution cycle.

### ISSUE THREAD

**Issue by Janemils** [kubeshop/testkube#4781]
**Describe the bug**
When I run a test script [in my example: K6] in testkube, for a duration of 30m and total number of 30 virtual users, I am observing that the testkube ui is crashing and behaving abnormally after 10 minutes of the test execution. When I say abnormally, I have observed the following scenarios:
- The dashboard becomes unresponsive.

- The liveness and readiness status of the pods like testkube-api-server, testkube-dashboard, testkube-mongodb, etc fails and the pods keep restarting during the duration of the test execution.

- After the test execution is done, I am not able to access the logs, both from the dashboard as well as the CLI.  
![image](https://github.com/kubeshop/testkube/assets/143650941/2a01a33d-b3c0-464f-b937-e2bc2b12c084)
![image](https://github.com/kubeshop/testkube/assets/143650941/1e036948-44d9-4ad5-ad97-2a0008c62023)

**To Reproduce**
1) Create a test in testkube using a sample k6 scripts.
2) Run the test for a duration of 30 minutes for 30 virtual users. [longer duration and more number of vus]

**Expected behavior**
You should be able to view the k6 performance metrics, something as similar to the one in the screenshot.
![image](https://github.com/kubeshop/testkube/assets/143650941/248f6f71-fac1-4684-a743-6abc28ab1b25)

**Version / Cluster**

- Which testkube version? 
Client Version 1.14.4
Server Version 1.16.16

- What Kubernetes cluster? 
Local Minikube.

- What Kubernetes version?
minikube version: v1.32.0

**Screenshots**
- Unresponsive dashboard:
![image](https://github.com/kubeshop/testkube/assets/143650941/2e9eda68-bcf4-44cd-9efe-43ff3a153ede)

- Liveness and Readiness Probes failing:
 ![image](https://github.com/kubeshop/testkube/assets/143650941/6081125c-51ff-4d1b-8453-42c42caae029)

- Multiple pod restarts:
![image](https://github.com/kubeshop/testkube/assets/143650941/52ba0218-01c6-42dd-842e-74c63835fcdf)
 
**Additional context**
When I run for 30s with just 2 users, the tests runs flawlessly and generates the output.
The issue is observed, when we run tests for longer duration and with a heavy load.

**Comment by vsukhin** [comment]
hey @Janemils it's  not Testkube speicif or something unexpected. Our client run tests fo several hours or create load of a few thousands requests per second. But you need to have enough k8s resources for this as obvious. Ping @TheBrunoLopes  to know more about Testkube Pro scalability and performance feeature

**Comment by vsukhin** [comment]
hey @Janemils have you increased k8s resource to avoid this issue?

**Comment by vsukhin** [comment]
closing for now: k8s resource provisioning is out of Testkube scope
