### ISSUE TITLE
Store test execution history much longer

### ISSUE THREAD

**Issue by HenryGuo1019** [kubeshop/testkube#4804]
When i check the historical test exectution in UI ,it seems like they only store in one day . Is there any parameter I can config for that?

**Comment by vsukhin** [comment]
for our frontend team to check @rangoo94

**Comment by rangoo94** [comment]
Hi @HenryGuo1019!

By default, we are showing the executions from the last 7 days. If you want to display them from a longer timeframe, you may select a different period with a timeframe dropdown.

<img width="2056" alt="Zrzut ekranu 2023-12-30 o 15 36 02" src="https://github.com/kubeshop/testkube/assets/3843526/e830ae52-ba52-4d51-9263-ea39261cd0c4">

Does it help you, or maybe there are actually execution data missing?
