### ISSUE TITLE
Documentation on running tests uses an invalid flag in the example

### ISSUE THREAD

**Issue by dejanzele** [kubeshop/testkube#4844]
**Describe the bug**
In the [Passing Parameters](https://docs.testkube.io/articles/running-tests/#passing-parameters) section of the [Running tests](https://docs.testkube.io/articles/running-tests) page it is mentioned that parameters can be passed using `-p`.

Example:
```
kubectl testkube run test kubeshop-cypress -p testparam=testvalue -f --secret secret-name=secret-key
```

But when this command is executed, it errors with `unknown shorthand flag: 'p' in -p`

**To Reproduce**
1. Try to run any test with `-p` parameter and it will fail with the same error

**Expected behavior**
Test is run with the provided parameter(s).

**Version / Cluster**
- Which testkube version?  Any
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) Any
- What Kubernetes version? Any
 
**Additional context**
This was reported by users on Discord [here](https://discord.com/channels/884464549347074049/885185707419770930/1187835143667335219)

**Comment by windowsrefund** [comment]
FYI, This may relate in one way or another to #787 which was also recently discussed in this Discord [thread](https://discord.com/channels/884464549347074049/885185660808474664/1188663142918656123).
