### ISSUE TITLE
jmeter test - argument list too long 

### ISSUE THREAD

**Issue by luca-loiacono** [kubeshop/testkube#4883]
Good evening, 
with testkube we receive an "argument list too long" error when we use jmeter type tests. The tests were created by the gui in various ways (file, string, browse) but the error is always the same. the .jmx file runs fine from type jmeter without testkube.

if instead I use the same .jmx file with the jmeter binary it works correctly

the file is about 3k lines long

how can I solve it?

**Comment by vsukhin** [comment]
hey @luca-loiacono can you please provide your test CRD?

**Comment by luca-loiacono** [comment]
hi @vsukhin , sure!
I attached test CRD.

[jmeter-testkube.txt](https://github.com/kubeshop/testkube/files/13908869/jmeter-testkube.txt)


Thank You!

**Comment by vsukhin** [comment]
hey @luca-loiacono please move it to git epo. see our examples https://github.com/kubeshop/testkube/tree/develop/test/jmeter/executor-tests
content:string not for such big files

**Comment by vsukhin** [comment]
do you still have error about missing secret?

**Comment by vsukhin** [comment]
please follow provided suggestion
