### ISSUE TITLE
Cloud - issue with schedule

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#4888]
**Describe the bug**

Issue with cron scheduler for tests 

Issues reported by user on 

```
tarting test execution testkube/leyline-backend-auth-develop-postman-collection (error: api/POST-testkube.Execution returned error: can't get problem from api response: invalid character '{' after top-level value, output: {"type":"about:blank","title":"Request Timeout","status":408,"detail":"agent request timeout","instance":"/organizations/tkcorg_75bca4e677bcd352/environments/tkcenv_fa028ff32eb6cccb/agent/tests/leyline-backend-auth-develop-postman-collection/executions"}{"type":"about:blank","title":"Internal Server Error","status":500,"detail":"An internal error has occurred. The development team has been notified and will fix it soon.","instance":"/organizations/tkcorg_75bca4e677bcd352/environments/tkcenv_fa028ff32eb6cccb/agent/tests/leyline-backend-auth-develop-postman-collection/executions"})
```

**Version / Cluster**
- Which testkube version? 1.16.16, Installed with helm.
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Comment by elmbark2023** [comment]
we are using AKS cluster, 

kubernetes. 1.28.3.

**Comment by elmbark2023** [comment]
error log:

```
{"level":"error","ts":1705340327.2537289,"caller":"agent/agent.go:197","msg":"agent stream receive: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR","stacktrace":"github.com/kubeshop/testkube/pkg/agent.(*Agent).receiveCommand\n\t/home/runner/work/testkube/testkube/pkg/agent/agent.go:197\ngithub.com/kubeshop/testkube/pkg/agent.(*Agent).runCommandLoop.func1\n\t/home/runner/work/testkube/testkube/pkg/agent/agent.go:235\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75"}
{"level":"error","ts":1705340327.2539122,"caller":"agent/agent.go:120","msg":"agent connection failed, reconnecting","error":"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR","stacktrace":"github.com/kubeshop/testkube/pkg/agent.(*Agent).Run\n\t/home/runner/work/testkube/testkube/pkg/agent/agent.go:120\nmain.main.func3\n\t/home/runner/work/testkube/testkube/cmd/api-server/main.go:491\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75"}
{"level":"info","ts":1705340332.254776,"caller":"agent/agent.go:221","msg":"initiating streaming connection with Cloud API"}
{"level":"info","ts":1705340332.2552564,"caller":"agent/logs.go:22","msg":"initiating log streaming connection with Cloud API"}
{"level":"error","ts":1705344553.239975,"caller":"agent/agent.go:197","msg":"agent stream receive: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR","stacktrace":"github.com/kubeshop/testkube/pkg/agent.(*Agent).receiveCommand\n\t/home/runner/work/testkube/testkube/pkg/agent/agent.go:197\ngithub.com/kubeshop/testkube/pkg/agent.(*Agent).runCommandLoop.func1\n\t/home/runner/work/testkube/testkube/pkg/agent/agent.go:235\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75"}
{"level":"error","ts":1705344553.2401547,"caller":"agent/agent.go:120","msg":"agent connection failed, reconnecting","error":"rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: INTERNAL_ERROR","stacktrace":"github.com/kubeshop/testkube/pkg/agent.(*Agent).Run\n\t/home/runner/work/testkube/testkube/pkg/agent/agent.go:120\nmain.main.func3\n\t/home/runner/work/testkube/testkube/cmd/api-server/main.go:491\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\t/home/runner/go/pkg/mod/golang.org/x/sync@v0.4.0/errgroup/errgroup.go:75"}
```

**Comment by elmbark2023** [comment]
test definition,

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: | 
(**postman collection file content)
  creationTimestamp: "2024-01-11T16:11:19Z"
  generation: 6
  labels:
    argocd.argoproj.io/instance: testkube-service-tests-postman
    executor: postman-executor
    test-type: postman-collection
  name: leyline-backend-jobs-develop-postman-collection
  namespace: testkube
  resourceVersion: "65262804"
  uid: abe149c9-8be7-450c-81e6-01e30ad4edc5
spec:
  content:
    data: (**postman collection file content)
    type: string
  schedule: '*/5 * * * *'
  type: postman/collection
status:
  latestExecution:
    endTime: "2024-01-13T17:00:15Z"
    id: 65a2c190b4e8e2810ee4c419
    number: 10
    startTime: "2024-01-13T17:00:00Z"
    status: passed
```

**Comment by elmbark2023** [comment]
any update?

**Comment by jmorante-ks** [comment]
@vsukhin , please, could you help us with this issue? Do you have any suggestion/guess about what could be causing this problem? Thanks!

**Comment by vsukhin** [comment]
hey @elmbark2023 can you please list cronjobs in Testkube namespace kubectl get cronjobs -n testkube
Also can you try to change your schedule to */10 and check testkube-operator logs, which is responsible for cronjob creation

**Comment by elmbark2023** [comment]
thanks for the response!
`kubectl get cronjobs -n testkube` outputs nothing, how to check the testkube-operator logs?

**Comment by exu** [comment]
@elmbark2023 

```
kubectl logs -ntestkube  -l control-plane=controller-manager --all-containers
```

**Comment by vsukhin** [comment]
@elmbark2023   is it still an issue?

**Comment by elmbark2023** [comment]
{"L":"LEVEL(-5)","T":"2024-02-15T21:44:21.318Z","M":"Reconciling","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-applications-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-applications-develop-postman-collection","reconcileID":"de2304bc-d317-4a27-b418-cb2405543a86"}
{"L":"ERROR","T":"2024-02-15T21:44:21.321Z","M":"Reconciler error","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-applications-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-applications-develop-postman-collection","reconcileID":"de2304bc-d317-4a27-b418-cb2405543a86","error":"CronJob.batch \"leyline-backend-applications-develop-postman-collection-tests\" is invalid: metadata.name: Invalid value: \"leyline-backend-applications-develop-postman-collection-tests\": must be no more than 52 characters","S":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"L":"LEVEL(-5)","T":"2024-02-15T21:44:21.321Z","M":"Reconciling","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-auth-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-auth-develop-postman-collection","reconcileID":"a55d351d-04e6-48d5-a78e-b83aa70d5e81"}
{"L":"ERROR","T":"2024-02-15T21:44:21.324Z","M":"Reconciler error","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-auth-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-auth-develop-postman-collection","reconcileID":"a55d351d-04e6-48d5-a78e-b83aa70d5e81","error":"CronJob.batch \"leyline-backend-auth-develop-postman-collection-tests\" is invalid: metadata.name: Invalid value: \"leyline-backend-auth-develop-postman-collection-tests\": must be no more than 52 characters","S":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"L":"LEVEL(-5)","T":"2024-02-15T21:44:21.324Z","M":"Reconciling","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-companies-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-companies-develop-postman-collection","reconcileID":"fecba680-c71a-4275-bb39-ba588ab7ebc3"}
{"L":"ERROR","T":"2024-02-15T21:44:21.328Z","M":"Reconciler error","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-companies-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-companies-develop-postman-collection","reconcileID":"fecba680-c71a-4275-bb39-ba588ab7ebc3","error":"CronJob.batch \"leyline-backend-companies-develop-postman-collection-tests\" is invalid: metadata.name: Invalid value: \"leyline-backend-companies-develop-postman-collection-tests\": must be no more than 52 characters","S":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"L":"LEVEL(-5)","T":"2024-02-15T21:44:21.329Z","M":"Reconciling","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-jobs-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-jobs-develop-postman-collection","reconcileID":"6bca4173-07ca-4bfc-95bb-98d022a31540"}
{"L":"ERROR","T":"2024-02-15T21:44:21.332Z","M":"Reconciler error","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-jobs-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-jobs-develop-postman-collection","reconcileID":"6bca4173-07ca-4bfc-95bb-98d022a31540","error":"CronJob.batch \"leyline-backend-jobs-develop-postman-collection-tests\" is invalid: metadata.name: Invalid value: \"leyline-backend-jobs-develop-postman-collection-tests\": must be no more than 52 characters","S":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"L":"LEVEL(-5)","T":"2024-02-15T21:44:21.334Z","M":"Reconciling","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-projects-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-projects-develop-postman-collection","reconcileID":"6a419fae-3e87-405a-8d49-86598bc2bbc7"}
{"L":"ERROR","T":"2024-02-15T21:44:21.337Z","M":"Reconciler error","controller":"test","controllerGroup":"tests.testkube.io","controllerKind":"Test","Test":{"name":"leyline-backend-projects-develop-postman-collection","namespace":"testkube"},"namespace":"testkube","name":"leyline-backend-projects-develop-postman-collection","reconcileID":"6a419fae-3e87-405a-8d49-86598bc2bbc7","error":"CronJob.batch \"leyline-backend-projects-develop-postman-collection-tests\" is invalid: metadata.name: Invalid value: \"leyline-backend-projects-develop-postman-collection-tests\": must be no more than 52 characters","S":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
I1218 06:21:19.834467       1 main.go:190] Valid token audiences: 
I1218 06:21:19.835061       1 main.go:262] Generating self signed cert as no cert is provided
I1218 06:21:20.596917       1 main.go:311] Starting TCP socket on 0.0.0.0:8443
I1218 06:21:20.597359       1 main.go:318] Listening securely on 0.0.0.0:8443


it seems we have to rename the collection.

**Comment by vsukhin** [comment]
sounds like we need to sanitize cronjob name. pls rename, we will add a wrapper

**Comment by vsukhin** [comment]
sanitized name
