### ISSUE TITLE
Support ServiceAccount in Testkube CLI

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4904]
**Describe the enhancement you'd like to see**

At the moment, when Testkube CLI is running within Kubernetes, we need to either:
* try to convert service account to kubeconfig, or
* use `--client direct` with internal API URL

It would be great if Testkube CLI would use the provided Service Account, similarly to [**kubernetes/client-go's example**](https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L41-L50).

The logic responsible for connecting with Kubernetes is [**here**](https://github.com/kubeshop/testkube/blob/develop/pkg/api/v1/client/proxy_client.go#L22-L41).

**Additional context**

As an example, using `bitnami/kubectl` image with service account in Kubernetes will lead to `kubectl` working automatically.

**Comment by TheBrunoLopes** [comment]
can you give an example of the command that the user is going to write ?

**Comment by rangoo94** [comment]
Any kind of command. As an example, `testkube run test example-test`.

**Comment by kennethredler** [comment]
Yes. Is there an alternative, perhaps more declarative pattern for triggering a test other than invoking testkube CLI?

It's one thing to [sync](https://testkube.io/blog/flux-testkube-gitops-testing-is-here) the test definitions to Kubernetes with a GitOps approach.

But what about invoking the tests using similar GitOps approach? Demo/docs only mention testkube CLI.

![Screenshot_20240227-164426](https://github.com/kubeshop/testkube/assets/22832065/e84a5d1c-4c3d-4d09-9732-eb839d79fed2)


CLI could be run as a (Cron)Job but doesn't support ServiceAccount-mapped tokens.

**Comment by vsukhin** [comment]
sure, http://docs.testkube.io/articles/test-executions
