### ISSUE TITLE
Cache the Testkube binary in the GitHub Action

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4939]
We should cache the Testkube binary using [**@actions/tool-cache**](https://www.npmjs.com/package/@actions/tool-cache). You may find an example in [`azure/setup-kubectl`](https://github.com/Azure/setup-kubectl/blob/main/src/run.ts).

At the moment we are calling GitHub API each time, which results in the [**rate limit errors**](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users) for frequent workflows.

**Comment by rangoo94** [comment]
Fixed with https://github.com/kubeshop/setup-testkube/pull/4

**Comment by itsme2980** [comment]
Hi @devcatalin , @rangoo94 Thank you for the concise support regarding this feature. I've recently had the opportunity to review your implementation, and I'd like to share some comments from my perspective. This approach is only viable once Testkube is successfully installed within the GitHub Actions (GA) workflow. This means the cache is effective only when Testkube has been installed. There's a scenario where GitHub.io might impose rate limits, rejecting installation from anonymous access, rendering this caching implementation ineffective.

I propose we implement an additional feature: allowing users to define the GitHub.io Personal Access Token (PAT) within the action.yaml. This PAT could then be used to authorize with GitHub.io, overcoming potential rate-limiting issues. For more details about the token property I mentioned, you can refer to https://github.com/actions/setup-python.

The combination of a GitHub.io token and caching would be highly beneficial. 👍

**Comment by itsme2980** [comment]
Also, once the `setup-testkube` is executed successfully, I could not find the cache at `https://<git-url>/<repo-org>/<repo-name>/actions/caches`. In the build log, at `Complete runner` and `Complete job` I also couldn't find the message to store cache. Do you need any further details to help you able to trace this issue?

**Comment by rangoo94** [comment]
Hi @itsme2980!

Thank you, regarding the first proposal, I have added a new ticket for that - https://github.com/kubeshop/testkube/issues/4965.

When it comes to cache - you won't find the cache, as we are using built-in GitHub's mechanism for caching binaries, and it's working only on self-hosted workers ([**@actions/tool-cache**](https://www.npmjs.com/package/@actions/tool-cache)). We cannot use the actual GH cache, as it's not possible from the action level.

If you want to avoid requests to the GH API, you may also use [**`version` parameter**](https://github.com/kubeshop/setup-testkube?tab=readme-ov-file#common) specifically - this way, the `setup-testkube` won't try to find the latest release using GH API, it will only download the binary.
