### ISSUE TITLE
Bug: nothing is run when the `preRunScript` is passed

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4980]
**Describe the bug**

The Test succeeds without running anything 

**To Reproduce**

* https://demo.testkube.io/tests/prerun-bug

**Expected behavior**

It should run both command and pre run script

**Comment by vsukhin** [comment]
1. It should be used `$CONTENTS`, not `$CONTENT`
2. No need to bash shell in command, just `node index.js`
