### ISSUE TITLE
prerun.sh is not run using source command

### ISSUE THREAD

**Issue by Estegar** [kubeshop/testkube#5004]
**Describe the bug**
Unable to export environment variables in a manner that allows Playwright to access them.

**To Reproduce**
create .sh file with:

```bash
export SOME_ENV_VARIABLE=some_value
npx playwright test
```

In Playwright code read somewhere SOME_ENV_VARIABLE using process.env.SOME_ENV_VARIABLE

Create Testkube test that will use native Playwright executor. Add your .sh file to run in Pre-Run phase.
What will happen is test run in Pre-Run phase will have access to SOME_ENV_VARIABLE but test run using executor-binary will not have access to that variable.

**Expected behavior**
SOME_ENV_VARIABLE should be available in both cases. export SOME_ENV_VARIABLE should add it to global context

**Version / Cluster**
- Which testkube version? 
API Versionv1.16.26
Dashboard Versionv1.16.2
Helm Chart Versionv1.16.34

- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
Kubernetes cluster OnPrem
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.20.2
 
**Additional context**
To resolve that problem, entrypoint.sh, prerun.sh, postrun.sh should all be run using the source command. We tried that and it worked.
We aim to utilize the native Playwright executor and prefer not to develop our own, especially just for incorporating environment variables.

**Comment by Destrukcja95** [comment]
The same problem here... 
I thought that configured prerun.sh script badly. But we have the same problem in our kubernetes cluster. I tried to run entrypoint.sh, prerun.sh with source command and it's work but i think it is not the best way to do it.
Is it possible to solve this problem?

**Comment by loorcker** [comment]
Up! Same problem here. Spent many hours.

**Comment by vsukhin** [comment]
thank you, @Estegar Have you try to use Testkube variablles, or there is a reason to export this env var in pre run script?

**Comment by Estegar** [comment]
> thank you, @Estegar Have you try to use Testkube variablles, or there is a reason to export this env var in pre run script?

I have multiple variables to export, and they are dynamic. Some of these values need to be obtained from other sources using scripts (Python, for instance). I also need to retrieve library versions. All of this information needs to be available in my Playwright script.

I don't believe there is a way to achieve this using Testkube variables.

To provide some context: we already have a system in place that operates similarly, but Testkube provides a better way to handle things than our current system. In order for this to work, we need to replicate some elements, and for the most part, we have done that. The only remaining task is dealing with these environment variables.

**Comment by vsukhin** [comment]
thank you, @Estegar it make sense

**Comment by Estegar** [comment]
> thank you, @Estegar it make sense. we will work on it

@vsukhin 
Hello, what is the estimated time for resolving this issue? Will it be completed in days or weeks? I'm asking because if it takes longer, I may implement a workaround to proceed with my tasks. :)

**Comment by Estegar** [comment]
@vsukhin
For now, I have a workaround in place. I simply save the data needed in Playwright to files and just read them in TypeScript. It works okay but is a little more complex, so having the source would be a great addition to Testkube features.

**Comment by vsukhin** [comment]
Sure, pr is ready. But I'm busy with other tasks at the moment,so probably weeks (
