### ISSUE TITLE
Adding override job-container-template.yml.tmpl section in testkube/values.yaml 

### ISSUE THREAD

**Issue by loorcker** [kubeshop/testkube#5017]
Hello, 

is there a possibility of adding section to main chart testkube/values.yaml to override job-container-template for custom container jobs?

At the moment its possible to override just job-template for built-in executors [[LINK](https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml#L281)]:

281 #Custom job-template.yml that will be passed to Testkube API. Example:
282  configValues: |
283    apiVersion: batch/v1
284    kind: Job
285    metadata:
 
   
 **The desired effect:**
```
 
  #Custom job-container-template.yml that will be passed to Testkube API. Example:
  configValues: |
    apiVersion: batch/v1
    kind: Job
    metadata:` 
   .
   .
   .
   #Custom job-template.yml that will be passed to Testkube API. Example:
  configValues: |
    apiVersion: batch/v1
    kind: Job
    metadata:
    .
    .

```

**Comment by vsukhin** [comment]
hey, @loorcker Guess, it shouldn't be difficult to add. @ypoplavs pls take a look

**Comment by loorcker** [comment]
Hello @vsukhin @ypoplavs is it going to be released? :)

**Comment by vsukhin** [comment]
merged to develop
