### ISSUE TITLE
Container executors - unable to download artifacts (404)

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#5040]
**Describe the bug**
It's not possible to download artifacts from container executor - the test is executed, looks like the artifact is scraped correctly, but it's not possible to download them - 404.
Examples:
https://demo.testkube.dev/tests/container-executor-playwright-smoke-args/executions/65d600c42e18ae6af465828d/artifacts
https://demo.testkube.dev/tests/container-executor-cypress-v12.7.0-smoke-git-dir/executions/65d5f1788bffe556407377ef/artifacts

Everything is fine for prebuilt executors:
https://demo.testkube.dev/tests/cypress-default-executor-smoke-electron/executions/65d5ec8c99de3d8d9ac923c2/artifacts

**Comment by vsukhin** [comment]
kubectl testkube download artifacts container-executor-playwright-smoke-args-47
```
Context:  (999.0.0-dev)   Namespace: testkube
---------------------------------------------
parsing server version '62fb735': Invalid Semantic Version
Getting artifacts count = 1 

 - downloading file  artifacts/playwright-report/index.html
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset='UTF-8'>
    <meta name='color-scheme' content='dark light'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Playwright Test Report</title>
    <script type="module">var $p=Object.defineProperty;var e0=(e,t,n)=>t in e?$p(e,t,{enumerable:!0,configurable:!0,writable:!0,value:n}):e[t]=n;var Kt=(e,t,n)=>(e0(e,typeof t!="symbol"?t+"":t,n),n);(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerpolicy&&(s.referrerPolicy=o.referrerpolicy),o.crossorigin==="use-credentials"?s.credentials="include":o.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(o){if(o.ep)return;o.ep=!0;const s=n(o);fetch(o.href,s)}})();var Un=typeof globalThis<"u"?globalThis:typeof window<"u"?window:typeof global<"u"?global:typeof self<"u"?self:{},Ar={},t0={get exports(){return Ar},set exports(e){Ar=e}},cs={},j={},n0={get exports(){return j},set exports(e){j=e}},Q={};/**
 * @license React
 * react.production.min.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 ..
```

**Comment by tkonieczny** [comment]
CLI is fine - so, it's just Dashboard

**Comment by tkonieczny** [comment]
Looks like it happens only while downloading files from inside directory:
- https://demo.testkube.dev/tests/container-executor-cypress-v12.7.0-smoke-git-dir/executions/65d5f1788bffe556407377ef/artifacts - in this case it's `videos/smoke.cy.js.mp4` inside `/data/artifacts`.
- https://demo.testkube.dev/tests/container-executor-cypress-v12.7.0-video-artifacts-only/executions/65d64ec22f6e461b1c9932c6/artifacts - I changed artifacts directory to `/data/artifacts/videos`, so the files are directly there - everything is fine.

Some issue with directories/escaping?

**Comment by MarcoBergonzi** [comment]
i have the same issue here 

![Screenshot from 2024-04-02 11-29-48](https://github.com/kubeshop/testkube/assets/135220486/0933f6ba-84b5-4bac-b25e-0b3a79f888cf)

i cant download the logs, but the report.html is possible
I found out that if i go to the bucket and copy the same file in the directory ( not moving  the existing one, it will be possible downloading the logs.
But it on the ui the logs  are duplicated.
![Screenshot from 2024-04-02 11-36-20](https://github.com/kubeshop/testkube/assets/135220486/9e92b54c-4d46-4946-afcc-d9e3a0b84269)

**Comment by rangoo94** [comment]
We no longer support the [**Dashboard in the OSS version**](https://testkube.io/blog/testkube-dashboard-announcement), so I think that it's obsolete. @TheBrunoLopes?

**Comment by rangoo94** [comment]
We no longer support the [**Dashboard in the OSS version**](https://testkube.io/blog/testkube-dashboard-announcement), so I think that it's obsolete, if that's FE problem. @TheBrunoLopes, @tkonieczny?

**Comment by jmorante-ks** [comment]
This issue is obsolete as @rangoo94 indicated. Closing it.
