### ISSUE TITLE
Container executor - post-run script isn't run after command (test) fails

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#5048]
**Describe the bug**
Post-run script isn't run after command (test) fails in case of container executor. 
Example:
https://demo.testkube.dev/tests/expected-fail-container-pre-post-run-script - pre-run script is executed, test fails, post-run script isn't executed at all

Everything is fine for prebuilt executors (https://demo.testkube.dev/tests/expected-fail-pre-post-run-script/executions/65d70339d23cbe05dcebef98)

**Expected behavior**
Post-run script should be executed even if command failed (and the whole test should be marked as failed then)

**Comment by vsukhin** [comment]
released
