### ISSUE TITLE
Slack integration permissions are scoped too broadly.

### ISSUE THREAD

**Issue by windowsrefund** [kubeshop/testkube#5077]
The Slack integration should not be asking for this permission: `Send messages to channels @testkube-bot isn't a member of`

**Comment by vsukhin** [comment]
thank you @windowsrefund good point!

**Comment by vsukhin** [comment]
for @nicufk to check

**Comment by windowsrefund** [comment]
yes

**Comment by nicufk** [comment]
Hey @windowsrefund, from what I remember it was added to fix a bug when the slack bot was not able to send/update messages in public channels despite it being the member of it. If this is a major concern for you, we can raise it and to plan some research on this topic.

**Comment by vsukhin** [comment]
closing for nowwwww

**Comment by windowsrefund** [comment]
Why was this closed?

**Comment by vsukhin** [comment]
https://github.com/kubeshop/testkube/issues/5077#issuecomment-2007355931

**Comment by vsukhin** [comment]
hey @windowsrefund Regarding using your own bot with restricted permissions.
Can you please try to create it, get Slack token and supply it in helm chart value?
https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml#L708

**Comment by windowsrefund** [comment]
@vsukhin Has something changed to where I might get a different result from when this issue was raised?

**Comment by vsukhin** [comment]
hey @windowsrefund we didn't change anything, but Testkube Bot is not hardcoded in api, we pass the slack token as a helm chart value. So you can create your own bot with allowed permission set like there  https://api.slack.com/start/quickstart and then just pass token value to helm chat. In this case Testkube Bot will not be involved

**Comment by windowsrefund** [comment]
Based on the feedback here and my understanding our team has decided to use a different approach for notifications, I'll get this closed for the time being. As always, thanks for the feedback.
