### ISSUE TITLE
Deduplication of alerts on webhook feature

### ISSUE THREAD

**Issue by Fernandoramas** [kubeshop/testkube#5078]
**Is your feature request related to a problem? Please describe.**
We are missing a functionality which deduplicates the alerts before they reach the incident management platform. If the test runs each 10s, it would trigger the alert only when the status changes, so only one successful event until the status changes to failure. The aim is to **reduce events ingestion** to Incident and management response like PagerDuty. 

**Describe the solution you'd like**
A simple feature that checks the Alert status on a specific configured webhook on Testkube. 

**Describe alternatives you've considered**
To develop an external webhook proxy API to perform the deduplication of alerts.

**Additional context**
Why this is relevant? For instance, PagerDuty has a limit of 960 events/request per minute. If you have some tests with a high enough frequency are going to reach that limit. Plus, alerts are going to floade the incidents dashboards, even with the same dedupkey (+100 pages). This, will make the work for the operators to analyze the incident quite imposible. There are more use cases that would benefit from this feature.
Please, take that into consideration, and thank you for all the effort and good work.

**Comment by vsukhin** [comment]
thank you @Fernandoramas good idea!

**Comment by vsukhin** [comment]
@TheBrunoLopes @jmorante-ks should be included in a list of improvements for webhooks

**Comment by vsukhin** [comment]
implemented in linked pr
