### ISSUE TITLE
Can't use --copy-files with direct client

### ISSUE THREAD

**Issue by ValTimof** [kubeshop/testkube#5118]
**Describe the bug**
When I am running test with `--copy-files` flag and `--client=direct` testkube cli returns error:
```
could not upload files (error: could not upload file test.txt for execution with name 65ea99f7-fa37-45cc-a734-f03c51c33230: Post "/uploads": unsupported protocol scheme "")
```

**To Reproduce**
1. Create testkube test
```sh
echo '{"command": ["curl", "https://jsonplaceholder.typicode.com/todos/1"]' | testkube create test --name example-test --type curl/test
```
2. Create file 'test.txt'
3. Make sure testkube-api-server url is avalable
4. Run test with client direct 
```
testkube run test example-test --copy-files=test.txt:test.txt --client=direct -a http://testkube-api-server:8088
```
5. See error

**Expected behavior**
Testkube CLI direct client mode allows coping files   

**Version / Cluster**
```text
❯ testkube version
Client Version 1.16.34
Server Version 1.16.23
```
```
❯ kubectl version
Client Version: v1.29.2
Server Version: v1.27.11
```

**Additional context**
I am executing test from another pod running in the same namespace using testkube cli binary. Also able to reproduce locally when port forwarding testkube-api-server using kubefwd tool.

**Comment by vsukhin** [comment]
thank you @ValTimof good catch! @vLia can you check it out>

**Comment by vLia** [comment]
Hello @ValTimof , I will try to reproduce this locally and get back to you

**Comment by vLia** [comment]
Hello @ValTimof , I reproduced the issue locally and I also created a PR with the fix. Will ping you as soon as it is released. Thank you for reporting this bug!
