### ISSUE TITLE
Watch execution error with Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by wbauern** [kubeshop/testkube#5210]
**Describe the bug**
We are receiving a runtime error when executing a kubectl testkube watch execution on Ubuntu OS systems.  The same command works fine when running on MacOS laptops.

**To Reproduce**
1. Use an Ubuntu 22.04 LTS system
2. Run a test
3. Run a watch execution command on the test while it is still running
4. See error like the following: 
```panic: runtime error: invalid memory address or nil pointer dereference```

**Expected behavior**
We expected to see the running test's ouput just like on MacOS.

**Version / Cluster**
- Which testkube version? 1.16.25
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.28.6

**Screenshots**
```
$ kubectl testkube watch execution frontend-dev-51

Context:  (1.17.2)   Namespace: testkube
----------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1d5fcf8]

goroutine 1 [running]:
github.com/kubeshop/testkube/cmd/kubectl-testkube/commands.NewWatchCmd.NewWatchExecutionCmd.func3(0xc00054a608?, {0xc00046a250, 0x1, 0x21fb978?})
	github.com/kubeshop/testkube/cmd/kubectl-testkube/commands/tests/watch.go:34 +0x278
github.com/spf13/cobra.(*Command).execute(0xc00054a608, {0xc00046a220, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x867
github.com/spf13/cobra.(*Command).ExecuteC(0x3795f40)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.7.0/command.go:985
github.com/kubeshop/testkube/cmd/kubectl-testkube/commands.Execute()
	github.com/kubeshop/testkube/cmd/kubectl-testkube/commands/root.go:198 +0x4ca
main.main()
	./main.go:24 +0xf
```
 
**Additional context**

**Comment by vsukhin** [comment]
So, yes, we added api in 1.17.*, that is not available in 1.16. Please use same version cli and api
