### ISSUE TITLE
Extend metrics to cover Minio storage

### ISSUE THREAD

**Issue by windowsrefund** [kubeshop/testkube#5303]
Following up on this interesting [Slack thread](https://testkubeworkspace.slack.com/archives/C06D9EYTQ2J/p1712947191041469). I thought it would make sense to ask for some observability into Minio storage via metrics.

**Comment by vsukhin** [comment]
thank you @windowsrefund intersting topic for  our devops team @ypoplavs

**Comment by vsukhin** [comment]
https://github.com/kubeshop/helm-charts/pull/834

**Comment by windowsrefund** [comment]
Awesome! I'll need a day or two since I have to fork newer charts in order to add my network policies. I'll confirm this functionality and look forward to closing this. Thanks again.

**Comment by windowsrefund** [comment]
@vsukhin It looks like this made it into 1.17.43 but I don't see the changes when I pull down and extract that version of the chart.

**Comment by vsukhin** [comment]
not yet published, should be tmo
