### ISSUE TITLE
Docker image inspection broken while using private registry

### ISSUE THREAD

**Issue by frederikb** [kubeshop/testkube#5335]
**Describe the bug**
Similar premise to #5214 . We want to use `preRunScript`s with tests using a custom executor (using container executor).
This custom executor is pulling an image from a private registry.
This triggers Docker image introspection with skopeo which fails with the following error:

```
{"level":"error","ts":1713888739.4958453,"caller":"containerexecutor/tmpl.go:222","msg":"Docker image inspection error","error":"inspecting image: 'my/image/name:sha-deadbeef' at 'my.internal.registry.net' registry: fetching 'my/image/name:sha-deadbeef' image from 'my.internal.registry.net'' registry: could not start process with command: skopeo, exited with code:1  error: exit status 1\noutput: time=\"2024-04-23T16:12:19Z\" level=fatal msg=\"Error parsing image name \\\"my.internal.registry.net/my/image/name:sha-deadbeef\\\": Invalid image name \\\"my.internal.registry.net/my/image/name:sha-deadbeef\\", unknown transport \\\"my.internal.registry.net/my/image/name:sha-deadbeef\\\"\"\n","errorVerbose":"could not start process with command: skopeo, exited with code:1  error: exit status 1\noutput: time=\"2024-04-23T16:12:19Z\" level=fatal msg=\"Error parsing image name \\\"my.internal.registry.net/my/image/name:sha-deadbeef\\\": Invalid image name \\\"my.internal.registry.net/my/image/name:sha-deadbeef\\\", unknown transport \\\"my.internal.registry.net/my/image/name:sha-deadbeef\\"\"\n\nfetching 'my/image/name:sha-deadbeef' image from 'my.internal.registry.net' registry\ngithub.com/kubeshop/testkube/pkg/imageinspector.
```
 The error has skopeo complaining about an `unknown transport`.

**Version / Cluster**
- Which testkube version? 1.17.16
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.29.1
 
**Additional context**
The fix provided in #5224 is IMHO broken:

```go
config := "docker://" + image
if registry != "" {
	config = registry + "/" + image
 }

args = append(args, "--config", config)
```

in case we specify a `registry` this overrides `config` and never prepends `docker://` like in the standard case, thus causing skopeo to error out as seen in the stacktrace which says `unknown transport`.

**Comment by vsukhin** [comment]
hey, @frederikb what solution will work universally? if transport sheme is not provided, then always use docker://. will it work for any private registry?

**Comment by vsukhin** [comment]
?

**Comment by frederikb** [comment]
Hi @vsukhin,

thanks for the follow-up. I haven't had a previous use case with Skopeo, but to my limited knowledge ( https://github.com/containers/skopeo ) you always need to specify the transport when referencing an image.

In my case the private registry is based on Harbor ( https://github.com/goharbor/harbor ) and we access images via the "Docker Registry HTTP API V2", thus `docker://` would be fine for us.

**Comment by vsukhin** [comment]
thank you @frederikb got it

**Comment by vsukhin** [comment]
pr submitted https://github.com/kubeshop/testkube/pull/5377
