### ISSUE TITLE
Support changing output type when running test (suites) via Testkube CLI

### ISSUE THREAD

**Issue by frederikb** [kubeshop/testkube#5336]
**Describe the enhancement you'd like to see**
[As discussed in Slack](https://testkubeworkspace.slack.com/archives/C06D9EYTQ2J/p1713900700059639).

There is currently no way to get only the execution id as the output of `testkube run test` and `testkube run testsuite` in order to process it easily programmatically. The only solution is to parse the pretty output, which is a bit brittle.

I would like to be able to use the `--output` and `--go-template` as already availale for `testkube get execution`. 

**Additional context**
Excerpt from help text for `testkube get execution`.
```
      --go-template string   go template to render (default "{{.}}")
  -o, --output string        output type can be one of json|yaml|pretty|go-template (default "pretty")
```

**Comment by vsukhin** [comment]
thank you @frederikb definitely a tech debt

**Comment by frederikb** [comment]
Thanks, @vsukhin !

**Comment by vsukhin** [comment]
welcome. will release it in next few days
