### ISSUE TITLE
Can this work without creating CRDs?

### ISSUE THREAD

**Issue by taylorjonl** [kubeshop/testkube#5487]
Pretty basic question, can this work without creating CRDs in the cluster?  I ask because I don't have permissions to create CRDs and would like to try this out in a single(existing) namespace.

**Comment by vsukhin** [comment]
hey, @taylorjonl it will not work without CRD. but you can check this article https://docs.testkube.io/articles/install/quickstart-no-k8s

**Comment by vsukhin** [comment]
hope, this is answering the question
