### ISSUE TITLE
Testkube UI Dashboard is not opening

### ISSUE THREAD

**Issue by prashanth-sams** [kubeshop/testkube#5494]
**Describe the bug**

When I type the cmd `testkube dashboard`, I expect the testkube UI to open but it is not happening in my case.

**To Reproduce**
1. Run `testkube dashboard`
2. See error `No dashboard found. Is it running in the testkube namespace`

**Expected behavior**
Testkube UI to be opened in the browser.

**Version / Cluster**
- Which testkube version? 
```
Client Version 1.17.45
Server Version 1.17.46
```
- What Kubernetes cluster?
**local Minikube**

- What Kubernetes version?
**minikube v1.24.0**

**Screenshots**
<img width="683" alt="image" src="https://github.com/kubeshop/testkube/assets/2948696/335ef0b9-3ae8-48ec-8466-e59df8d2fae8">

**Comment by vsukhin** [comment]
hey, @prashanth-sams   https://testkube.io/blog/testkube-dashboard-announcement

**Comment by prashanth-sams** [comment]
@vsukhin Thank you for the link.

Is there a way to do a test run by myself creating a new project with free user access? (I need to use my local as the Kubernetes cluster)

These options doesn't seems to work for a test run in my local

<img width="1619" alt="image" src="https://github.com/kubeshop/testkube/assets/2948696/c8d7b267-0b71-4a24-a23c-0e75423165d6">

Or is it only available for the paid versions?
