### ISSUE TITLE
Double quote disappear when saving args

### ISSUE THREAD

**Issue by padubrulle** [kubeshop/testkube#5506]
**Describe the bug**
In the settings>Variable & Secrets tab we can input text in the argument text box to define args passed to the executor.
When we enter a value between double quotes (e.g. text with spaces) and save, double quotes disappears. They're correctly set in the definition tab but it can be confusing as user.
The issue seems to occurs when you enter something like -argletter "text between quotes" (for example : -g "test name with space")

**To Reproduce**
1 create or open the test page of a test
2 go to Settings
3 go to Variable & Secrets
4 In the text box arguments enter : -g "test name to try the double quote bug"
5 Click on Save button
Result : Double quote disappears

**Expected behavior**
How it should appears : 
![text before save](https://github.com/kubeshop/testkube/assets/138253244/c0ed76d1-65de-47c1-bcab-ebc1042b8ec6)
How it appears : 
![text after save](https://github.com/kubeshop/testkube/assets/138253244/e79e0103-e937-4b62-ab69-ed7e0b17f0bf)

**Version / Cluster**
- Which testkube version? 
API v1.15.13
Dashboard v1.14.2
- What Kubernetes cluster? 
GKE
- What Kubernetes version?
v1.27.12-gke.1115000

**Comment by vsukhin** [comment]
hey @padubrulle it looks like quite old version. we are now at 1.17.48

**Comment by vsukhin** [comment]
we don't support OSS Dashboard, switch to latest available version
