### ISSUE TITLE
testworkflows CLI twe - missing logs property

### ISSUE THREAD

**Issue by Fernandoramas** [kubeshop/testkube#5517]
**Is your feature request related to a problem? Please describe.**
1. I cannot find a way to get the testWorkflows logs with the CLI:
Something similar to this would be neccesary
`testkube get twe [executionID] --logs-only` 

**Describe the solution you'd like**
A concise way of outputing via CLI the logs of the execution and each step of the execution.

**Comment by vsukhin** [comment]
thank you @Fernandoramas !

**Comment by Fernandoramas** [comment]
Hi @vsukhin ,
Thanks for the support. I have checked my somehow is still the flag is not been available:
```
Client Version 1.17.63
Server Version 1.17.63
Commit e1878be7e7bb8781404b7d8da560a40d899a0f8a
Built by goreleaser
Build date 2024-06-12T16:07:37Z
```
```
testkube get testworkflowexecution 6671512041c1ef642d01eb06 --logs-only
Error: unknown flag: --logs-only
Usage:
  testkube get testworkflowexecution [executionID] [flags]
```

**Comment by vsukhin** [comment]
it's in develop branch, will be released soon
