### ISSUE TITLE
Add RunningContext to Test Workflow Execution

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#5632]
**Describe the enhancement you'd like to see**
Add RunningContext to Test Workflow Execution similar to Test and Test Suites

**Comment by rangoo94** [comment]
> blocked by missing requirements for Enterprise edition @jmorante-ks

I wouldn't say that it's just Enterprise - we just don't have anything defined even for OSS

**Comment by vsukhin** [comment]
added
