### ISSUE TITLE
Empty Artifacts Directories in Test Suite

### ISSUE THREAD

**Issue by patrick-kilburn** [kubeshop/testkube#5651]
**Describe the bug**
We're using the older pre-workflow version of Testkube. I have a set of tests in a test suite that have artifacts associated with them. Then there is a final test that executes at the end to analyze all the artifacts. 

The test suite definition for this final analysis test has the following configuration:
`    - stopOnFailure: false
      execute:
        - test: fast-check-test-artifacts
      downloadArtifacts:
        allPreviousSteps: true`

When the final test is executed and I run a simple `ls` command to check for the artifacts, I see the directories created from each previous test located in `/data/download-artifacts`, however all the directories are empty. 

When trying to get the artifacts through the CLI with:
`testkube download testsuite-artifacts {executionId}`
It responds with:
`error: an error on the server ("unknown") has prevented the request from succeeding (get services testkube-api-server:8088)`

I validated that each test execution contains artifacts, however for some reason they're not carried over to final analysis test.

**To Reproduce**
1. Run the test suite with a test that executes at the end with `allPreviousSteps` set to `true`
2. Check the `/data/download-artifacts` directory in the last test

**Expected behavior**
The directory contains a folder for each test execution and its associated artifacts

**Actual behavior**
The directory contains folders for each test execution, but all folders are empty

**Version / Cluster**
- Client Version 1.17.12
- Server Version 1.17.14
- EKS: Server Version: v1.29.4-eks-036c24b

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by patrick-kilburn** [comment]
I did notice further up that it's getting 500s when trying to access the S3 bucket for some reason.
![Screenshot 2024-07-10 at 11 52 49 AM](https://github.com/kubeshop/testkube/assets/127142826/8f37e187-16ce-4dd6-a90f-148ed9f0e140)

**Comment by patrick-kilburn** [comment]
This might be a duplicate of https://github.com/kubeshop/testkube/issues/5279

**Comment by vsukhin** [comment]
hey, @patrick-kilburn 
As you could see in above error - acess is denied to this bucket
And yes, in case of S3 we need different buckets for logs and artifacts.
You can also to try run it in your local k8s cluster with Minio storage to make sure, the whole flow works as expected

**Comment by patrick-kilburn** [comment]
Thanks Vladislav for taking an initial look. This was a duplicate of 5279. After separating the Logs and Artifacts into different S3 buckets, the artifacts were successfully downloaded from previous tests in the test suite.

**Comment by vsukhin** [comment]
welcome!
