### ISSUE TITLE
Unable to login to dashboard

### ISSUE THREAD

**Issue by benke33** [kubeshop/testkube#5752]
**Describe the bug**
Unable to login to the dashboard after installation. 

Login is successful in Dex, but getting this redirect error:
{
  "type": "about:blank",
  "title": "Forbidden",
  "status": 403,
  "detail": "forbidden redirect URL: http://localhost:8082/auth/success",
  "instance": "/auth/callback"
}

**To Reproduce**
$ testkube init demo
$ testkube dashboard

login to dashboard with default credentials:
admin@example.com/password

**Expected behavior**
Login to the dashboard works

**Version / Cluster**
- Which testkube version? 
 v2.0.19
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
Tested in EKS & Minikube with same results
- What Kubernetes version?
1.29 & 1.30
- what browsers?
Chrome & Firefox

**Screenshots**
![Screenshot from 2024-08-08 15-31-38](https://github.com/user-attachments/assets/470dae66-056f-4393-afc5-1cc77a617bf9)

**Comment by vsukhin** [comment]
hey, @benke33 we removed dashboard for OSS in 1.17. If you need it, try our Free Pro edition https://testkube.io/pricing

**Comment by rangoo94** [comment]
@vsukhin, `testkube init demo` is actually the Pro edition

**Comment by benke33** [comment]
works with later versions, 2.1.18

**Comment by CShah-CitiusTech** [comment]
i still see this issue .. what is the quick fix ?
{"type":"about:blank","title":"Forbidden","status":403,"detail":"forbidden redirect URL: http://localhost:8081/auth/success","instance":"/auth/callback"}
