### ISSUE TITLE
Specify the prerun and postrun script paths when creating a test using the testkube CLI.

### ISSUE THREAD

**Issue by dommgifer** [kubeshop/testkube#5787]
**Describe the bug**
When creating a test using the Testkube CLI and specifying the --prerun-script and --postrun-script parameters, the scripts must exist in the specified directory; otherwise, the configuration will fail with a "no such file or directory" error.

My container already includes prerun and postrun scripts, and I just want to set the execution path.

However, after preparing the scripts in the directory, the result of the configuration ends up being the script content rather than the script path.

When I checked the help description for --postrun-script and --prerun-script, it says "path to script to be run." Based on this, the configured result should be the script path, not the script content.

How can I use the CLI to specify the script path?

**To Reproduce**
1. Run `testkube create test --client direct --name test-pytest -t container-executor-pytest/test --prerun-script /app/prerun.sh --postrun-script /app/postrun.sh --update`
2. see error
![image](https://github.com/user-attachments/assets/dc2b5a4b-b4ca-4ed5-887c-2836b2e2df31)
3. Prepare script in directory and run `testkube create test --client direct --name test-pytest -t container-executor-pytest/test --prerun-script ./prerun.sh --postrun-script ./postrun.sh --update`
3. see testkube dashboard  
![image](https://github.com/user-attachments/assets/d7a4ed97-4509-4fb1-82e0-e292bd05a5f5)

**Expected behavior**
Pre-Run  command is /app/prerun.sh
and Post-Run command is /app/postrun.sh

**Version / Cluster**
- Which testkube version?  
  - API Version: v1.16.29
  - Dashboard Version: v1.16.6
  - Helm Chart Version: v1.16.43
- What Kubernetes cluster? open source k8s
- What Kubernetes version? v1.26.6

**Screenshots**
 
**Additional context**

**Comment by vsukhin** [comment]
hey, @dommgifer might be it's a bit confused docs, but these fieldss are used to store shell commands

**Comment by vsukhin** [comment]
hope, explanation is enought
