### ISSUE TITLE
ARM64 Images

### ISSUE THREAD

**Issue by seanuleh** [kubeshop/testkube#5798]
**Is your feature request related to a problem? Please describe.**
Is it possible to publish linux/arm64 platform images for `kubeshop/testkube-enterprise-api` and `kubeshop/testkube-enterprise-worker-service`. The rest of the stack is compatible on arm64 nodes and my company has migrated away from using amd64 nodes.

**Additional context**
```
~ > docker pull --platform linux/arm64 kubeshop/testkube-enterprise-api:1.10.50
1.10.50: Pulling from kubeshop/testkube-enterprise-api
Digest: sha256:2e7a296aa2597157360b23c74aaf6497d76c20bb636c639bbc23aafb52ca6bd3
Status: Image is up to date for kubeshop/testkube-enterprise-api:1.10.50

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview kubeshop/testkube-enterprise-api:1.10.50
image with reference docker.io/kubeshop/testkube-enterprise-api:1.10.50 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
~ > docker pull --platform linux/arm64 kubeshop/testkube-enterprise-worker-service:1.10.41 
1.10.41: Pulling from kubeshop/testkube-enterprise-worker-service
Digest: sha256:3829dae80f547a4344cb3b8ea9ee60e9240254e34bffdf8a3dceeae7e90dedc0
Status: Image is up to date for kubeshop/testkube-enterprise-worker-service:1.10.41

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview kubeshop/testkube-enterprise-worker-service:1.10.41
image with reference docker.io/kubeshop/testkube-enterprise-worker-service:1.10.41 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
```

**Comment by vsukhin** [comment]
hey, @seanuleh indeed, a good question! our devops ppl can provide some feedback about it @kubeshop/testkube-devops

**Comment by vsukhin** [comment]
@ypoplavs @dejanzele

**Comment by ypoplavs** [comment]
Sorry for the delay @seanuleh! I will take a look at the issue and get back to you in the following days.

**Comment by ypoplavs** [comment]
Hello @seanuleh! 
`kubeshop/testkube-enterprise-api` and `kubeshop/testkube-enterprise-worker-service` images now have ARM support. Please upgrade to the latest version of the Enterprise chart: `testkube-enterprise-1.153.0`
