### ISSUE TITLE
Test Workflow Templates documentation example mistake

### ISSUE THREAD

**Issue by narsdk** [kubeshop/testkube#5919]
I think that there is a typo in one Test Workflow Templates documentation:

![image](https://github.com/user-attachments/assets/c11fae25-554b-4a97-8658-ef628d558ad3)

I guess the highlighted part should be "steps" instead of "pod".

**Comment by olensmar** [comment]
thanks - will update!

**Comment by olensmar** [comment]
fixed here - https://docs.testkube.io/articles/test-workflow-templates
