### ISSUE TITLE
argocd config mgmt plugin

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#596]
I would like to establish a gitops pipeline using argocd for my testing with testkube:
- i will store my postman collections in github
- i want to configure argocd to automatically deploy these to my cluster as testkube scripts to make sure i have the latest scripts available for test execution at any time
- to achieve this I would like add a config-mgmt plugin to argocd that generates the corresponding script yaml manifests for my postman collections - argocd can then sync these with my cluster - see https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/

**Comment by TheBrunoLopes** [comment]
notes: Get inspirations from https://github.com/aabedraba/testkube-argocd-devops/blob/main/argocd-customization/argocd-plugins.yaml

`testkube generate test-crds .` should:
- Print for each file/folder found if it generated a test crd or it didn't match any test type.
- it should not be cluster aware

cc: @aabedraba

**Comment by TheBrunoLopes** [comment]
Should we also automate the ArgoCD_Testkube dockerfile creation ?

**Comment by aabedraba** [comment]
>  Should we also automate the ArgoCD_Testkube dockerfile creation ?

with every release; yes, we should

**Comment by vsukhin** [comment]
Moved Docker image creation to https://github.com/kubeshop/testkube/issues/1636
