### ISSUE TITLE
Minio artifacts bucket public access

### ISSUE THREAD

**Issue by david-polak-ataccama** [kubeshop/testkube#5967]
**Describe the enhancement you'd like to see**
Would it be possible to add a configuration variable which would compliment the `STORAGE_BUCKET` variable and allow the bucket to be set with anonymous (public) access?

We would like to be able to directly link to artifacts in the minio bucket from outside the deployment without the need for users to log in.

**Comment by vsukhin** [comment]
hey @david-polak-ataccama in general, it would not be hard to add, but we will deprecate Tests resources in near future and don't add new features. So, you can either do it manually or prepare a script to make this buclet public

**Comment by david-polak-ataccama** [comment]
@vsukhin thank you for the quick response. Apologies I failed to make the original post clear.

What we are after is to set the entire artifacts bucket specified by `testkube-api.storage.bucket` in https://artifacthub.io/packages/helm/kubeshop/testkube as public. Not the artifacts from individual test cases.

The `testkube-api.storage.bucket` seems to propagate to the `STORAGE_BUCKET` environment variable on the entire api deployment.

We want to be able to directly access and render the index.html report files produced by our tests by exposing the minio bucket inside our network in order for our devs to be able to review the report without having to log in or download it.

**Comment by david-polak-ataccama** [comment]
We have decided to implement something similar: patching the templated chart before deployment which runs a script on startup of the minio pod and sets the bucket as public. It's a bit hacky but it does work. Thank you.
