### ISSUE TITLE
Dashboard - better testing for artifacts

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#601]
**Describe the enhancement you'd like to see**
For now dashboard is hitting in api endpoint for `/execution/ID/artifacts` like crazy - even when executor don't handle artifacts. 

Would be nice to have info about what features particular executor handles 

- Add `features` enum to Executor CRD
- Use Artifacts only when  `artifacts` exists in executor features

<img width="591" alt="Zrzut ekranu 2021-11-29 o 12 27 11" src="https://user-images.githubusercontent.com/30776/143860194-a9e7ad3f-8957-4a11-afa5-3337c40000c5.png">

**Comment by TheBrunoLopes** [comment]
@exu @vsukhin this issue is a very old, does it still apply ? or perhaps we solved this already no ?

**Comment by TheBrunoLopes** [comment]
Seems this issue is done. Closing it.
