### ISSUE TITLE
Dashboard - TestsExecutions list

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#629]
Implement TestExecutions list 

Tests executions will get Test name as parameter and will display given tests executions list (tests executions contains scripts executions) 

## Data organisation

* splitting to 4 will simplify a lot implementation:
scripts executions behaviour will stay the same
we need to add filters to executions (by script and by some execution ids array)
* we need to add 3 views of data on dashboard:
  - tests (top level) - can show scripts (how test is organized will pass test id) or show test executions (will pass test id) 
  - scripts (must have possibility to be filtered by test id) - show executions will go to executions grid
   -  test executions (list of test executions show executions go to executions grid - will pass multiple executions ID’s attached to test execution
* on backend everything will stay almost as planned today

![img](https://raw.githubusercontent.com/kubeshop/testkube/ce93438fe1c4e70aac6f55ae0fc3358227de9bd6/docs/img/objects-dependencies.png)

**Comment by olensmar** [comment]
For the test executions list we should have the following columns:
- Execution Name
- test Name
- Started at
- Duration
- Status

**Comment by exu** [comment]
@Toxer10 @olensmar this is how currently result record looks like for test execution - I think all is here
- duration need to be calculated (`start-end` time)
- number of steps executed is simply `response.results.execution.length`

here is example record (in results array) 

```
{
  ............
  "results": [
     .........
    {
      "id": "61dff61867326ad521b2a0d6",
      "name": "test-example.verbally-merry-hagfish",
      "testName": "test-example",
      "status": "success",
      "startTime": "2022-01-13T09:51:20.443Z",
      "endTime": "2022-01-13T09:51:32.942Z",
      "execution": [
        {
          "id": "61dff61967326ad521b2a0d8",
          "name": "run script: testkube/test1",
          "scriptName": "test1",
          "status": "success",
          "type": "executeScript"
        },
        {
          "id": "",
          "name": "delay 2000ms",
          "status": "success",
          "type": "delay"
        },
        {
          "id": "61dff62067326ad521b2a0da",
          "name": "run script: testkube/test1",
          "scriptName": "test1",
          "status": "success",
          "type": "executeScript"
        }
      ]
    }
  ]
}
```
