### ISSUE TITLE
Details-panel for scripts

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#647]
Similar to the details panel I can see for a test-execution, I would like to see a details panel for a script, containing;
- basic metadata; name, description, create-date
- total number of executions (total, failed, success)
- script execution time metrics; min, max, avg (per total, failed, success)
- a graph showing number of executions over time - separating total, failed, success
- a graph showing script execution time distribution (per total, failed, success)
- the content of the script (downloadable) if available
- update history of the script (if available?)
- a link to "see executions"

**Comment by TheBrunoLopes** [comment]
All features done except the graphs part.
Will close this issue since this will be tackled in a different UI layout and perhaps not in the details panel.
