### ISSUE TITLE
Test details panel

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#658]
When selecting a test from #626 I would like to see a details panel for the test showing:
- basic metadata (name, description, etc)
- number of repeats
- list of teststeps
- beforeSteps (list of steps run before the list of teststeps)
- afterSteps (list of steps run before the list of teststeps)

there are currently two types of teststeps:
- Execute Script - which show the name of the script and link to the corresponding script
- Delay - in ms

**Comment by WarElephant27** [comment]
See mock-up here: https://xd.adobe.com/view/eda29c5e-e9b2-4649-95e4-fefe4eeec48d-b8f1/screen/2b446190-4986-4a67-ab69-012d0fdab7c5/

**Comment by TheBrunoLopes** [comment]
done
