### ISSUE TITLE
Research using go-git library for checking out repositories

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#709]
We need git to be installed inside container now 
Would be nice to limit dependencies and introduce go-git library 

In middle 2021 there was no go-git library (or we didn't found one) that has spatial checkout (partial checkouts for bigger repositories) - which is *crucial* for checking out tests from subdirectories in repository.

**Comment by TheBrunoLopes** [comment]
we have an init container that solves this issue correct ?
closing this issue, please comment otherwise.
