### ISSUE TITLE
Version update in the helm_charts pipeline is messing the testkube Chart.yaml

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#716]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. Specify '...'
3. See error

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by fog1985** [comment]
Fixed.
