### ISSUE TITLE
REACT_APP_API_SERVER_ENDPOINT should be used as the default dashboard endpoint not the hardcoded one

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#717]
**Describe the bug**
Right now the default endpoint for dashboard is hardcoded for demo.testkube.io/v1, we should take the value from the REACT_APP_API_SERVER_ENDPOINT env var.

**To Reproduce**
1. Run '...'
2. Specify '...'
3. See error

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by Toxer10** [comment]
![image](https://user-images.githubusercontent.com/25991946/148738288-bc09da6d-cc07-459f-9f3a-ea8a92b711f5.png)


As I can see we already have .env file in the root so we can specify any value to REACT_APP_API_SERVER_ENDPOINT variable. @nicufk how can I help more?

**Comment by nicufk** [comment]
it is there, but it seems that it is not used, can you make sure that u use the env variable for the default endpoint?
