### ISSUE TITLE
http://demo.testkube.io/apiEndpoint?apiEndpoint=demoresults.testkube.io is not working

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#718]
**Describe the bug**

**To Reproduce**
1. Run '...'
2. Specify '...'
3. See error

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by Toxer10** [comment]
![image](https://user-images.githubusercontent.com/25991946/148738136-f4277400-9afc-496f-8c9f-f6f5d4908165.png)


Can't access demoresults.testkube.io @nicufk could you help?
