### ISSUE TITLE
Consider using Kusk Gateway as API gateway for api and dashboard

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#722]
To limit issues with nginx-ingress we should consider using Kusk Gateway as main gateway

Todo items: 
- [ ] add kusk to helm charts (should have enabled flag)
- [ ] add `--no-kusk` to `kubectl-testkube` `install` command

Rationale: 
@nicufk please describe your recent  issues here

**Comment by vsukhin** [comment]
Do I understand it right, that the idea is to use Kusk for generating of nginx-ingress using OpenApi specs, becuase it's just a cli tool for generating specs, not a server or gateway?

**Comment by nicufk** [comment]
> @nicufk would be great to know which nginx-ingress issues should be fixed

I was overreacting I guess 😊 the issue I had previously was because the api-server was crashing and the request to it were handled by the dashboard/demo ingress

**Comment by vsukhin** [comment]
Ok, cool, I was worried about nginx a bit ;)

**Comment by exu** [comment]
> 

no - we was testing to use `kusk-gateway`(kusk is some kind of generator, gateway is standalone app)

**Comment by vsukhin** [comment]
yeah, I updated this ticket

**Comment by vsukhin** [comment]
So, after investgiating this task:
1. We don't have real need for this, because the original issue was solved using nginx ingress.
2. Installation of Kusk Gateway looks complex and requires kubernetes administartor intervention
