### ISSUE TITLE
Sync `testkube-operator` CRD's with `helm-charts/testkube-operator` chart repo automatically

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#723]
Currently all CRD's need to be synced manually to helm-charts repo - they should be overriden automatically on merge to master? 

research kustomize vs helm here (maybe we can generate helm chart automatically from kubebuilder somehow?)

**Comment by TheBrunoLopes** [comment]
Closing this issue. Let me know if this is still an issue and we re-open it.
