### ISSUE TITLE
Service of type NodePort

### ISSUE THREAD

**Issue by bioslikk** [kubeshop/testkube#757]
**Description**
As seen on the image, Testkube creates 3 services of type Nodeport. However, one of the caveats of this type of service is that it allocates a specific port in all the nodes of a cluster. Is there advantage on using the service of type Nodeport ? Would the type ClusterIP work as well ? 
![image](https://user-images.githubusercontent.com/13501228/149118104-948811a5-4f7f-4246-b122-0abd3a6b2acf.png)

**Comment by exu** [comment]
@fog1985 do you see any issues with that ?
