### ISSUE TITLE
Add google analytics to dashboard 

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#772]
**Describe the enhancement you'd like to see**

As testkube team member I want to know who visits my testkube dashboard .

**Additional context**

pass it from ‘env’ variable to allow user configure it 

User will pass ga id during helm charts installation for 

helm should set env variable in dashboard deployment

Dashboard need to load them during start 
(We was doing that for react already somewhere)

**Comment by exu** [comment]
@bioslikk ping

**Comment by bioslikk** [comment]
Gave it to @Toxer10 this morning 👍
