### ISSUE TITLE
Add autocompletion for test names to run

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#78]
As an engineer I don't want to always remember what test names are stored in CR. 

when running tests it would be nice to have autocompletion added e.g. when running 
```
kubectl kubetest scripts start [TEST_NAME]
```
TEST_NAME could be autocompleted based on available  tests in cluster 

Autocomplete script could be generated by `kubectl kubetest` plugin e.g. 
```
kubectl kubetest autocomplete
```

**Comment by TheBrunoLopes** [comment]
duplicated https://github.com/kubeshop/testkube/issues/1422
