### ISSUE TITLE
Brew formula misconfiguration

### ISSUE THREAD

**Issue by bioslikk** [kubeshop/testkube#781]
**Describe the bug**
Brew formula has the incorrect name and doesn't work as described in the docs.

**To Reproduce**
1. Run ' 
![image](https://user-images.githubusercontent.com/13501228/149753044-f3372901-b2b4-4c1c-9b40-3dc70496debc.png)

**Expected behavior**
Instead the command that works is the following, where testkube is repeated twice.
![image](https://user-images.githubusercontent.com/13501228/149753244-8970dc0a-8b88-4eb9-92fb-03d2313f20f2.png)

**Comment by exu** [comment]
confirmed - it's changed after adding additional brew repository (kubeshop/testkube-dev)
