### ISSUE TITLE
No CI Best practices

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#805]
**Describe the enhancement you'd like to see**

In CNCF landscape there is info that testkube miss CICD best practices 
https://bestpractices.coreinfrastructure.org/en 

<img width="904" alt="Zrzut ekranu 2022-01-19 o 13 05 59" src="https://user-images.githubusercontent.com/30776/150126404-8edddbf3-90bc-492c-91b3-4448d7682821.png">

We should fix this.

details in TestKube card https://landscape.cncf.io/card-mode?grouping=no&selected=test-kube&sort=stars

**Comment by bioslikk** [comment]
It's done.
