### ISSUE TITLE
Docs: nice downloads count grouped by binary architecture

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#826]
like in rush repo 
![image](https://user-images.githubusercontent.com/30776/150509100-26db36ba-9acf-4f0e-91fd-1717e241869c.png)

**Comment by Saurabhpatil-dev** [comment]
Hello @exu , 
can you please help me in classifing this 'https://github.com/kubeshop/testkube/releases/tag/v0.10.3' like above ?
I am confused because there are so many tar files.

**Comment by TheBrunoLopes** [comment]
won't do the count downloads for now.

@Saurabhpatil-dev good point on adding more info and helping classifying the systems the binary is for.
We now add the name of the OS is on the name of the file. Let me know if you think we need to make it even more clear ;)
<img width="1998" alt="image" src="https://user-images.githubusercontent.com/13501228/190627625-c78afc19-f763-4d8a-8e31-6d7eef3170d2.png">
