### ISSUE TITLE
`apt` package build

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#833]
Allow user to install testkube using apt package manager.
The flow should be something like `sudo apt install testkube`

In addition create a docker image FROM UBUNTU with the testkube CLI installed using apt.
This will serve as a docker image users could take to automate commands for their pipelines.

**Comment by nicufk** [comment]
Here is a recipe on how to do it with golang packages: https://people.debian.org/~stapelberg/2015/07/27/dh-make-golang.html

When running `gbp buildpackage --git-pbuilder` following output is given
`go: downloading github.com/denisbrodbeck/machineid v1.0.1
cloud.google.com/go@v0.81.0: module lookup disabled by GOPROXY=off
	cd _build && go install -trimpath -v -p 1
no Go files in /build/testkube-0.9.5~beta001/_build
dh_auto_build: error: cd _build && go install -trimpath -v -p 1 returned exit code 1
make: *** [debian/rules:4: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
I: copying local configuration
E: Failed autobuilding of package
I: unmounting dev/ptmx filesystem
I: unmounting dev/pts filesystem
I: unmounting dev/shm filesystem
I: unmounting proc filesystem
I: unmounting sys filesystem
I: Cleaning COW directory
I: forking: rm -rf /var/cache/pbuilder/build/cow.99029
gbp:error: 'git-pbuilder' failed: it exited with 1`

I've tried --git prebuild flag to set the proxy but with the same effect, env var was overridden when running build, here is the command:
`gbp buildpackage --git-pbuilder --git-verbose --git-prebuild="export GOPROXY=https://proxy.golang.org,direct & go env"`

It seems that pbuilder is creating a clean chroot env when building to see if all depenedencies can be met see doc here: https://wiki.ubuntu.com/PbuilderHowto
