### ISSUE TITLE
generate cli commands in dashboard

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#849]
To help me craft CLI commands I would like the details pane for a script to show me commands that I can copy/past to my terminal:
- for starting the script
- for deleting the script
- ?

Same would apply to Test and results details panels - with corresponding commands to start/delete/get/etc

**Comment by exu** [comment]
we should also think a little about IDs as they are not visible on scripts and test executions panels

**Comment by TheBrunoLopes** [comment]
done
