### ISSUE TITLE
dashboard: drill down into test-step results

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#853]
I would like to be able to click to the individual script results from the test execution pane, for example below there are three script executions - each should be clickable and show me the corresponding script execution (so I can see logs, artifacts, etc)

![image](https://user-images.githubusercontent.com/1917063/150953740-82909553-20aa-4ec1-ae15-6fe27034829d.png)

**Comment by TheBrunoLopes** [comment]
done
