### ISSUE TITLE
dashboard: improve pending execution details

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#859]
The details for a pending script should show some kind of in-progress indicator - together with real-time log output if possible - currently I see the below which makes me think the test is faulty (although it just hasn't finished)

![image](https://user-images.githubusercontent.com/1917063/150987997-27d7bf35-65a6-49b5-a57a-976622d4dcc5.png)

**Comment by exu** [comment]
It could be hard to implement real progress - as we are not able to check where we are during run - so we could cheat a little - maybe calculate stats for execution of given script and make assumption about ETA ?

**Comment by TheBrunoLopes** [comment]
fixed
