### ISSUE TITLE
dashboard: test details panel improvements

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#863]
See below:
- the "Repeats" value should be 0
- there should be a "Executions" number which shows how often the test has been executed, with a corresponding link to the test-executions panel
- the steps of the Test should be shown - for script steps it should be possible to click to the corresponding script

![image](https://user-images.githubusercontent.com/1917063/151033791-249e8ce2-c837-4987-917c-e5b25e3aa0ac.png)

**Comment by exu** [comment]
should we load here list of several last executions ?

**Comment by olensmar** [comment]
> should we load here list of several last executions ?

I was thinking a link to the test-executions pane filtered on the selected test

**Comment by exu** [comment]
@olensmar closing this as it relate to really old UI which was redesigned completely
