### ISSUE TITLE
dashboard: wrong percentage shown for pending test

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#864]
See screenshot below - the percentage should be relative to which step the execution is at - in this case it has finished 4 steps of 5 - so the percentage should be 80%

![image](https://user-images.githubusercontent.com/1917063/151034417-8e0c16bc-b62e-4035-b498-f7b4565b3bc3.png)

**Comment by exu** [comment]
We need to change how steps are saved (maybe prepopulate them as currently they are added after completion of step)
