### ISSUE TITLE
delete all is not working

### ISSUE THREAD

**Issue by nicufk** [kubeshop/testkube#876]
**Describe the bug**
` kubectl testkube scripts delete all                                                                                                                                                                      ─╯

████████ ███████ ███████ ████████ ██   ██ ██    ██ ██████  ███████ 
   ██    ██      ██         ██    ██  ██  ██    ██ ██   ██ ██      
   ██    █████   ███████    ██    █████   ██    ██ ██████  █████   
   ██    ██           ██    ██    ██  ██  ██    ██ ██   ██ ██      
   ██    ███████ ███████    ██    ██   ██  ██████  ██████  ███████ 
                                           /tɛst kjub/ by Kubeshop

⨯ delete script all from namespace testkube (error: the server could not find the requested resource (delete services testkube-api-server:8088))`

**To Reproduce**
1. Run '...'
2. Specify '...'
3. See error

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**

**Comment by vsukhin** [comment]
new command delete-all
