### ISSUE TITLE
Support parameterization of postman collections

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#88]
Newman allows the specification of an environments file when running collections - this file can contain arbitrary values that are used in the collections for URL, parameters, etc..  see https://learning.postman.com/docs/running-collections/using-newman-cli/command-line-integration-with-newman/#options

the actual format of these files is a simple json object - as follows: 
```
{
	"id": "c7a230f3-7fe6-4e35-8f3e-83309219e9e1",
	"name": "Oletest",
	"values": [
		{
			"key": "baseurl",
			"value": "https://petstore.io",
			"enabled": true
		}
	],
	"_postman_variable_scope": "environment",
	"_postman_exported_at": "2021-08-02T12:34:36.922Z",
	"_postman_exported_using": "Postman/7.34.0"
}
```

A (very) common use case for environments is the specification of the baseUrl for all requests - making it easy to target tests at different services/environments.

Kubetest currently supports the specification of arbitrary name/value pairs when running a script - when running a postman-collection we should automatically generate an environment file containing those parameters/values and pass that file to newman. 

Future improvements could be to support aliases or config-map references in parameter values - not needed for now!

**Comment by olensmar** [comment]
Thanks @om3171991 - Unfortunately I don't think so - @exu should we add a feature request?

**Comment by om3171991** [comment]
oh. @olensmar - Can you help me with how can we pass key-value from CLI ?

**Comment by exu** [comment]
@om3171991 you can pass `--env-var` parameter 

example of testkube internal test suite: 
```sh
	kubectl testkube scripts start sanity -f -p api_uri=http://testkube-api-server:8088 -p script_api_uri=http://testkube-api-server:8088 -p script_type=postman/collection -p script_name=fill-me -p execution_name=fill-me
```

It's almost the same as passing env vars to newman: 
```sh
	newman run test/e2e/TestKube-Sanity.postman_collection.json --env-var script_name=fill-me --env-var script_type=local-postman/collection  --env-var api_uri=http://localhost:8088 --env-var script_api_uri=http://localhost:8088 --env-var execution_name=fill --verbose
```

those vars can be easily used in your postman collection. 

Does this solve your problem ?

**Comment by om3171991** [comment]
@exu - It will be able to solve those cases where we have a small number of env variables but it will be great if we can have the option to pass env via file as JSON.
