### ISSUE TITLE
Pass file content by Volume 

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#956]
**Describe the enhancement you'd like to see**

Currently, the information about tests are passed as a data structure (part of execution), as it complicates creating 
We could try to create volume in the API server and then mount it in the job container (if possible). 

https://kubernetes.io/docs/concepts/storage/volumes/#emptydir-configuration-example

**Additional context**
It'll simplify a lot writing a new executor - currently, we have only libs for Go which help getting files, we can move this logic to api - and simply pass everything fetched to volume.

**Comment by vsukhin** [comment]
So, the idea is to use Empty dir volumes for job pods and implement init container, that prefill volume with data using code block from the executor
