### ISSUE TITLE
Success Metrics System

### ISSUE THREAD

**Issue by bioslikk** [kubeshop/testkube#970]
### User experience on CLI
Enabled by default

Actions user can take on analytics:
- `testkube analytics disable`
- `testkube analytics enable`
- `testkube analytics status`

### User experience on UI
Enabled by default

User accepts or rejects on the UI
E.g.,: 

<img width="1407" alt="image" src="https://user-images.githubusercontent.com/13501228/153861653-f562e658-95f5-4963-8f9c-aebbfa447100.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/13501228/153861737-4fca8b7c-245f-4cea-a4ac-052fae404587.png">

## Documentation
**The structure of all analytics information must be anonymous and the data structure should be in documentation.**

## Which metrics to track ?
<img width="383" alt="image" src="https://user-images.githubusercontent.com/13501228/153862122-da1810c2-c3a6-4a35-ba8b-838472f60d45.png">

### Activation 
<img width="765" alt="image" src="https://user-images.githubusercontent.com/13501228/153862365-15a89c59-51eb-4704-9541-2b405e25d423.png">

### Retention
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/13501228/153862460-c83e4977-8cee-4bfb-95a3-7f60dd00753b.png">

### Note
**Any data that is not relevant for the metrics specified above, must not be collected at all.**

**Comment by exu** [comment]
added config part in #1001

**Comment by exu** [comment]
@bioslikk please manage access to GA and create proper sites/groups where we should pass stats from cli and website (or simply pass to team if there is any)

**Comment by bioslikk** [comment]
Closed to work on: https://github.com/kubeshop/testkube/issues/1283
