### ISSUE TITLE
Testkube dashboard is blocked by ad-blocker

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#974]
**Describe the bug**
When accessing the dashboard through https://demo.testkube.io/ the page is completely black. 
Looking at the console shows that ga4-react is being blocked by _ublock origin_.  

**To Reproduce**
1. Install _[ublock origin](https://ublockorigin.com/)_
2. Access https://demo.testkube.io/
3. See blank page
4. Go to private mode and see that the page is not blank

**Expected behavior**
I don't think adblockers should affect the testkube dashboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/27779735/154050519-6eb335a3-4559-402d-8950-5de0f5037bdc.png)

**Comment by exu** [comment]
@Toxer10  can you look at it please
