### ISSUE TITLE
Getting logs freeze

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#976]
**Describe the bug**
Try to get logs from Test run - it freeze when starting test

**To Reproduce**
1. Run `kubectl testkube test run NAME -f`
3. See freeze instead of log stream

**Expected behavior**
Log stream

**Version / Cluster**
- Which testkube version? dev (0.9.3-beta002)  
- What Kubernetes cluster? testkube bare metal

**Screenshots**
<img width="668" alt="image" src="https://user-images.githubusercontent.com/30776/154236983-3f0807cb-3eba-47ca-9400-28360619e843.png">

**Comment by exu** [comment]
[#2108](https://github.com/kubeshop/testkube/issues/2108) will fix this

**Comment by exu** [comment]
For now haven't found way to override http client in Kubernetes REST client. 
When setting new transport getting SSL errors. There is quite a bit of logic inside REST Client around networking.

**Comment by exu** [comment]
Status of this issue: 
- Managed logs freeze on UI (new websockets implementation() 
- Managed logs freeze on CLI (direct client) 
- Kubernetes golang using proxy client still without success. Looks like we can't override clients transport

**Comment by rangoo94** [comment]
@exu, is it still relevant?
