### ISSUE TITLE
New executor (K6s)

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#978]

**Comment by lreimer** [comment]
Hey @exu
Funny enough, I was working on exactly that "feature" for the last few days.
https://github.com/lreimer/testkube-executor-k6
Maybe this work is a good start for a contribution to TestKube?

**Comment by exu** [comment]
Hi, @lreimer sounds awesome! - we'll review your work at the beginning of next week - and if everything will work well we can merge it into our main k6 repo if you want to work on an official testkube one.

**Comment by lreimer** [comment]
👍 Excellent. Looking forward to your review.

**Comment by exu** [comment]
@lreimer was looking quickly at your code - looks good! 

What I'm missing is mapping test steps details to our data structure - it's needed if the test is more complicated and is split into several parts to know what part was valid - but we can help you with that :) 

FYI We have planned for today (and probably Monday) quite a big refactor (about tests and scripts -> they will be TestSuites and Test) as it was quite confusing for users - so we would need to adopt it for this change (some small changes only like bumping main testkube version and renamings)

**Comment by exu** [comment]
One thing which left is to return step results.

**Comment by lreimer** [comment]
@exu will do. Can you please give me a hint or docs on how to do this? What are sensible step results in your view?

**Comment by lreimer** [comment]
So what you are referring to is to fill the following field, right?
```go
// execution steps (for collection of requests)
Steps []ExecutionStepResult `json:"steps,omitempty"`
```

**Comment by exu** [comment]
yes exactly - @lreimer this data structure is based for now on curl|postman|cypress - if you have any suggestions ping us here we'll discuss any fields which need to be added

**Comment by exu** [comment]
I think we can close this one as @lreimer has implemented whole executor 🎉 
https://github.com/kubeshop/testkube-executor-k6

**Comment by olensmar** [comment]
awesome - thank you @lreimer !

**Comment by lreimer** [comment]
My pleasure. Will make some final improvements to the current implementation today, in order to support multiple k6 scenarios and report back the test step results. But the current implementation is fully functional for the default scenario already.
