### ISSUE TITLE
An option to pass newman --insecure flag

### ISSUE THREAD

**Issue by pnx472** [kubeshop/testkube#992]
**Describe the enhancement you'd like to see**
Hello, I'm getting an error "unable to verify the first certificate" when running tests. I'm failing to find how to run tests without it.

**Additional context**
The issue also happens locally when running tests with newman. A fix is to pass `--insecure` flag.

**Comment by exu** [comment]
Hi @pnx472 - Good idea! - we had parts of this already in place for the executor I just need to update clients and make some small changes in API. I've applied changes already when it'll be reviewed we'll generate a new version and ping you 
#993

**Comment by exu** [comment]
@pnx472 please update your cluster and kubectl client on top of this version 

https://github.com/kubeshop/testkube/releases/tag/v0.9.7

**Comment by mjrlgue** [comment]
Hello, same issue here, when I run testkube with a postman collection I have `unable to verify the first certificate at request ` error. Even before adding the postman collection to testkube I add the paramaeter `insecure`:
```
"request": {
"method": "GET",
"header": [],
"url": {
	"raw": "{{host}}/version",
	"host": [
		"{{host}}"
	],
	"path": [
		"version"
	]
},
"insecure": false
```
But in Postman the test are working fine because I disabled the SSL check, How can I do the same in testkube please?

**Comment by vsukhin** [comment]
@mjrlgue when you create a test using cli please add `--executions-args="--insecure"`

**Comment by mjrlgue** [comment]
yes exactly @vsukhin, found it in [K6 executor](https://kubeshop.github.io/testkube/test-types/executor-k6/#git-directory), I had to add `--executions-args "--insecure"` when creating the test as follow:
`testkube create test --name postman-test --type postman/collection --file postman_collection.json --executor-args '--insecure'` as a result the test passed! And thank you for your quick repsonse!
