### ISSUE TITLE
Dasboard tests against demo are failing

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#999]
e.g. this one 

https://github.com/kubeshop/testkube-dashboard/runs/5249635301?check_suite_focus=true

**Comment by Toxer10** [comment]
@exu fix tests, they are outdated. Change this line `a[href="/dashboard/scripts"]` to `a[href="/dashboard/tests"]` for example; we don't have scripts anymore...

**Comment by exu** [comment]
> @exu fix tests, they are outdated. Change this line `a[href="/dashboard/scripts"]` to `a[href="/dashboard/tests"]` for example; we don't have scripts anymore...

@Toxer10 https://github.com/kubeshop/testkube-dashboard/pull/252/files fixed and added simple walk through all data grids
